/* archive.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/archive.c to work on it by hand) */

struct bf8_6_1 { unsigned char _:6; unsigned char f:1; };
extern char D_00170150[];
extern char D_0017015A[];
extern char D_00170172[];
extern char D_00183294[];
extern char D_00183298[];
extern char D_00195AA4[];
extern char D_00195BE0[];
extern char D_00195C44[];
extern char D_001962B4[];
extern char D_00196304[];
extern char D_0019632C[];
extern char D_00196354[];

extern int func_00069938(int, int, int);
extern int func_0007CBA1(int);
extern int func_0007D6AE(int, int);
extern int func_0009DEA7();
extern int func_000A0024();
extern int func_000A006E();
extern int func_000A00AF();
extern int func_000A00CB();
extern int func_000A0B42();
extern int func_000A0E82();
extern int func_000A0ED9(int, int);
extern int func_000A0F5C(int, ...);
extern void func_0003D01C(int, int);
extern void func_00050069(int);
extern void func_00064589(int, int);
extern void func_00070370(int, unsigned char);
int func_0001345E(int);
#pragma aux func_000A0ED9 parm routine [];

void func_00012F27(int a1)
{
    if (a1 == 0) return;
    *(short *)(D_0019632C + (a1 * 2)) = 0;
    if (*(int *)(D_001962B4 + (a1 << 2)) == 0) goto L12F71;
    if (*(int *)(D_001962B4 + (a1 << 2)) != (-1751672937)) goto L12F73;
L12F71:;
    goto L12F9E;
L12F73:;
    func_000A0024(*(int *)(D_001962B4 + (a1 << 2)), (int)D_00170150, 67);
    *(int *)(D_001962B4 + (a1 << 2)) = -1751672937;
L12F9E:;
    *(int *)(D_001962B4 + (a1 << 2)) = 0;
    *(short *)(D_00196304 + (a1 * 2)) = 0;
    func_0009DEA7(a1);
}

int func_00012FCE(int a1, int a2, int a3)
{
    int l_1C;
    int l_18;
    int l_14;

    if (((int)(short)*(short *)(D_00196304 + (a1 * 2))) != 256) goto L1304F;
    l_1C = *(int *)(D_001962B4 + (a1 << 2));
    l_14 = 0;
L1300C:;
    if (((int)(short)*(short *)(D_0019632C + (a1 * 2))) > l_14) goto L1302E;
    goto L1304D;
L1301F:;
    l_14++;
    (*(char (**)[18])&l_1C)++;
    goto L1300C;
L1302E:;
    if (func_000A0E82(a2, l_1C, a3) != 0) goto L1304B;
    return l_14;
L1304B:;
    goto L1301F;
L1304D:;
    goto L1309E;
L1304F:;
    l_18 = *(int *)(D_001962B4 + (a1 << 2));
    l_14 = 0;
L13065:;
    if (((int)(short)*(short *)(D_0019632C + (a1 * 2))) > l_14) goto L13087;
    goto L1309E;
L13078:;
    l_14++;
    (*(char (**)[8])&l_18)++;
    goto L13065;
L13087:;
    if (a3 != *(int *)((char *)l_18)) goto L1309C;
    return l_14;
L1309C:;
    goto L13078;
L1309E:;
    if (((int)(short)*(short *)(D_00196304 + (a1 * 2))) != 256) goto L130E4;
    func_000A0ED9(105, (int)D_00170150);
    func_000A0F5C(*(int *)D_00195C44, (int)D_0017015A, a2, ((int)D_00196354) + (a1 * 13));
    goto L13115;
L130E4:;
    func_000A0ED9(107, (int)D_00170150);
    func_000A0F5C(*(int *)D_00195C44, (int)D_00170172, a3, ((int)D_00196354) + (a1 * 13));
L13115:;
    func_00050069(*(int *)D_00195C44);
    return 0;
}

int func_00013131(int a1, int a2)
{
    int l_1C;
    int l_18;

    if (((int)(short)*(short *)(D_00196304 + (a1 * 2))) != 256) goto L13178;
    l_1C = *(int *)(D_001962B4 + (a1 << 2));
    l_1C += a2 * 18;
    return *(int *)((char *)l_1C + 14);
L13178:;
    l_18 = *(int *)(D_001962B4 + (a1 << 2));
    l_18 += a2 << 3;
    return *(int *)((char *)l_18 + 4);
}

int func_000131A5(int a1, int a2)
{
    int l_24;
    int l_20;
    int l_1C;
    int l_18;

    l_18 = 4;
    if (((int)(short)*(short *)(D_00196304 + (a1 * 2))) != 256) goto L13214;
    l_24 = *(int *)(D_001962B4 + (a1 << 2));
    l_1C = 0;
L131E8:;
    if (l_1C < a2) goto L13201;
    goto L1320C;
L131F2:;
    l_1C++;
    (*(char (**)[18])&l_24)++;
    goto L131E8;
L13201:;
    l_18 += *(int *)((char *)l_24 + 14);
    goto L131F2;
L1320C:;
    return l_18;
L13214:;
    l_20 = *(int *)(D_001962B4 + (a1 << 2));
    l_1C = 0;
L1322A:;
    if (l_1C < a2) goto L13243;
    goto L1324E;
L13234:;
    l_1C++;
    (*(char (**)[8])&l_20)++;
    goto L1322A;
L13243:;
    l_18 += *(int *)((char *)l_20 + 4);
    goto L13234;
L1324E:;
    return l_18;
}

int func_00013260(int a1, int a2, int a3)
{
    int l_24;
    int l_20;
    int l_1C;
    int l_18;
    int l_14;

    l_14 = 4;
    if (((int)(short)*(short *)(D_00196304 + (a1 * 2))) != 256) goto L132D4;
    l_24 = *(int *)(D_001962B4 + (a1 << 2));
    l_1C = 0;
L132A5:;
    if (l_1C < a2) goto L132BE;
    goto L132C9;
L132AF:;
    l_1C++;
    (*(char (**)[18])&l_24)++;
    goto L132A5;
L132BE:;
    l_14 += *(int *)((char *)l_24 + 14);
    goto L132AF;
L132C9:;
    l_18 = *(int *)((char *)l_24 + 14);
    goto L13317;
L132D4:;
    l_20 = *(int *)(D_001962B4 + (a1 << 2));
    l_1C = 0;
L132EA:;
    if (l_1C < a2) goto L13303;
    goto L1330E;
L132F4:;
    l_1C++;
    (*(char (**)[8])&l_20)++;
    goto L132EA;
L13303:;
    l_14 += *(int *)((char *)l_20 + 4);
    goto L132F4;
L1330E:;
    l_18 = *(int *)((char *)l_20 + 4);
L13317:;
    if (a3 != 0) goto L13332;
    a3 = func_000A00AF(l_18, (int)D_00170150, 205);
L13332:;
    func_000A006E(a1, l_14, 0);
    func_000A00CB(a1, a3, l_18);
    return a3;
}

void func_0001335E(int a1, int a2, int a3)
{
    int l_20;
    int l_1C;
    int l_18;
    int l_14;
    int l_10;

    l_10 = 4;
    if (((int)(short)*(short *)(D_00196304 + (a1 * 2))) != 256) goto L133D2;
    l_20 = *(int *)(D_001962B4 + (a1 << 2));
    l_18 = 0;
L133A3:;
    if (l_18 < a2) goto L133BC;
    goto L133C7;
L133AD:;
    l_18++;
    (*(char (**)[18])&l_20)++;
    goto L133A3;
L133BC:;
    l_10 += *(int *)((char *)l_20 + 14);
    goto L133AD;
L133C7:;
    l_14 = *(int *)((char *)l_20 + 14);
    goto L13415;
L133D2:;
    l_1C = *(int *)(D_001962B4 + (a1 << 2));
    l_18 = 0;
L133E8:;
    if (l_18 < a2) goto L13401;
    goto L1340C;
L133F2:;
    l_18++;
    (*(char (**)[8])&l_1C)++;
    goto L133E8;
L13401:;
    l_10 += *(int *)((char *)l_1C + 4);
    goto L133F2;
L1340C:;
    l_14 = *(int *)((char *)l_1C + 4);
L13415:;
    func_000A006E(a1, l_10, 0);
    func_000A0B42(a1, a3, l_14);
}

void func_00013438(int a1)
{
    int l_18;

    l_18 = func_0001345E(a1);
}

int func_0001345E(int a1)
{
    int l_1C;

    if (*(unsigned short *)((char *)a1 + 25) != *(short *)(*(char **)D_00195BE0 + 235)) goto L13494;
    return 0;
L13494:;
    if (((int)(unsigned short)*(short *)((char *)a1 + 23)) < 20) goto L134C8;
    func_0007CBA1(*(int *)D_00183294);
    func_00064589(a1, 4);
    return 0;
L134C8:;
    func_0003D01C(13, 1);
    if (((struct bf8_6_1 *)(*(char **)D_00195BE0 + 137))->f == 0) goto L13504;
    l_1C = (int)(unsigned char)*(signed char *)(*(char **)D_00195BE0 + 542);
    *(signed char *)(*(char **)D_00195BE0 + 137) &= 191;
    goto L13513;
L13504:;
    l_1C = (int)(short)*(short *)(*(char **)D_00195BE0 + 235);
L13513:;
    l_1C += (((int)(unsigned char)*(signed char *)((char *)*(int *)D_00195BE0 + 129)) - ((int)(unsigned short)*(short *)((char *)a1 + 23))) * 5;
    if (l_1C >= 5) goto L13543;
    l_1C = 5;
    goto L13550;
L13543:;
    if (l_1C <= 95) goto L13550;
    l_1C = 95;
L13550:;
    if (func_0007D6AE(0, 100) > l_1C) goto L1359A;
    *(signed char *)((char *)a1 + 21) |= 64;
    func_0007CBA1(*(int *)D_00183298);
    func_00064589(a1, 7);
    func_00069938(60, a1, 100);
    return 1;
L1359A:;
    if (((struct bf8_6_1 *)(*(char **)D_00195BE0 + 137))->f != 0) goto L135BB;
    *(short *)((char *)a1 + 25) = *(short *)(*(char **)D_00195BE0 + 235);
L135BB:;
    func_0007CBA1(*(int *)D_00183294);
    func_00064589(a1, 4);
    return 0;
}

int func_000135E6(int a1, int a2, int a3)
{
    int l_14;

    if (((int)(unsigned char)*(signed char *)((char *)a1 + 8)) < 10) goto L13617;
    return 1;
L13617:;
    if (*(unsigned short *)((char *)a3 + 25) != *(short *)(*(char **)D_00195BE0 + 235)) goto L1363C;
    return 0;
L1363C:;
    if (a2 < 20) goto L13658;
    func_0007CBA1(*(int *)D_00183294);
    return 0;
L13658:;
    func_0003D01C(13, 1);
    if (((struct bf8_6_1 *)(*(char **)D_00195BE0 + 137))->f == 0) goto L13694;
    l_14 = (int)(unsigned char)*(signed char *)(*(char **)D_00195BE0 + 542);
    *(signed char *)(*(char **)D_00195BE0 + 137) &= 191;
    goto L136A3;
L13694:;
    l_14 = (int)(short)*(short *)(*(char **)D_00195BE0 + 235);
L136A3:;
    l_14 -= a2 * 5;
    if (l_14 >= 5) goto L136BB;
    l_14 = 5;
    goto L136C8;
L136BB:;
    if (l_14 <= 95) goto L136C8;
    l_14 = 95;
L136C8:;
    if (func_0007D6AE(0, 100) > l_14) goto L13710;
    func_0007CBA1(*(int *)D_00183298);
    func_00069938(60, *(int *)D_00195AA4, 110);
    func_00070370(5, 1);
    return 1;
L13710:;
    if (((struct bf8_6_1 *)(*(char **)D_00195BE0 + 137))->f != 0) goto L13731;
    *(short *)((char *)a3 + 25) = *(short *)(*(char **)D_00195BE0 + 235);
L13731:;
    func_0007CBA1(*(int *)D_00183294);
    return 0;
}
