/* click.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/click.c to work on it by hand) */

extern char D_0012AC00[];
extern char D_00142309[];
extern char D_00176198[];
extern char D_001876AC[];
extern char D_001876E8[];
extern char D_00187734[];
extern char D_00187750[];
extern char D_00187770[];
extern char D_00187784[];
extern char D_001877A0[];
extern char D_001877DC[];
extern char D_00187828[];
extern char D_00187844[];
extern char D_00187864[];
extern char D_00187878[];
extern char D_00190BE4[];
extern char D_001940D4[];
extern char D_001940D5[];
extern char D_00195A00[];
extern char D_00195AA4[];
extern char D_00195ADC[];
extern char D_00195AEC[];
extern char D_00195BE0[];
extern char D_00195BE8[];
extern char D_00195F58[];
extern char D_001960D9[];
extern char D_00196118[];
extern char D_00196272[];
extern char D_00196274[];
extern char D_001A3F5E[];
extern char D_001A4C84[];
extern char D_001A4C88[];
extern char D_001A4C90[];
extern char D_001A4C9D[];
extern char D_001A4E20[];
extern char D_001A4E24[];
extern char D_001A4E28[];
extern char D_001A4FA0[];
extern char D_001A4FA4[];
extern char D_001A4FA8[];
extern char D_001A4FAC[];
extern char D_001A4FB0[];
extern char D_001A4FB4[];
extern char D_001A4FC8[];

extern int func_0004C274();
extern int func_0008DADD(int);
extern int func_0008DD46(int, int);
extern int func_000A0024();
extern int func_0012B136();
extern void func_000202C5(int);
extern void func_000756C6(int);
extern void func_000757C9(int);
extern void func_0007653C(int, int);
extern void func_0008DA1C(int);
extern void func_0008E3F7(int, int);
extern void func_000922F6(int, int, int);
void func_0007567B(int, int);
void func_00075A75(void);
void func_00075B3F(void);
void func_00075CFF(void);
void func_00076952(void);

void func_00074C10(void)
{
    int l_1C;
    int l_18;

    *(int *)D_00195ADC = 0;
    l_1C = *(int *)D_00196118;
L74C30:;
    if (l_1C == 0) return;
    l_18 = *(int *)((char *)l_1C + 55);
    *(signed char *)((char *)l_1C + 21) |= 2;
    func_0008DADD(l_1C);
    func_0008DD46(*(int *)D_00195AEC, l_1C);
    *(signed char *)((char *)l_1C) = 36;
    *(short *)((char *)l_1C + 27) = *(short *)D_00195F58;
    l_1C = l_18;
    goto L74C30;
}

void func_0007567B(int a1, int a2)
{
    int l_14;

    *(signed char *)D_001940D4 &= 253;
    l_14 = *(int *)((char *)a2 + 63);
    if (l_14 == 0) goto L756AB;
    *(signed char *)((char *)l_14 + 21) |= 1;
L756AB:;
    func_000922F6(a2, 3, 7);
}

int func_000757F9(int a1)
{
    *(int *)D_00190BE4 = 0;
    func_0008E3F7(*(int *)((char *)a1 + 63), (int)func_000757C9);
    return *(int *)D_00190BE4;
}

void func_00075A75(void)
{
L75A83:;
    if (*(signed char *)D_00142309 != 0) goto L75A83;
L75A8C:;
    if (*(signed char *)D_0012AC00 == 0) goto L75A9C;
    func_0012B136();
    goto L75A8C;
L75A9C:;
    if (*(int *)D_00195BE8 == 0) goto L75AB1;
    if (*(int *)D_00195BE8 != (-1751672937)) goto L75AB3;
L75AB1:;
    goto L75AD1;
L75AB3:;
    func_000A0024(*(int *)D_00195BE8, (int)D_00176198, 891);
    *(int *)D_00195BE8 = -1751672937;
L75AD1:;
    *(signed char *)D_00196274 = 0;
    *(signed char *)D_00196272 = 0;
}

void func_00075AE9(void)
{
    func_00075A75();
    func_0007567B((unsigned char)*(signed char *)D_001A4C9D, *(int *)D_001A4C90);
}

void func_00075B18(void)
{
    func_00075A75();
    func_000756C6(*(int *)D_001A4C90);
}

void func_00075B3F(void)
{
    func_00075A75();
    func_0008DA1C((int)D_001960D9);
    func_000922F6((int)D_001960D9, 2, 6);
}

void func_00075CFF(void)
{
L75D0D:;
    if (*(signed char *)D_00142309 != 0) goto L75D0D;
L75D16:;
    if (*(signed char *)D_0012AC00 == 0) goto L75D26;
    func_0012B136();
    goto L75D16;
L75D26:;
    if (*(int *)D_00195BE8 == 0) goto L75D3B;
    if (*(int *)D_00195BE8 != (-1751672937)) goto L75D3D;
L75D3B:;
    goto L75D5B;
L75D3D:;
    func_000A0024(*(int *)D_00195BE8, (int)D_00176198, 957);
    *(int *)D_00195BE8 = -1751672937;
L75D5B:;
    *(signed char *)D_00196274 = 0;
    *(signed char *)D_00196272 = 0;
}

void func_00075D73(void)
{
    func_00075CFF();
    func_000756C6(*(int *)D_001A4C88);
}

void func_00075D9A(void)
{
    func_00075CFF();
    func_000202C5(*(int *)D_001A4C88);
}

void func_00075DC1(void)
{
    func_00075CFF();
    func_0004C274(81, 81, 48, 67, (unsigned char)*(signed char *)((char *)*(int *)D_00195BE0 + 129));
}

void func_00075E7B(int a1, int a2)
{
    func_0007653C(a1, a2);
}

void func_0007606C(int a1, int a2)
{
}

int func_0007667A(short a1)
{
    int l_20;

    l_20 = *(int *)((char *)*(int *)D_00195A00 + 63);
L76696:;
    if (l_20 == 0) goto L766BD;
    if (*(short *)((char *)l_20 + 73) != a1) goto L766B2;
    return 1;
L766B2:;
    l_20 = *(int *)((char *)l_20 + 55);
    goto L76696;
L766BD:;
    return 0;
}

void func_00076952(void)
{
L76960:;
    if (*(signed char *)D_0012AC00 == 0) goto L76970;
    func_0012B136();
    goto L76960;
L76970:;
    if (*(signed char *)D_00142309 != 0) goto L76970;
    if (*(int *)D_00195BE8 == 0) goto L7698E;
    if (*(int *)D_00195BE8 != (-1751672937)) goto L76990;
L7698E:;
    goto L769AE;
L76990:;
    func_000A0024(*(int *)D_00195BE8, (int)D_00176198, 1372);
    *(int *)D_00195BE8 = -1751672937;
L769AE:;
    *(signed char *)D_00196274 = 0;
    *(signed char *)D_00196272 = 0;
}

void func_000769C6(void)
{
    func_00076952();
    func_000756C6(*(int *)D_001A4C84);
}

void func_00076A15(void)
{
    func_00075B3F();
}

void func_00076A8F(int a1)
{
    if (a1 == 0) return;
    a1 = *(int *)((char *)a1 + 63);
L76AAF:;
    if (a1 == 0) return;
    *(int *)((char *)a1 + 7) = *(int *)((char *)*(int *)D_00195AA4 + 7);
    *(int *)((char *)a1 + 11) = *(int *)((char *)*(int *)D_00195AA4 + 11);
    *(int *)((char *)a1 + 15) = *(int *)((char *)*(int *)D_00195AA4 + 15);
    a1 = *(int *)((char *)a1 + 55);
    goto L76AAF;
}

void func_00077B03(void)
{
    if (*(signed char *)D_001A3F5E == 0) goto L77B58;
    *(int *)D_001A4FB0 = (int)D_001877A0;
    *(int *)D_001A4FA8 = (int)D_001877DC;
    *(int *)D_001A4FAC = (int)D_00187828;
    *(int *)D_001A4FA4 = (int)D_00187844;
    *(int *)D_001A4FB4 = (int)D_00187864;
    *(int *)D_001A4FA0 = (int)D_00187878;
    return;
L77B58:;
    *(int *)D_001A4FB0 = (int)D_001876AC;
    *(int *)D_001A4FA8 = (int)D_001876E8;
    *(int *)D_001A4FAC = (int)D_00187734;
    *(int *)D_001A4FA4 = (int)D_00187750;
    *(int *)D_001A4FB4 = (int)D_00187770;
    *(int *)D_001A4FA0 = (int)D_00187784;
}

void func_000784EE(void)
{
    (*(int *)D_001A4FC8)--;
    if (*(int *)D_001A4FC8 != (-1)) goto L78515;
    *(int *)D_001A4FC8 = 31;
L78515:;
    *(int *)((char *)*(int *)D_00195AA4 + 7) = *(int *)(D_001A4E20 + (*(int *)D_001A4FC8 * 12));
    *(int *)((char *)*(int *)D_00195AA4 + 11) = *(int *)(D_001A4E24 + (*(int *)D_001A4FC8 * 12));
    *(int *)((char *)*(int *)D_00195AA4 + 15) = *(int *)(D_001A4E28 + (*(int *)D_001A4FC8 * 12));
    *(signed char *)D_001940D5 |= 2;
}
