/* custom.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/custom.c to work on it by hand) */

extern char D_0012AC00[];
extern char D_0012AC04[];
extern char D_0012AC06[];
extern char D_0012B508[];
extern char D_0012DA44[];
extern char D_00143550[];
extern char D_00147964[];
extern char D_00175420[];
extern char D_00175429[];
extern char D_00175436[];
extern char D_00175443[];
extern char D_00175450[];
extern char D_0017545D[];
extern char D_0017546A[];
extern char D_001755DC[];
extern char D_001755E2[];
extern char D_0017567E[];
extern char D_0017568B[];
extern char D_00175698[];
extern char D_0017CC27[];
extern char D_0018082A[];
extern char D_0018084E[];
extern char D_0018092E[];
extern char D_00185370[];
extern char D_001853A0[];
extern char D_0018549C[];
extern char D_001854C8[];
extern char D_001854F4[];
extern char D_00185644[];
extern char D_00185646[];
extern char D_00185648[];
extern char D_0018564A[];
extern char D_0018564C[];
extern char D_00185650[];
extern char D_00185652[];
extern char D_00185654[];
extern char D_00185656[];
extern char D_00185658[];
extern char D_0018565C[];
extern char D_0018565E[];
extern char D_00185662[];
extern char D_001856A4[];
extern char D_001856C8[];
extern char D_00187CA8[];
extern char D_001903A4[];
extern char D_00190BE4[];
extern char D_00190BE8[];
extern char D_00190CE4[];
extern char D_00190D64[];
extern char D_00190D66[];
extern char D_00190D68[];
extern char D_00190D6C[];
extern char D_00190D70[];
extern char D_00190D72[];
extern char D_00190D74[];
extern char D_00190D76[];
extern char D_00190D78[];
extern char D_00190D7A[];
extern char D_00190D7C[];
extern char D_00190D7E[];
extern char D_00190D7F[];
extern char D_00190D82[];
extern char D_00190D84[];
extern char D_00190D86[];
extern char D_00190DE4[];
extern char D_00190DE8[];
extern char D_00190DEC[];
extern char D_00190DF0[];
extern char D_00190DF4[];
extern char D_00190DF8[];
extern char D_00190DFC[];
extern char D_00190E00[];
extern char D_00190E0C[];
extern char D_00190E10[];
extern char D_00190EE0[];
extern char D_00190EE4[];
extern char D_001940D4[];
extern char D_001940D8[];
extern char D_00195AA4[];
extern char D_00195B58[];
extern char D_00195BE0[];
extern char D_00195BE8[];
extern char D_00195BEC[];
extern char D_00195C44[];
extern char D_00195C94[];
extern char D_0019626F[];
extern char D_00196272[];
extern char D_00196274[];
extern char D_00196279[];
extern char D_0019981C[];
extern char D_00199820[];
extern char D_00199821[];
extern char D_0019982E[];
extern char D_0019982F[];
extern char D_0019983C[];

extern int func_00053494(short);
extern int func_00069938(int, int, int);
extern int func_0006CB53(int, int);
extern int func_0006CE0D(int);
extern int func_0007D5D9(void);
extern int func_0009DEA7();
extern int func_000A0024();
extern int func_000A0040();
extern int func_000A00AF();
extern int func_000A0AD9();
extern int func_000A0B42();
extern int func_000A0DF4();
extern int func_000A0ED9(int, int);
extern int func_000A0F5C(int, ...);
extern int func_000A1023();
extern int func_000A1054();
extern int func_000A1079();
extern int func_000CE483();
extern int func_0012B136();
extern int func_0012B2D3();
extern int func_00144E84();
extern int func_00144F68();
extern int func_00144FB4();
extern void func_0003F09F(int, int);
extern void func_000425F2(void);
extern void func_000537B6(void);
extern void func_00053A89(int, short, int);
extern void func_00053E83(int);
extern void func_00054526(void);
extern void func_000551B1(short, int);
extern void func_000553B2(short, int);
extern void func_000557A7(void);
extern void func_00055A5B(void);
extern void func_00055F0F(void);
extern void func_000567CA(unsigned char);
extern void func_0007CA1F(int, int, int, int, unsigned char);
extern void func_0007D3CA(int);
int func_000540F9(int, int);
int func_00054DC5(void);
int func_0005500F(short);
void func_0005425C(int);
void func_00054D75(void);
void func_0005559C(void);
#pragma aux func_000A0ED9 parm routine [];
#pragma dagger KKND_CONFREV func_000549DB
#pragma dagger slots func_00054B27 l_2C 24 l_28 20 l_24 16 l_20 12 l_1C 8 l_18 4
#pragma dagger slots func_0005500F a1 8 l_18 4 ret 12

void func_00052DC3(void)
{
    int l_2C;
    int l_28;
    int l_24;
    int l_20;
    int l_1C;
    int l_18;

    func_000A0040(*(int *)D_00195BEC + 16, -1, 12, (int)D_00175420, 88, 12);
    *(signed char *)(*(char **)D_00195BEC + 52) = 8;
    *(short *)(*(char **)D_00195BEC + 4) = 5120;
    func_000CE483(*(int *)D_00195BEC + 58, 50, 16);
    *(signed char *)D_00190D7E = (*(signed char *)D_00190D7F = (*(short *)D_00190D7C = (*(short *)D_00190D78 = (*(short *)D_00190D6C = (*(short *)D_00190D66 = (*(short *)D_00190D64 = 0))))));
    *(signed char *)D_00147964 &= 254;
    *(short *)D_00190D68 = 115;
    func_00053E83(0);
    *(short *)D_00190D76 = 0;
    *(short *)D_00190D84 = 65535;
    *(short *)D_00190D86 = 0;
    *(signed char *)D_001940D8 |= 1;
    if (*(signed char *)D_00195C94 == 0) goto L52EBC;
    func_0006CB53((int)D_00195C94, *(int *)D_00195BEC);
L52EBC:;
    func_0006CB53((int)D_00175429, *(int *)D_00143550);
    *(int *)D_00190DF4 = func_000A00AF(64000, (int)D_00175420, 105);
    func_000A1023(*(int *)D_00190DF4, *(int *)D_00143550, 64000, (int)D_00175420, 106, 4);
    *(int *)D_00190DEC = func_0006CB53((int)D_00175436, 0);
    *(int *)D_00190DE4 = func_000A00AF(5520, (int)D_00175420, 109);
    func_00144E84(219, 46, 40, 138, *(int *)D_00190DE4, 0);
    *(int *)D_00190DF0 = func_0006CB53((int)D_00175443, 0);
    *(int *)D_00190DE8 = func_000A00AF(((int)(unsigned short)*(short *)(*(char **)D_00190DF0 + 4)) * ((int)(unsigned short)*(short *)(*(char **)D_00190DF0 + 6)), (int)D_00175420, 113);
    *(int *)D_00190DF8 = func_0006CB53((int)D_00175450, 0);
    *(int *)D_00190E00 = func_0006CB53((int)D_0017545D, 0);
    *(int *)D_00190DFC = func_0006CB53((int)D_0017546A, 0);
    l_28 = 1132;
    *(int *)D_00190BE4 = *(int *)((char *)l_28);
L52FD3:;
    if (*(short *)D_00190D6C != 0) goto L533C3;
    func_000425F2();
    *(signed char *)D_00196279 = *(signed char *)D_0012AC00;
    func_0012B136();
    func_0012B2D3((int)(short)*(short *)D_0012AC04, (int)(short)*(short *)D_0012AC06);
    if (*(signed char *)D_0012AC00 != 0) goto L53031;
    *(short *)D_00190D86 = 0;
    *(short *)D_00190D72 = 16;
    *(short *)D_00190D74 = 16;
    goto L530F9;
L53031:;
    if (*(short *)D_00190D76 != 0) goto L530F9;
    if (*(short *)D_0012AC04 <= *(short *)D_00185650) goto L5305D;
    if (*(short *)D_0012AC04 < *(short *)D_00185654) goto L5305F;
L5305D:;
    goto L5306E;
L5305F:;
    if (*(short *)D_0012AC06 > *(short *)D_00185652) goto L53070;
L5306E:;
    goto L5307F;
L53070:;
    if (*(short *)D_0012AC06 < *(short *)D_00185656) goto L53081;
L5307F:;
    goto L5309C;
L53081:;
    func_00069938(203, *(int *)D_00195AA4, 100);
    ((int (*)())(*(int *)D_00185658))();
L5309C:;
    if (*(short *)D_0012AC04 <= *(short *)D_00185644) goto L530BA;
    if (*(short *)D_0012AC04 < *(short *)D_00185648) goto L530BC;
L530BA:;
    goto L530CB;
L530BC:;
    if (*(short *)D_0012AC06 > *(short *)D_00185646) goto L530CD;
L530CB:;
    goto L530DC;
L530CD:;
    if (*(short *)D_0012AC06 < *(short *)D_0018564A) goto L530DE;
L530DC:;
    goto L530F9;
L530DE:;
    func_00069938(203, *(int *)D_00195AA4, 100);
    ((int (*)())(*(int *)D_0018564C))();
L530F9:;
    if (*(short *)D_00190D86 == 0) goto L5310A;
    (*(short *)D_00190D86)--;
L5310A:;
    if (*(short *)D_00190D76 != 0) goto L53127;
    *(int *)D_0019983C = (int)D_001854F4;
    l_1C = 28;
    goto L53176;
L53127:;
    if (((int)(short)*(short *)D_00190D76) != 1) goto L53146;
    *(int *)D_0019983C = (int)D_0018565C;
    l_1C = 6;
    goto L53176;
L53146:;
    *(int *)D_0019983C = (int)D_001856A4;
    if (((int)(short)(*(short *)D_00190D76 & 16)) == 0) goto L53169;
    l_2C = 1;
    goto L53170;
L53169:;
    l_2C = 3;
L53170:;
    l_1C = l_2C;
L53176:;
    if (((int)(unsigned char)*(signed char *)D_00196274) == 8) goto L5333E;
    if (*(short *)D_00190D76 != 0) goto L53199;
    if (*(signed char *)D_0012AC00 != 0) goto L5319B;
L53199:;
    goto L531A8;
L5319B:;
    if (*(signed char *)D_0012AC00 != *(signed char *)D_00196279) goto L531AD;
L531A8:;
    goto L5326E;
L531AD:;
    l_18 = 0;
L531B4:;
    if ((short)(short)l_18 < *(short *)&l_1C) goto L531CA;
    goto L53269;
L531C2:;
    l_18++;
    goto L531B4;
L531CA:;
    if (*(short *)D_0012AC04 <= *(short *)((char *)(int)(*(char **)D_0019983C + (((int)(short)*(short *)&l_18) * 12)))) goto L531FF;
    if (*(short *)D_0012AC04 < *(short *)(*(char **)D_0019983C + 4 + (((int)(short)*(short *)&l_18) * 12))) goto L53201;
L531FF:;
    goto L5321C;
L53201:;
    if (*(short *)D_0012AC06 > *(short *)(*(char **)D_0019983C + 2 + (((int)(short)*(short *)&l_18) * 12))) goto L5321E;
L5321C:;
    goto L53239;
L5321E:;
    if (*(short *)D_0012AC06 < *(short *)(*(char **)D_0019983C + 6 + (((int)(short)*(short *)&l_18) * 12))) goto L5323B;
L53239:;
    goto L53264;
L5323B:;
    func_00069938(203, *(int *)D_00195AA4, 100);
    ((int (*)())(*(int *)(*(char **)D_0019983C + 8 + (((int)(short)*(short *)&l_18) * 12))))();
    goto L53269;
L53264:;
    goto L531C2;
L53269:;
    goto L5333E;
L5326E:;
    if (((int)(unsigned char)(*(signed char *)D_0012AC00 & 1)) == 0) goto L5333E;
    l_18 = 0;
L53289:;
    if ((short)(short)l_18 < *(short *)&l_1C) goto L5329F;
    goto L5333E;
L53297:;
    l_18++;
    goto L53289;
L5329F:;
    if (*(short *)D_0012AC04 <= *(short *)((char *)(int)(*(char **)D_0019983C + (((int)(short)*(short *)&l_18) * 12)))) goto L532D4;
    if (*(short *)D_0012AC04 < *(short *)(*(char **)D_0019983C + 4 + (((int)(short)*(short *)&l_18) * 12))) goto L532D6;
L532D4:;
    goto L532F1;
L532D6:;
    if (*(short *)D_0012AC06 > *(short *)(*(char **)D_0019983C + 2 + (((int)(short)*(short *)&l_18) * 12))) goto L532F3;
L532F1:;
    goto L5330E;
L532F3:;
    if (*(short *)D_0012AC06 < *(short *)(*(char **)D_0019983C + 6 + (((int)(short)*(short *)&l_18) * 12))) goto L53310;
L5330E:;
    goto L53339;
L53310:;
    func_00069938(203, *(int *)D_00195AA4, 100);
    ((int (*)())(*(int *)(*(char **)D_0019983C + 8 + (((int)(short)*(short *)&l_18) * 12))))();
    goto L5333E;
L53339:;
    goto L53297;
L5333E:;
    if (*(short *)D_00190D76 != 0) goto L53354;
    func_00053494(1);
    goto L5336C;
L53354:;
    if (((int)(short)*(short *)D_00190D76) != 1) goto L53367;
    func_000537B6();
    goto L5336C;
L53367:;
    func_00054526();
L5336C:;
    func_00054DC5();
    func_000A1023(655360, *(int *)D_00143550, 64000, (int)D_00175420, 205, 4);
    l_24 = 1132;
    if (*(int *)D_00190BE4 == *(int *)((char *)l_24)) goto L533BE;
    (*(short *)D_00190D74)++;
    l_20 = 1132;
    *(int *)D_00190BE4 = *(int *)((char *)l_20);
L533BE:;
    goto L52FD3;
L533C3:;
    *(signed char *)D_001940D8 &= 254;
    func_000A0024(*(int *)D_00190DE4, (int)D_00175420, 217);
    func_000A0024(*(int *)D_00190DEC, (int)D_00175420, 218);
    func_000A0024(*(int *)D_00190DE8, (int)D_00175420, 219);
    func_000A0024(*(int *)D_00190DF0, (int)D_00175420, 220);
    func_000A0024(*(int *)D_00190DF4, (int)D_00175420, 221);
    func_000A0024(*(int *)D_00190DF8, (int)D_00175420, 222);
    func_000A0024(*(int *)D_00190DFC, (int)D_00175420, 223);
    func_000A0024(*(int *)D_00190E00, (int)D_00175420, 224);
    func_000A0040((int)D_00190DE4, 0, 512, (int)D_00175420, 226, 512);
}

void func_000539D2(void)
{
    if (*(signed char *)(*(char **)D_00195BEC + 28) != 0) goto L539FF;
    func_0003F09F(301, 1);
    return;
L539FF:;
    if (func_000A1079(*(int *)D_00195BEC + 16, -1, 12) == 0) goto L53A2B;
    func_0003F09F(300, 1);
    return;
L53A2B:;
    if (*(short *)D_00190D64 == 0) goto L53A46;
    func_0003F09F(302, 1);
    return;
L53A46:;
    if (((int)(short)*(short *)D_00190D68) < 81) goto L53A60;
    if (((int)(short)*(short *)D_00190D68) <= 161) goto L53A71;
L53A60:;
    func_0003F09F(306, 1);
    return;
L53A71:;
    func_0005559C();
    *(short *)D_00190D6C = 1;
}

void func_00053B22(void)
{
    func_00053A89(*(int *)D_00195BEC + 28, 14, (int)func_00053494);
}

void func_00053B51(void)
{
    *(signed char *)(*(char **)D_00195BEC + 16) = func_000540F9((int)D_0017CC27, *(int *)D_00190DF4);
}

void func_00053B83(void)
{
    *(signed char *)(*(char **)D_00195BEC + 17) = func_000540F9((int)D_0017CC27, *(int *)D_00190DF4);
}

void func_00053BB5(void)
{
    *(signed char *)(*(char **)D_00195BEC + 18) = func_000540F9((int)D_0017CC27, *(int *)D_00190DF4);
}

void func_00053BE7(void)
{
    *(signed char *)(*(char **)D_00195BEC + 19) = func_000540F9((int)D_0017CC27, *(int *)D_00190DF4);
}

void func_00053C19(void)
{
    *(signed char *)(*(char **)D_00195BEC + 20) = func_000540F9((int)D_0017CC27, *(int *)D_00190DF4);
}

void func_00053C4B(void)
{
    *(signed char *)(*(char **)D_00195BEC + 21) = func_000540F9((int)D_0017CC27, *(int *)D_00190DF4);
}

void func_00053C7D(void)
{
    *(signed char *)(*(char **)D_00195BEC + 22) = func_000540F9((int)D_0017CC27, *(int *)D_00190DF4);
}

void func_00053CAF(void)
{
    *(signed char *)(*(char **)D_00195BEC + 23) = func_000540F9((int)D_0017CC27, *(int *)D_00190DF4);
}

void func_00053CE1(void)
{
    *(signed char *)(*(char **)D_00195BEC + 24) = func_000540F9((int)D_0017CC27, *(int *)D_00190DF4);
}

void func_00053D13(void)
{
    *(signed char *)(*(char **)D_00195BEC + 25) = func_000540F9((int)D_0017CC27, *(int *)D_00190DF4);
}

void func_00053D45(void)
{
    *(signed char *)(*(char **)D_00195BEC + 26) = func_000540F9((int)D_0017CC27, *(int *)D_00190DF4);
}

void func_00053D77(void)
{
    *(signed char *)(*(char **)D_00195BEC + 27) = func_000540F9((int)D_0017CC27, *(int *)D_00190DF4);
}

void func_00053DA9(void)
{
    func_0003F09F((int)(short)*(short *)(D_001856C8 + (func_000540F9((int)D_0018082A, *(int *)D_00190DF4) * 2)), 1);
}

void func_00053DE6(void)
{
    *(int *)D_00190E0C = (int)D_0018084E;
    *(int *)D_00190E10 = (int)D_001853A0;
    *(short *)D_00190D76 = 2;
    *(short *)D_00190D82 = 0;
}

void func_00053E24(void)
{
    *(int *)D_00190E0C = (int)D_0018092E;
    *(int *)D_00190E10 = (int)D_001854C8;
    *(short *)D_00190D76 = 3;
    *(short *)D_00190D82 = 1;
}

void func_00053E62(void)
{
    *(short *)D_00190D76 = 1;
}

void func_00053EFE(void)
{
    func_00053E83(0);
}

void func_00053F1D(void)
{
    func_00053E83(1);
}

void func_00053F3F(void)
{
    func_00053E83(2);
}

void func_00053F61(void)
{
    func_00053E83(3);
}

void func_00053F83(void)
{
    func_00053E83(4);
}

void func_00053FA5(void)
{
    func_00053E83(5);
}

void func_00053FC7(void)
{
    func_00053E83(6);
}

void func_00053FE9(void)
{
    func_00053E83(7);
}

void func_0005400B(void)
{
    int l_1C;
    int l_18;

    l_1C = 1132;
    if (((unsigned)(*(int *)((char *)l_1C) - *(int *)D_00190BE8)) < 6) return;
    l_18 = 1132;
    *(int *)D_00190BE8 = *(int *)((char *)l_18);
    if (((int)(short)*(short *)(*(char **)D_00195BEC + 58 + (((int)(short)*(short *)D_00190D70) * 2))) == 75) return;
    (*(short *)(*(char **)D_00195BEC + 58 + (((int)(short)*(short *)D_00190D70) * 2)))++;
    (*(short *)D_00190D64)--;
}

void func_00054082(void)
{
    int l_1C;
    int l_18;

    l_1C = 1132;
    if (((unsigned)(*(int *)((char *)l_1C) - *(int *)D_00190BE8)) < 6) return;
    l_18 = 1132;
    *(int *)D_00190BE8 = *(int *)((char *)l_18);
    if (((int)(short)*(short *)(*(char **)D_00195BEC + 58 + (((int)(short)*(short *)D_00190D70) * 2))) == 10) return;
    (*(short *)(*(char **)D_00195BEC + 58 + (((int)(short)*(short *)D_00190D70) * 2)))--;
    (*(short *)D_00190D64)++;
}

int func_000540F9(int a1, int a2)
{
    short l_18;
    short l_14;

    if (((int)D_0017CC27) != a1) goto L54194;
    *(int *)&l_14 = 0;
    *(int *)&l_18 = *(int *)&l_14;
L54127:;
    if (*(int *)((char *)((((int)(short)l_14) << 2) + a1)) == 0) goto L54177;
    if (func_0005500F((int)(short)l_14) != 0) goto L5416E;
    *(signed char *)(D_00190CE4 + ((int)(short)l_18)) = *(signed char *)&l_14;
    *(int *)(D_00190EE4 + (((int)(short)(*(int *)&l_18)++) << 2)) = *(int *)((char *)(a1 + (((int)(short)l_14) << 2)));
L5416E:;
    l_14++;
    goto L54127;
L54177:;
    *(int *)(D_00190EE4 + (((int)(short)l_18) << 2)) = 0;
    func_0007D3CA((int)D_00190EE4);
    goto L5419C;
L54194:;
    func_0007D3CA(a1);
L5419C:;
    *(signed char *)D_001940D4 &= 254;
L541A3:;
    func_000425F2();
    func_0012B136();
    func_000A1023(*(int *)D_00143550, a2, 64000, (int)D_00175420, 558, 4);
    l_14 = func_0007D5D9();
    if (((int)(short)l_14) <= (-1)) goto L54210;
L541DD:;
    if (*(signed char *)D_0012AC00 == 0) goto L541ED;
    func_0012B136();
    goto L541DD;
L541ED:;
    if (((int)D_0017CC27) != a1) goto L54207;
    return (int)(signed char)*(signed char *)(D_00190CE4 + ((int)(short)l_14));
L54207:;
    return (int)(short)l_14;
L54210:;
    *(signed char *)D_00147964 &= 254;
    func_0012B2D3((int)(short)*(short *)D_0012AC04, (int)(short)*(short *)D_0012AC06);
    func_000A1023(655360, *(int *)D_00143550, 64000, (int)D_00175420, 568, 4);
    goto L541A3;
}

void func_0005425C(int a1)
{
    int l_1C;
    int l_18;

    l_18 = (((int)(short)*(short *)(D_0018565E + (((int)(short)*(short *)&a1) * 12))) + ((int)(short)*(short *)(D_00185662 + (((int)(short)*(short *)&a1) * 12)))) >> 1;
    if (((int)(short)*(short *)D_0012AC06) >= 81) goto L542CA;
    *(short *)(*(char **)D_00195BE0 + 145 + (((int)(short)*(short *)&a1) * 2)) = (((int)(short)*(short *)D_0012AC06) - 81) / 5;
    goto L5431C;
L542CA:;
    if (((int)(short)*(short *)D_0012AC06) <= 81) goto L54304;
    *(short *)(*(char **)D_00195BE0 + 145 + (((int)(short)*(short *)&a1) * 2)) = (((int)(short)*(short *)D_0012AC06) - 81) / 5;
    goto L5431C;
L54304:;
    *(short *)(*(char **)D_00195BE0 + 145 + (((int)(short)*(short *)&a1) * 2)) = 0;
L5431C:;
    *(short *)(*(char **)D_00195BE0 + 145 + (((int)(short)*(short *)&a1) * 2)) = -*(short *)(*(char **)D_00195BE0 + 145 + (((int)(short)*(short *)&a1) * 2));
}

void func_00054352(void)
{
    func_0005425C(0);
}

void func_00054371(void)
{
    func_0005425C(1);
}

void func_00054393(void)
{
    func_0005425C(2);
}

void func_000543B5(void)
{
    func_0005425C(3);
}

void func_000543D7(void)
{
    func_0005425C(4);
}

void func_000543F9(void)
{
    int l_1C;
    short l_18;

    l_1C = 0;
    *(int *)&l_18 = l_1C;
L54414:;
    if (((int)(short)*(short *)&l_1C) < 5) goto L54427;
    goto L54442;
L5441F:;
    l_1C++;
    goto L54414;
L54427:;
    l_18 += *(short *)(*(char **)D_00195BE0 + 145 + (((int)(short)*(short *)&l_1C) * 2));
    goto L5441F;
L54442:;
    if (l_18 == 0) goto L54461;
    *(signed char *)D_0012B508 = 145;
    func_0003F09F(303, 1);
    return;
L54461:;
    *(short *)D_00190D76 = 0;
L5446A:;
    if (*(signed char *)D_0012AC00 == 0) return;
    func_0012B136();
    goto L5446A;
}

int func_00054484(void)
{
    int l_1C;

L54492:;
    func_000425F2();
    func_0012B136();
    l_1C = func_0007D5D9();
    if (l_1C <= (-1)) goto L544CA;
L544AA:;
    if (*(signed char *)D_0012AC00 == 0) goto L544BA;
    func_0012B136();
    goto L544AA;
L544BA:;
    *(signed char *)D_00147964 &= 254;
    return l_1C + 1;
L544CA:;
    if (l_1C != (-2)) goto L544E0;
    *(signed char *)D_00147964 &= 254;
    return 0;
L544E0:;
    func_0012B2D3((int)(short)*(short *)D_0012AC04, (int)(short)*(short *)D_0012AC06);
    func_000A1023(655360, *(int *)D_00143550, 64000, (int)D_00175420, 655, 4);
    goto L54492;
}

int func_000549DB(int a1)
{
    int l_24;
    int l_20;
    int l_1C;

    l_20 = (int)(unsigned char)*(signed char *)(D_00199820 + (int)((char *)(((int)(unsigned char)*(signed char *)(D_00190D7E + a1)) * 2) + (a1 * 14)));
    l_1C = (int)(unsigned char)*(signed char *)(D_00199821 + ((((int)(unsigned char)*(signed char *)(D_00190D7E + a1)) * 2) + (a1 * 14)));
    l_24 = 0;
L54A32:;
    if (((int)(unsigned char)*(signed char *)(D_00190D7E + a1)) > l_24) goto L54A4F;
    goto L54A9B;
L54A47:;
    l_24++;
    goto L54A32;
L54A4F:;
    if (((int)(unsigned char)*(signed char *)(D_00199820 + ((a1 * 14) + (l_24 * 2)))) != l_20) goto L54A85;
    if (((int)(unsigned char)*(signed char *)(D_00199821 + ((a1 * 14) + (l_24 * 2)))) == l_1C) goto L54A87;
L54A85:;
    goto L54A99;
L54A87:;
    (*(signed char *)(D_00190D7E + a1))--;
    return 1;
L54A99:;
    goto L54A47;
L54A9B:;
    return 0;
}

void func_00054AAF(void)
{
    *(short *)D_00190D76 = 0;
L54AC6:;
    if (*(signed char *)D_0012AC00 == 0) return;
    func_0012B136();
    goto L54AC6;
}

void func_00054AE0(void)
{
    if (((int)(unsigned char)*(signed char *)(D_00190D7E + ((int)(short)*(short *)D_00190D82))) == 7) return;
    *(signed char *)D_00190D76 |= 16;
    func_0007D3CA(*(int *)D_00190E0C);
    *(signed char *)D_001940D4 |= 1;
}

void func_00054B27(void)
{
    int l_2C;
    int l_28;
    int l_24;
    int l_1C;
    short l_20;
    short l_18;

    l_28 = *(int *)D_00190E0C;
    *(int *)&l_20 = 30;
    if (*(signed char *)D_0012AC00 == 0) goto L54B5A;
    if (*(signed char *)D_0012AC00 != *(signed char *)D_00196279) goto L54B5C;
L54B5A:;
    goto L54B68;
L54B5C:;
    if (((int)(short)*(short *)D_0012AC04) > 10) goto L54B6A;
L54B68:;
    goto L54B78;
L54B6A:;
    if (((int)(short)*(short *)D_0012AC04) < 161) goto L54B7A;
L54B78:;
    goto L54B83;
L54B7A:;
    l_2C = 1;
    goto L54B8A;
L54B83:;
    l_2C = 0;
L54B8A:;
    *(int *)&l_18 = l_2C;
    *(short *)D_00190D7A = 65535;
    l_1C = 0;
L54BA0:;
    if (*(int *)((char *)l_28) == 0) goto L54C27;
    func_0007CA1F(*(int *)((char *)l_28), 10, (int)(short)l_20, 145, 141);
    l_24 = *(int *)&l_20;
    l_20 += *(short *)D_0012DA44;
    if (l_18 == 0) goto L54BEC;
    if (*(short *)D_0012AC06 > *(short *)&l_24) goto L54BEE;
L54BEC:;
    goto L54BFA;
L54BEE:;
    if (*(short *)D_0012AC06 < l_20) goto L54BFC;
L54BFA:;
    goto L54C15;
L54BFC:;
    *(short *)D_00190D7A = l_1C;
L54C05:;
    if (*(signed char *)D_0012AC00 == 0) goto L54C15;
    func_0012B136();
    goto L54C05;
L54C15:;
    l_1C++;
    (*(char (**)[4])&l_28)++;
    goto L54BA0;
L54C27:;
    l_1C = (int)(unsigned char)*(signed char *)(D_00190D7E + ((int)(short)*(short *)D_00190D82));
    *(signed char *)(D_00199820 + (((((int)(short)*(short *)D_00190D82) * 14) + (((int)(short)*(short *)&l_1C) * 2)) + ((int)(short)*(short *)D_00190D7C))) = *(signed char *)D_00190D7A;
    if (*(short *)D_00190D7C != 0) goto L54C83;
    *(signed char *)(D_00199821 + ((((int)(short)*(short *)D_00190D82) * 14) + (((int)(short)*(short *)&l_1C) * 2))) = 0;
L54C83:;
    if (((int)(short)*(short *)D_00190D7A) == (-1)) goto L54C99;
    if (*(short *)D_00190D7C != 0) goto L54C9B;
L54C99:;
    goto L54CC2;
L54C9B:;
    if (*(short *)D_00190D82 != 0) goto L54CB2;
    func_000551B1((int)(short)*(short *)&l_1C, 0);
    goto L54CBD;
L54CB2:;
    func_000553B2((int)(short)*(short *)&l_1C, 0);
L54CBD:;
    func_00054D75();
L54CC2:;
    if (((int)(short)(*(short *)D_00190D76 & 16)) == 0) goto L54CDE;
    if (((int)(short)*(short *)D_00190D7A) != (-1)) goto L54CE0;
L54CDE:;
    goto L54CF1;
L54CE0:;
    if (((int)(short)(*(short *)D_00190D76 & 15)) == 2) goto L54CF3;
L54CF1:;
    goto L54D21;
L54CF3:;
    *(int *)D_00190E0C = *(int *)(D_00185370 + (((int)(short)*(short *)D_00190D7A) << 2));
    *(short *)D_00190D7C = 1;
    if (*(int *)D_00190E0C != 0) goto L54D1F;
    func_00054D75();
L54D1F:;
    return;
L54D21:;
    if (((int)(short)(*(short *)D_00190D76 & 16)) == 0) goto L54D3D;
    if (((int)(short)*(short *)D_00190D7A) != (-1)) goto L54D3F;
L54D3D:;
    return;
L54D3F:;
    *(int *)D_00190E0C = *(int *)(D_0018549C + (((int)(short)*(short *)D_00190D7A) << 2));
    *(short *)D_00190D7C = 1;
    if (*(int *)D_00190E0C != 0) return;
    func_00054D75();
}

void func_00054D75(void)
{
    int l_18;

    *(signed char *)D_00190D76 &= 239;
    if (((int)(short)*(short *)D_00190D76) != 2) goto L54D9F;
    l_18 = (int)D_0018084E;
    goto L54DA6;
L54D9F:;
    l_18 = (int)D_0018092E;
L54DA6:;
    *(int *)D_00190E0C = l_18;
    (*(signed char *)(D_00190D7E + ((int)(short)*(short *)D_00190D82)))++;
}

int func_00054DC5(void)
{
    int l_2C;
    int l_28;
    int l_24;
    short l_1C;
    short l_18;

    l_28 = 65536;
    l_24 = 0;
    *(int *)&l_18 = 0;
L54DE8:;
    if ((short)(short)((int)(unsigned char)*(signed char *)D_00190D7E) > l_18) goto L54DFF;
    goto L54E37;
L54DF7:;
    (*(int *)&l_18)++;
    goto L54DE8;
L54DFF:;
    l_24 += *(int *)((char *)(int)(*(char **)(D_001853A0 + (((int)(unsigned char)*(signed char *)(D_00199820 + (((int)(short)l_18) * 2))) << 2)) + (((int)(unsigned char)*(signed char *)(D_00199821 + (((int)(short)l_18) * 2))) << 2)));
    goto L54DF7;
L54E37:;
    l_2C = 0;
    *(int *)&l_18 = 0;
L54E45:;
    if ((short)(short)((int)(unsigned char)*(signed char *)D_00190D7F) > l_18) goto L54E5C;
    goto L54E94;
L54E54:;
    (*(int *)&l_18)++;
    goto L54E45;
L54E5C:;
    l_2C += *(int *)((char *)(int)(*(char **)(D_001854C8 + (((int)(unsigned char)*(signed char *)(D_0019982E + (((int)(short)l_18) * 2))) << 2)) + (((int)(unsigned char)*(signed char *)(D_0019982F + (((int)(short)l_18) * 2))) << 2)));
    goto L54E54;
L54E94:;
    *(int *)&l_1C = (((int)(unsigned char)*(signed char *)(*(char **)D_00195BEC + 52)) - 8) * 3277;
    if (((int)(unsigned char)*(signed char *)(*(char **)D_00195BEC + 52)) >= 8) goto L54EC2;
    *(int *)&l_1C <<= 1;
L54EC2:;
    l_28 = (int)(*(char **)&l_1C + ((l_24 + 65536) - l_2C));
    if (l_28 >= 6554) goto L54EE5;
    l_28 = 6554;
L54EE5:;
    *(int *)(*(char **)D_00195BEC + 54) = l_28;
    if (l_28 <= 65536) goto L54F24;
    *(short *)D_00190D68 = 115 - (((l_28 - 65536) * 69) / 262144);
    goto L54F59;
L54F24:;
    if (l_28 >= 65536) goto L54F50;
    *(short *)D_00190D68 = (((65536 - l_28) * 69) / 65536) + 115;
    goto L54F59;
L54F50:;
    *(short *)D_00190D68 = 115;
L54F59:;
    if (((int)(short)*(short *)D_00190D68) >= 46) goto L54F6E;
    *(short *)D_00190D68 = 46;
L54F6E:;
    return l_28;
}

void func_00054F81(void)
{
    if (((int)(unsigned char)*(signed char *)(*(char **)D_00195BEC + 52)) == 30) goto L54FAB;
    if (*(short *)D_00190D86 == 0) goto L54FAD;
L54FAB:;
    return;
L54FAD:;
    *(short *)D_00190D86 = 20;
    (*(signed char *)(*(char **)D_00195BEC + 52))++;
}

void func_00054FC8(void)
{
    if (((int)(unsigned char)*(signed char *)(*(char **)D_00195BEC + 52)) == 4) goto L54FF2;
    if (*(short *)D_00190D86 == 0) goto L54FF4;
L54FF2:;
    return;
L54FF4:;
    *(short *)D_00190D86 = 20;
    (*(signed char *)(*(char **)D_00195BEC + 52))--;
}

int func_0005500F(short a1)
{
    int l_18;

    l_18 = 0;
L55027:;
    if (((int)(short)*(short *)&l_18) < 12) goto L5503A;
    goto L5505B;
L55032:;
    l_18++;
    goto L55027;
L5503A:;
    if ((short)((unsigned short)(unsigned char)*(signed char *)(*(char **)D_00195BEC + 16 + ((int)(short)*(short *)&l_18))) != a1) goto L55059;
    return 1;
L55059:;
    goto L55032;
L5505B:;
    return 0;
}

void func_0005506F(void)
{
    func_00144F68(219, 46, 40, 138, *(int *)D_00190DE4);
    func_00144FB4(219, (int)(short)*(short *)D_00190D68, (int)(unsigned short)*(short *)(*(char **)D_00190DEC + 4), (int)(unsigned short)*(short *)(*(char **)D_00190DEC + 6), *(int *)D_00190DEC + 12);
}

void func_000550D6(void)
{
    if (((int)(short)*(short *)D_00190D84) == (-1)) return;
    if (*(short *)D_00190D82 != 0) goto L55111;
    func_000551B1((int)(short)*(short *)D_00190D84, 1);
    goto L55122;
L55111:;
    func_000553B2((int)(short)*(short *)D_00190D84, 1);
L55122:;
    if (((int)(short)*(short *)D_00190D84) == 6) goto L5518A;
    func_000A1023((((int)(short)*(short *)D_00190D84) * 2) + (((int)D_00199820) + (((int)(short)*(short *)D_00190D82) * 14)), (((int)D_00199820) + (((int)(short)*(short *)D_00190D82) * 14)) + ((((int)(short)*(short *)D_00190D84) * 2) + 2), (6 - ((int)(short)*(short *)D_00190D84)) * 2, (int)D_00175420, 952, 4);
L5518A:;
    (*(signed char *)(D_00190D7E + ((int)(short)*(short *)D_00190D82)))--;
L55197:;
    if (*(signed char *)D_0012AC00 == 0) return;
    func_0012B136();
    goto L55197;
}

void func_0005559C(void)
{
    int l_18;

    if (*(signed char *)D_00195C94 == 0) return;
    l_18 = func_0006CE0D((int)D_00195C94);
    func_000A0B42(l_18, *(int *)D_00195BEC, 74);
    func_0009DEA7(l_18);
}

int func_000555E5(int a1, int a2, int a3)
{
    int l_1C;
    int l_18;
    int l_14;

    if (a1 != 0) goto L55606;
    if (a2 >= 2) goto L55608;
L55606:;
    goto L55614;
L55608:;
    return 0;
L55614:;
    if (a1 == 0) goto L55620;
    if (a2 != 6) goto L55622;
L55620:;
    goto L55628;
L55622:;
    if (a2 != 7) goto L5562A;
L55628:;
    goto L55636;
L5562A:;
    return 0;
L55636:;
    l_18 = 0;
L5563D:;
    if (l_18 < 2) goto L55650;
    goto L55736;
L55648:;
    l_18++;
    goto L5563D;
L55650:;
    l_14 = (int)(unsigned char)*(signed char *)(D_00190D7E + l_18);
    l_1C = 0;
L55665:;
    if (l_1C < l_14) goto L5567A;
    goto L55731;
L55672:;
    l_1C++;
    goto L55665;
L5567A:;
    if (l_18 != 0) goto L5569B;
    if (((int)(unsigned char)*(signed char *)(D_00199820 + ((l_18 * 14) + (l_1C * 2)))) < 2) goto L5569D;
L5569B:;
    goto L556B8;
L5569D:;
    if (((int)(unsigned char)*(signed char *)(D_00199821 + ((l_18 * 14) + (l_1C * 2)))) == a3) goto L556BA;
L556B8:;
    goto L556C6;
L556BA:;
    return 1;
L556C6:;
    if (l_18 == 0) goto L55704;
    if (((int)(unsigned char)*(signed char *)(D_00199820 + ((l_18 * 14) + (l_1C * 2)))) == 6) goto L55702;
    if (((int)(unsigned char)*(signed char *)(D_00199820 + ((l_18 * 14) + (l_1C * 2)))) != 7) goto L55704;
L55702:;
    goto L55706;
L55704:;
    goto L55721;
L55706:;
    if (((int)(unsigned char)*(signed char *)(D_00199821 + ((l_18 * 14) + (l_1C * 2)))) == a3) goto L55723;
L55721:;
    goto L5572C;
L55723:;
    return 1;
L5572C:;
    goto L55672;
L55731:;
    goto L55648;
L55736:;
    return 0;
}

int func_00055748(void)
{
    *(signed char *)((char *)(*(int *)D_0019981C = *(int *)D_00195C44 + 55000)) = 0;
    func_000557A7();
    func_00055A5B();
    *(signed char *)((char *)(int)(func_000A0DF4(*(int *)D_0019981C) + *(char **)D_0019981C) + 1) = 0;
    return *(int *)D_00195C44 + 55000;
}

void func_00055D93(int a1, int a2)
{
    if (a2 == 0) goto L55DDA;
    func_000A0ED9(1221, (int)D_00175420);
    func_000A0F5C((int)D_001903A4, (int)D_001755DC, a1, a2);
    goto L55DF6;
L55DDA:;
    func_000A0AD9((int)D_001903A4, a1, 160, (int)D_00175420, 1223);
L55DF6:;
    func_000A1054(*(int *)D_0019981C, (int)D_001903A4, (int)D_00175420, 1225, 4);
    func_000A1054(*(int *)D_0019981C, (int)D_001755E2, (int)D_00175420, 1226, 4);
}

int func_00055E35(int a1)
{
    if (((int)(unsigned char)*(signed char *)D_0019626F) != 10) goto L55E5E;
    if (((int)(unsigned char)*(signed char *)D_00196274) == 8) goto L55E60;
L55E5E:;
    goto L55E6C;
L55E60:;
    return 1;
L55E6C:;
    if (a1 == 0) goto L55EE0;
    *(short *)D_00190D68 = a1;
    *(signed char *)D_00187CA8 = 0;
    *(signed char *)D_001940D8 |= 4;
    *(signed char *)D_00196274 = 10;
    *(int *)D_00195BE8 = func_0006CB53((int)D_0017567E, 0);
    *(int *)D_00195B58 = func_0006CB53((int)D_0017568B, 0);
    *(int *)D_00190EE0 = func_0006CB53((int)D_00175698, 0);
    *(signed char *)D_00196272 = 1;
    *(signed char *)D_001940D8 &= 254;
    func_000567CA(15);
    func_00055F0F();
L55EE0:;
    return ((((int)(unsigned char)*(signed char *)D_00196274) == 10) ? 1 : 0);
}
