/* disease.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/disease.c to work on it by hand) */

extern char D_00175970[];
extern char D_0017597A[];
extern char D_001759EB[];
extern char D_001759F8[];
extern char D_001940D8[];
extern char D_00195AA0[];
extern char D_00195B0C[];
extern char D_00195BE0[];
extern char D_00195BF4[];
extern char D_001961F5[];
extern char D_001A3AA4[];

extern int func_0004C274(unsigned char, unsigned char, unsigned char, unsigned char, unsigned char);
extern int func_00067A47(int);
extern int func_00067C04(int);
extern int func_0007D6AE(int, int);
extern int func_000A0AD9();
extern void func_0003EC2A(int, int);
extern void func_0003F09F(short, int);
extern void func_00058E15(int, int);
extern void func_000728D2(void);
extern void func_0007D12D(void);
extern void func_00094E25(void);
extern void func_00094F31(void);
int func_00067270(void);

void func_0006630B(int a1)
{
    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 10) goto L66333;
    *(signed char *)((char *)a1) = 29;
    return;
L66333:;
    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 29) return;
    *(signed char *)((char *)a1) = 10;
}

void func_00066B7A(void)
{
    int l_18;

    func_00094E25();
    if (((int)(unsigned char)*(signed char *)((char *)*(int *)D_00195BE0 + 67)) != 8) goto L66BED;
    *(short *)((char *)*(int *)D_00195BE0 + 175) -= 30;
    *(short *)((char *)*(int *)D_00195BE0 + 283) -= 30;
    *(short *)((char *)*(int *)D_00195BE0 + 253) -= 30;
    *(short *)((char *)*(int *)D_00195BE0 + 361) -= 30;
    *(short *)((char *)*(int *)D_00195BE0 + 265) -= 30;
    *(short *)((char *)*(int *)D_00195BE0 + 337) -= 30;
L66BED:;
    if (func_00067270() == 0) return;
    *(short *)((char *)*(int *)D_00195BE0 + 259) -= 30;
    *(short *)((char *)*(int *)D_00195BE0 + 265) -= 30;
    *(short *)((char *)*(int *)D_00195BE0 + 175) -= 30;
    *(short *)((char *)*(int *)D_00195BE0 + 253) -= 30;
    *(short *)((char *)*(int *)D_00195BE0 + 283) -= 30;
    *(short *)((char *)*(int *)D_00195BE0 + 361) -= 30;
    *(short *)((char *)*(int *)D_00195BE0 + 337) -= 30;
}

void func_00066C5B(void)
{
    func_00094F31();
    if (((int)(unsigned char)*(signed char *)((char *)*(int *)D_00195BE0 + 67)) != 8) goto L66CCE;
    *(short *)((char *)*(int *)D_00195BE0 + 175) += 30;
    *(short *)((char *)*(int *)D_00195BE0 + 283) += 30;
    *(short *)((char *)*(int *)D_00195BE0 + 253) += 30;
    *(short *)((char *)*(int *)D_00195BE0 + 361) += 30;
    *(short *)((char *)*(int *)D_00195BE0 + 265) += 30;
    *(short *)((char *)*(int *)D_00195BE0 + 337) += 30;
L66CCE:;
    if (func_00067270() == 0) return;
    *(short *)((char *)*(int *)D_00195BE0 + 259) += 30;
    *(short *)((char *)*(int *)D_00195BE0 + 265) += 30;
    *(short *)((char *)*(int *)D_00195BE0 + 175) += 30;
    *(short *)((char *)*(int *)D_00195BE0 + 253) += 30;
    *(short *)((char *)*(int *)D_00195BE0 + 283) += 30;
    *(short *)((char *)*(int *)D_00195BE0 + 361) += 30;
    *(short *)((char *)*(int *)D_00195BE0 + 337) += 30;
}

void func_00067027(int a1)
{
    int l_1C;
    int l_18;

    l_18 = 0;
    if (a1 != 0) goto L67057;
    if (((int)(unsigned char)*(signed char *)((char *)*(int *)D_00195BE0 + 67)) < 8) goto L67059;
L67057:;
    goto L67071;
L67059:;
    if (((unsigned)(*(int *)D_00195BF4 - *(int *)((char *)*(int *)D_00195BE0 + 513))) < 1200) goto L67073;
L67071:;
    goto L67095;
L67073:;
    if (func_00067C04(3) != 0) goto L67095;
    func_0003EC2A((int)D_0017597A, 1);
    return;
L67095:;
    *(signed char *)D_001940D8 |= 8;
    *(int *)((char *)*(int *)D_00195BE0 + 513) = *(int *)D_00195BF4;
    l_1C = *(int *)((char *)*(int *)D_00195AA0 + 63);
L670B8:;
    if (l_1C == 0) goto L67108;
    if (((int)(unsigned char)*(signed char *)((char *)l_1C)) != 11) goto L670FD;
    l_18 = l_1C + 71;
    if (((int)(unsigned char)*(signed char *)((char *)l_18)) == 101) goto L670F4;
    if (((int)(unsigned char)*(signed char *)((char *)l_18)) != 102) goto L670F6;
L670F4:;
    goto L67108;
L670F6:;
    l_18 = 0;
L670FD:;
    l_1C = *(int *)((char *)l_1C + 55);
    goto L670B8;
L67108:;
    if (l_18 == 0) return;
    if (((int)(unsigned char)*(signed char *)((char *)*(int *)D_00195BE0 + 67)) >= 8) goto L671E0;
    if (((int)(unsigned char)*(signed char *)((char *)l_18)) != 101) goto L67142;
    *(signed char *)((char *)*(int *)D_00195BE0 + 67) = 9;
    goto L6714B;
L67142:;
    *(signed char *)((char *)*(int *)D_00195BE0 + 67) = 10;
L6714B:;
    *(short *)((char *)*(int *)D_00195BE0 + 145) -= 100;
    *(short *)((char *)*(int *)D_00195BE0 + 147) -= 100;
    *(short *)((char *)*(int *)D_00195BE0 + 149) -= 100;
    *(short *)((char *)*(int *)D_00195BE0 + 151) -= 100;
    *(short *)((char *)*(int *)D_00195BE0 + 153) -= 100;
    *(signed char *)((char *)*(int *)D_00195BE0 + 66) = 2;
    *(short *)((char *)*(int *)D_00195BE0 + 124) = *(short *)((char *)*(int *)D_00195BE0 + 126);
    *(signed char *)D_001940D8 |= 8;
    func_00058E15(0, 0);
    *(int *)((char *)*(int *)D_00195BE0 + 443) = 0;
    *(int *)((char *)*(int *)D_00195BE0 + 451) = 0;
    func_000728D2();
    return;
L671E0:;
    *(signed char *)((char *)*(int *)D_00195BE0 + 67) = *(signed char *)((char *)*(int *)D_00195BE0 + 498);
    *(short *)((char *)*(int *)D_00195BE0 + 145) += 100;
    *(short *)((char *)*(int *)D_00195BE0 + 147) += 100;
    *(short *)((char *)*(int *)D_00195BE0 + 149) += 100;
    *(short *)((char *)*(int *)D_00195BE0 + 151) += 100;
    *(short *)((char *)*(int *)D_00195BE0 + 153) += 100;
    *(signed char *)((char *)*(int *)D_00195BE0 + 66) = 0;
    *(short *)((char *)*(int *)D_00195BE0 + 124) = *(short *)((char *)*(int *)D_00195BE0 + 126);
    *(signed char *)D_001940D8 |= 8;
    func_00058E15(0, 0);
    func_000728D2();
}

int func_00067270(void)
{
    int l_24;
    int l_20;
    int l_1C;

    l_1C = 0;
    l_20 = *(int *)((char *)*(int *)D_00195AA0 + 63);
L67290:;
    if (l_20 == 0) goto L672E0;
    if (((int)(unsigned char)*(signed char *)((char *)l_20)) != 11) goto L672D5;
    l_1C = l_20 + 71;
    if (((int)(unsigned char)*(signed char *)((char *)l_1C)) == 101) goto L672CC;
    if (((int)(unsigned char)*(signed char *)((char *)l_1C)) != 102) goto L672CE;
L672CC:;
    goto L672E0;
L672CE:;
    l_1C = 0;
L672D5:;
    l_20 = *(int *)((char *)l_20 + 55);
    goto L67290;
L672E0:;
    if (l_1C == 0) goto L672EF;
    l_24 = 1;
    goto L672F6;
L672EF:;
    l_24 = 0;
L672F6:;
    return l_24;
}

void func_0006770E(int a1)
{
    if (((int)(unsigned char)*(signed char *)((char *)*(int *)D_00195BE0 + 67)) != 8) goto L67826;
    if (a1 == 0) goto L6774F;
    if (func_0007D6AE(10, 100) < 30) goto L67751;
L6774F:;
    goto L67774;
L67751:;
    func_000A0AD9((int)D_001961F5, (int)D_001759EB, 13, (int)D_00175970, 952);
    return;
L67774:;
    if (a1 != 0) goto L67788;
    if (*(signed char *)((char *)*(int *)D_00195BE0 + 504) != 0) goto L6778A;
L67788:;
    goto L6779E;
L6778A:;
    if (func_0007D6AE(1, 100) < 50) goto L677A0;
L6779E:;
    goto L677CC;
L677A0:;
    func_0004C274(80, 0, 48, 66, (int)(unsigned char)*(signed char *)((char *)*(int *)D_00195BE0 + 129));
    return;
L677CC:;
    if (a1 != 0) goto L677E6;
    if (func_0007D6AE(1, 100) < 50) goto L677E8;
L677E6:;
    goto L67824;
L677E8:;
    func_0004C274(80, 0, 48, 65, (int)(unsigned char)*(signed char *)((char *)*(int *)D_00195BE0 + 129));
    if (*(signed char *)D_001961F5 == 0) goto L67824;
    *(signed char *)((char *)*(int *)D_00195BE0 + 504) = 1;
L67824:;
    return;
L67826:;
    if (func_00067270() == 0) goto L67835;
    if (a1 != 0) goto L67837;
L67835:;
    goto L6784B;
L67837:;
    if (func_0007D6AE(1, 100) < 30) goto L6784D;
L6784B:;
    return;
L6784D:;
    func_000A0AD9((int)D_001961F5, (int)D_001759F8, 13, (int)D_00175970, 971);
}

void func_00067A1D(int a1, int a2)
{
    *(int *)D_001A3AA4 += func_00067A47(a2);
}

void func_000686DA(int a1)
{
    if (a1 <= 0) goto L68702;
    if (((unsigned)a1) > *(int *)((char *)*(int *)D_00195BE0 + 133)) goto L68704;
L68702:;
    goto L6871A;
L68704:;
    func_0003F09F(454, 1);
    a1 = 0;
L6871A:;
    *(int *)D_00195B0C = a1;
    func_0007D12D();
}
