/* equip.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/equip.c to work on it by hand) */

extern char D_00185F88[];

extern int func_0007D6AE(int, int);
extern void func_0005DE74(unsigned short, short, short, int);
extern void func_00060430(int, int);
extern void func_0006077F(int, int);
#pragma dagger slots func_0005E450 a1 4 a2 12 l_20 16 l_18 8

void func_0005E450(short a1, int a2)
{
    int l_18;

    switch ((unsigned short)*(int *)&a1) {
case 5:
    func_0006077F(a2, func_0007D6AE(0, 22));
    return;
case 4:
    func_00060430(a2, -1);
    return;
case 11:
    func_0005DE74(287, 27, 8, a2);
    return;
default:
    l_18 = 0;
L5E4D8:;
    if (((int)(short)*(short *)((char *)(int)(*(char **)(D_00185F88 + (((int)(unsigned short)a1) << 2)) + (l_18++ * 2)))) != (-1)) goto L5E4D8;
{
    int l_20;
    l_20 = func_0007D6AE(0, l_18 - 2);
    func_0005DE74((int)(unsigned short)*(short *)((char *)(int)(*(char **)(D_00185F88 + (((int)(unsigned short)a1) << 2)) + (l_20 * 2))), (int)(short)a1, (int)(short)*(short *)&l_20, a2);
}
}
}
