/* kludge.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/kludge.c to work on it by hand) */

struct bf8_1_1 { unsigned char _:1; unsigned char f:1; };
struct bf8_2_1 { unsigned char _:2; unsigned char f:1; };
extern char D_0012B508[];
extern char D_00132F6C[];
extern char D_00142314[];
extern char D_00142315[];
extern char D_00171044[];
extern char D_0017104D[];
extern char D_0017105A[];
extern char D_0017105D[];
extern char D_00171062[];
extern char D_00171077[];
extern char D_00171083[];
extern char D_00171096[];
extern char D_001710A7[];
extern char D_001710BA[];
extern char D_001710C3[];
extern char D_001710D6[];
extern char D_001710EB[];
extern char D_0017BABC[];
extern char D_0017BABD[];
extern char D_0017BAE2[];
extern char D_0017BB01[];
extern char D_0017BB39[];
extern char D_0017BB3F[];
extern char D_00180B3A[];
extern char D_00180B42[];
extern char D_001830E6[];
extern char D_0018F044[];
extern char D_001903A4[];
extern char D_001903BA[];
extern char D_00190CE4[];
extern char D_00190CE5[];
extern char D_001917E4[];
extern char D_00191834[];
extern char D_001940D4[];
extern char D_001940D6[];
extern char D_001940D9[];
extern char D_001940DA[];
extern char D_001959D8[];
extern char D_001959DC[];
extern char D_001959E0[];
extern char D_001959E4[];
extern char D_00195AA0[];
extern char D_00195AC4[];
extern char D_00195B04[];
extern char D_00195B10[];
extern char D_00195B30[];
extern char D_00195BE0[];
extern char D_00195BEC[];
extern char D_00195BF4[];
extern char D_00195D98[];
extern char D_00196272[];
extern char D_00196274[];
extern char D_001962A6[];
extern char D_001962AB[];
extern char D_00196710[];
extern char D_0019672C[];
extern char D_00196A8C[];
extern char D_00196A90[];
extern char D_00199634[];
extern char D_00199714[];
extern char D_00199718[];
extern char D_00199724[];
extern char D_00199728[];
extern char D_001A5C28[];

extern int func_000192EE(short);
extern int func_000392AD(void);
extern int func_0003B1F3(int);
extern int func_0004596E(int, unsigned short);
extern int func_00045AED(int, int);
extern int func_0006CB53(int, int);
extern int func_000702A0(unsigned char);
extern int func_0007CBA1(int);
extern int func_0007D6AE(int, int);
extern int func_0008DA4D(int);
extern int func_0008DA91(int);
extern int func_0008DCE3(int, int, int);
extern int func_0008DD46(int, int);
extern int func_0008E6C5(int, int, int);
extern int func_0008EB88(int);
extern int func_0009DA1C(int, int);
extern int func_0009DAEE(int, ...);
extern int func_0009DC25();
extern int func_0009DC49();
extern int func_0009DC59(int, ...);
extern int func_0009DEA7();
extern int func_000A0040();
extern int func_000A00CB();
extern int func_000A0AD9();
extern int func_000A0ED9(int, int);
extern int func_000A0F5C(int, ...);
extern int func_000A1023();
extern int func_000A148C(int, ...);
extern int func_000A16F8(int, ...);
extern int func_000C7FD9();
extern int func_000CAE1C();
extern void func_0001374D(int);
extern void func_0001D739(void);
extern void func_0004F3F6(void);
extern void func_0005A54A(int, int, int);
extern void func_0005E37F(unsigned short, int, int, int);
extern void func_0005E540(int, int, int);
extern void func_0006077F(int, int);
extern void func_000705D9(void);
extern void func_00078566(int, int);
extern void func_0007D3CA(int);
extern void func_0008DA1C(int);
extern void func_0008E3F7(int, int);
extern void func_00095F82(int);
extern void func_00097101(int);
extern void func_0009721F(void);
extern void func_000973B3(int, unsigned char);
int func_00045A1D(int, int, int, int);
int func_00045EB1(int);
void func_0004504D(int);
void func_00045FFB(int);
void func_00046114(int);
#pragma aux func_0009DA1C parm routine [];
#pragma aux func_000A0ED9 parm routine [];

void func_00044D03(int a1)
{
    int l_1C;
    int l_18;

    func_000A0ED9(78, (int)D_00171044);
    func_000A0F5C((int)D_001903A4, (int)D_0017104D, (int)D_001917E4);
    l_1C = func_0009DC59((int)D_001903A4, 512);
    if (l_1C >= 0) goto L44D9E;
    func_000A0ED9(81, (int)D_00171044);
    func_000A0F5C((int)D_001903A4, (int)D_0017104D, (int)D_00191834);
    l_1C = func_0009DC59((int)D_001903A4, 512);
    if (l_1C < 0) return;
L44D9E:;
    func_000A00CB(l_1C, (int)D_001903A4, 80);
    func_000A16F8((int)D_001903BA, (int)D_0017105A, (int)&l_18);
    if (a1 == 0) goto L44DEF;
    func_0009DA1C(90, (int)D_00171044);
    func_0009DAEE((int)D_0017105D, l_18);
    goto L44E0E;
L44DEF:;
    func_000A0ED9(92, (int)D_00171044);
    func_000A148C((int)D_00171062, l_18);
L44E0E:;
    func_0009DEA7(l_1C);
}

void func_00044E20(int a1)
{
    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 18) return;
    *(int *)D_00199724 = a1;
}

void func_00044E52(void)
{
    func_0007D3CA((int)D_0017BB01);
    *(signed char *)D_00199728 = 1;
    *(signed char *)D_00196274 = 200;
    *(signed char *)D_00196272 = 1;
}

void func_00044E89(void)
{
    int l_18;

    if (*(signed char *)D_00199728 == 0) return;
    if (((struct bf8_2_1 *)&D_001940D4)->f == 0) goto L44EB7;
    l_18 = func_000392AD();
    if (l_18 > (-1)) goto L44EB9;
L44EB7:;
    return;
L44EB9:;
    *(signed char *)D_00199728 = 0;
    *(signed char *)D_00196274 = 0;
    *(signed char *)D_00196272 = 0;
    func_000CAE1C(l_18);
}

void func_00044EE0(void)
{
    func_0001D739();
}

void func_00044EFD(void)
{
    *(short *)(*(char **)D_00195BE0 + 147) = (func_0009DC25() % 50) + 10;
}

void func_00044F3A(void)
{
    *(int *)D_00195BF4 += 43200;
}

void func_00044F5C(void)
{
    *(signed char *)D_001940D9 |= 4;
    func_0003B1F3(1);
}

void func_00044F85(int a1)
{
    int l_24;
    int l_20;
    int l_1C;
    short l_18;

    func_0004504D(a1);
    *(int *)&l_18 = 0;
L44FA5:;
    if (((int)(short)l_18) < *(int *)D_00195D98) goto L44FBE;
    return;
L44FB6:;
    (*(int *)&l_18)++;
    goto L44FA5;
L44FBE:;
    if (*(signed char *)(*(char **)D_00195B04 + 47 + (((int)(short)l_18) * 89)) == 0) goto L44FB6;
    l_20 = func_0008E6C5(*(int *)(*(char **)D_00195AA0 + 63), 27, 0);
    l_20 = func_0008DCE3(l_20, 0, 89);
    *(signed char *)((char *)l_20) = 9;
    *(int *)((char *)l_20 + 31) = func_0008EB88(100);
    func_000A1023(l_20 + 71, (int)(*(char **)D_00195B04 + (((int)(short)l_18) * 89)), 89, (int)D_00171044, 165, 4);
    goto L44FB6;
}

void func_0004504D(int a1)
{
    int l_38;
    int l_34;
    int l_30;
    int l_2C;
    int l_28;
    int l_24;
    int l_20;
    int l_1C;
    int l_18;

    l_18 = func_0009DC25();
    func_0009DC49(12345);
    *(signed char *)D_001940D9 |= 8;
    if (*(signed char *)D_001A5C28 == 0) goto L45086;
    if (a1 != 0) goto L45088;
L45086:;
    goto L45093;
L45088:;
    *(short *)(*(char **)D_00195BE0 + 64) = 1;
L45093:;
    if (((int)(unsigned short)(*(short *)(*(char **)D_00195BE0 + 64) & 1)) == 0) goto L450B6;
    *(int *)D_00195B10 = 12;
    goto L450C0;
L450B6:;
    *(int *)D_00195B10 = 6;
L450C0:;
    *(int *)(*(char **)D_00195BE0 + 133) = 5000;
    *(signed char *)(*(char **)D_00195BE0 + 129) = 2;
    if (a1 == 0) goto L4520C;
    func_0006CB53((int)D_00171077, *(int *)D_00195BEC);
    *(short *)(*(char **)D_00195BEC + 14) = 0;
    *(short *)(*(char **)D_00195BEC + 11) = 0;
    func_000A0AD9(*(int *)D_00195BE0, (int)D_00171083, 32, (int)D_00171044, 197);
    func_000A1023(*(int *)D_00195BE0 + 32, (int)D_0017BAE2, 16, (int)D_00171044, 198, 16);
    func_000A1023(*(int *)D_00195BE0 + 48, *(int *)D_00195BE0 + 32, 16, (int)D_00171044, 199, 16);
    *(signed char *)(*(char **)D_00195BE0 + 66) = 0;
    l_1C = 0;
L45183:;
    if (l_1C < 35) goto L45193;
    goto L451B8;
L4518B:;
    l_1C++;
    goto L45183;
L45193:;
    *(short *)(*(char **)D_00195BE0 + 157 + (l_1C * 6)) = func_0007D6AE(10, 60);
    goto L4518B;
L451B8:;
    *(short *)(*(char **)D_00195BE0 + 289) = 30;
    *(short *)(*(char **)D_00195BE0 + 295) = 30;
    *(short *)(*(char **)D_00195BE0 + 301) = 30;
    *(short *)(*(char **)D_00195BE0 + 307) = 30;
    *(short *)(*(char **)D_00195BE0 + 313) = 30;
    *(short *)(*(char **)D_00195BE0 + 319) = 30;
L4520C:;
    func_000705D9();
    *(short *)((char *)func_000192EE(108) + 29) = 99;
    *(signed char *)((char *)func_000702A0(0)) = 9;
    l_1C = 0;
L45232:;
    if (l_1C < 35) goto L45242;
    goto L45268;
L4523A:;
    l_1C++;
    goto L45232;
L45242:;
    *(short *)(*(char **)D_00195BE0 + 161 + (l_1C * 6)) = *(short *)(*(char **)D_00195BE0 + 157 + (l_1C * 6));
    goto L4523A;
L45268:;
    *(int *)D_00195B30 = (int)D_0018F044;
    l_38 = func_0008DCE3(*(int *)D_001959E0, 0, 107);
    *(short *)((char *)l_38 + 29) = 202;
    *(signed char *)((char *)l_38) = 2;
    l_20 = l_38 + 71;
    func_0005E37F((int)(unsigned short)*(short *)D_00195B10, 10, 11, l_20);
    l_38 = func_0008DCE3(*(int *)D_001959E0, 0, 107);
    *(short *)((char *)l_38 + 29) = 203;
    *(signed char *)((char *)l_38) = 2;
    l_20 = l_38 + 71;
    func_0005E37F((int)(unsigned short)*(short *)D_00195B10, 0, 4, l_20);
    func_00045A1D(*(int *)D_001959E0, *(int *)D_00195B10, 0, 1);
    func_00045A1D(*(int *)D_001959E0, *(int *)D_00195B10, 17, 1);
    func_00045A1D(*(int *)D_001959E0, *(int *)D_00195B10, 9, 0);
    func_00045A1D(*(int *)D_001959E0, *(int *)D_00195B10, 10, 0);
    func_00045A1D(*(int *)D_001959E0, 23, 1, 0);
    l_38 = func_00045A1D(*(int *)D_00195AA0, 23, 0, 0);
    func_0009721F();
    func_00045AED(*(int *)D_001959D8, 2);
    func_00045AED(*(int *)D_001959D8, 2);
    func_00045AED(*(int *)D_001959D8, 2);
    func_00045AED(*(int *)D_001959D8, 2);
    func_00045A1D(*(int *)D_001959D8, 3, 7, 0);
    *(signed char *)D_001962AB = 1;
    func_00045A1D(*(int *)D_001959D8, 3, 1, 0);
    func_00045A1D(*(int *)D_001959D8, 3, 17, 0);
    func_00045A1D(*(int *)D_001959D8, 2, 5, 0);
    func_00045AED(*(int *)D_001959E0, *(int *)D_00195B10);
    func_000973B3(*(int *)D_00195AA0, 250);
    func_0004596E(*(int *)D_001959DC, 4);
    func_0004596E(*(int *)D_001959DC, 4);
    func_0004596E(*(int *)D_001959E4, 20);
    func_0004596E(*(int *)D_001959E4, 20);
    func_0004596E(*(int *)D_001959E4, 17);
    func_00045A1D(*(int *)D_001959E4, 21, 4, 0);
    func_00045A1D(*(int *)D_001959E4, 17, 1, 0);
    func_00045A1D(*(int *)D_001959E0, 25, 2, 0);
    func_00045A1D(*(int *)D_001959E0, 27, 4, 0);
    func_00045A1D(*(int *)D_001959DC, 27, 0, 0);
    func_00045A1D(*(int *)D_001959E0, 27, 1, 0);
    func_00045A1D(*(int *)D_001959E0, 27, 2, 0);
    func_00045A1D(*(int *)D_001959E0, 7, 0, 0);
    func_00045A1D(*(int *)D_001959E0, 7, 0, 0);
    func_00045A1D(*(int *)D_001959E0, 7, 0, 0);
    func_00045A1D(*(int *)D_001959E0, 7, 0, 0);
    func_00045A1D(*(int *)D_001959E0, 7, 0, 0);
    func_00045A1D(*(int *)D_001959E0, 13, 0, 0);
    l_38 = func_0008E6C5(*(int *)(*(char **)D_00195AA0 + 63), 27, 1);
    l_38 = func_0008DCE3(l_38, 0, 0);
    *(signed char *)((char *)l_38) = 20;
    *(short *)((char *)l_38 + 21) = 3;
    *(short *)((char *)l_38 + 27) = 31;
    l_38 = func_0008E6C5(*(int *)(*(char **)D_00195AA0 + 63), 27, 2);
    l_20 = l_38 + 71;
    *(int *)((char *)l_20 + 36) = 10000;
    l_38 = func_0008DCE3(*(int *)D_00195AC4, 0, 107);
    *(signed char *)((char *)l_38) = 2;
    *(signed char *)((char *)l_38 + 21) |= 1;
    func_0005E540(1, 1, l_38 + 71);
    *(int *)((char *)l_38 + 107) = (int)(unsigned short)*(short *)D_00180B42;
    func_00097101(l_38);
    l_38 = func_0008DCE3(l_38, 0, 109);
    *(signed char *)((char *)l_38) = 31;
    func_000A1023(l_38 + 71, (int)D_00180B3A, 109, (int)D_00171044, 289, 4);
    l_38 = func_0008DCE3(*(int *)D_001959DC, 0, 107);
    *(signed char *)((char *)l_38) = 2;
    l_20 = l_38 + 71;
    func_0006077F(l_20, 7);
    l_38 = func_0008DCE3(*(int *)D_001959DC, 0, 107);
    *(signed char *)((char *)l_38) = 2;
    l_20 = l_38 + 71;
    func_0006077F(l_20, 8);
    l_38 = func_0008DCE3(*(int *)D_001959DC, 0, 107);
    *(signed char *)((char *)l_38) = 2;
    l_20 = l_38 + 71;
    func_0006077F(l_20, 2);
    l_38 = func_0008DCE3(*(int *)D_001959DC, 0, 107);
    *(signed char *)((char *)l_38) = 2;
    l_20 = l_38 + 71;
    func_0006077F(l_20, 10);
    l_38 = func_0008DCE3(*(int *)D_001959DC, 0, 107);
    *(signed char *)((char *)l_38) = 2;
    l_20 = l_38 + 71;
    func_0006077F(l_20, (int)(unsigned char)*(signed char *)D_001962A6);
    func_0004F3F6();
    *(signed char *)D_001940D9 &= 247;
    func_0009DC49(l_18);
}

void func_0004579D(void)
{
    int l_20;
    int l_1C;
    int l_18;

    *(signed char *)D_001940D9 |= 8;
    if (((int)(unsigned short)(*(short *)(*(char **)D_00195BE0 + 64) & 1)) == 0) goto L457D5;
    *(int *)D_00195B10 = 12;
    goto L457DF;
L457D5:;
    *(int *)D_00195B10 = 6;
L457DF:;
    if (((int)(unsigned short)(*(short *)(*(char **)D_00195BE0 + 64) & 1)) == 0) goto L45812;
    func_00045A1D(*(int *)D_001959E0, *(int *)D_00195B10, 8, 1);
    goto L4582C;
L45812:;
    func_00045A1D(*(int *)D_001959E0, *(int *)D_00195B10, 10, 1);
L4582C:;
    func_00045A1D(*(int *)D_001959E0, *(int *)D_00195B10, 24, 1);
    if (((int)(unsigned char)*(signed char *)(D_0017BABC + (*(int *)D_00199634 * 2))) == 255) goto L45878;
    if (((int)(unsigned char)*(signed char *)(D_0017BABC + (*(int *)D_00199634 * 2))) != 254) goto L4587A;
L45878:;
    goto L458CB;
L4587A:;
    *(signed char *)D_001962AB = *(signed char *)(D_0017BABD + (*(int *)D_00199634 * 2)) + 1;
    l_18 = func_00045A1D(*(int *)D_001959D8, 3, (int)(unsigned char)*(signed char *)(D_0017BABC + (*(int *)D_00199634 * 2)), 0);
    *(signed char *)((char *)l_18 + 127) = *(signed char *)((char *)l_18 + 125) + 16;
    *(int *)((char *)l_18 + 107) = 15;
    goto L4592C;
L458CB:;
    if (((int)(unsigned char)*(signed char *)(D_0017BABC + (*(int *)D_00199634 * 2))) != 254) goto L4592C;
    l_18 = func_00045A1D(*(int *)D_001959D8, 3, 17, 0);
    *(signed char *)D_001962AB = 1;
    l_18 = func_00045A1D(*(int *)D_001959D8, 3, 14, 0);
    func_000973B3(*(int *)D_00195AA0, 24);
L4592C:;
    func_00045A1D(*(int *)D_001959DC, 27, 0, 0);
    func_00045FFB(func_0008E6C5(*(int *)(*(char **)D_00195AA0 + 63), 27, 0));
    func_0004F3F6();
    *(signed char *)D_001940D9 &= 247;
}

int func_00045A1D(int a1, int a2, int a3, int a4)
{
    int l_18;
    int l_14;
    int l_10;

    l_18 = func_0008DCE3(a1, 0, 107);
    *(signed char *)((char *)l_18) = 2;
    l_10 = l_18 + 71;
    func_0005E540((int)(unsigned short)*(short *)&a2, a3, l_10);
    if (((int)(unsigned short)(*(short *)((char *)l_10 + 42) & 8)) == 0) goto L45ACF;
    l_14 = func_0008DCE3(a1, 0, 107);
    *(signed char *)((char *)l_14) = 2;
    func_0008DD46(l_14, l_18);
    l_10 = l_14 + 71;
    func_0005E540(1, 1, l_10);
    if (a4 == 0) goto L45AC7;
    func_00095F82(l_14);
L45AC7:;
    return l_14;
L45ACF:;
    if (a4 == 0) goto L45ADD;
    func_00095F82(l_18);
L45ADD:;
    return l_18;
}

void func_00045B41(void)
{
    *(signed char *)D_001940D6 ^= 1;
}

void func_00045B60(void)
{
    *(signed char *)D_001940D6 ^= 8;
}

void func_00045B7F(void)
{
    int l_1C;
    int l_18;

    *(signed char *)D_00190CE4 = 1;
    *(short *)(*(char **)D_00195BE0 + 247) = 80;
    l_1C = func_0008DCE3(*(int *)D_00195AC4, 0, 659);
    *(signed char *)((char *)l_1C) = 18;
    l_18 = func_0009DC25() % 20;
    *(signed char *)D_00190CE4 = 2;
    *(signed char *)D_00190CE5 = *(signed char *)&l_18;
    func_00078566(l_1C, l_18);
    *(signed char *)D_00190CE4 = 3;
    func_000A0ED9(448, (int)D_00171044);
    func_000A0F5C((int)D_001903A4, (int)D_00171096, *(int *)(D_001830E6 + (l_18 << 2)));
    func_0007CBA1((int)D_001903A4);
    *(signed char *)D_00190CE4 = 4;
    func_0001374D(l_1C);
    *(signed char *)D_00190CE4 = 5;
    func_0008DA1C(l_1C);
    *(signed char *)D_00190CE4 = 6;
    func_0008DA4D(l_1C);
    *(signed char *)D_00190CE4 = 7;
}

void func_00045C6B(void)
{
    *(signed char *)D_001940DA ^= 2;
    if (((struct bf8_1_1 *)&D_001940DA)->f == 0) return;
    func_0007CBA1((int)D_001710A7);
}

void func_00045C9D(void)
{
    int l_18;

    func_000A0040(*(int *)D_00195BE0 + 367, 0, 108, (int)D_00171044, 469, 108);
    l_18 = *(int *)(*(char **)D_00195AA0 + 63);
L45CD8:;
    if (l_18 == 0) return;
    l_18 = func_0008DA91(l_18);
    goto L45CD8;
}

void func_00045CF5(void)
{
    int l_24;
    int l_20;
    int l_1C;
    int l_18;

    *(signed char *)D_0012B508 = 146;
    l_24 = 0;
    l_20 = l_24;
    l_1C = l_20;
L45D1D:;
    if (l_24 < 512) goto L45D33;
    goto L45DD7;
L45D2B:;
    l_24++;
    goto L45D1D;
L45D33:;
    if (*(int *)(D_00132F6C + (l_24 << 2)) == 0) goto L45D2B;
    l_18 = *(int *)(D_00132F6C + (l_24 << 2)) - 22;
    func_000A0ED9(487, (int)D_00171044);
    func_000A0F5C((int)D_001903A4, (int)D_001710BA, *(int *)((char *)l_18 + 8), *(int *)(D_00132F6C + (l_24 << 2)) + 2);
    func_0005A54A((int)D_001903A4, (l_20 / 25) * 160, (l_20 % 25) << 3);
    l_20++;
    l_1C += *(int *)((char *)l_18 + 8);
    goto L45D2B;
L45DD7:;
    *(signed char *)D_0012B508 = 245;
    func_000A0ED9(494, (int)D_00171044);
    func_000A0F5C((int)D_001903A4, (int)D_001710C3, l_1C);
    func_0005A54A((int)D_001903A4, (l_20 / 25) * 160, (l_20 % 25) << 3);
}

int func_00045E45(int a1)
{
    short l_1C;
    int l_24;
    short l_18;

    *(int *)&l_18 = a1;
    *(int *)&l_1C = *(int *)D_00196A90;
    l_24 = 0;
L45E6B:;
    if (l_24 < *(int *)D_00196A8C) goto L45E87;
    goto L45E9D;
L45E78:;
    l_24++;
    (*(char (**)[6])&(*(int *)&l_1C))++;
    goto L45E6B;
L45E87:;
    if ((short)*(int *)&l_18 != *(short *)(*(char **)&l_1C + 4)) goto L45E9B;
    return *(int *)&l_1C;
L45E9B:;
    goto L45E78;
L45E9D:;
    return 0;
}

int func_00045EB1(int a1)
{
    int l_20;
    int l_1C;

    l_20 = 0;
L45EC9:;
    if (l_20 < 12) goto L45ED9;
    goto L45F11;
L45ED1:;
    l_20++;
    goto L45EC9;
L45ED9:;
    l_1C = 0;
L45EE0:;
    if (l_1C < 6) goto L45EF0;
    goto L45F0F;
L45EE8:;
    l_1C++;
    goto L45EE0;
L45EF0:;
    if (*(signed char *)((char *)(a1 + l_20) + 16) != *(signed char *)(D_0017BB39 + l_1C)) goto L45F0D;
    return 1;
L45F0D:;
    goto L45EE8;
L45F0F:;
    goto L45ED1;
L45F11:;
    return 0;
}

void func_00045F25(void)
{
    int l_1C;
    int l_18;

    l_1C = *(int *)D_0019672C;
    func_0007CBA1((int)D_001710D6);
    l_18 = 0;
L45F4C:;
    if (l_18 < *(int *)D_00196710) goto L45F68;
    goto L45F7E;
L45F59:;
    l_18++;
    (*(char (**)[92])&l_1C)++;
    goto L45F4C;
L45F68:;
    if (((int)(short)*(short *)((char *)l_1C + 29)) > 90) goto L45F7C;
    *(short *)((char *)l_1C + 29) += 10;
L45F7C:;
    goto L45F59;
L45F7E:;
    *(signed char *)D_00142314 = 0;
}

void func_00045F8F(void)
{
    int l_18;

    func_0007CBA1((int)D_001710EB);
    l_18 = 0;
L45FAE:;
    if (l_18 < 35) goto L45FBE;
    goto L45FEA;
L45FB6:;
    l_18++;
    goto L45FAE;
L45FBE:;
    if (((int)(short)*(short *)(*(char **)D_00195BE0 + 157 + (l_18 * 6))) == 100) goto L45FE8;
    (*(short *)(*(char **)D_00195BE0 + 157 + (l_18 * 6)))++;
L45FE8:;
    goto L45FB6;
L45FEA:;
    *(signed char *)D_00142315 = 0;
}

void func_00045FFB(int a1)
{
    int l_24;
    int l_20;
    int l_1C;
    int l_18;

    l_24 = 0;
    if (*(int *)D_00199634 <= 6) goto L46025;
    if (*(int *)D_00199634 != 18) goto L46027;
L46025:;
    goto L4602C;
L46027:;
    return;
L4602C:;
    if (*(int *)D_00199634 != 18) goto L46043;
    if (func_00045EB1(*(int *)D_00195BEC) == 0) goto L46045;
L46043:;
    goto L4604A;
L46045:;
    return;
L4604A:;
    if (*(int *)D_00199634 != 18) goto L4605C;
    l_1C = 1;
    goto L46064;
L4605C:;
    l_1C = *(int *)D_00199634;
L46064:;
    if (((int)(unsigned char)*(signed char *)(D_0017BB3F + ((l_1C * 6) + l_24))) == 255) return;
    l_18 = func_0008DCE3(a1, 0, 89);
    *(signed char *)((char *)l_18) = 9;
    *(int *)((char *)l_18 + 31) = func_0008EB88(100);
    l_20 = 0;
L460B2:;
    if (*(signed char *)((char *)(int)((l_20 * 89) + *(char **)D_00195B04) + 73) == *(signed char *)(D_0017BB3F + ((l_1C * 6) + l_24))) goto L460D8;
    l_20++;
    goto L460B2;
L460D8:;
    func_000A1023(l_18 + 71, (int)(*(char **)D_00195B04 + (l_20 * 89)), 89, (int)D_00171044, 582, 4);
    l_24++;
    goto L46064;
}

void func_00046114(int a1)
{
    int l_18;

    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 32) return;
    if (*(int *)((char *)a1 + 11) < (-1300)) goto L4614C;
    if (*(int *)((char *)a1 + 11) <= (-1200)) goto L4614E;
L4614C:;
    return;
L4614E:;
    l_18 = func_000C7FD9(*(int *)((char *)a1 + 7), *(int *)((char *)a1 + 15), *(int *)(*(char **)D_00195AC4 + 7) + 664, *(int *)(*(char **)D_00195AC4 + 15) + 2035);
    if (l_18 >= *(int *)D_00199718) return;
    *(int *)D_00199714 = a1;
    *(int *)D_00199718 = l_18;
}

int func_000461A3(void)
{
    *(int *)D_00199718 = 50000;
    *(int *)D_00199714 = 0;
    func_0008E3F7(*(int *)D_00195AC4, (int)func_00046114);
    return *(int *)D_00199714;
}
