/* kludge.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/kludge.c to work on it by hand) */

extern char D_00171044[];
extern char D_001710A7[];
extern char D_0017BB01[];
extern char D_0017BB39[];
extern char D_001940D4[];
extern char D_001940D6[];
extern char D_001940D9[];
extern char D_001940DA[];
extern char D_00195AA0[];
extern char D_00195AC4[];
extern char D_00195BE0[];
extern char D_00195BF4[];
extern char D_00196272[];
extern char D_00196274[];
extern char D_00199714[];
extern char D_00199718[];
extern char D_00199724[];
extern char D_00199728[];

extern int func_000392AD(void);
extern int func_0003B1F3(short);
extern int func_0007CBA1(int);
extern int func_0008DA91(int);
extern int func_000A0040();
extern int func_000C7FD9();
extern int func_000CAE1C();
extern void func_0001D739(void);
extern void func_0007D3CA(int);
extern void func_0008E3F7(int, int);
void func_00046114(int);

void func_00044E20(int a1)
{
    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 18) return;
    *(int *)D_00199724 = a1;
}

void func_00044E52(void)
{
    func_0007D3CA((int)D_0017BB01);
    *(signed char *)D_00199728 = 1;
    *(signed char *)D_00196274 = 200;
    *(signed char *)D_00196272 = 1;
}

void func_00044E89(void)
{
    int l_18;

    if (*(signed char *)D_00199728 == 0) return;
    if ((*(signed char *)D_001940D4 & 4) == 0) goto L44EB7;
    l_18 = func_000392AD();
    if (l_18 > (-1)) goto L44EB9;
L44EB7:;
    return;
L44EB9:;
    *(signed char *)D_00199728 = 0;
    *(signed char *)D_00196274 = 0;
    *(signed char *)D_00196272 = 0;
    func_000CAE1C(l_18);
}

void func_00044EE0(void)
{
    func_0001D739();
}

void func_00044F3A(void)
{
    *(int *)D_00195BF4 += 43200;
}

void func_00044F5C(void)
{
    *(signed char *)D_001940D9 |= 4;
    func_0003B1F3(1);
}

void func_00045B41(void)
{
    *(signed char *)D_001940D6 ^= 1;
}

void func_00045B60(void)
{
    *(signed char *)D_001940D6 ^= 8;
}

void func_00045C6B(void)
{
    *(signed char *)D_001940DA ^= 2;
    if ((*(signed char *)D_001940DA & 2) == 0) return;
    func_0007CBA1((int)D_001710A7);
}

void func_00045C9D(void)
{
    int l_18;

    func_000A0040(*(int *)D_00195BE0 + 367, 0, 108, (int)D_00171044, 469, 108);
    l_18 = *(int *)((char *)*(int *)D_00195AA0 + 63);
L45CD8:;
    if (l_18 == 0) return;
    l_18 = func_0008DA91(l_18);
    goto L45CD8;
}

int func_00045EB1(int a1)
{
    int l_20;
    int l_1C;

    l_20 = 0;
L45EC9:;
    if (l_20 < 12) goto L45ED9;
    goto L45F11;
L45ED1:;
    l_20++;
    goto L45EC9;
L45ED9:;
    l_1C = 0;
L45EE0:;
    if (l_1C < 6) goto L45EF0;
    goto L45F0F;
L45EE8:;
    l_1C++;
    goto L45EE0;
L45EF0:;
    if (*(signed char *)((char *)(a1 + l_20) + 16) != *(signed char *)(D_0017BB39 + l_1C)) goto L45F0D;
    return 1;
L45F0D:;
    goto L45EE8;
L45F0F:;
    goto L45ED1;
L45F11:;
    return 0;
}

void func_00046114(int a1)
{
    int l_18;

    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 32) return;
    if (*(int *)((char *)a1 + 11) < (-1300)) goto L4614C;
    if (*(int *)((char *)a1 + 11) <= (-1200)) goto L4614E;
L4614C:;
    return;
L4614E:;
    l_18 = func_000C7FD9(*(int *)((char *)a1 + 7), *(int *)((char *)a1 + 15), *(int *)((char *)*(int *)D_00195AC4 + 7) + 664, *(int *)((char *)*(int *)D_00195AC4 + 15) + 2035);
    if (l_18 >= *(int *)D_00199718) return;
    *(int *)D_00199714 = a1;
    *(int *)D_00199718 = l_18;
}

int func_000461A3(void)
{
    *(int *)D_00199718 = 50000;
    *(int *)D_00199714 = 0;
    func_0008E3F7(*(int *)D_00195AC4, (int)func_00046114);
    return *(int *)D_00199714;
}
