/* loadsave.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/loadsave.c to work on it by hand) */

extern char D_0012AC02[];
extern char D_0012DE00[];
extern char D_00147954[];
extern char D_00176884[];
extern char D_0017688F[];
extern char D_001768BD[];
extern char D_001768D5[];
extern char D_001768DF[];
extern char D_001768E4[];
extern char D_001768FC[];
extern char D_00176909[];
extern char D_00176934[];
extern char D_0017693D[];
extern char D_001769EA[];
extern char D_001769F7[];
extern char D_00178A0E[];
extern char D_00178A10[];
extern char D_00178A14[];
extern char D_00178A18[];
extern char D_00187F28[];
extern char D_0018DD94[];
extern char D_0018DDB4[];
extern char D_0018DDD4[];
extern char D_0018DE14[];
extern char D_0018DE44[];
extern char D_0018F044[];
extern char D_001903A4[];
extern char D_00190D16[];
extern char D_00190FE4[];
extern char D_001913E4[];
extern char D_001940D4[];
extern char D_001940D5[];
extern char D_001940D7[];
extern char D_001940D8[];
extern char D_001952EC[];
extern char D_001952EE[];
extern char D_00195303[];
extern char D_0019530D[];
extern char D_00195998[];
extern char D_0019599C[];
extern char D_001959A0[];
extern char D_001959A4[];
extern char D_001959A8[];
extern char D_001959AC[];
extern char D_001959B0[];
extern char D_001959B4[];
extern char D_001959B8[];
extern char D_001959C4[];
extern char D_001959D8[];
extern char D_001959FC[];
extern char D_00195A00[];
extern char D_00195A04[];
extern char D_00195A08[];
extern char D_00195A0C[];
extern char D_00195A14[];
extern char D_00195A78[];
extern char D_00195A8C[];
extern char D_00195A98[];
extern char D_00195A9C[];
extern char D_00195AA0[];
extern char D_00195AA4[];
extern char D_00195AAC[];
extern char D_00195AB8[];
extern char D_00195AC4[];
extern char D_00195AE8[];
extern char D_00195B10[];
extern char D_00195B18[];
extern char D_00195B44[];
extern char D_00195B84[];
extern char D_00195B98[];
extern char D_00195BE0[];
extern char D_00195BEC[];
extern char D_00195BF4[];
extern char D_00195BF8[];
extern char D_00195BFC[];
extern char D_00195C40[];
extern char D_00195C44[];
extern char D_00195CDC[];
extern char D_00195CE0[];
extern char D_00195CE4[];
extern char D_00195D48[];
extern char D_00195E2A[];
extern char D_00195F62[];
extern char D_00195FB1[];
extern char D_001961F5[];
extern char D_00196263[];
extern char D_00196265[];
extern char D_00196266[];
extern char D_00196268[];
extern char D_0019626A[];
extern char D_0019627C[];
extern char D_0019627D[];
extern char D_0019627E[];
extern char D_0019627F[];
extern char D_00196280[];
extern char D_00196289[];
extern char D_0019629B[];
extern char D_0019976C[];
extern char D_00199808[];
extern char D_001A4A0C[];
extern char D_001A4FE0[];
extern char D_001A4FE4[];
extern char D_001A94C4[];
extern char D_001A94C8[];
extern char D_001A99F8[];
extern char D_001A99FC[];
extern char D_001A9A00[];
extern char D_001A9A04[];
extern char D_001AA540[];
extern char D_001AA544[];
extern char D_001AA57C[];
extern char D_001AA580[];

extern int func_000641CD(int);
extern int func_00079A28(int);
extern int func_00079D0D(int, int, int);
extern int func_0007B624(int, int, int, int);
extern int func_0008DA91(int);
extern int func_0008DD46(int, int);
extern int func_0008E925(int, int);
extern int func_0008EB88(int);
extern int func_0009DC59(int, ...);
extern int func_0009DEA7();
extern int func_000A0040();
extern int func_000A00CB();
extern int func_000A0AD9();
extern int func_000A0B42();
extern int func_000A0E3B();
extern int func_000A0ED9(int, int);
extern int func_000A0F5C(int, ...);
extern int func_000A1004();
extern int func_000A1023();
extern int func_000C010F();
extern int func_0012A274();
extern int func_0012A2D0();
extern void func_0001C960(int);
extern void func_0001CA8C(int);
extern void func_00050069(int);
extern void func_0007A3D0(int);
extern void func_0008E357(int, int);
extern void func_0008E3A7(int, int);
extern void func_0008E3F7(int, int);
int func_00079A6E(int);
int func_00079E6E(int);
void func_00079C75(int);
void func_0007A02A(int);
void func_0007A191(int);
void func_0007A23E(int);
void func_0007A325(int);
void func_0007A42B(int);
void func_0007C56F(int);
void func_0007C78B(int);
#pragma aux func_000A0ED9 parm routine [];

int func_00079A6E(int a1)
{
    int l_28;
    char l_24[12];

    l_28 = *(int *)D_00195C44;
    *(int *)l_24 = *(int *)((char *)a1 - 6);
    if (*(int *)l_24 != 0) goto L79AC1;
    func_000A0ED9(84, (int)D_00176884);
    func_000A0F5C(*(int *)D_00195C44, (int)D_0017688F);
    func_00050069(*(int *)D_00195C44);
L79AC1:;
    func_000A0B42(*(int *)D_001A4A0C, (int)l_24, 4);
    func_000A1023(l_28, a1, *(int *)l_24, (int)D_00176884, 90, 4);
    if (*(int *)((char *)l_28 + 51) == 0) goto L79B17;
    if (*(signed char *)((char *)l_28 + 38) == 0) goto L79B0D;
    *(int *)((char *)l_28 + 51) = *(int *)((char *)*(int *)((char *)l_28 + 51) + 31);
    goto L79B17;
L79B0D:;
    *(int *)((char *)l_28 + 51) = 0;
L79B17:;
    switch (*(unsigned char *)((char *)a1)) {
case 3:
case 18:
case 44:
    func_0007A325(l_28);
    goto L79B84;
case 9:
    if (((int)(unsigned char)*(signed char *)((char *)*(int *)((char *)a1 + 67))) == 3) goto L79B75;
    if (((int)(unsigned char)*(signed char *)((char *)*(int *)((char *)a1 + 67))) != 18) goto L79B84;
L79B75:;
    *(int *)((char *)l_28 + 47) = *(int *)((char *)*(int *)((char *)l_28 + 47) + 31);
default:
L79B84:;
    if (*(int *)((char *)a1 + 67) == 0) goto L79BAC;
    *(int *)((char *)l_28 + 67) = (int)(unsigned char)*(signed char *)((char *)*(int *)((char *)a1 + 67));
    *(int *)((char *)l_28 + 39) = *(int *)((char *)*(int *)((char *)a1 + 67) + 31);
L79BAC:;
    if (func_000A0B42(*(int *)D_001A4A0C, l_28, *(int *)l_24) == *(int *)l_24) goto L79BCA;
{
    int l_34;
    l_34 = 1;
    goto L79BD1;
L79BCA:;
    l_34 = 0;
L79BD1:;
    return l_34;
}
}
}

void func_00079BE4(int a1)
{
    int l_24;
    int l_20;
    int l_1C;
    int l_18;

    l_24 = *(int *)D_00195C44;
    l_18 = func_00079A28(l_24);
L79C08:;
    if (l_18 == 0) return;
    *(int *)((char *)l_24 + 59) = 0;
    *(int *)((char *)l_24 + 55) = *(int *)((char *)l_24 + 59);
    *(int *)((char *)l_24 + 67) = *(int *)((char *)l_24 + 55);
    *(int *)((char *)l_24 + 63) = *(int *)((char *)l_24 + 67);
    l_20 = func_00079D0D(a1, l_24, l_18);
    func_0007A02A(l_20);
    l_1C = *(int *)((char *)l_20 + 31);
    l_18 = func_00079A28(l_24);
    goto L79C08;
}

void func_00079C75(int a1)
{
    int l_18;

    l_18 = *(int *)((char *)a1 + 55);
    *(int *)((char *)a1 + 55) = 0;
    func_0008E357(a1, (int)func_00079A6E);
    *(int *)((char *)a1 + 55) = l_18;
}

void func_00079CB9(int a1)
{
    int l_20;
    int l_1C;
    int l_18;

    l_18 = 0;
L79CD1:;
    if (a1 == 0) return;
    if (func_00079E6E(a1) == 0) goto L79CED;
    func_00079C75(a1);
    goto L79CF8;
L79CED:;
    func_00079CB9(*(int *)((char *)a1 + 63));
L79CF8:;
    a1 = *(int *)((char *)a1 + 55);
    goto L79CD1;
}

int func_00079E6E(int a1)
{
    if (*(signed char *)((char *)a1 + 38) == 0) goto L79E94;
    return 1;
L79E94:;
    if (func_000641CD(a1) == 0) goto L79EAC;
    return 1;
L79EAC:;
    switch (*(unsigned char *)((char *)a1)) {
    goto L7A00D;
case 8:
    return (int)(unsigned short)(*(short *)((char *)a1 + 21) & 512);
case 2:
case 3:
case 4:
case 9:
case 14:
case 18:
case 19:
case 20:
case 25:
case 26:
case 27:
case 32:
case 36:
case 42:
case 44:
case 45:
case 46:
case 51:
case 52:
case 53:
case 54:
    return 1;
case 33:
    if (*(int *)((char *)a1 + 63) == 0) goto L79FBB;
    return 1;
L79FBB:;
    if (*(short *)((char *)a1 + 25) == 0) goto L79FCE;
    return 1;
L79FCE:;
    goto L7A016;
case 34:
    if ((((int)(unsigned short)(*(short *)((char *)a1 + 27) & 31)) - 2) == 14) goto L7A002;
    if ((((int)(unsigned short)(*(short *)((char *)a1 + 27) & 31)) - 2) != 13) goto L7A00B;
L7A002:;
    return 1;
L7A00B:;
    goto L7A016;
default:
L7A00D:;
    return 0;
L7A016:;
    return 0;
}
}

void func_0007A02A(int a1)
{
    switch (*(unsigned char *)((char *)a1)) {
    return;
case 4:
    *(int *)D_00195AA4 = a1;
    return;
case 5:
    *(int *)D_00195A98 = a1;
    return;
case 3:
    *(int *)D_00195AA0 = a1;
    *(int *)D_00195BE0 = *(int *)D_00195AA0 + 71;
    *(int *)D_00195BEC = *(int *)D_00195BE0 + 560;
    return;
case 52:
    if (*(int *)(D_001959D8 + (((int)(unsigned short)*(short *)((char *)a1 + 27)) << 2)) == 0) goto L7A133;
    if (*(int *)((char *)*(int *)(D_001959D8 + (((int)(unsigned short)*(short *)((char *)a1 + 27)) << 2)) + 63) != 0) goto L7A148;
L7A133:;
    *(int *)(D_001959D8 + (((int)(unsigned short)*(short *)((char *)a1 + 27)) << 2)) = a1;
L7A148:;
    return;
case 16:
    *(int *)D_00195A00 = a1;
    return;
case 23:
    *(int *)D_001959B4 = a1;
    *(int *)D_00195BF8 = *(int *)D_001959B4 + 71;
    return;
case 24:
    *(int *)D_001959B0 = a1;
    return;
case 25:
    *(int *)D_00195A04 = a1;
    return;
case 39:
    *(int *)D_001959A8 = a1;
default:;
}
}

void func_0007A191(int a1)
{
    switch (*(unsigned char *)((char *)a1)) {
case 3:
case 18:
case 44:
    func_0007A23E(a1);
    return;
case 9:
    *(int *)((char *)a1 + 47) = func_0008E925(*(int *)D_00195AC4, *(int *)((char *)a1 + 47));
default:;
}
}

void func_0007A1FE(void)
{
    func_0008E3F7(*(int *)D_00195AC4, (int)func_0007A191);
    func_0008E3F7(*(int *)D_001959A8, (int)func_0007A191);
    *(int *)D_001AA57C = *(int *)D_001959D8;
}

void func_0007A23E(int a1)
{
    int l_24;
    int l_20;
    int l_1C;
    int l_18;

    l_24 = a1 + 71;
    l_20 = l_24 + 560;
    l_1C = l_20 + 74;
    l_18 = 0;
L7A273:;
    if (l_18 < 27) goto L7A283;
    goto L7A2C1;
L7A27B:;
    l_18++;
    goto L7A273;
L7A283:;
    if (*(int *)((char *)((l_18 << 2) + l_24) + 367) == 0) goto L7A2BF;
    *(int *)((char *)((l_18 << 2) + l_24) + 367) = func_0008E925(*(int *)D_00195AC4, *(int *)((char *)((l_18 << 2) + l_24) + 367));
L7A2BF:;
    goto L7A27B;
L7A2C1:;
    if (*(int *)((char *)l_24 + 112) == 0) goto L7A2F5;
    *(int *)((char *)l_24 + 112) = func_0008E925(*(int *)D_00195AC4, *(int *)((char *)l_24 + 112));
    if (*(int *)((char *)l_24 + 112) != 0) goto L7A2F5;
    func_00050069((int)D_001768BD);
L7A2F5:;
    if (((int)(unsigned char)*(signed char *)((char *)a1)) == 18) goto L7A313;
    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 44) return;
L7A313:;
    func_000C010F(l_1C);
}

void func_0007A325(int a1)
{
    int l_1C;
    int l_18;

    l_1C = a1 + 71;
    l_18 = 0;
L7A346:;
    if (l_18 < 27) goto L7A356;
    goto L7A38B;
L7A34E:;
    l_18++;
    goto L7A346;
L7A356:;
    if (*(int *)((char *)((l_18 << 2) + l_1C) + 367) == 0) goto L7A389;
    *(int *)((char *)((l_18 << 2) + l_1C) + 367) = *(int *)((char *)*(int *)((char *)((l_18 << 2) + l_1C) + 367) + 31);
L7A389:;
    goto L7A34E;
L7A38B:;
    if (*(int *)((char *)l_1C + 112) == 0) return;
    if (func_0008E925(*(int *)D_00195AC4, *(int *)((char *)*(int *)((char *)l_1C + 112) + 31)) == 0) goto L7A3BC;
    *(int *)((char *)l_1C + 112) = *(int *)((char *)*(int *)((char *)l_1C + 112) + 31);
    return;
L7A3BC:;
    *(int *)((char *)l_1C + 112) = 0;
}

void func_0007A42B(int a1)
{
    int l_1C;
    int l_18;

    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 34) goto L7A45A;
    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 32) goto L7A45C;
L7A45A:;
    return;
L7A45C:;
    l_1C = *(int *)D_00195C44;
    l_18 = 0;
L7A46B:;
    if (l_18 < *(int *)D_00195B84) goto L7A487;
    return;
L7A478:;
    l_18++;
    (*(char (**)[4])&l_1C)++;
    goto L7A46B;
L7A487:;
    if (*(int *)((char *)a1 + 31) != *(int *)((char *)l_1C)) goto L7A4A7;
    func_0008DA91(a1);
    *(int *)((char *)l_1C) = 0;
    return;
L7A4A7:;
    goto L7A478;
}

void func_0007A4B3(void)
{
    *(int *)D_00195B84 = 0;
    func_0008E3F7(*(int *)((char *)*(int *)D_00195AC4 + 63), (int)func_0007A3D0);
    func_0008E3A7(*(int *)((char *)*(int *)D_00195AC4 + 63), (int)func_0007A42B);
}

void func_0007A4F9(void)
{
    func_000A0ED9(494, (int)D_00176884);
    func_000A0F5C((int)D_001913E4, (int)D_001768DF, (int)D_001903A4, (int)D_001768D5);
    func_000A1004((int)D_001913E4);
    *(int *)D_001A4A0C = func_0009DC59((int)D_001913E4, 546, 384);
    if (*(int *)D_001A4A0C >= 0) goto L7A571;
    func_00050069((int)D_001768E4);
L7A571:;
    func_000A0B42(*(int *)D_001A4A0C, *(int *)D_00147954 + 24000, 4000);
    func_0009DEA7(*(int *)D_001A4A0C);
}

int func_0007A5A0(int a1)
{
    func_000A0ED9(516, (int)D_00176884);
    func_000A0F5C((int)D_001913E4, (int)D_001768DF, (int)D_001903A4, (int)D_001768FC);
    func_000A1004((int)D_001913E4);
    *(int *)D_001A4A0C = func_0009DC59((int)D_001913E4, 546, 384);
    func_000A0B42(*(int *)D_001A4A0C, a1, 32);
    func_0009DEA7(*(int *)D_001A4A0C);
    return 0;
}

void func_0007A8BE(void)
{
    int l_24;
    int l_20;
    int l_1C;
    int l_18;

    l_24 = *(int *)((char *)*(int *)D_00195A00 + 63);
    l_1C = 0;
    l_18 = 0;
    if (((int)(unsigned char)*(signed char *)D_00196268) == 31) return;
L7A8F5:;
    if (l_24 == 0) goto L7A938;
    if (((int)(unsigned char)*(signed char *)((char *)l_24)) != 14) goto L7A92D;
    l_20 = l_24 + 71;
    if (func_000A0E3B(l_20 + 6, (int)D_00176934) != 0) goto L7A92D;
    l_18++;
L7A92D:;
    l_24 = *(int *)((char *)l_24 + 55);
    goto L7A8F5;
L7A938:;
    if (l_18 != 0) goto L7A947;
    if (*(signed char *)D_00195303 != 0) goto L7A949;
L7A947:;
    goto L7A952;
L7A949:;
    if (*(signed char *)D_0019530D == 0) goto L7A954;
L7A952:;
    return;
L7A954:;
    func_000A0AD9((int)D_001961F5, (int)D_0017693D, 13, (int)D_00176884, 616);
    *(signed char *)D_001952EE = 0;
}

int func_0007B5AF(int a1, int a2, int a3, int a4)
{
    if (*(signed char *)D_0012AC02 == 0) goto L7B5E9;
    func_0007B624(a1, a2, a3, a4);
    return -1;
L7B5E9:;
    if (a1 >= 6) goto L7B604;
    return a1 % 3;
L7B604:;
    return (a1 % 3) + 3;
}

int func_0007B72D(int a1, int a2, int a3, int a4)
{
    *(signed char *)D_00190D16 = 1;
    return -1;
}

void func_0007B9A1(int a1)
{
    func_000A0ED9(1008, (int)D_00176884);
    func_000A0F5C((int)D_001903A4, (int)D_00176909, a1);
    func_000A0ED9(1009, (int)D_00176884);
    func_000A0F5C((int)D_00190FE4, (int)D_001768DF, (int)D_001903A4, (int)D_001769EA);
    *(int *)D_001A4A0C = func_0009DC59((int)D_00190FE4, 512);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_0018DE14, 48);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_0018DDD4, 64);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001959B8, 12);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00196266, 1);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195A14, 100);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001959C4, 20);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00178A0E, 2);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_0018DE44, 512);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00196265, 1);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195FB1, 71);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001959FC, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195A08, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195A0C, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195A78, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001952EC, 64);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195F62, 2);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00196280, 1);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001961F5, 13);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00178A10, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_0019627E, 1);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_0019627F, 1);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_0019627C, 1);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_0019627D, 1);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00178A14, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195CDC, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195CE0, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195CE4, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195E2A, 6);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001940D4, 8);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001959AC, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195BF4, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195C40, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195B10, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195B18, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_0019626A, 1);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_0018F044, 4960);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00196268, 1);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195AE8, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195AB8, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195AAC, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195A8C, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00178A18, 2);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001959A4, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001959A0, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_0018DD94, 32);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_0018DDB4, 32);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00196263, 1);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_0019599C, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195998, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001A94C8, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00195E2A, 6);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_0012DE00, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_00187F28, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001A9A04, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001A99F8, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001A99FC, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001A9A00, 4);
    if (*(int *)D_001A4FE4 < 294) goto L7BEDE;
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001AA540, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001AA544, 4);
    func_000A00CB(*(int *)D_001A4A0C, (int)D_001AA580, 4);
L7BEDE:;
    func_0001CA8C(*(int *)D_001A4A0C);
    func_0009DEA7(*(int *)D_001A4A0C);
}

void func_0007BEFC(int a1)
{
    func_000A0ED9(1092, (int)D_00176884);
    func_000A0F5C((int)D_00190FE4, (int)D_001768DF, (int)D_001903A4, (int)D_001769EA);
    func_000A1004((int)D_00190FE4);
    *(int *)D_001A4A0C = func_0009DC59((int)D_00190FE4, 546, 384);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_0018DE14, 48);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_0018DDD4, 64);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001959B8, 12);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00196266, 1);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195A14, 100);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001959C4, 20);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00178A0E, 2);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_0018DE44, 512);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00196265, 1);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195FB1, 71);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001959FC, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195A08, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195A0C, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195A78, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001952EC, 64);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195F62, 2);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00196280, 1);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001961F5, 13);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00178A10, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_0019627E, 1);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_0019627F, 1);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_0019627C, 1);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_0019627D, 1);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00178A14, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195CDC, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195CE0, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195CE4, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195E2A, 6);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001940D4, 8);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001959AC, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195BF4, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195C40, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195B10, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195B18, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_0019626A, 1);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_0018F044, 4960);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00196268, 1);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195AE8, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195AB8, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195AAC, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195A8C, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00178A18, 2);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001959A4, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001959A0, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_0018DD94, 32);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_0018DDB4, 32);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00196263, 1);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_0019599C, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195998, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001A94C8, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00195E2A, 6);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_0012DE00, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_00187F28, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001A9A04, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001A99F8, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001A99FC, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001A9A00, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001AA540, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001AA544, 4);
    func_000A0B42(*(int *)D_001A4A0C, (int)D_001AA580, 4);
    func_0001C960(*(int *)D_001A4A0C);
    func_0009DEA7(*(int *)D_001A4A0C);
}

void func_0007C432(void)
{
    int l_1C;
    int l_18;

    *(signed char *)D_00196289 = 1;
    *(int *)D_0019976C = 0;
    *(int *)D_001A94C4 = -1;
    if (((int)(unsigned short)(*(short *)((char *)*(int *)D_00195BF8) & 1)) == 0) goto L7C48C;
    func_0012A2D0(160, 100, 160, 100);
    goto L7C4A5;
L7C48C:;
    func_0012A2D0(160, 77, 160, 77);
L7C4A5:;
    func_0012A274(200, 180);
    *(int *)D_00195D48 = 10000;
    *(signed char *)D_0019629B = 0;
    func_000A0040((int)D_00195BFC, 0, 68, (int)D_00176884, 1188, 68);
    func_000A0040((int)D_00195B98, 0, 68, (int)D_00176884, 1189, 68);
    *(int *)D_00195B44 = *(int *)D_00195BF4;
    *(signed char *)D_001940D7 |= 1;
    *(signed char *)D_001940D5 |= 2;
    *(signed char *)D_001940D8 |= 8;
    *(int *)D_00195A9C = 0;
    l_18 = ((unsigned)*(int *)D_00195BF4) % 1440;
    if (l_18 <= 360) goto L7C54B;
    if (l_18 < 1080) goto L7C54D;
L7C54B:;
    goto L7C556;
L7C54D:;
    l_1C = 1;
    goto L7C55D;
L7C556:;
    l_1C = 0;
L7C55D:;
    *(int *)D_00199808 = l_1C;
}

void func_0007C56F(int a1)
{
    int l_34;
    int l_30;
    int l_2C;
    int l_28;
    int l_24;
    int l_20;
    int l_1C;
    int l_18;
{
    int l_3C;

    if (*(int *)((char *)a1 + 51) == 0) goto L7C5F2;
    if (*(signed char *)((char *)a1 + 38) == 0) goto L7C5E8;
    l_3C = func_0008E925(*(int *)D_001A4FE0, *(int *)((char *)a1 + 51));
    *(int *)((char *)a1 + 51) = l_3C;
    if (*(int *)D_001A4FE0 != *(int *)D_00195AC4) goto L7C5E6;
    if (*(int *)((char *)a1 + 51) != 0) goto L7C5CE;
    func_00050069((int)D_001769F7);
L7C5CE:;
    if (*(int *)((char *)*(int *)((char *)a1 + 51) + 51) != 0) goto L7C5E6;
    *(int *)((char *)*(int *)((char *)a1 + 51) + 51) = a1;
L7C5E6:;
    goto L7C5F2;
L7C5E8:;
    *(int *)((char *)a1 + 51) = 0;
L7C5F2:;
    switch (*(unsigned char *)((char *)a1)) {
case 52:
    if (a1 == *(int *)(D_001959D8 + (((int)(unsigned short)*(short *)((char *)a1 + 27)) << 2))) goto L7C6A0;
L7C66F:;
    if (*(int *)((char *)a1 + 63) == 0) goto L7C69A;
    func_0008DD46(*(int *)(D_001959D8 + (((int)(unsigned short)*(short *)((char *)a1 + 27)) << 2)), *(int *)((char *)a1 + 63));
    goto L7C66F;
L7C69A:;
    *(signed char *)((char *)a1) = 0;
L7C6A0:;
    return;
case 33:
    if (((int)(unsigned char)*(signed char *)((char *)*(int *)((char *)a1 + 67))) != 52) goto L7C6CB;
    if (((int)(unsigned short)*(short *)((char *)*(int *)((char *)a1 + 67) + 27)) < 5) goto L7C6CD;
L7C6CB:;
    goto L7C6D3;
L7C6CD:;
    *(signed char *)((char *)a1) = 2;
L7C6D3:;
    return;
case 43:
    l_30 = a1 + 71;
    l_2C = *(int *)((char *)l_30 + 5);
    l_20 = 0;
L7C6F1:;
    if (((int)(unsigned char)*(signed char *)((char *)l_30)) > l_20) goto L7C711;
    goto L7C725;
L7C702:;
    l_20++;
    (*(char (**)[66])&l_2C)++;
    goto L7C6F1;
L7C711:;
    l_34 = l_2C + 4;
    *(int *)((char *)l_34) = 0;
    goto L7C702;
L7C725:;
    return;
case 56:
    l_2C = a1 + 71;
    l_20 = 0;
L7C737:;
    if (((int)(unsigned short)*(short *)((char *)a1 + 27)) > l_20) goto L7C759;
    goto L7C76D;
L7C74A:;
    l_20++;
    (*(char (**)[66])&l_2C)++;
    goto L7C737;
L7C759:;
    l_34 = l_2C + 4;
    *(int *)((char *)l_34) = 0;
    goto L7C74A;
L7C76D:;
    return;
case 6:
case 32:
    l_34 = a1 + 71;
    *(int *)((char *)l_34) = 0;
default:;
}
}
}

void func_0007C78B(int a1)
{

    switch (*(unsigned char *)((char *)a1)) {
case 0:
case 42:
    func_0008DA91(a1);
    return;
case 9:
    if (((int)(unsigned char)*(signed char *)((char *)*(int *)((char *)a1 + 67))) == 47) goto L7C7F6;
    if (((int)(unsigned char)*(signed char *)((char *)*(int *)((char *)a1 + 67))) != 38) goto L7C7F8;
L7C7F6:;
    goto L7C80E;
L7C7F8:;
    if (((int)(unsigned char)*(signed char *)((char *)*(int *)((char *)a1 + 67))) != 1) goto L7C883;
L7C80E:;
{
    int l_20;
    l_20 = a1 + 71;
    if (((int)(unsigned short)(*(short *)((char *)a1 + 21) & 8192)) != 0) goto L7C839;
    func_0008DA91(a1);
    return;
L7C839:;
    if (*(int *)((char *)a1 + 47) != *(int *)D_00195AA0) goto L7C851;
    func_0008DA91(a1);
    return;
L7C851:;
    if ((((unsigned)*(int *)((char *)a1 + 31)) >> 16) == (((unsigned)*(int *)((char *)*(int *)D_00195AC4 + 31)) >> 16)) goto L7C881;
    *(int *)((char *)a1 + 31) = func_0008EB88(((unsigned)*(int *)((char *)*(int *)D_00195AC4 + 31)) >> 16);
L7C881:;
    return;
L7C883:;
    if ((((unsigned)*(int *)((char *)a1 + 31)) >> 16) == 801) return;
    *(int *)((char *)a1 + 31) = func_0008EB88(801);
}
default:;
}
}

void func_0007C8AF(void)
{
    *(int *)D_001A4FE0 = *(int *)D_001959A8;
    func_0008E3F7(*(int *)D_00195AC4, (int)func_0007C56F);
    *(int *)D_001A4FE0 = *(int *)D_00195AC4;
    func_0008E3F7(*(int *)D_001959A8, (int)func_0007C56F);
    func_0008E3A7(*(int *)D_00195AC4, (int)func_0007C78B);
}
