/* monster.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/monster.c to work on it by hand) */

extern char D_00175934[];
extern char D_00187FB8[];
extern char D_00190504[];
extern char D_00190704[];
extern char D_00190FE4[];
extern char D_001959A8[];
extern char D_00195AC4[];
extern char D_00195AD8[];
extern char D_00195BE0[];
extern char D_00195C70[];
extern char D_00195CB8[];
extern char D_00199D9B[];
extern char D_001A3A78[];

extern int func_0005C9BF(unsigned char);
extern int func_00069938(int, int, int);
extern int func_0007D6AE(int, int);
extern int func_0008EA20(int, int);
extern int func_000A0024();
extern int func_000A0040();
extern int func_000A1079();
extern void func_00073DF9(int, int);
extern void func_0008E3F7(int, int);
int func_000631AA(int);
void func_00062FBE(int);

int func_0006299F(int a1)
{
    a1 = *(int *)((char *)a1 + 63);
L629B9:;
    if (a1 == 0) goto L629E4;
    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 22) goto L629D9;
    return *(int *)((char *)a1 + 63);
L629D9:;
    a1 = *(int *)((char *)a1 + 55);
    goto L629B9;
L629E4:;
    return 0;
}

int func_00062C15(int a1)
{
    int l_1C;
{
    int l_24;

    l_1C = *(int *)(D_00190504 + (a1 << 2)) + 71;
    if ((*(signed char *)((char *)l_1C + 138) & 1) == 0) goto L62C4D;
    return 0;
L62C4D:;
    *(int *)D_00195AD8 = func_0008EA20(*(int *)(D_00190504 + (a1 << 2)), 9);
    if (func_0005C9BF((int)(unsigned char)*(signed char *)((char *)*(int *)D_00195AD8 + 144)) == 0) goto L62C8A;
    return 0;
L62C8A:;
    if (*(int *)D_00195AD8 == 0) goto L62C9C;
    l_24 = 1;
    goto L62CA3;
L62C9C:;
    l_24 = 0;
L62CA3:;
    return l_24;
}
}

int func_00062CB6(int a1)
{
    int l_1C;
{
    int l_24;

    l_1C = *(int *)(D_00190504 + (a1 << 2)) + 71;
    if ((*(signed char *)((char *)l_1C + 138) & 1) == 0) goto L62CEE;
    return 0;
L62CEE:;
    *(int *)D_00195AD8 = func_0008EA20(*(int *)(D_00190504 + (a1 << 2)), 9);
    if (func_0005C9BF((int)(unsigned char)*(signed char *)((char *)*(int *)D_00195AD8 + 144)) == 0) goto L62D2B;
    return 0;
L62D2B:;
    if (*(int *)D_00195AD8 == 0) goto L62D3D;
    l_24 = 1;
    goto L62D44;
L62D3D:;
    l_24 = 0;
L62D44:;
    return l_24;
}
}

void func_00062EBE(int a1, int a2)
{
    func_00069938(6, a1, 100);
    func_00073DF9(a1, a2);
}

int func_00062EF7(int a1, int a2, int a3)
{
    int l_14;

    a1 &= 2047;
    a2 &= 2047;
    l_14 = a2 - a1;
    if (l_14 != 0) goto L62F34;
    return l_14;
L62F34:;
    if (l_14 <= 1024) goto L62F58;
    *(int *)((char *)a3) = -1;
    return a1 + (2048 - a2);
L62F58:;
    if (l_14 <= 0) goto L62F67;
    if (l_14 <= 1024) goto L62F69;
L62F67:;
    goto L62F7D;
L62F69:;
    *(int *)((char *)a3) = 1;
    return a2 - a1;
L62F7D:;
    if (l_14 >= (-1024)) goto L62FA1;
    *(int *)((char *)a3) = 1;
    return a2 + (2048 - a1);
L62FA1:;
    *(int *)((char *)a3) = -1;
    return a1 - a2;
}

void func_00062FBE(int a1)
{
    int l_18;

    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 18) return;
    l_18 = a1 + 71;
    *(signed char *)(D_00190FE4 + ((int)(unsigned char)*(signed char *)((char *)l_18 + 75))) = 1;
}

int func_00063003(void)
{
    int l_1C;

    func_000A0040((int)D_00190FE4, 0, 128, (int)D_00175934, 829, 2048);
    func_0008E3F7(*(int *)((char *)*(int *)D_00195AC4 + 63), (int)func_00062FBE);
    func_0008E3F7(*(int *)((char *)*(int *)D_001959A8 + 63), (int)func_00062FBE);
    l_1C = 0;
L6305C:;
    if (l_1C < 128) goto L63072;
    goto L630DF;
L6306A:;
    l_1C++;
    goto L6305C;
L63072:;
    if (*(signed char *)(D_00190FE4 + l_1C) != 0) goto L6308D;
    if (*(int *)(D_00190704 + (l_1C << 2)) != 0) goto L6308F;
L6308D:;
    goto L630DD;
L6308F:;
    if (*(int *)(D_00190704 + (l_1C << 2)) == 0) goto L630B0;
    if (*(int *)(D_00190704 + (l_1C << 2)) != (-1751672937)) goto L630B2;
L630B0:;
    goto L630DD;
L630B2:;
    func_000A0024(*(int *)(D_00190704 + (l_1C << 2)), (int)D_00175934, 836);
    *(int *)(D_00190704 + (l_1C << 2)) = -1751672937;
L630DD:;
    goto L6306A;
L630DF:;
    l_1C = 0;
L630E6:;
    if (*(signed char *)(D_00190FE4 + l_1C) == 0) goto L630FA;
    l_1C++;
    goto L630E6;
L630FA:;
    return l_1C;
}

int func_000631AA(int a1)
{
    return func_000A1079((int)D_00187FB8, a1, 14);
}

int func_000631DD(int a1)
{
    int l_1C;
{
    int l_24;

    if ((*(short *)((char *)*(int *)D_00195BE0 + 137) & 12292) != 0) goto L6320A;
    return 1;
L6320A:;
    if ((*(signed char *)((char *)*(int *)D_00195BE0 + 137) & 4) == 0) goto L63225;
    return func_000631AA(a1);
L63225:;
    if ((*(signed char *)((char *)*(int *)D_00195BE0 + 138) & 32) == 0) goto L6323C;
    l_1C = 8;
    goto L63243;
L6323C:;
    l_1C = 4;
L63243:;
    if (func_000631AA(a1) == 0) goto L63258;
    return 1;
L63258:;
    if (func_0007D6AE(1, 100) > l_1C) goto L63275;
    l_24 = 1;
    goto L6327C;
L63275:;
    l_24 = 0;
L6327C:;
    return l_24;
}
}

int func_000641CD(int a1)
{
    int l_1C;

    l_1C = 0;
L641E5:;
    if (l_1C < *(int *)D_001A3A78) goto L641FA;
    goto L64214;
L641F2:;
    l_1C++;
    goto L641E5;
L641FA:;
    if (*(int *)(D_00199D9B + (l_1C * 39)) != a1) goto L64212;
    return 1;
L64212:;
    goto L641F2;
L64214:;
    return 0;
}

void func_00064301(void)
{
    *(int *)D_001A3A78 = 0;
    *(int *)D_00195C70 = 0;
    *(int *)D_00195CB8 = *(int *)D_00195C70;
}
