/* names.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/names.c to work on it by hand) */

extern char D_00176D8C[];
extern char D_00176D98[];
extern char D_00176DA0[];
extern char D_001A9A08[];
extern char D_001A9A20[];
extern char D_001A9A38[];
extern char D_001A9A7E[];
extern char D_001A9A9C[];
extern char D_001A9AB0[];

extern int func_0006CD6E(int);
extern int func_0007D6AE(int, int);
extern int func_0008B65C(unsigned char, unsigned char);
extern int func_0008B79D(unsigned char, unsigned char);
extern int func_0008C2D7(int, short, short, short, short, int);
extern int func_0009DC25();
extern int func_0009DEA7();
extern int func_000A006E();
extern int func_000A00CB();
extern int func_000A0AD9();
extern int func_000A1054();
extern int func_00142790();

int func_0008B572(unsigned char a1, unsigned char a2)
{
    int l_20;

    *(signed char *)D_001A9A38 = 0;
    *(short *)D_001A9A9C = func_0006CD6E((int)D_00176D8C);
    func_000A006E((int)(short)*(short *)D_001A9A9C, ((int)(unsigned char)a1) * 48, 0);
    func_000A00CB((int)(short)*(short *)D_001A9A9C, (int)D_001A9A08, 48);
    func_000A0AD9((int)D_001A9A38, func_0008B79D((int)(unsigned char)a1, (int)(unsigned char)a2), 40, (int)D_00176D98, 90);
    l_20 = func_0008B65C((int)(unsigned char)a1, (int)(unsigned char)a2);
    if (*(signed char *)((char *)l_20) == 0) goto L8B63D;
    func_000A1054((int)D_001A9A38, (int)D_00176DA0, (int)D_00176D98, 96, 40);
    func_000A1054((int)D_001A9A38, l_20, (int)D_00176D98, 97, 40);
L8B63D:;
    func_0009DEA7((int)(short)*(short *)D_001A9A9C);
    return (int)D_001A9A38;
}

void func_0008BCE9(short a1, short a2)
{
    func_000A006E((int)(short)a1, *(int *)(D_001A9A08 + (((int)(short)a2) << 2)) + ((func_0009DC25() % *(int *)(D_001A9A20 + (((int)(short)a2) << 2))) * 10), 0);
    func_000A00CB((int)(short)a1, (int)D_001A9A7E, 10);
}

int func_0008C232(int a1)
{
    int l_1C;

    l_1C = 0;
L8C24A:;
    if (*(int *)((char *)((l_1C++ << 2) + a1)) != 0) goto L8C24A;
    l_1C = func_0007D6AE(0, l_1C - 2);
    return *(int *)((char *)((l_1C << 2) + a1));
}

void func_0008C286(int a1, short a2, int a3, short a4, short a5, short a6)
{
    func_00142790();
    *(signed char *)D_001A9AB0 = 1;
    func_0008C2D7(a1, (int)(short)a2, (int)(short)*(short *)&a3, (int)(short)a4, (int)(short)a5, (int)(short)a6);
    *(signed char *)D_001A9AB0 = 0;
}
