/* pflc.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/pflc.c to work on it by hand) */

extern char D_00143550[];
extern char D_00175404[];

extern int func_0006CD6E(int);
extern int func_0009DEA7();
extern int func_000A0024();
extern int func_000A0040();
extern int func_000A006E();
extern int func_000A00AF();
extern int func_000A00CB();
extern int func_000A0DF4();
extern int func_000A1023();
extern int func_000CD33A();
extern int func_0012D887();
extern int func_00144F68();
extern int func_00144FB4();
extern void func_000527D6(int, int, unsigned char);
extern void func_00052B50(int, int);
extern void func_0007CA85(int, int, int, int, unsigned char);
void func_0005247B(int);
void func_000528FB(int, int);
void func_000529FA(int, int);
#pragma dagger DAGGER_NODEMOTE func_000529FA
#pragma dagger reg func_0005247B 381 esi
#pragma dagger slots func_0005247B a1 16 l_2C 24 l_20 12 l_1C 8 l_18 4
#pragma dagger slots func_000528FB a1 20 a2 16 l_1C 12 l_18 8 l_14 4
#pragma dagger slots func_000529FA a1 36 a2 32 l_2C 28 l_28 24 l_24 20 l_20 16 l_1C 12 l_18 8 l_14 4

void func_00051CF9(int a1)
{
    if (((int)(short)*(short *)((char *)a1 + 18)) != 320) goto L51D26;
    if (((int)(short)*(short *)((char *)a1 + 20)) == 200) goto L51D6D;
L51D26:;
    func_00144FB4((int)(short)*(short *)((char *)a1 + 14), (int)(short)*(short *)((char *)a1 + 16), (int)(short)*(short *)((char *)a1 + 18), (int)(short)*(short *)((char *)a1 + 20), *(int *)((char *)a1 + 30));
    func_000A1023(655360, *(int *)D_00143550, 64000, (int)D_00175404, 113, 4);
    return;
L51D6D:;
    if (*(short *)((char *)a1 + 6) == 0) goto L51D97;
    func_000A1023(655360, *(int *)D_00143550, 64000, (int)D_00175404, 117, 4);
    return;
L51D97:;
    if (((int)(unsigned char)*(signed char *)((char *)a1 + 43)) <= 1) return;
    func_000A1023(655360, *(int *)D_00143550, 64000, (int)D_00175404, 118, 4);
}

int func_0005209D(int a1, int a2)
{
{
    char l_A8[128];
    char l_28[12];

    *(short *)((char *)a2 + 2) = func_0006CD6E(a1);
    if (((int)(unsigned short)*(short *)((char *)a2 + 2)) >= 1) goto L520DE;
    return 0;
L520DE:;
    func_000A00CB((int)(unsigned short)*(short *)((char *)a2 + 2), (int)l_A8, 128);
    *(short *)((char *)a2 + 4) = *(int *)((char *)l_A8 + 6);
    *(short *)((char *)a2 + 8) = (int)&*(signed char *)((char *)(((unsigned)*(int *)((char *)l_A8 + 16)) / 55) + 1);
    *(short *)((char *)a2 + 18) = *(int *)((char *)l_A8 + 8);
    *(short *)((char *)a2 + 20) = *(int *)((char *)l_A8 + 10);
    *(short *)((char *)a2 + 14) = 0;
    *(short *)((char *)a2 + 16) = *(short *)((char *)a2 + 14);
    *(int *)((char *)a2 + 10) = *(int *)((char *)l_A8 + 84);
    if (*(int *)((char *)a2 + 22) != 0) goto L52191;
    *(signed char *)((char *)a2) |= 1;
    *(int *)((char *)a2 + 22) = func_000A00AF(((int)(short)*(short *)((char *)a2 + 18)) * ((int)(short)*(short *)((char *)a2 + 20)), (int)D_00175404, 225);
L52191:;
    if (*(int *)((char *)a2 + 26) != 0) goto L521BC;
    *(signed char *)((char *)a2) |= 2;
    *(int *)((char *)a2 + 26) = func_000A00AF(2050, (int)D_00175404, 231);
L521BC:;
    func_000A0040(*(int *)((char *)a2 + 26), 0, 2050, (int)D_00175404, 233, 4);
    func_000A00CB((int)(unsigned short)*(short *)((char *)a2 + 2), (int)l_28, 10);
    if (((int)(unsigned short)*(short *)((char *)l_28 + 4)) != 61696) goto L5224E;
    func_000A00CB((int)(unsigned short)*(short *)((char *)a2 + 2), (int)l_28, 8);
    if (((int)(short)*(short *)l_28) != 3) goto L5224E;
    *(short *)((char *)a2 + 14) = ((int)(short)*(short *)((char *)l_28 + 4)) - (((int)(short)*(short *)((char *)a2 + 18)) >> 1);
    *(short *)((char *)a2 + 16) = ((int)(short)*(short *)((char *)l_28 + 6)) - (((int)(short)*(short *)((char *)a2 + 20)) >> 1);
L5224E:;
    func_000A006E((int)(unsigned short)*(short *)((char *)a2 + 2), *(int *)((char *)l_A8 + 80), 0);
    *(short *)((char *)a2 + 6) = 1;
    if (*(int *)((char *)a2 + 30) != 0) goto L522A4;
    *(signed char *)((char *)a2) |= 64;
    *(int *)((char *)a2 + 30) = func_000A00AF(((int)(short)*(short *)((char *)a2 + 18)) * ((int)(short)*(short *)((char *)a2 + 20)), (int)D_00175404, 255);
L522A4:;
    return 1;
}
}

void func_000522B7(int a1)
{
    if (((int)(unsigned short)(*(short *)((char *)a1) & 1)) == 0) goto L52312;
    if (*(int *)((char *)a1 + 22) == 0) goto L522F1;
    if (*(int *)((char *)a1 + 22) != (-1751672937)) goto L522F3;
L522F1:;
    goto L52312;
L522F3:;
    func_000A0024(*(int *)((char *)a1 + 22), (int)D_00175404, 263);
    *(int *)((char *)a1 + 22) = -1751672937;
L52312:;
    if (((int)(unsigned short)(*(short *)((char *)a1) & 2)) == 0) goto L5235C;
    if (*(int *)((char *)a1 + 26) == 0) goto L5233B;
    if (*(int *)((char *)a1 + 26) != (-1751672937)) goto L5233D;
L5233B:;
    goto L5235C;
L5233D:;
    func_000A0024(*(int *)((char *)a1 + 26), (int)D_00175404, 264);
    *(int *)((char *)a1 + 26) = -1751672937;
L5235C:;
    if (((int)(unsigned short)(*(short *)((char *)a1) & 64)) == 0) goto L523A6;
    if (*(int *)((char *)a1 + 30) == 0) goto L52385;
    if (*(int *)((char *)a1 + 30) != (-1751672937)) goto L52387;
L52385:;
    goto L523A6;
L52387:;
    func_000A0024(*(int *)((char *)a1 + 30), (int)D_00175404, 265);
    *(int *)((char *)a1 + 30) = -1751672937;
L523A6:;
    func_0009DEA7((int)(unsigned short)*(short *)((char *)a1 + 2));
}

int func_000523C1(int a1)
{
    if (((int)(unsigned short)(*(short *)((char *)a1) & 4)) == 0) goto L523F9;
    *(signed char *)((char *)a1 + 43) = 0;
    return 1;
L523F9:;
    func_0005247B(a1);
    if (((int)(unsigned short)(*(short *)((char *)a1) & 4)) == 0) goto L52425;
    *(signed char *)((char *)a1 + 43) = 0;
    return 1;
L52425:;
    if (((int)(unsigned short)(*(short *)((char *)a1) & 8)) == 0) goto L5244D;
    if (((int)(unsigned short)(*(short *)((char *)a1) & 16)) == 0) goto L5244F;
L5244D:;
    goto L52467;
L5244F:;
    *(signed char *)((char *)a1) &= 247;
    func_000CD33A(*(int *)((char *)a1 + 26), 0, 256);
L52467:;
    return 0;
}

void func_0005247B(int a1)
{
    unsigned l_1C;
    unsigned short l_20;
    short l_18;
{
    char l_2C[8];

    l_20 = *(short *)((char *)a1 + 2);
L52496:;
    func_000A00CB((int)(unsigned short)l_20, (int)l_2C, 6);
    if (((int)(unsigned short)*(short *)((char *)l_2C + 4)) == 61946) goto L524CE;
    func_000A006E((int)(unsigned short)l_20, (int)(*(char **)l_2C - 6), 1);
    goto L52496;
L524CE:;
    func_000A00CB((int)(unsigned short)l_20, (int)&l_18, 2);
    func_000A006E((int)(unsigned short)l_20, 8, 1);
    l_1C = 0;
L524FD:;
    if (*(unsigned short *)&l_1C < (short)l_18) goto L52518;
    goto L527A5;
L52510:;
    l_1C++;
    goto L524FD;
L52518:;
    func_000A00CB((int)(unsigned short)l_20, (int)l_2C, 6);
    *(int *)l_2C += -6;
    switch ((unsigned short)*(int *)((char *)l_2C + 4)) {
case 4:
    if (((int)(unsigned short)(*(short *)((char *)a1) & 16)) == 0) goto L525D2;
    func_000A006E((int)(unsigned short)l_20, (int)(unsigned short)*(short *)l_2C, 1);
    goto L5261E;
L525D2:;
    func_0012D887((int)(*(char **)((char *)a1 + 26) + 768));
    func_000A00CB((int)(unsigned short)l_20, (int)(*(char **)((char *)a1 + 26) + 768), (int)(unsigned short)*(short *)l_2C);
    func_000527D6(*(int *)((char *)a1 + 26), (int)&*(signed char *)(*(char **)((char *)a1 + 26) + 768), 0);
    *(signed char *)((char *)a1) |= 8;
L5261E:;
    goto L527A0;
case 11:
    if (((int)(unsigned short)(*(short *)((char *)a1) & 16)) == 0) goto L5264F;
    func_000A006E((int)(unsigned short)l_20, (int)(unsigned short)*(short *)l_2C, 1);
    goto L5269B;
L5264F:;
    func_0012D887((int)(*(char **)((char *)a1 + 26) + 768));
    func_000A00CB((int)(unsigned short)l_20, (int)(*(char **)((char *)a1 + 26) + 768), (int)(unsigned short)*(short *)l_2C);
    func_000527D6(*(int *)((char *)a1 + 26), (int)&*(signed char *)(*(char **)((char *)a1 + 26) + 768), 0);
    *(signed char *)((char *)a1) |= 8;
L5269B:;
    goto L527A0;
case 13:
    func_000A0040(*(int *)((char *)a1 + 30), 0, ((int)(short)*(short *)((char *)a1 + 18)) * ((int)(short)*(short *)((char *)a1 + 20)), (int)D_00175404, 347, 4);
    goto L527A0;
case 16:
    if (((int)(unsigned short)(*(short *)((char *)a1) & 128)) != 0) goto L526FC;
    func_000A00CB((int)(unsigned short)l_20, *(int *)D_00143550, (int)(unsigned short)*(short *)l_2C);
    goto L52713;
L526FC:;
    func_000A00CB((int)(unsigned short)l_20, *(int *)((char *)a1 + 30), (int)(unsigned short)*(short *)l_2C);
L52713:;
    goto L527A0;
case 15:
    func_000A00CB((int)(unsigned short)l_20, *(int *)((char *)a1 + 22), (int)(unsigned short)*(short *)l_2C);
    func_000528FB(*(int *)((char *)a1 + 22), a1);
    goto L527A0;
case 12:
    func_000A00CB((int)(unsigned short)l_20, *(int *)((char *)a1 + 22), (int)(unsigned short)*(short *)l_2C);
    func_000529FA(*(int *)((char *)a1 + 22), a1);
    goto L527A0;
case 7:
    func_000A00CB((int)(unsigned short)l_20, *(int *)((char *)a1 + 22), (int)(unsigned short)*(short *)l_2C);
    func_00052B50(*(int *)((char *)a1 + 22), a1);
    goto L527A0;
default:
    func_000A006E((int)(unsigned short)l_20, *(int *)l_2C, 1);
L527A0:;
    goto L52510;
L527A5:;
    func_00144F68((int)(short)*(short *)((char *)a1 + 14), (int)(short)*(short *)((char *)a1 + 16), (int)(short)*(short *)((char *)a1 + 18), (int)(short)*(short *)((char *)a1 + 20), *(int *)((char *)a1 + 30));
}
}
}

void func_000528FB(int a1, int a2)
{
    int l_1C;
    signed char l_14;
    short l_18;

    l_1C = 0;
L52915:;
    if ((short)(short)l_1C < *(short *)((char *)a2 + 20)) goto L5292E;
    return;
L52926:;
    l_1C++;
    goto L52915;
L5292E:;
    ++a1;
    *(int *)&l_18 = 0;
L52938:;
    l_14 = *(signed char *)((char *)a1++);
    if (l_14 <= 0) goto L52991;
    func_000A0040((int)(*(char **)((char *)a2 + 30) + (((int)(short)*(short *)((char *)a2 + 18)) * ((int)(short)*(short *)&l_1C))) + ((int)(short)l_18), (int)(unsigned char)*(signed char *)((char *)a1), (int)(signed char)l_14, (int)D_00175404, 443, 4);
    l_18 += (short)(signed char)l_14;
    a1++;
    goto L529DC;
L52991:;
    if (l_14 >= 0) goto L529DC;
    func_000A1023((int)(*(char **)((char *)a2 + 30) + (((int)(short)*(short *)((char *)a2 + 18)) * ((int)(short)*(short *)&l_1C))) + ((int)(short)l_18), a1, -((int)(signed char)l_14), (int)D_00175404, 449, 4);
    l_18 -= (short)(signed char)l_14;
    a1 -= (int)(signed char)l_14;
L529DC:;
    if ((short)(short)*(int *)&l_18 < *(short *)((char *)a2 + 18)) goto L52938;
    goto L52926;
}

void func_000529FA(int a1, int a2)
{
    int l_2C;
    int l_28;
    unsigned char l_18;
    signed char l_14;
    short l_24;
    short l_20;
    unsigned short l_1C;

    l_24 = *(short *)((char *)a1);
    l_20 = *(short *)((char *)a1 + 2);
    a1 += 4;
    l_2C = *(int *)&l_24;
L52A2A:;
    if (((int)(short)*(short *)&l_2C) < (((int)(short)l_24) + ((int)(short)l_20))) goto L52A49;
    return;
L52A41:;
    l_2C++;
    goto L52A2A;
L52A49:;
    l_18 = *(signed char *)((char *)a1);
    a1++;
    if (l_18 == 0) goto L52B42;
    l_1C = (unsigned short)(unsigned char)((unsigned short)(unsigned char)*(signed char *)((char *)a1));
    a1++;
    l_28 = 0;
L52A7A:;
    if ((short)(short)((int)(unsigned char)l_18) > *(short *)&l_28) goto L52A92;
    goto L52B42;
L52A8A:;
    l_28++;
    goto L52A7A;
L52A92:;
    l_14 = *(signed char *)((char *)a1);
    a1++;
    if (l_14 >= 0) goto L52AF2;
    func_000A0040((int)(*(char **)((char *)a2 + 30) + (((int)(short)*(short *)((char *)a2 + 18)) * ((int)(short)*(short *)&l_2C))) + ((int)(unsigned short)l_1C), (int)(unsigned char)*(signed char *)((char *)a1), -((int)(signed char)l_14), (int)D_00175404, 492, 4);
    l_1C -= (short)(signed char)l_14;
    a1++;
    goto L52B3D;
L52AF2:;
    if (l_14 <= 0) goto L52B3D;
    func_000A1023((int)(*(char **)((char *)a2 + 30) + (((int)(short)*(short *)((char *)a2 + 18)) * ((int)(short)*(short *)&l_2C))) + ((int)(unsigned short)l_1C), a1, (int)(signed char)l_14, (int)D_00175404, 498, 4);
    l_1C += (short)(signed char)l_14;
    a1 += (int)(signed char)l_14;
L52B3D:;
    goto L52A8A;
L52B42:;
    goto L52A41;
}

int func_00052D3C(int a1)
{
    int l_20;
    int l_1C;

    l_1C = 0;
    l_20 = 150;
L52D5B:;
    if (*(signed char *)((char *)a1) == 0) goto L52D69;
    if (l_1C < 4) goto L52D6B;
L52D69:;
    goto L52D9F;
L52D6B:;
    func_0007CA85(a1, 160, (int)(short)*(short *)&l_20, 145, 156);
    l_20 += 10;
    l_1C++;
    a1 += func_000A0DF4(a1) + 1;
    goto L52D5B;
L52D9F:;
    if (*(signed char *)((char *)a1) == 0) goto L52DAF;
    return a1;
L52DAF:;
    return 0;
}
