/* profile.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/profile.c to work on it by hand) */


extern int func_00012D3B(int);
extern int func_000A0D13();
#pragma aux sosconv "*" parm caller [] value [eax] modify [eax ebx ecx edx];
#pragma dagger slots func_00011F93 l_38 48 l_36 46 l_18 16 l_14 12 l_10 8 ret 4
#pragma aux (sosconv) func_00011F93;

int func_00011F93(int a1, int a2)
{
    char l_38[32];
    char l_36[30];
    int l_18;
    int l_14;
    int l_10;

    if (*(int *)((char *)a1 + 164) == 0) goto L11FB8;
    l_18 = *(int *)((char *)a1 + 164);
    goto L11FC4;
L11FB8:;
    l_18 = *(int *)((char *)a1 + 160);
L11FC4:;
    if (l_18 != 0) goto L11FD6;
    return 0;
L11FD6:;
    if (((int)(unsigned char)*(signed char *)((char *)l_18)) != 32) goto L11FED;
    l_18++;
    goto L11FD6;
L11FED:;
    if (((int)(unsigned char)*(signed char *)((char *)l_18)) != 13) goto L12008;
    return 0;
L12008:;
    l_10 = 0;
L1200F:;
    if (((int)(unsigned char)*(signed char *)((char *)l_18)) == 13) goto L1202D;
    if (((int)(unsigned char)*(signed char *)((char *)l_18)) != 44) goto L1202F;
L1202D:;
    goto L1203E;
L1202F:;
    if (((int)(unsigned char)*(signed char *)((char *)l_18)) != 32) goto L12040;
L1203E:;
    goto L12054;
L12040:;
    *(signed char *)((char *)l_38 + l_10++) = *(signed char *)((char *)l_18++);
    goto L1200F;
L12054:;
    *(signed char *)((char *)l_38 + l_10) = 0;
    if (l_10 != 0) goto L1206E;
    return 0;
L1206E:;
    if (((int)(unsigned char)*(signed char *)((char *)l_18)) != 32) goto L12085;
    l_18++;
    goto L1206E;
L12085:;
    if (((int)(unsigned char)*(signed char *)((char *)l_18)) != 44) goto L120A5;
    ++l_18;
    *(int *)((char *)a1 + 164) = l_18;
    goto L120B1;
L120A5:;
    *(int *)((char *)a1 + 164) = l_18;
L120B1:;
    if (((int)(signed char)*(signed char *)((char *)l_38 + 1)) != 120) goto L120C7;
    l_14 = func_00012D3B((int)l_36);
    goto L120D2;
L120C7:;
    l_14 = func_000A0D13((int)l_38);
L120D2:;
    *(int *)((char *)a2) = l_14;
    return 1;
}
