/* quests.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/quests.c to work on it by hand) */

extern char D_00174F47[];
extern char D_001959A8[];
extern char D_00195AC4[];
extern char D_00195AF4[];
extern char D_00195B84[];
extern char D_00195C44[];
extern char D_00195D50[];
extern char D_001961F5[];
extern char D_00196282[];

extern int func_000192EE(short);
extern int func_0004BDB7(int);
extern int func_0004CFA7(int, int);
extern int func_0007D6AE(int, int);
extern int func_0009DC25();
extern int func_0009DC49();
extern int func_000A0AD9();
extern int func_000A0DF4();
extern int func_000A0E3B();
extern void func_0001B470(int, int);
extern void func_0004C588(int);
extern void func_0004CB5D(int);
extern void func_0004CC14(int);
extern void func_0008E3F7(int, int);
extern void func_0008E4A8(int, int);

void func_0004C242(void)
{
    if (*(signed char *)D_001961F5 == 0) return;
    func_0004BDB7((int)D_001961F5);
    *(signed char *)D_001961F5 = 0;
}

int func_0004C4A0(int a1, int a2)
{
    int l_1C;
    int l_18;

    l_18 = *(int *)D_00195C44;
    l_1C = 0;
L4C4C2:;
    if (l_1C < a2) goto L4C4D4;
    goto L4C4F9;
L4C4CC:;
    l_1C++;
    goto L4C4C2;
L4C4D4:;
    if (func_000A0E3B(l_18, a1) != 0) goto L4C4EB;
    return a2;
L4C4EB:;
    l_18 += func_000A0DF4(l_18) + 1;
    goto L4C4CC;
L4C4F9:;
    func_000A0AD9(l_18, a1, 4, (int)D_00174F47, 383);
    return a2 + 1;
}

void func_0004C759(void)
{
    *(signed char *)D_00196282 = 0;
    func_0008E4A8(*(int *)D_001959A8, (int)func_0004C588);
}

void func_0004C835(int a1, int a2)
{
    int l_14;

    l_14 = *(int *)((char *)a2 + 32);
    *(signed char *)((char *)l_14 + 22) |= 10;
    if (*(int *)((char *)l_14 + 51) == 0) return;
    *(signed char *)((char *)*(int *)((char *)l_14 + 51) + 22) |= 10;
}

void func_0004C874(int a1, int a2)
{
}

void func_0004C890(int a1, int a2)
{
    int l_14;

    l_14 = *(int *)((char *)a2 + 32);
    *(signed char *)((char *)l_14 + 22) &= 245;
    if (*(int *)((char *)l_14 + 51) == 0) return;
    *(signed char *)((char *)*(int *)((char *)l_14 + 51) + 22) &= 245;
}

void func_0004C8CF(int a1, int a2)
{
}

int func_0004CB2F(int a1)
{
    return (unsigned char)(*(signed char *)((char *)a1 + 73) & 128);
}

int func_0004CC82(void)
{
    *(int *)D_00195B84 = 32768;
    func_0008E3F7(*(int *)D_00195AC4, (int)func_0004CC14);
    if (*(int *)D_00195B84 != 32768) goto L4CCBE;
    return 0;
L4CCBE:;
    *(int *)D_00195B84 = func_0007D6AE(0, (*(int *)D_00195B84 & 32767) - 1) + 1;
    *(int *)D_00195AF4 = 0;
    func_0008E3F7(*(int *)D_00195AC4, (int)func_0004CC14);
    *(int *)D_00195D50 = *(int *)D_00195AF4;
    return *(int *)D_00195AF4;
}

int func_0004CD10(int a1)
{
    int l_1C;

    l_1C = func_0009DC25();
    func_0009DC49(*(int *)((char *)a1 + 31));
    *(signed char *)D_001961F5 = 0;
    func_0004CB5D(a1);
    func_0009DC49(l_1C);
    if (*(signed char *)D_001961F5 == 0) goto L4CD6C;
    *(int *)D_00195D50 = a1;
    *(signed char *)D_001961F5 = 0;
    return 1;
L4CD6C:;
    return 0;
}

void func_0004CDE3(int a1)
{
    int l_18;

    if (*(short *)((char *)a1 + 2) == 0) return;
    l_18 = func_000192EE((short)*(short *)((char *)a1 + 2));
    func_0001B470(l_18, 5);
}

void func_0004D195(int a1)
{
    int l_1C;
    int l_18;

    l_18 = a1 + 71;
    l_1C = 0;
L4D1B6:;
    if (l_1C < 7) goto L4D1C6;
    return;
L4D1BE:;
    l_1C++;
    goto L4D1B6;
L4D1C6:;
    *(signed char *)((char *)(l_18 + l_1C) + 68) = func_0004CFA7(a1, l_1C);
    goto L4D1BE;
}
