/* region.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/region.c to work on it by hand) */

extern char D_001705F8[];
extern char D_00179D74[];
extern char D_0018F044[];
extern char D_00195AA4[];
extern char D_00195B30[];
extern char D_00196268[];
extern char D_00196269[];
extern char D_0019627B[];
extern char D_00196285[];
extern char D_00196B00[];
extern char D_00196B04[];

extern int func_000A0024();
extern void func_0001DF7F(int);
extern void func_00086314(void);
unsigned char func_00020089(int, int);
unsigned char func_0002010F(int, int);
unsigned char func_000201B8(int, int, int);
void func_0001FF3F(unsigned char, unsigned char);
#pragma dagger slots func_0001FF92 l_18 4 ret 8

void func_0001FEBD(void)
{
    if (*(int *)D_00196B00 == 0) goto L1FEE0;
    if (*(int *)D_00196B00 != (-1751672937)) goto L1FEE2;
L1FEE0:;
    goto L1FF00;
L1FEE2:;
    func_000A0024(*(int *)D_00196B00, (int)D_001705F8, 33);
    *(int *)D_00196B00 = -1751672937;
L1FF00:;
    if (*(int *)D_00196B04 == 0) goto L1FF15;
    if (*(int *)D_00196B04 != (-1751672937)) goto L1FF17;
L1FF15:;
    return;
L1FF17:;
    func_000A0024(*(int *)D_00196B04, (int)D_001705F8, 34);
    *(int *)D_00196B04 = -1751672937;
}

void func_0001FF3F(unsigned char a1, unsigned char a2)
{
    *(signed char *)D_00196268 = a2;
    *(int *)D_00195B30 = ((int)D_0018F044) + (((int)(unsigned char)*(signed char *)D_00196268) * 80);
    *(signed char *)D_00196269 = *(signed char *)D_00196268;
    func_00086314();
    func_0001DF7F((int)(unsigned char)a2);
}

int func_0001FF92(void)
{
    unsigned char l_18;

    l_18 = func_00020089(*(int *)(*(char **)D_00195AA4 + 7), *(int *)(*(char **)D_00195AA4 + 15));
    if ((signed char)l_18 == *(signed char *)D_00196268) goto L1FFDD;
    func_0001FF3F((int)(unsigned char)*(signed char *)D_00196268, (int)(unsigned char)l_18);
    return 1;
L1FFDD:;
    return 0;
}

int func_0001FFF1(void)
{
    return (int)(unsigned char)*(signed char *)(D_00179D74 + ((int)(unsigned char)*(signed char *)D_0019627B));
}

int func_0002001F(void)
{
    return (int)(unsigned char)func_0002010F(*(int *)(*(char **)D_00195AA4 + 7), *(int *)(*(char **)D_00195AA4 + 15));
}

unsigned char func_00020089(int a1, int a2)
{
    int l_20;
    int l_1C;
    unsigned char l_18;

    l_20 = (a1 >> 15) + 2;
    l_1C = 499 - (a2 >> 15);
    if (l_1C >= 1) goto L200C7;
    l_1C = 1;
    goto L200D7;
L200C7:;
    if (l_1C <= 499) goto L200D7;
    l_1C = 499;
L200D7:;
    l_18 = func_000201B8(l_20, l_1C, *(int *)D_00196B00);
    if (((int)(unsigned char)l_18) != 64) goto L200FB;
    return 31;
L200FB:;
    return l_18 & 127;
}

unsigned char func_0002010F(int a1, int a2)
{
    int l_1C;
    int l_18;

    l_1C = (a1 >> 15) + 2;
    l_18 = 499 - (a2 >> 15);
    if (l_18 >= 1) goto L2014D;
    l_18 = 1;
    goto L2015D;
L2014D:;
    if (l_18 <= 499) goto L2015D;
    l_18 = 499;
L2015D:;
    *(signed char *)D_0019627B = func_000201B8(l_1C, l_18, *(int *)D_00196B04);
    if (((int)(unsigned char)*(signed char *)D_0019627B) != 223) goto L20195;
    *(signed char *)D_0019627B = 228;
    *(signed char *)D_00196285 = 1;
    return 3;
L20195:;
    *(signed char *)D_00196285 = 0;
    return *(signed char *)(D_00179D74 + ((int)(unsigned char)*(signed char *)D_0019627B));
}

unsigned char func_000201B8(int a1, int a2, int a3)
{
    int l_18;
    int l_14;

    l_18 = a3;
    l_14 = (int)(*(char **)((char *)((a2 << 2) + l_18)) + a3);
    a1 -= (int)(short)*(short *)((char *)l_14);
L201EF:;
    if (a1 <= 0) goto L20207;
    (*(char (**)[3])&l_14)++;
    a1 -= (int)(short)*(short *)((char *)l_14);
    goto L201EF;
L20207:;
    return *(signed char *)((char *)l_14 + 2);
}
