/* runspell.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/runspell.c to work on it by hand) */

extern char D_000CEA30[];
extern char D_000CEA34[];
extern char D_0012AC04[];
extern char D_0012AC06[];
extern char D_00153408[];
extern char D_0015340D[];
extern char D_00153411[];
extern char D_001757F4[];
extern char D_001757FF[];
extern char D_00175820[];
extern char D_00175837[];
extern char D_00175858[];
extern char D_0017586C[];
extern char D_00175881[];
extern char D_001789F8[];
extern char D_0017A84C[];
extern char D_0017A94B[];
extern char D_0018509B[];
extern char D_00185C14[];
extern char D_00185C16[];
extern char D_00185C20[];
extern char D_00185C2A[];
extern char D_00185C34[];
extern char D_00185C3A[];
extern char D_00185C3F[];
extern char D_00185C43[];
extern char D_00185CEC[];
extern char D_00190504[];
extern char D_001959B8[];
extern char D_001959BC[];
extern char D_001959FC[];
extern char D_00195A98[];
extern char D_00195AA0[];
extern char D_00195AA4[];
extern char D_00195AB0[];
extern char D_00195AC4[];
extern char D_00195AE8[];
extern char D_00195B04[];
extern char D_00195B14[];
extern char D_00195B40[];
extern char D_00195B48[];
extern char D_00195B50[];
extern char D_00195B68[];
extern char D_00195B84[];
extern char D_00195BE0[];
extern char D_00195BF8[];
extern char D_00195C48[];
extern char D_00195CBC[];
extern char D_00195D5C[];
extern char D_00195F28[];
extern char D_00195F30[];
extern char D_00195F62[];
extern char D_00196291[];
extern char D_00196292[];
extern char D_00196D64[];
extern char D_00199D64[];
extern char D_00199D6C[];
extern char D_00199D71[];

extern int func_000219B8(int, int, int);
extern int func_00023C72(int, int);
extern int func_00023EC2(int, int, int);
extern int func_0003A0C0(int, int);
extern int func_0004B192(void);
extern int func_0005AE5F(int);
extern int func_00069938(int, int, int);
extern int func_00073F5D(int, int, int);
extern int func_0007CBA1(int);
extern int func_0007D6AE(int, int);
extern int func_0008ADC3(int, int, int, int, int, int);
extern int func_0008B1CC(int, int, int);
extern int func_0008DA91(int);
extern int func_0008DC58(int);
extern int func_0008DCE3(int, int, int);
extern int func_0008DD46(int, int);
extern int func_0008E6C5(int, int, int);
extern int func_0008EB88(int);
extern int func_000A0040();
extern int func_000A0AD9();
extern int func_000A1023();
extern int func_000C2000();
extern int func_000C2043();
extern int func_000C7FD9();
extern int func_000C7FF4();
extern int func_000C808D();
extern int func_000CAE0E();
extern int func_000CD20E();
extern int func_000CDB7A();
extern int func_000CE4C4();
extern int func_000CE4E0();
extern int func_000CE70D();
extern void func_0002F490(int, int, int);
extern void func_0002F72F(int, int, int, int);
extern void func_0003A2AD(int, int);
extern void func_00064589(int, int);
extern void func_00067027(int);
extern void func_0007D774(int, int);
extern void func_0007D7BA(void);
extern void func_0008A4E4(int);
extern void func_0008A550(int, int, int);
extern void func_0008E3F7(int, int);
int func_0005B107(int, int, int);
int func_0005B408(int, int);
int func_0005B905(int, int, int, int);
int func_0005B9DF(int, int, int);
int func_0005C448(int, int);
void func_0005ABE6(int, int, int);
void func_0005B206(int);
void func_0005BA28(int, unsigned short, int);
void func_0005C1CA(int, int, int);
void func_0005C6A2(int);
void func_0005C856(int, int);
void func_0005C897(int);
void func_0005CA28(int);
void func_0005CA87(int);
#pragma dagger reg func_0005AAE4 437 bx
#pragma dagger reg func_0005C1CA 72 edx 74 edx 85 dx 437 bx
#pragma dagger reg func_0005CA87 437 bx
#pragma dagger slots func_0005BA28 a1 16 a2 4 a3 8 l_18 12
#pragma dagger slots func_0005C1CA a1 36 a2 24 a3 32 l_3C 48 l_28 28 l_20 20 l_1C 16 l_18 12 l_14 8 l_10 4
#pragma dagger slots func_0005C448 a1 20 a2 24 l_44 52 l_40 48 l_34 36 l_20 16 l_1C 12 l_18 8 ret 4

int func_0005AAE4(int a1, int a2, int a3)
{
    int l_18;
    int l_14;

    l_18 = 0;
    l_14 = func_0008DCE3(*(int *)D_00195AC4, 0, 89);
L5AB14:;
    if (*(signed char *)((char *)(int)(*(char **)D_00195B04 + (l_18 * 89)) + 47) == 0) goto L5AB3E;
    if (((int)(unsigned char)*(signed char *)((char *)(int)(*(char **)D_00195B04 + (l_18 * 89)) + 73)) == a3) goto L5AB46;
L5AB3E:;
    l_18++;
    goto L5AB14;
L5AB46:;
    *(signed char *)((char *)l_14) = 9;
    *(int *)((char *)l_14 + 31) = func_0008EB88(((unsigned)*(int *)(*(char **)D_00195AC4 + 31)) >> 16);
    *(int *)((char *)l_14 + 47) = a1;
    func_000A1023(l_14 + 71, (int)(*(char **)D_00195B04 + (l_18 * 89)), 89, (int)D_001757F4, 144, 4);
    if (*(signed char *)D_00196292 == 0) goto L5ABA7;
    *(signed char *)((char *)l_14 + 143) = 250;
L5ABA7:;
    l_18 = func_0003A0C0(l_14 + 89, a1 + 71);
    if (func_0005B107(l_14, a1, a2) == 0) goto L5ABD5;
    func_0008DA91(l_14);
L5ABD5:;
    return l_18;
}

void func_0005ABE6(int a1, int a2, int a3)
{
    int l_24;
    int l_20;
    int l_1C;
    int l_18;
    int l_14;
    int l_10;

    l_18 = 0;
    if (*(int *)((char *)a1 + 47) == *(int *)D_00195AA0) goto L5AC19;
    if ((*(unsigned char *)D_00195AE8 & 128) != 0) goto L5AC1B;
L5AC19:;
    goto L5AC20;
L5AC1B:;
    return;
L5AC20:;
    if (*(int *)((char *)a1 + 47) != *(int *)D_00195AA0) goto L5AC39;
    if (a2 == *(int *)D_00195AA0) goto L5AC3B;
L5AC39:;
    goto L5AC4B;
L5AC3B:;
    if (((int)(unsigned char)*(signed char *)((char *)a1 + 78)) == 3) goto L5AC4D;
L5AC4B:;
    goto L5AC52;
L5AC4D:;
    return;
L5AC52:;
    *(short *)D_00195F28 = 512;
    l_10 = a1 + 71;
    if (((int)(unsigned char)*(signed char *)((char *)l_10 + 7)) == 2) goto L5AC84;
    if (((int)(unsigned char)*(signed char *)((char *)l_10 + 7)) != 4) goto L5AC86;
L5AC84:;
    goto L5ACEA;
L5AC86:;
    func_00069938((int)(short)*(short *)(D_00185C20 + (((int)(unsigned char)*(signed char *)((char *)l_10 + 6)) * 2)), *(int *)D_00195AA4, 110);
    if (*(int *)((char *)a1 + 47) != *(int *)D_00195AA0) goto L5ACC1;
    if (*(signed char *)D_00196291 == 0) goto L5ACC3;
L5ACC1:;
    goto L5ACD5;
L5ACC3:;
    func_0005C897((int)(unsigned char)*(signed char *)((char *)l_10 + 6));
    goto L5ACEA;
L5ACD5:;
    func_0002F490(*(int *)((char *)a1 + 47), 3, 3);
L5ACEA:;
    if (a3 != 0) goto L5AD15;
    l_14 = func_0005B408(a1, (int)&a2);
    if (l_14 != 0) goto L5AD13;
    func_0007CBA1(*(int *)D_0018509B);
    return;
L5AD13:;
    goto L5AD1C;
L5AD15:;
    l_14 = 100;
L5AD1C:;
    l_24 = func_0008DC58(a1);
    *(int *)((char *)l_24 + 47) = *(int *)((char *)a1 + 47);
    *(int *)((char *)l_24 + 31) = func_0008EB88(801);
    l_10 = l_24 + 71;
    func_0005BA28(l_10, (int)(unsigned short)((unsigned short)(unsigned char)*(signed char *)(*(char **)((char *)l_24 + 47) + 200)), l_14);
    l_20 = 0;
    l_1C = l_20;
L5AD79:;
    if (l_20 < 3) goto L5AD8C;
    goto L5AE36;
L5AD84:;
    l_20++;
    goto L5AD79;
L5AD8C:;
    if (((int)(unsigned char)*(signed char *)((char *)((l_20 * 2) + l_10))) == 255) goto L5AD84;
    if (((int)(unsigned char)*(signed char *)((char *)l_10 + 72)) < 200) goto L5ADC6;
    if (((int)(unsigned char)*(signed char *)((char *)l_10 + 72)) != 250) goto L5ADD8;
L5ADC6:;
    if (func_0008B1CC(a2, l_10, l_20) != 0) goto L5ADDA;
L5ADD8:;
    goto L5ADE2;
L5ADDA:;
    l_18++;
    goto L5ADF0;
L5ADE2:;
    func_0005B9DF(l_24, l_20, a2);
L5ADF0:;
    if (((int)(unsigned char)*(signed char *)((char *)((l_20 * 2) + l_10))) == 255) goto L5AE29;
    if (((int)(unsigned char)(*(signed char *)(D_0017A94B + (((int)(unsigned char)*(signed char *)((char *)((l_20 * 2) + l_10))) * 12)) & 1)) != 0) goto L5AE2B;
L5AE29:;
    goto L5AE31;
L5AE2B:;
    l_1C++;
L5AE31:;
    goto L5AD84;
L5AE36:;
    l_1C -= l_18;
    if (l_1C != 0) goto L5AE4C;
    func_0008DA91(l_24);
    return;
L5AE4C:;
    func_0008DD46(a2, l_24);
}

int func_0005AFD5(int a1, int a2)
{
    int l_18;

    l_18 = a1 + 71;
    *(int *)((char *)a1 + 47) = *(int *)D_00195AA0;
    if (((int)(unsigned char)*(signed char *)((char *)l_18 + 73)) != 92) goto L5B037;
    func_00067027(0);
    return 1;
__dagger_tbl5B023:;
L5B037:;
    switch (*(unsigned char *)((char *)l_18 + 7)) {
case 0:
    func_0005ABE6(a1, *(int *)D_00195AA0, 0);
    return 1;
case 1:
    func_0005ABE6(a1, a2, 0);
    return 1;
case 2:
    func_0005ABE6(a1, a2, 0);
    return 1;
case 3:
    *(int *)D_00195D5C = 0;
    *(int *)((char *)a1 + 7) = *(int *)(*(char **)D_00195AA4 + 7);
    *(int *)((char *)a1 + 11) = *(int *)(*(char **)D_00195AA4 + 11);
    *(int *)((char *)a1 + 15) = *(int *)(*(char **)D_00195AA4 + 15);
    func_0005C6A2(a1);
    func_0007D7BA();
    return 1;
case 4:
    return 1;
default:
    return 1;
}
}

int func_0005B107(int a1, int a2, int a3)
{
    int l_14;

__dagger_tbl5B11F:;
    l_14 = a1 + 71;
    *(int *)((char *)a1 + 47) = a2;
    switch (*(unsigned char *)((char *)l_14 + 7)) {
case 0:
    func_0005ABE6(a1, a2, 0);
    if (a2 == *(int *)D_00195AA0) goto L5B191;
    func_0002F490(a2, 3, 3);
L5B191:;
    return 1;
case 1:
    func_0005ABE6(a1, a3, 0);
    return 1;
case 2:
    func_0005C1CA(a1, a2, a3);
    return 0;
case 3:
    func_0005ABE6(a1, a3, 0);
    return 1;
case 4:
    func_0005C1CA(a1, a2, a3);
    return 0;
default:
    return 1;
}
}

void func_0005B206(int a1)
{
    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 9) return;
    if ((short)((unsigned short)(unsigned char)*(signed char *)((char *)a1 + 144)) != *(short *)D_00185C14) return;
    *(int *)D_00195B50 = a1;
}

int func_0005B24C(void)
{
    int l_28;
    int l_24;
    int l_20;
    int l_1C;

    if (*(int *)D_00195B40 != 0) goto L5B26C;
    if (*(int *)D_00195B48 == 0) goto L5B282;
L5B26C:;
    func_0007CBA1((int)D_001757FF);
    return 0;
L5B282:;
    if (((int)(short)*(short *)D_00185C14) != (-1)) goto L5B29A;
    return 0;
L5B29A:;
    l_28 = func_0008E6C5(*(int *)(*(char **)D_00195AA0 + 63), 27, 0);
    if (l_28 != 0) goto L5B2CD;
    func_0007CBA1((int)D_00175820);
    return 0;
L5B2CD:;
    *(int *)D_00195B50 = 0;
    func_0008E3F7(*(int *)((char *)l_28 + 63), (int)func_0005B206);
    l_28 = *(int *)D_00195B50;
    l_20 = l_28 + 71;
    l_1C = (int)(short)*(short *)D_00195F62;
    if ((((int)(short)*(short *)(*(char **)D_00195BE0 + 141)) + *(int *)D_001959FC) >= l_1C) goto L5B32F;
    func_0007CBA1((int)D_00175837);
    return 0;
L5B32F:;
    func_0003A2AD(l_20, 1);
    if (*(int *)D_001959FC == 0) goto L5B376;
    if (l_1C <= *(int *)D_001959FC) goto L5B364;
    l_1C -= *(int *)D_001959FC;
    *(int *)D_001959FC = 0;
    goto L5B376;
L5B364:;
    *(int *)D_001959FC -= l_1C;
    *(short *)D_00195F62 = 0;
L5B376:;
    *(short *)(*(char **)D_00195BE0 + 141) -= l_1C;
    l_24 = func_0008DCE3(*(int *)(*(char **)D_00195AA4 + 67), 0, 89);
    *(signed char *)((char *)l_24) = 9;
    *(int *)((char *)l_24 + 31) = func_0008EB88(((unsigned)*(int *)(*(char **)D_00195AC4 + 31)) >> 16);
    func_000A1023(l_24 + 71, l_28 + 71, 89, (int)D_001757F4, 443, 4);
    if (func_0005AE5F(l_24) == 0) goto L5B3F4;
    func_0008DA91(l_24);
L5B3F4:;
    return 1;
}

int func_0005B408(int a1, int a2)
{
    int l_2C;
    int l_28;
    int l_24;
    int l_20;
    char l_1C[8];

    *(int *)((char *)l_1C + 4) = a1 + 71;
    if (*(signed char *)(*(char **)((char *)l_1C + 4) + 7) != 0) goto L5B439;
    return 100;
L5B439:;
    if (*(int *)((char *)a1 + 47) != *(int *)((char *)a2)) goto L5B456;
    if (((int)(unsigned char)*(signed char *)(*(char **)((char *)l_1C + 4) + 7)) == 3) goto L5B458;
L5B456:;
    goto L5B464;
L5B458:;
    return 100;
L5B464:;
    l_2C = *(int *)((char *)a2) + 71;
    l_28 = l_2C + 560;
    if (((int)(unsigned char)(*(signed char *)((char *)l_28 + 9) & 7)) != 0) goto L5B49B;
    if ((*(unsigned char *)((char *)l_2C + 138) & 2) == 0) goto L5B5A7;
L5B49B:;
    if ((*(unsigned char *)((char *)l_2C + 138) & 2) != 0) goto L5B4B8;
    if (((int)(unsigned char)(*(signed char *)((char *)l_28 + 9) & 4)) == 0) goto L5B4BA;
L5B4B8:;
    goto L5B4D6;
L5B4BA:;
    if (((int)(unsigned char)(*(signed char *)((char *)l_28 + 9) & 2)) == 0) goto L5B4D4;
    if (func_0004B192() == 0) goto L5B4D6;
L5B4D4:;
    goto L5B4D8;
L5B4D6:;
    goto L5B4F7;
L5B4D8:;
    if (((int)(unsigned char)(*(signed char *)((char *)l_28 + 9) & 1)) == 0) goto L5B4F2;
    if (func_0004B192() != 0) goto L5B4F7;
L5B4F2:;
    goto L5B5A7;
L5B4F7:;
    if ((*(unsigned char *)((char *)l_2C + 138) & 2) == 0) goto L5B559;
    if (func_0005B905(*(int *)((char *)a2), 20, (int)l_1C, 0) != 0) goto L5B545;
    *(int *)l_1C = ((int)(unsigned char)*(signed char *)((char *)l_2C + 129)) + 25;
    if (func_0007D6AE(1, 100) > *(int *)l_1C) goto L5B5A7;
    goto L5B559;
L5B545:;
    if (func_0007D6AE(1, 100) > *(int *)l_1C) goto L5B5A7;
L5B559:;
    l_20 = func_0003A0C0(*(int *)((char *)l_1C + 4), l_2C);
    if ((l_20 + ((int)(short)*(short *)((char *)l_2C + 141))) > ((int)(short)*(short *)((char *)l_2C + 143))) goto L5B5A7;
    *(short *)((char *)l_2C + 141) += l_20;
    func_0007CBA1((int)D_00175858);
    return 0;
L5B5A7:;
    if ((*(unsigned char *)((char *)l_2C + 138) & 4) == 0) goto L5B606;
    func_0005B905(*(int *)((char *)a2), 21, (int)l_1C, 0);
    if (func_0007D6AE(1, 100) > *(int *)l_1C) goto L5B606;
    *(int *)((char *)a2) = *(int *)((char *)a1 + 47);
    l_2C = *(int *)((char *)a2) + 71;
    l_28 = l_2C + 560;
    func_0007CBA1((int)D_0017586C);
L5B606:;
    if ((*(unsigned char *)((char *)l_2C + 138) & 8) == 0) goto L5B64D;
    func_0005B905(*(int *)((char *)a2), 22, (int)l_1C, 0);
    if (func_0007D6AE(1, 100) > *(int *)l_1C) goto L5B64D;
    func_0007CBA1((int)D_00175881);
    return 0;
L5B64D:;
    return func_0008ADC3((int)(unsigned char)*(signed char *)(*(char **)((char *)l_1C + 4) + 6), (int)(unsigned char)*(signed char *)(D_00185C3A + ((int)(unsigned char)*(signed char *)(*(char **)((char *)l_1C + 4) + 6))), l_2C, l_28, 2, (-(((int)(unsigned char)*(signed char *)(*(char **)((char *)a1 + 47) + 200)) - ((int)(unsigned char)*(signed char *)((char *)l_2C + 129)))) * 5);
}

int func_0005B6AE(int a1, int a2, int a3)
{
    int l_1C;
    int l_18;
    int l_14;

    l_1C = 0;
    l_14 = l_1C;
L5B6D0:;
    if (l_1C < 3) goto L5B6E3;
    goto L5B761;
L5B6DB:;
    l_1C++;
    goto L5B6D0;
L5B6E3:;
    if (((int)(unsigned char)*(signed char *)((char *)((l_1C * 2) + a1))) == 255) goto L5B6DB;
    l_18 = (int)(unsigned short)*(short *)((char *)((l_1C * 2) + a1) + 8);
    l_18 = ((110 - ((int)(short)*(short *)((char *)((((int)(unsigned char)*(signed char *)(D_00185C34 + ((int)(unsigned char)*(signed char *)(D_0017A84C + ((int)(unsigned char)*(signed char *)((char *)((l_1C * 2) + a1))))))) * 6) + a2) + 157))) * l_18) / 100;
    l_14 += l_18;
    goto L5B6DB;
L5B761:;
    return l_14;
}

void func_0005B828(int a1)
{
    int l_24;
    int l_20;
    int l_1C;
    int l_18;

    l_20 = a1 + 71;
    if ((*(unsigned short *)((char *)l_20 + 137) & 12292) == 0) return;
    l_18 = 0;
L5B85B:;
    if (l_18 < 3) goto L5B86E;
    return;
L5B866:;
    l_18++;
    goto L5B85B;
L5B86E:;
    l_24 = func_0005B905(a1, *(int *)(D_00185C3F + (l_18 << 3)), (int)&l_1C, (int)&l_1C);
    if (l_24 != 0) goto L5B8AA;
    *(int *)((char *)l_20 + 137) &= ~*(int *)(D_00185C43 + (l_18 << 3));
    goto L5B866;
L5B8AA:;
    if (*(signed char *)((char *)((((int)(short)*(short *)D_00195F30) * 2) + l_24) + 1) != 0) goto L5B8F6;
    func_0008A550(l_24, (int)(short)*(short *)D_00195F30, a1);
    if (*(short *)D_00195F30 != 0) goto L5B8EA;
    if (((int)(unsigned char)*(signed char *)((char *)l_24 + 2)) == 255) goto L5B8EC;
L5B8EA:;
    goto L5B8F6;
L5B8EC:;
    func_0008A4E4(*(int *)D_00195B50);
L5B8F6:;
    goto L5B866;
}

int func_0005B905(int a1, int a2, int a3, int a4)
{
    int l_14;
    int l_10;

    a1 = *(int *)((char *)a1 + 63);
L5B925:;
    if (a1 == 0) goto L5B9CE;
    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 9) goto L5B9C0;
    l_14 = a1 + 71;
    l_10 = 0;
L5B952:;
    if (l_10 < 3) goto L5B962;
    goto L5B9C0;
L5B95A:;
    l_10++;
    goto L5B952;
L5B962:;
    if (((int)(unsigned char)*(signed char *)((char *)((l_10 * 2) + l_14))) != a2) goto L5B9BE;
    if (a3 == 0) goto L5B98C;
    *(int *)((char *)a3) = (int)(unsigned char)*(signed char *)((char *)(l_14 + l_10) + 86);
L5B98C:;
    if (a4 == 0) goto L5B9A5;
    *(int *)((char *)a4) = (int)(unsigned short)*(short *)((char *)((l_10 * 2) + l_14) + 80);
L5B9A5:;
    *(short *)D_00195F30 = l_10;
    *(int *)D_00195B50 = a1;
    return l_14;
L5B9BE:;
    goto L5B95A;
L5B9C0:;
    a1 = *(int *)((char *)a1 + 55);
    goto L5B925;
L5B9CE:;
    return 0;
}

int func_0005B9DF(int a1, int a2, int a3)
{
    int l_14;

    l_14 = a1 + 71;
    return func_000CAE0E((int)(unsigned char)*(signed char *)((char *)((a2 * 2) + l_14)), a1, a2, a3);
}

void func_0005BA28(int a1, unsigned short a2, int a3)
{
    int l_18;

    if (((int)(unsigned char)*(signed char *)((char *)a1 + 72)) < 200) goto L5BA56;
    *(int *)&a2 = 8;
L5BA56:;
    l_18 = 0;
L5BA5D:;
    if (l_18 < 3) goto L5BA70;
    return;
L5BA68:;
    l_18++;
    goto L5BA5D;
L5BA70:;
    if (((int)(unsigned char)*(signed char *)((char *)((l_18 * 2) + a1))) == 255) goto L5BA68;
    if (((int)(signed char)*(signed char *)((char *)((l_18 * 3) + a1) + 14)) == (-1)) goto L5BB26;
    if (((int)(unsigned char)(*(signed char *)(D_0017A94B + (((int)(unsigned char)*(signed char *)((char *)((l_18 * 2) + a1))) * 12)) & 1)) == 0) goto L5BB16;
    *(short *)((char *)((l_18 * 2) + a1) + 74) = ((((int)(signed char)*(signed char *)((char *)((l_18 * 3) + a1) + 14)) + (((int)(signed char)*(signed char *)((char *)((l_18 * 3) + a1) + 15)) * (((int)(unsigned short)a2) / ((int)(signed char)*(signed char *)((char *)((l_18 * 3) + a1) + 16))))) * a3) / 100;
    goto L5BB24;
L5BB16:;
    *(short *)((char *)((l_18 * 2) + a1) + 74) = 0;
L5BB24:;
    goto L5BB34;
L5BB26:;
    *(short *)((char *)((l_18 * 2) + a1) + 74) = 65535;
L5BB34:;
    if (((int)(unsigned char)(*(signed char *)(D_0017A94B + (((int)(unsigned char)*(signed char *)((char *)((l_18 * 2) + a1))) * 12)) & 2)) == 0) goto L5BB99;
    *(signed char *)((char *)(a1 + l_18) + 86) = ((int)(signed char)*(signed char *)((char *)((l_18 * 3) + a1) + 23)) + (((int)(signed char)*(signed char *)((char *)((l_18 * 3) + a1) + 24)) * (((int)(unsigned short)a2) / ((int)(signed char)*(signed char *)((char *)((l_18 * 3) + a1) + 25))));
L5BB99:;
    if (((int)(unsigned char)(*(signed char *)(D_0017A94B + (((int)(unsigned char)*(signed char *)((char *)((l_18 * 2) + a1))) * 12)) & 4)) == 0) goto L5BC4E;
    *(short *)((char *)((l_18 * 2) + a1) + 80) = (a3 * (func_0007D6AE((int)(signed char)*(signed char *)((char *)((l_18 * 5) + a1) + 32), (int)(signed char)*(signed char *)((char *)((l_18 * 5) + a1) + 33)) + ((((int)(unsigned short)a2) / ((int)(signed char)*(signed char *)((char *)((l_18 * 5) + a1) + 36))) * func_0007D6AE((int)(signed char)*(signed char *)((char *)((l_18 * 5) + a1) + 34), (int)(signed char)*(signed char *)((char *)((l_18 * 5) + a1) + 35))))) / 100;
    *(short *)((char *)((l_18 * 5) + a1) + 34) = 0;
L5BC4E:;
    goto L5BA68;
}

void func_0005BC5B(int a1, int a2)
{
    int l_18;
    int l_14;

    a1 = *(int *)((char *)a1 + 63);
L5BC77:;
    if (a1 == 0) return;
    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 9) goto L5BCCA;
    l_18 = a1 + 71;
    l_14 = func_000CE4C4(l_18, a2);
    if (l_14 == 0) goto L5BCCA;
    *(signed char *)((char *)((l_14 * 2) + l_18)) = 255;
    if (func_000CE4E0(l_18) == 0) goto L5BCCA;
    func_0008DA91(a1);
    return;
L5BCCA:;
    a1 = *(int *)((char *)a1 + 55);
    goto L5BC77;
}

void func_0005BCDE(int a1)
{
    int l_20;
    int l_1C;
    int l_18;
{
    char l_40[12];
    char l_34[16];

    func_0008DD46(*(int *)D_00195AC4, a1);
    *(int *)((char *)l_34 + 12) = func_0008DCE3(a1, 0, 0);
    *(signed char *)(*(char **)((char *)l_34 + 12)) = 7;
    *(short *)(*(char **)((char *)l_34 + 12) + 27) = 48;
    *(short *)(*(char **)((char *)l_34 + 12) + 23) = 64;
    *(int *)((char *)a1 + 7) = *(int *)(*(char **)D_00195AA4 + 7);
    *(int *)(*(char **)((char *)l_34 + 12) + 7) = *(int *)((char *)a1 + 7);
    *(int *)((char *)a1 + 11) = *(int *)(*(char **)D_00195AA4 + 11) - 50;
    *(int *)(*(char **)((char *)l_34 + 12) + 11) = *(int *)((char *)a1 + 11);
    *(int *)((char *)a1 + 15) = *(int *)(*(char **)D_00195AA4 + 15);
    *(int *)(*(char **)((char *)l_34 + 12) + 15) = *(int *)((char *)a1 + 15);
    *(short *)(*(char **)((char *)l_34 + 12) + 1) = 0;
    *(short *)(*(char **)((char *)l_34 + 12) + 3) = 0;
    if (*(signed char *)D_00153408 == 0) goto L5BE03;
    *(short *)((char *)a1 + 1) = ((((int)(short)*(short *)(*(char **)D_00195A98 + 1)) + ((((((int)(short)*(short *)D_0012AC06) + 6) - ((int)(short)*(short *)D_000CEA34)) * 307) >> 8)) + *(int *)D_0015340D) & 2047;
    *(short *)((char *)a1 + 3) = (((((*(short *)D_0012AC04 + 6) - *(short *)D_000CEA30) * 2) + *(short *)(*(char **)D_00195A98 + 3)) + *(short *)D_00153411) & 2047;
    goto L5BE89;
L5BE03:;
    *(short *)((char *)a1 + 1) = ((((((((int)(short)*(short *)D_0012AC06) + 6) - ((int)(short)*(short *)D_000CEA34)) * 150) / 100) + ((int)(short)*(short *)(*(char **)D_00195A98 + 1))) + *(int *)D_001959B8) & 2047;
    *(short *)((char *)a1 + 3) = ((((int)(short)*(short *)(*(char **)D_00195A98 + 3)) + ((((((int)(short)*(short *)D_0012AC04) + 6) - ((int)(short)*(short *)D_000CEA30)) * 160) / 100)) + *(int *)D_001959BC) & 2047;
L5BE89:;
    *(short *)((char *)a1 + 5) = 0;
    *(short *)(*(char **)((char *)l_34 + 12) + 5) = *(short *)((char *)a1 + 5);
    func_000A0040((int)l_40, 0, 12, (int)D_001757F4, 711, 4);
    func_000CE70D((int)(short)*(short *)((char *)a1 + 1), (int)(short)*(short *)((char *)a1 + 3), 1024, (int)l_40);
    *(int *)l_40 += *(int *)((char *)a1 + 7);
    *(int *)((char *)l_40 + 4) += *(int *)((char *)a1 + 11);
    *(int *)((char *)l_40 + 8) += *(int *)((char *)a1 + 15);
    func_000A0040((int)l_34, 0, 12, (int)D_001757F4, 717, 4);
    func_000C2000(a1 + 7, (int)l_40, a1 + 118);
    func_000C2043(a1 + 118, 110, (int)l_34);
    *(int *)((char *)a1 + 7) += *(int *)l_34;
    *(int *)((char *)a1 + 11) += *(int *)((char *)l_34 + 4);
    *(int *)((char *)a1 + 15) += *(int *)((char *)l_34 + 8);
    *(int *)(*(char **)((char *)l_34 + 12) + 7) = *(int *)((char *)a1 + 7);
    *(int *)(*(char **)((char *)l_34 + 12) + 11) = *(int *)((char *)a1 + 11);
    *(int *)(*(char **)((char *)l_34 + 12) + 15) = *(int *)((char *)a1 + 15);
    l_1C = a1 + 71;
    *(short *)((char *)a1 + 23) = *(short *)(D_00185C16 + (((int)(unsigned char)*(signed char *)((char *)l_1C + 6)) * 2));
    *(signed char *)((char *)a1 + 22) |= 32;
    *(short *)((char *)a1 + 29) = 0;
    *(int *)l_34 = (*(int *)(*(char **)D_00195AA4 + 7) + *(int *)((char *)a1 + 7)) / 2;
    *(int *)((char *)l_34 + 4) = (*(int *)(*(char **)D_00195AA4 + 11) + *(int *)((char *)a1 + 11)) / 2;
    *(int *)((char *)l_34 + 8) = (*(int *)(*(char **)D_00195AA4 + 15) + *(int *)((char *)a1 + 15)) / 2;
    if (func_00023EC2(*(int *)D_00195AA4, (int)l_34, 65) == 0) goto L5C08D;
    func_00069938((int)(short)*(short *)(D_00185C2A + (((int)(unsigned char)*(signed char *)((char *)a1 + 77)) * 2)), a1, 110);
    *(signed char *)((char *)a1 + 23) |= 1;
    *(short *)((char *)a1 + 29) = 32768;
    *(short *)(*(char **)((char *)a1 + 63) + 23) <<= 2;
    func_0005C856(a1, *(int *)D_00195C48);
    if (((int)(unsigned char)*(signed char *)((char *)l_1C + 7)) == 2) goto L5C078;
    if (((int)(unsigned char)*(signed char *)((char *)l_1C + 7)) != 4) goto L5C088;
L5C078:;
    func_0005C897((int)(unsigned char)*(signed char *)((char *)l_1C + 6));
L5C088:;
    return;
L5C08D:;
    func_0005C448(a1, 1);
    if (((int)(unsigned char)*(signed char *)((char *)l_1C + 7)) == 2) goto L5C0BA;
    if (((int)(unsigned char)*(signed char *)((char *)l_1C + 7)) != 4) goto L5C0CA;
L5C0BA:;
    func_0005C897((int)(unsigned char)*(signed char *)((char *)l_1C + 6));
L5C0CA:;
    *(int *)((char *)a1 + 11) += 40;
    if (func_00023C72(*(int *)D_00195AA4, a1) != 0) goto L5C15B;
    *(int *)((char *)a1 + 11) -= 40;
    func_00069938((int)(short)*(short *)(D_00185C2A + (((int)(unsigned char)*(signed char *)((char *)l_1C + 6)) * 2)), a1, 110);
    *(signed char *)((char *)a1 + 23) |= 1;
    *(short *)((char *)a1 + 29) = 32768;
    *(short *)(*(char **)((char *)a1 + 63) + 23) <<= 2;
    if (((int)(unsigned char)*(signed char *)((char *)l_1C + 7)) == 2) goto L5C149;
    if (((int)(unsigned char)*(signed char *)((char *)l_1C + 7)) != 4) goto L5C159;
L5C149:;
    func_0005C897((int)(unsigned char)*(signed char *)((char *)l_1C + 6));
L5C159:;
    return;
L5C15B:;
    *(int *)((char *)a1 + 11) -= 40;
    func_0005C448(a1, 1);
    if (((int)(unsigned char)*(signed char *)((char *)l_1C + 7)) == 2) goto L5C18F;
    if (((int)(unsigned char)*(signed char *)((char *)l_1C + 7)) != 4) goto L5C19F;
L5C18F:;
    func_0005C897((int)(unsigned char)*(signed char *)((char *)l_1C + 6));
L5C19F:;
    func_00069938((int)(short)*(short *)(D_00185C20 + (((int)(unsigned char)*(signed char *)((char *)l_1C + 6)) * 2)), a1, 110);
}
}

void func_0005C1CA(int a1, int a2, int a3)
{
    char l_3C[12];
    int l_28;
    int l_20;
    int l_1C;
    int l_18;
    int l_14;
    int l_10;

    func_0008DD46(*(int *)D_00195AC4, a1);
    l_28 = func_0008DCE3(a1, 0, 0);
    *(signed char *)((char *)l_28) = 7;
    *(short *)((char *)l_28 + 27) = 48;
    *(short *)((char *)l_28 + 23) = 64;
    *(int *)((char *)a1 + 7) = *(int *)((char *)a2 + 7);
    *(int *)((char *)l_28 + 7) = *(int *)((char *)a1 + 7);
    *(int *)((char *)a1 + 11) = *(int *)((char *)a2 + 11) - 50;
    *(int *)((char *)l_28 + 11) = *(int *)((char *)a1 + 11);
    *(int *)((char *)a1 + 15) = *(int *)((char *)a2 + 15);
    *(int *)((char *)l_28 + 15) = *(int *)((char *)a1 + 15);
    *(short *)((char *)l_28 + 1) = 0;
    *(short *)((char *)a1 + 1) = func_000C808D(*(int *)((char *)a2 + 11), *(int *)((char *)a2 + 15), *(int *)((char *)a3 + 11), *(int *)((char *)a3 + 15));
    *(short *)((char *)l_28 + 3) = 0;
    *(short *)((char *)a1 + 3) = func_000C808D(*(int *)((char *)a2 + 7), *(int *)((char *)a2 + 15), *(int *)((char *)a3 + 7), *(int *)((char *)a3 + 15));
    *(short *)((char *)a1 + 5) = 0;
    *(short *)((char *)l_28 + 5) = *(short *)((char *)a1 + 5);
    func_000CE70D((int)(short)*(short *)((char *)a1 + 1), (int)(short)*(short *)((char *)a1 + 3), 110, a1 + 7);
    *(int *)((char *)l_28 + 7) = *(int *)((char *)a1 + 7);
    *(int *)((char *)l_28 + 11) = *(int *)((char *)a1 + 11);
    *(int *)((char *)l_28 + 15) = *(int *)((char *)a1 + 15);
    *(int *)((char *)a3 + 11) -= 50;
    func_000C2000(a1 + 7, a3 + 7, a1 + 118);
    *(int *)((char *)a3 + 11) += 50;
    l_10 = a1 + 71;
    *(short *)((char *)a1 + 23) = *(short *)(D_00185C16 + (((int)(unsigned char)*(signed char *)((char *)l_10 + 6)) * 2));
    *(signed char *)((char *)a1 + 22) |= 32;
    *(short *)((char *)a1 + 29) = 0;
    *(int *)l_3C = (*(int *)((char *)a2 + 7) + *(int *)((char *)a1 + 7)) / 2;
    *(int *)((char *)l_3C + 4) = (*(int *)((char *)a2 + 11) + *(int *)((char *)a1 + 11)) / 2;
    *(int *)((char *)l_3C + 8) = (*(int *)((char *)a2 + 15) + *(int *)((char *)a1 + 15)) / 2;
    if (func_00023EC2(a2, (int)l_3C, 65) == 0) goto L5C412;
    func_00069938((int)(short)*(short *)(D_00185C2A + (((int)(unsigned char)*(signed char *)((char *)a1 + 77)) * 2)), a1, 110);
    *(signed char *)((char *)a1 + 23) |= 1;
    *(short *)((char *)a1 + 29) = 32768;
    *(short *)(*(char **)((char *)a1 + 63) + 23) <<= 2;
    func_0005C856(a1, *(int *)D_00195C48);
    return;
L5C412:;
    func_0005C448(a1, 1);
    func_00069938((int)(short)*(short *)(D_00185C20 + (((int)(unsigned char)*(signed char *)((char *)l_10 + 6)) * 2)), a1, 110);
}

int func_0005C448(int a1, int a2)
{
    int l_44;
    char l_40[12];
    char l_34[12];
    int l_20;
    int l_1C;
    int l_18;

    if (((int)(unsigned short)(*(short *)((char *)a1 + 23) & 1)) == 0) goto L5C49E;
    if (((int)(unsigned short)*(short *)((char *)a1 + 29)) != 36863) goto L5C48C;
    l_44 = 1;
    goto L5C493;
L5C48C:;
    l_44 = 0;
L5C493:;
    return l_44;
L5C49E:;
    l_1C = func_000C7FF4(*(int *)(*(char **)D_00195AA4 + 11) - *(int *)((char *)a1 + 11), func_000C7FD9(*(int *)(*(char **)D_00195AA4 + 7), *(int *)(*(char **)D_00195AA4 + 15), *(int *)((char *)a1 + 7), *(int *)((char *)a1 + 15)));
    if (l_1C <= 2048) goto L5C509;
    (*(short *)((char *)a1 + 23))++;
    *(short *)((char *)a1 + 29) = 32768;
    *(short *)(*(char **)((char *)a1 + 63) + 23) <<= 2;
    return 0;
L5C509:;
    *(int *)l_34 = *(int *)((char *)a1 + 7);
    *(int *)((char *)l_34 + 4) = *(int *)((char *)a1 + 11);
    *(int *)((char *)l_34 + 8) = *(int *)((char *)a1 + 15);
    func_000C2043(a1 + 118, (*(int *)D_00195AB0 * 400) / 1000, (int)l_34);
    *(int *)l_40 = (int)(short)*(short *)((char *)a1 + 1);
    *(int *)((char *)l_40 + 4) = (int)(short)*(short *)((char *)a1 + 3);
    *(int *)((char *)l_40 + 8) = 0;
    *(signed char *)D_00196D64 |= 4;
    l_20 = func_000219B8(a1, (int)l_34, (int)l_40);
    if ((l_20 & 10) == 0) goto L5C600;
    func_00064589(*(int *)D_00195C48, 6);
    func_00069938((int)(short)*(short *)(D_00185C2A + (((int)(unsigned char)*(signed char *)((char *)a1 + 77)) * 2)), a1, 110);
    *(signed char *)((char *)a1 + 23) |= 1;
    *(short *)((char *)a1 + 29) = 32768;
    *(short *)(*(char **)((char *)a1 + 63) + 23) <<= 2;
    if ((l_20 & 8) == 0) goto L5C5F0;
    if (((int)(unsigned char)*(signed char *)((char *)a1 + 78)) == 2) goto L5C5F2;
L5C5F0:;
    goto L5C600;
L5C5F2:;
    func_0005C856(a1, *(int *)D_00195C48);
L5C600:;
    l_18 = func_00073F5D(*(int *)((char *)a1 + 7), *(int *)((char *)a1 + 11), *(int *)((char *)a1 + 15));
    if (l_18 != 0) goto L5C629;
    return 0;
L5C629:;
    if (*(int *)D_00195B84 <= 120) goto L5C63B;
    return 0;
L5C63B:;
    func_00064589(l_18, 6);
    func_00069938((int)(short)*(short *)(D_00185C2A + (((int)(unsigned char)*(signed char *)((char *)a1 + 77)) * 2)), a1, 110);
    *(signed char *)((char *)a1 + 23) |= 1;
    *(short *)((char *)a1 + 29) = 32768;
    *(short *)(*(char **)((char *)a1 + 63) + 23) <<= 2;
    func_0005C856(a1, l_18);
    return 0;
}

void func_0005C6A2(int a1)
{
    int l_20;
    int l_1C;
    int l_18;

    if (((int)(unsigned char)*(signed char *)((char *)a1 + 78)) == 2) return;
    if (((int)(unsigned char)*(signed char *)((char *)a1 + 143)) < 250) goto L5C6E5;
    l_1C = 168;
    goto L5C6FF;
L5C6E5:;
    l_1C = (((int)(unsigned char)*(signed char *)(*(char **)((char *)a1 + 47) + 200)) << 2) + 64;
L5C6FF:;
    l_1C = l_1C * 3;
    l_20 = 0;
L5C70F:;
    if (l_20 < *(int *)D_00195B14) goto L5C727;
    goto L5C7F5;
L5C71F:;
    l_20++;
    goto L5C70F;
L5C727:;
    if (func_000C7FF4(*(int *)((char *)a1 + 11) - *(int *)(*(char **)(D_00190504 + (l_20 << 2)) + 11), func_000C7FD9(*(int *)((char *)a1 + 7), *(int *)((char *)a1 + 15), *(int *)(*(char **)(D_00190504 + (l_20 << 2)) + 7), *(int *)(*(char **)(D_00190504 + (l_20 << 2)) + 15))) >= l_1C) goto L5C7F0;
    if (func_00023C72(a1, *(int *)(D_00190504 + (l_20 << 2))) == 0) goto L5C71F;
    func_0002F72F(*(int *)(D_00190504 + (l_20 << 2)), l_1C * 30, func_000C808D(*(int *)((char *)a1 + 7), *(int *)((char *)a1 + 15), *(int *)(*(char **)(D_00190504 + (l_20 << 2)) + 7), *(int *)(*(char **)(D_00190504 + (l_20 << 2)) + 15)), l_1C);
    func_0005C856(a1, *(int *)(D_00190504 + (l_20 << 2)));
L5C7F0:;
    goto L5C71F;
L5C7F5:;
    if (func_000C7FF4(*(int *)((char *)a1 + 11) - *(int *)(*(char **)D_00195AA4 + 11), func_000C7FD9(*(int *)((char *)a1 + 7), *(int *)((char *)a1 + 15), *(int *)(*(char **)D_00195AA4 + 7), *(int *)(*(char **)D_00195AA4 + 15))) >= l_1C) return;
    func_0005CA87(a1 + 71);
    func_0007D774(a1, *(int *)D_00195AA0);
}

void func_0005C856(int a1, int a2)
{
    func_0005CA87(a1 + 71);
    if (((int)(unsigned char)*(signed char *)((char *)a2)) != 18) return;
    func_0007D774(a1, a2);
}

void func_0005C897(int a1)
{
    if (((int)(short)*(short *)D_001789F8) > (-1)) return;
    *(short *)D_001789F8 = a1 << 4;
}

void func_0005C8CA(void)
{
    int l_1C;
    int l_18;

    if (*(short *)D_001789F8 < 0) return;
    if (((int)(short)(*(short *)D_001789F8 & 15)) != 6) goto L5C952;
    if (((int)(unsigned short)(*(short *)(*(char **)D_00195BF8) & 1)) == 0) goto L5C916;
    l_18 = 0;
    goto L5C92A;
L5C916:;
    l_18 = -((int)(unsigned short)*(short *)(*(char **)D_00195B68 + 6));
L5C92A:;
    func_000CDB7A(*(int *)(D_00195CBC + ((((int)(short)*(short *)D_001789F8) >> 4) << 2)), 0, l_18);
    *(short *)D_001789F8 = 65535;
    return;
L5C952:;
    if (((int)(unsigned short)(*(short *)(*(char **)D_00195BF8) & 1)) == 0) goto L5C971;
    l_1C = 0;
    goto L5C985;
L5C971:;
    l_1C = -((int)(unsigned short)*(short *)(*(char **)D_00195B68 + 6));
L5C985:;
    func_000CDB7A(*(int *)(D_00195CBC + ((((int)(short)*(short *)D_001789F8) >> 4) << 2)), (int)(short)(*(short *)D_001789F8 & 15), l_1C);
    (*(short *)D_001789F8)++;
}

int func_0005C9BF(unsigned char a1)
{
    int l_20;

    l_20 = *(int *)(*(char **)D_00195AA0 + 63);
L5C9DB:;
    if (l_20 == 0) goto L5CA14;
    if (((int)(unsigned char)*(signed char *)((char *)l_20)) != 9) goto L5C9FE;
    if (*(unsigned char *)((char *)l_20 + 144) == a1) goto L5CA00;
L5C9FE:;
    goto L5CA09;
L5CA00:;
    return 1;
L5CA09:;
    l_20 = *(int *)((char *)l_20 + 55);
    goto L5C9DB;
L5CA14:;
    return 0;
}

void func_0005CA28(int a1)
{
    if (((int)(unsigned char)*(signed char *)((char *)a1)) != 9) return;
    if (*(signed char *)(*(char **)D_00199D64 + 73) != *(signed char *)((char *)a1 + 144)) return;
    func_000A0AD9(*(int *)D_00199D64 + 47, a1 + 118, 25, (int)D_001757F4, 958);
}

void func_0005CA87(int a1)
{
    int l_1C;
    int l_18;

    l_1C = 0;
L5CA9F:;
    if (*(signed char *)((char *)(int)(*(char **)D_00195B04 + (l_1C * 89)) + 47) == 0) goto L5CAD2;
    if (*(signed char *)((char *)(int)(*(char **)D_00195B04 + (l_1C * 89)) + 73) == *(signed char *)((char *)a1 + 73)) goto L5CAD0;
    if (l_1C < 128) goto L5CAD2;
L5CAD0:;
    goto L5CADA;
L5CAD2:;
    l_1C++;
    goto L5CA9F;
L5CADA:;
    if (l_1C < 128) goto L5CB14;
    l_18 = func_0008E6C5(*(int *)(*(char **)D_00195AA0 + 63), 27, 0);
    *(int *)D_00199D64 = a1;
    func_0008E3F7(*(int *)((char *)l_18 + 63), (int)func_0005CA28);
    return;
L5CB14:;
    func_000A0AD9(a1 + 47, (int)&*(signed char *)((char *)(int)(*(char **)D_00195B04 + (l_1C * 89)) + 47), 25, (int)D_001757F4, 974);
}

void func_0005CB47(void)
{
    int l_48;
    int l_44;
    int l_40;
    int l_3C;
    int l_38;
    int l_34;
    int l_30;
    int l_2C;
    int l_28;
    int l_24;
    int l_20;
    int l_1C;
    int l_18;

    *(int *)D_00199D6C = 0;
    if (*(int *)(*(char **)D_00195AA0 + 63) == 0) return;
    l_3C = *(int *)(*(char **)D_00195AA0 + 63);
    *(signed char *)D_00199D71 = 1;
L5CB80:;
    if (l_3C == 0) goto L5CDA7;
    if (((int)(unsigned char)*(signed char *)((char *)l_3C)) != 9) goto L5CD99;
    if (*(int *)((char *)l_3C + 47) == *(int *)D_00195AA0) goto L5CBB4;
    l_40 = 1;
    goto L5CBBB;
L5CBB4:;
    l_40 = 0;
L5CBBB:;
    l_20 = l_40;
    if (l_20 == 0) goto L5CBCE;
    *(signed char *)D_00199D71 = 1;
L5CBCE:;
    l_34 = l_3C + 71;
    l_2C = 1;
    l_30 = 0;
L5CBE5:;
    if (l_30 < 3) goto L5CBF5;
    goto L5CC2E;
L5CBED:;
    l_30++;
    goto L5CBE5;
L5CBF5:;
    if (((int)(unsigned char)*(signed char *)((char *)((l_30 * 2) + l_34))) == 255) goto L5CC21;
    if (((int)(unsigned short)*(short *)((char *)((l_30 * 2) + l_34) + 74)) > 1) goto L5CC23;
L5CC21:;
    goto L5CC2C;
L5CC23:;
    l_2C = 0;
    goto L5CC2E;
L5CC2C:;
    goto L5CBED;
L5CC2E:;
    if (((int)(unsigned short)(*(short *)(*(char **)D_00195BF8) & 1)) == 0) goto L5CC4A;
    if (l_20 != 0) goto L5CC4C;
L5CC4A:;
    goto L5CC55;
L5CC4C:;
    l_1C = 11;
    goto L5CC5C;
L5CC55:;
    l_1C = 12;
L5CC5C:;
    l_28 = (int)(unsigned short)*(short *)(D_00185CEC + ((*(int *)D_00199D6C % l_1C) * 2));
    if (((int)(unsigned short)(*(short *)(*(char **)D_00195BF8) & 1)) == 0) goto L5CC95;
    l_28 += 35;
L5CC95:;
    l_24 = ((*(int *)D_00199D6C / 12) * 24) + 16;
    l_18 = 1132;
    if (l_2C == 0) goto L5CCC8;
    if ((*(unsigned char *)((char *)l_18) & 8) != 0) goto L5CCD2;
L5CCC8:;
    if (l_2C != 0) goto L5CD93;
L5CCD2:;
    if (l_20 == 0) goto L5CD13;
    if (((int)(unsigned short)(*(short *)(*(char **)D_00195BF8) & 1)) == 0) goto L5CCF7;
    l_44 = 177;
    goto L5CD0B;
L5CCF7:;
    l_44 = ((int)(unsigned short)*(short *)(*(char **)D_00195B68 + 2)) - 22;
L5CD0B:;
    l_24 = l_44;
    goto L5CD5F;
L5CD13:;
    if (((int)(unsigned char)*(signed char *)((char *)l_34)) != 35) goto L5CD34;
    if (((int)(unsigned char)*(signed char *)((char *)l_34 + 2)) == 255) goto L5CD36;
L5CD34:;
    goto L5CD44;
L5CD36:;
    if (*(int *)(*(char **)D_00195BE0 + 537) == 0) goto L5CD46;
L5CD44:;
    goto L5CD5F;
L5CD46:;
    l_38 = *(int *)((char *)l_3C + 55);
    func_0008A4E4(l_3C);
    l_3C = l_38;
    goto L5CDA2;
L5CD5F:;
    if (((int)(unsigned char)*(signed char *)((char *)l_34 + 72)) < 200) goto L5CD7A;
    l_48 = 10;
    goto L5CD85;
L5CD7A:;
    l_48 = (int)(unsigned char)*(signed char *)((char *)l_34 + 72);
L5CD85:;
    func_000CD20E(l_28, l_24, l_48);
L5CD93:;
    (*(int *)D_00199D6C)++;
L5CD99:;
    l_3C = *(int *)((char *)l_3C + 55);
L5CDA2:;
    goto L5CB80;
L5CDA7:;
    if (*(int *)D_00199D6C != 0) return;
    l_30 = 0;
L5CDB7:;
    if (l_30 < 8) goto L5CDC7;
    return;
L5CDBF:;
    l_30++;
    goto L5CDB7;
L5CDC7:;
    if (*(short *)(*(char **)D_00195BE0 + 32 + (l_30 * 2)) <= *(short *)(*(char **)D_00195BE0 + 48 + (l_30 * 2))) goto L5CE0B;
    *(short *)(*(char **)D_00195BE0 + 32 + (l_30 * 2)) = *(short *)(*(char **)D_00195BE0 + 48 + (l_30 * 2));
L5CE0B:;
    goto L5CDBF;
}
