/* sheet.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/sheet.c to work on it by hand) */

extern char D_0012AC00[];
extern char D_0012B508[];
extern char D_0012DA44[];
extern char D_00170C40[];
extern char D_00170C67[];
extern char D_00170C79[];
extern char D_00170CB1[];
extern char D_00170CC0[];
extern char D_00170CDB[];
extern char D_00170CEC[];
extern char D_00170CFD[];
extern char D_00170D4C[];
extern char D_00178A08[];
extern char D_0017B4C0[];
extern char D_0017B508[];
extern char D_0017B604[];
extern char D_0017B608[];
extern char D_0017B610[];
extern char D_0017B614[];
extern char D_0017CC27[];
extern char D_0017CCB7[];
extern char D_0017CCDA[];
extern char D_0017D1EA[];
extern char D_00182682[];
extern char D_001903A4[];
extern char D_001903A5[];
extern char D_00190BE4[];
extern char D_00190C34[];
extern char D_00190D64[];
extern char D_00190D6A[];
extern char D_00190D8C[];
extern char D_00190DE4[];
extern char D_001940D4[];
extern char D_001940D8[];
extern char D_001940D9[];
extern char D_00195AA0[];
extern char D_00195B14[];
extern char D_00195B5C[];
extern char D_00195BE0[];
extern char D_00195BE8[];
extern char D_00195BEC[];
extern char D_00195BF4[];
extern char D_00195C44[];
extern char D_00195D30[];
extern char D_00195D6C[];
extern char D_00195D78[];
extern char D_00195F36[];
extern char D_0019626C[];
extern char D_0019626F[];
extern char D_00196271[];
extern char D_00196272[];
extern char D_00196274[];
extern char D_0019963C[];
extern char D_00199644[];
extern char D_001A4A14[];

extern int func_000392AD(void);
extern int func_0003B1F3(int);
extern int func_0003B436(void);
extern int func_0003C3A8(int);
extern int func_0003C6F1(void);
extern int func_000417C8(int);
extern int func_00055748(void);
extern int func_0006A683(int);
extern int func_0006CB53(int, int);
extern int func_0006CD6E(int);
extern int func_0007D6AE(int, int);
extern int func_0007F2A8(int);
extern int func_000926AD(int, int, int);
extern int func_0009DEA7();
extern int func_000A0024();
extern int func_000A0AD9();
extern int func_000A0DD9();
extern int func_000A0DF4();
extern int func_000A0ED9(int, int);
extern int func_000A0F5C(int, ...);
extern int func_000A1054();
extern int func_000A1079();
extern int func_000CB552();
extern int func_000CDD81();
extern int func_0012B136();
extern int func_0012DB50();
extern int func_00144FB4();
extern void func_000255B7(void);
extern void func_0003B6CF(void);
extern void func_0003BB8D(int);
extern void func_0003BDB0(int, int);
extern void func_0003D01C(int, int);
extern void func_0003EC2A(int, int);
extern void func_0003F09F(int, int);
extern void func_0004AB2F(int);
extern void func_00058E15(int, int);
extern void func_0007CA85(int, int, int, int, unsigned char);
extern void func_0007D24F(int);
extern void func_0007DDC9(int);
extern void func_0007F1E3(int);
extern void func_0008C566(int, short);
extern void func_0008E3F7(int, int);
#pragma aux func_000A0ED9 parm routine [];
#pragma dagger DAGGER_DEADDEF func_0003C8B2
#pragma dagger KKND_CONFREV func_0003C010
#pragma dagger KKND_CONFREV func_0003C0D3

void func_0003BAD0(void)
{
    int l_18;

    l_18 = *(int *)D_00195C44 + 55000;
    func_000A0ED9(232, (int)D_00170C67);
    func_000A0F5C(l_18, (int)D_00170C79, *(int *)D_0017D1EA);
    *(signed char *)((char *)(func_000A0DF4(l_18) + l_18) + 1) = 0;
    func_0008C566(*(int *)D_00195BE0, 23);
    func_0003EC2A(l_18, 2);
}

void func_0003BB48(void)
{
L3BB56:;
    if (*(signed char *)D_0012AC00 == 0) goto L3BB66;
    func_0012B136();
    goto L3BB56;
L3BB66:;
    func_0003B436();
    func_000926AD(1, 0, 2);
    *(signed char *)D_001940D8 |= 32;
}

void func_0003BC48(void)
{
    *(short *)D_00195F36 = 0;
    *(int *)D_0019963C = *(int *)D_00195C44 + 55000;
    func_000A0ED9(264, (int)D_00170C67);
    func_000A0F5C(*(int *)D_0019963C, (int)D_00170CB1, *(int *)D_00182682);
    func_0008E3F7(*(int *)((char *)*(int *)D_00195AA0 + 63), (int)func_0003BB8D);
    if (*(short *)D_00195F36 != 0) goto L3BCC5;
    func_0003F09F(19, 1);
    return;
L3BCC5:;
    *(short *)D_00178A08 = 250;
    *(signed char *)((char *)(int)(*(char **)D_0019963C + func_000A0DF4(*(int *)D_0019963C)) - 1) = 0;
    func_0003EC2A(*(int *)D_0019963C, 1);
    *(short *)D_00178A08 = 310;
}

void func_0003BD06(void)
{
L3BD14:;
    if (*(signed char *)D_0012AC00 == 0) goto L3BD24;
    func_0012B136();
    goto L3BD14;
L3BD24:;
    func_0003B436();
    func_000417C8(1);
    *(signed char *)D_001940D8 |= 32;
}

void func_0003BD44(void)
{
    func_0003BDB0(0, 0);
}

void func_0003BD65(void)
{
    func_0003BDB0(3, 0);
}

void func_0003BD89(void)
{
    func_0003BDB0(6, 1);
}

void func_0003C010(int a1, short a2, int a3)
{
{
    int l_1C;

    if (((int)(short)a2) != 30) goto L3C035;
    *(signed char *)D_00199644 = 1;
L3C035:;
    func_000A0ED9(349, (int)D_00170C67);
    func_000A0F5C((int)D_001903A4, (int)D_00170CDB, *(int *)(D_0017CC27 + (((int)(short)a2) << 2)), (int)(short)*(short *)((char *)(int)(*(char **)D_00195BE0 + (((int)(short)a2) * 6)) + 157), *(int *)(D_0017CCDA + (((int)(unsigned char)*(signed char *)(D_0017CCB7 + ((int)(short)a2))) << 2)));
    if (a3 == 0) goto L3C0A3;
    l_1C = 96;
    goto L3C0AA;
L3C0A3:;
    l_1C = 145;
L3C0AA:;
    *(signed char *)D_001903A5 = *(signed char *)&l_1C;
    func_000A1054(a1, (int)D_001903A4, (int)D_00170C67, 351, 4);
}
}

void func_0003C0D3(void)
{
    int l_2C;
    int l_28;
    int l_24;
    int l_20;
    int l_1C;
    short l_18;

    l_24 = *(int *)D_00195C44 + 55000;
    *(signed char *)D_00199644 = 0;
    *(signed char *)((char *)l_24) = 0;
    l_20 = 0;
    l_1C = l_20;
L3C108:;
    if (((int)(short)*(short *)&l_20) < 35) goto L3C11E;
    goto L3C2B7;
L3C116:;
    l_20++;
    goto L3C108;
L3C11E:;
    if (func_000A1079(*(int *)D_00195BEC + 16, (int)(short)*(short *)&l_20, 12) != 0) goto L3C2B2;
    *(int *)&l_18 = func_0003C3A8((int)(short)*(short *)&l_20);
    if (((int)(short)(l_1C & 1)) == 0) goto L3C205;
    if (((int)(short)*(short *)&l_20) != 30) goto L3C169;
    *(signed char *)D_00199644 = 1;
L3C169:;
    func_000A0ED9(372, (int)D_00170C67);
    func_000A0F5C((int)D_001903A4, (int)D_00170CEC, *(int *)(D_0017CC27 + (((int)(short)*(short *)&l_20) << 2)), (int)(short)*(short *)((char *)(int)(*(char **)D_00195BE0 + (((int)(short)*(short *)&l_20) * 6)) + 157), *(int *)(D_0017CCDA + (((int)(unsigned char)*(signed char *)(D_0017CCB7 + ((int)(short)*(short *)&l_20))) << 2)));
    if (l_18 == 0) goto L3C1D8;
    l_28 = 96;
    goto L3C1DF;
L3C1D8:;
    l_28 = 145;
L3C1DF:;
    *(signed char *)D_001903A5 = *(signed char *)&l_28;
    func_000A1054(l_24, (int)D_001903A4, (int)D_00170C67, 374, 4);
    goto L3C2AC;
L3C205:;
    if (((int)(short)*(short *)&l_20) != 30) goto L3C215;
    *(signed char *)D_00199644 = 1;
L3C215:;
    func_000A0ED9(379, (int)D_00170C67);
    func_000A0F5C((int)D_001903A4, (int)D_00170CFD, *(int *)(D_0017CC27 + (((int)(short)*(short *)&l_20) << 2)), (int)(short)*(short *)((char *)(int)(*(char **)D_00195BE0 + (((int)(short)*(short *)&l_20) * 6)) + 157), *(int *)(D_0017CCDA + (((int)(unsigned char)*(signed char *)(D_0017CCB7 + ((int)(short)*(short *)&l_20))) << 2)));
    if (l_18 == 0) goto L3C284;
    l_2C = 96;
    goto L3C28B;
L3C284:;
    l_2C = 145;
L3C28B:;
    *(signed char *)D_001903A5 = *(signed char *)&l_2C;
    func_000A1054(l_24, (int)D_001903A4, (int)D_00170C67, 381, 4);
L3C2AC:;
    l_1C++;
L3C2B2:;
    goto L3C116;
L3C2B7:;
    if (*(signed char *)D_00199644 == 0) goto L3C33A;
    func_000A0ED9(389, (int)D_00170C67);
    func_000A0F5C((int)D_001903A4, (int)D_00170CC0, (((int)(short)*(short *)((char *)*(int *)D_00195BE0 + 337)) / 10) + 1, (((int)(short)*(short *)((char *)*(int *)D_00195BE0 + 337)) / 5) + 1);
    *(signed char *)D_001903A5 = 96;
    func_000A1054(l_24, (int)D_001903A4, (int)D_00170C67, 391, 4);
L3C33A:;
    if (((int)(short)(l_1C & 1)) == 0) goto L3C356;
    *(signed char *)((char *)(func_000A0DF4(l_24) + l_24) - 2) = 0;
L3C356:;
    *(signed char *)((char *)(func_000A0DF4(l_24) + l_24) - 1) = 0;
    func_000CB552(*(int *)D_00195BE8);
    func_00058E15(0, 0);
    func_0012DB50(4);
    func_0003B6CF();
    func_000CDD81(1);
    func_0003EC2A(l_24, 1);
}

void func_0003C400(void)
{
    int l_18;

    l_18 = func_00055748();
L3C416:;
    if (*(signed char *)D_0012AC00 == 0) goto L3C426;
    func_0012B136();
    goto L3C416;
L3C426:;
    if (*(signed char *)((char *)l_18) == 0) goto L3C43B;
    func_0003EC2A(l_18, 1);
L3C43B:;
    if (*(signed char *)D_0012AC00 == 0) goto L3C44B;
    func_0012B136();
    goto L3C43B;
L3C44B:;
    if (*(int *)D_00195BE8 == 0) goto L3C460;
    if (*(int *)D_00195BE8 != (-1751672937)) goto L3C462;
L3C460:;
    goto L3C480;
L3C462:;
    func_000A0024(*(int *)D_00195BE8, (int)D_00170C67, 428);
    *(int *)D_00195BE8 = -1751672937;
L3C480:;
    func_000255B7();
    *(int *)D_00195BE8 = func_0006CB53((int)D_00170C40, 0);
}

void func_0003C4A0(void)
{
L3C4AE:;
    if (*(signed char *)D_0012AC00 == 0) goto L3C4BE;
    func_0012B136();
    goto L3C4AE;
L3C4BE:;
    func_0003B436();
    func_0006A683(1);
    *(signed char *)D_001940D8 |= 32;
}

void func_0003C4DE(void)
{
    int l_18;

    l_18 = func_0003C6F1();
    if (l_18 != 0) goto L3C50B;
    func_0003F09F(18, 1);
    return;
L3C50B:;
    func_0003EC2A(l_18, 1);
}

void func_0003C5A4(int a1)
{
    *(short *)D_0017B604 = (*(short *)D_00190D6A = *(short *)(D_0017B508 + (a1 * 12)) + 1);
    *(short *)D_0017B608 = *(short *)D_00190D6A + 6;
    *(short *)D_0017B610 = *(short *)D_00190D6A + 13;
    *(short *)D_0017B614 = *(short *)D_00190D6A + 19;
}

void func_0003C81C(void)
{
    if ((*(unsigned char *)D_001940D9 & 4) == 0) return;
    func_00144FB4(176, (int)(short)*(short *)D_00190D6A, (int)(unsigned short)*(short *)((char *)*(int *)D_00195B5C + 4), (int)(unsigned short)*(short *)((char *)*(int *)D_00195B5C + 6), *(int *)D_00195B5C + 12);
    func_0007CA85(func_000A0DD9((int)(short)*(short *)D_00190D64, (int)D_001903A4, 10), 182, (int)(short)(((*(short *)D_00190D6A + 13) - *(short *)D_0012DA44) + 1), 145, 141);
}

void func_0003C8B2(int a1)
{
    int l_1C;
    int l_18;

    if ((*(unsigned char *)D_001940D9 & 4) == 0) return;
    l_1C = 1132;
    if (((unsigned)(*(int *)((char *)l_1C) - *(int *)D_00190BE4)) < 6) return;
    l_18 = 1132;
    *(int *)D_00190BE4 = *(int *)((char *)l_18);
    if (a1 != 21) goto L3C95D;
    if (*(short *)D_00190D64 == 0) goto L3C927;
    if (((int)(short)*(short *)((char *)(int)(*(char **)D_00195BE0 + (((int)(unsigned char)*(signed char *)D_0019626C) * 2)) + 48)) < 100) goto L3C929;
L3C927:;
    goto L3C95B;
L3C929:;
    (*(short *)D_00190D64)--;
    (*(short *)((char *)(int)(*(char **)D_00195BE0 + (((int)(unsigned char)*(signed char *)D_0019626C) * 2)) + 32))++;
    (*(short *)((char *)(int)(*(char **)D_00195BE0 + (((int)(unsigned char)*(signed char *)D_0019626C) * 2)) + 48))++;
L3C95B:;
    return;
L3C95D:;
    if (*(short *)((char *)(int)(*(char **)D_00195BE0 + (((int)(unsigned char)*(signed char *)D_0019626C) * 2)) + 48) <= *(short *)(D_00190D8C + (((int)(unsigned char)*(signed char *)D_0019626C) * 2))) return;
    (*(short *)D_00190D64)++;
    (*(short *)((char *)(int)(*(char **)D_00195BE0 + (((int)(unsigned char)*(signed char *)D_0019626C) * 2)) + 32))--;
    (*(short *)((char *)(int)(*(char **)D_00195BE0 + (((int)(unsigned char)*(signed char *)D_0019626C) * 2)) + 48))--;
}

void func_0003C9C1(int a1)
{
    if (((unsigned)(*(int *)D_00195BF4 - *(int *)((char *)*(int *)D_00195BE0 + 521))) >= 720) goto L3C9FB;
    func_0003F09F(4023, 1);
    return;
L3C9FB:;
    *(int *)D_00190DE4 = a1;
    *(int *)D_00190C34 = 1234;
    *(signed char *)D_00196274 = 23;
    *(signed char *)D_00196272 = 1;
    *(int *)D_00195D30 = ((int)(unsigned char)*(signed char *)((char *)*(int *)D_00195BE0 + 129)) * 100;
    if (*(int *)D_001A4A14 != 0) goto L3CA43;
    *(int *)D_00195D30 <<= 2;
L3CA43:;
    func_0007DDC9(8);
}

void func_0003CA57(void)
{
    int l_20;
    int l_1C;
    int l_18;

    if (((int)(unsigned char)*(signed char *)D_00196274) != 23) return;
    switch (*(int *)D_00190C34) {
case 1234:
    if (((int)(unsigned char)*(signed char *)D_00196271) != 2) goto L3CACD;
    *(int *)D_00190C34 = 1235;
    return;
L3CACD:;
    if (func_0007F2A8(*(int *)D_00195D30) != 0) goto L3CAF9;
    func_0003F09F(454, 1);
    *(int *)D_00190C34 = 1235;
    return;
L3CAF9:;
    *(signed char *)D_001940D8 |= 1;
    l_20 = *(int *)D_00190DE4;
    l_18 = 0;
    l_1C = *(int *)D_00195C44;
L3CB17:;
    if (((int)(unsigned char)*(signed char *)((char *)(l_20 + l_18))) == 255) goto L3CB6D;
    func_000A0AD9(l_1C, *(int *)(D_0017CC27 + (((int)(unsigned char)*(signed char *)((char *)(l_20 + l_18))) << 2)), 4, (int)D_00170C67, 615);
    l_1C += func_000A0DF4(l_1C) + 1;
    l_18++;
    goto L3CB17;
L3CB6D:;
    *(signed char *)((char *)l_1C) = 0;
    func_0007D24F(*(int *)D_00195C44);
    *(int *)D_00190C34 = 1236;
    return;
case 1235:
    *(signed char *)D_00196272 = 0;
    *(signed char *)D_00196274 = 0;
    return;
case 1236:
    if ((*(unsigned char *)D_001940D4 & 4) == 0) goto L3CBB6;
    l_18 = func_000392AD();
    if (l_18 > (-1)) goto L3CBBB;
L3CBB6:;
    goto L3CC86;
L3CBBB:;
    l_20 = *(int *)D_00190DE4;
    if (((int)(short)*(short *)((char *)(int)(*(char **)D_00195BE0 + (((int)(unsigned char)*(signed char *)((char *)(l_20 + l_18))) * 6)) + 157)) <= 50) goto L3CC05;
    func_0003F09F(4022, 1);
    *(int *)D_00190C34 = 1235;
    return;
L3CC05:;
    func_0007F1E3(*(int *)D_00195D30);
    *(int *)((char *)*(int *)D_00195BE0 + 521) = *(int *)D_00195BF4;
    func_0003D01C((int)(unsigned char)*(signed char *)((char *)(l_20 + l_18)), func_0007D6AE(10, 20) * ((int)(short)*(short *)(D_0017B4C0 + (((int)(unsigned char)*(signed char *)((char *)(l_20 + l_18))) * 2))));
    *(signed char *)D_0012B508 = 146;
    func_0003F09F(5221, 1);
    *(int *)D_00190C34 = 1235;
    func_0004AB2F(180);
L3CC86:;
    if ((*(unsigned char *)D_001940D4 & 4) != 0) return;
    *(int *)D_00190C34 = 1235;
default:;
}
}

void func_0003CFB9(void)
{
    if ((*(unsigned char *)D_001940D9 & 4) == 0) goto L3CFD9;
    if (*(int *)D_00195B14 == 0) goto L3CFDB;
L3CFD9:;
    goto L3CFE4;
L3CFDB:;
    if (*(signed char *)D_00196274 == 0) goto L3CFE6;
L3CFE4:;
    goto L3CFF2;
L3CFE6:;
    if (((int)(unsigned char)*(signed char *)D_0019626F) == 16) goto L3CFF4;
L3CFF2:;
    goto L3D006;
L3CFF4:;
    if (((int)(unsigned char)*(signed char *)((char *)*(int *)D_00195BE0 + 67)) < 9) goto L3D008;
L3D006:;
    return;
L3D008:;
    func_0003B1F3(1);
}

int func_0003D0A8(void)
{
    int l_1C;

    l_1C = 0;
L3D0BD:;
    if (l_1C < 6) goto L3D0CD;
    goto L3D0FF;
L3D0C5:;
    l_1C++;
    goto L3D0BD;
L3D0CD:;
    if (((int)(short)*(short *)((char *)(int)(*(char **)D_00195BE0 + (((int)(unsigned char)*(signed char *)((char *)(*(int *)D_00195BEC + l_1C) + 16)) * 6)) + 157)) != 100) goto L3D0FD;
    return 1;
L3D0FD:;
    goto L3D0C5;
L3D0FF:;
    return 0;
}

int func_0003D39D(void)
{
    int l_1C;

    *(int *)D_00195D78 = (*(int *)D_00195D6C = func_0006CD6E((int)D_00170D4C));
    if (*(int *)D_00195D6C <= 0) goto L3D3D6;
    l_1C = 1;
    goto L3D3DD;
L3D3D6:;
    l_1C = 0;
L3D3DD:;
    return l_1C;
}

void func_0003D3F0(void)
{
    func_0009DEA7(*(int *)D_00195D6C);
}
