/* support.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/support.c to work on it by hand) */

extern char detect_target[];
extern char D_00195B84[];


void detect_consider_creature(int a1, int a2)
{
    *(short *)((char *)a1 + 23) = a2;
    if (a2 >= *(int *)D_00195B84) goto L7DC0D;
    if (a2 < 2048) goto L7DC0F;
L7DC0D:;
    return;
L7DC0F:;
    *(int *)detect_target = a1;
    *(int *)D_00195B84 = a2;
}
