/* tamriel.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/tamriel.c to work on it by hand) */

extern char D_0012B508[];
extern char D_0018F08E[];
extern char D_00195A04[];
extern char D_00195B24[];
extern char D_00195B28[];
extern char D_00195B38[];
extern char D_00195B3C[];
extern char D_00195B4C[];
extern char D_00195BF4[];
extern char D_00195F24[];
extern char D_00195F25[];
extern char D_00196268[];
extern char D_00199764[];
extern char D_0019976C[];
extern char D_00199784[];
extern char D_00199788[];
extern char D_0019978A[];
extern char D_0019978C[];
extern char D_0019978E[];
extern char D_00199790[];
extern char D_00199792[];
extern char D_00199794[];
extern char D_00199796[];
extern char D_00199798[];
extern char D_0019979A[];

extern int func_0004A98C(int, int);
extern void func_0003081B(unsigned char);
extern void func_00030E34(unsigned char);
extern void func_0003F09F(short, int);
extern void func_0004AC01(int);

void func_0004AB2F(int a1)
{
    func_0004AC01(a1);
}

void func_0004B0C3(void)
{
    int l_1C;
    int l_18;

    *(int *)D_00195B24 = (((unsigned)*(int *)D_00195BF4) / 518400) + 400;
    *(int *)D_00195B38 = ((unsigned)(((unsigned)*(int *)D_00195BF4) % 518400)) / 43200;
    *(int *)D_00195B28 = ((unsigned)(((unsigned)*(int *)D_00195BF4) / 1440)) % 7;
    *(int *)D_00195B4C = ((unsigned)(((unsigned)*(int *)D_00195BF4) / 60)) % 24;
    *(int *)D_00195B3C = ((unsigned)*(int *)D_00195BF4) % 60;
    *(signed char *)D_00195F24 = ((unsigned)(((unsigned)*(int *)D_00195BF4) / 1440)) % 22;
    *(signed char *)D_00195F25 = (((unsigned)*(int *)D_00195BF4) / 1440) & 15;
}

void func_0004B796(void)
{
    int l_18;

    l_18 = func_0004A98C(*(int *)D_00195BF4, (unsigned char)*(signed char *)D_00196268);
    if (l_18 == 0) return;
    *(signed char *)D_0012B508 = 146;
    func_0003F09F((short)(l_18 + 8349), 1);
}

void func_0004BA0F(void)
{
    int l_1C;
    int l_18;

    l_18 = *(int *)D_00195A04 + 71;
    l_1C = 0;
L4BA2F:;
    if (l_1C < 62) goto L4BA3F;
    return;
L4BA37:;
    l_1C++;
    goto L4BA2F;
L4BA3F:;
    if (*(int *)((char *)l_18 + 8) == 0) goto L4BA37;
    if (*(int *)((char *)l_18 + 8) != *(int *)D_00195BF4) goto L4BA62;
    *(short *)(D_0018F08E + (l_1C * 80)) -= 5;
L4BA62:;
    goto L4BA37;
}

void func_0004BA70(void)
{
    *(short *)D_00199788 = 19;
    *(short *)D_0019978A = 94;
    *(short *)D_0019978C = 34;
    *(short *)D_0019978E = 20;
    *(short *)D_00199790 = 24;
    *(short *)D_00199792 = 16;
    *(short *)D_00199794 = 33;
    *(short *)D_00199796 = 14;
    *(short *)D_00199798 = 87;
    *(short *)D_0019979A = 8;
}

void func_0004BCA6(int a1)
{
    *(int *)D_00199784 = (short)*(short *)((char *)*(int *)D_00199764);
    func_00030E34((unsigned char)*(signed char *)((char *)*(int *)D_00199764));
    func_0003081B((unsigned char)*(signed char *)((char *)*(int *)D_00199764));
    *(int *)D_0019976C = 0;
}
