/* trade.c: lifted functions that match (generated by tools/promote_lifted.py;
 * do not edit: move a function to src/trade.c to work on it by hand) */

extern char D_000CDDA8[];
extern char D_001A3AE8[];
extern char D_001A3F3C[];
extern char D_001A3F40[];
extern char D_001A3F44[];
extern char D_001A3F5D[];

extern int func_000112A1();
extern int func_0009957D(int, int);
extern void func_00012F27(int);
extern void func_000696A3(int);
extern void func_000697E3(void);
extern void func_00069B53(int);

void func_00068B1B(void)
{
    int l_18;

    if (*(signed char *)D_001A3F5D == 0) return;
    func_00069B53(*(int *)D_001A3F3C);
    func_000697E3();
    func_00012F27(*(int *)D_001A3F44);
    l_18 = 0;
L68B52:;
    if (l_18 < 4) goto L68B62;
    goto L68B6C;
L68B5A:;
    l_18++;
    goto L68B52;
L68B62:;
    func_000696A3(l_18);
    goto L68B5A;
L68B6C:;
    func_000112A1();
    func_0009957D((int)D_001A3AE8, 5168);
    func_0009957D((int)D_000CDDA8, 4096);
    func_0009957D((int)D_001A3F40, 4096);
}
