/* xn_12B100.c: XnGine module xn_12B100 (FALL.EXE object 2, 0x12B100-0x12B500) as literal C.
   Generated by tools/xn_c.py from the code in src/xngine/xn_12B100.asm; do not edit (a hand-written
   replacement for a function goes in src/xngine_c/override/xn_<va>.c). Each function is the
   asm one instruction at a time, on the register file R (see runtime.h). */
#include "runtime.h"


/* xn_mouse_init (confirmed): init_video: int 33h fn 7 x range 10..630, fn 8 y range 10..460, fn 4 position (10,10) */
void xn_0012B100(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_12B100:
    t = R.esp; PUSH32(R.eax); PUSH32(R.ecx); PUSH32(R.edx); PUSH32(R.ebx); /* 12B100: pushal  */
    PUSH32(t); PUSH32(R.ebp); PUSH32(R.esi); PUSH32(R.edi);
    R.eax = 0x7;                                                 /* 12B101: mov eax, 7 */
    R.ecx = 0xA;                                                 /* 12B106: mov ecx, 0xa */
    R.edx = 0x276;                                               /* 12B10B: mov edx, 0x276 */
    xn_int(0x33);                                                /* 12B110: int 0x33 */
    R.eax = 0x8;                                                 /* 12B112: mov eax, 8 */
    R.ecx = 0xA;                                                 /* 12B117: mov ecx, 0xa */
    R.edx = 0x1CC;                                               /* 12B11C: mov edx, 0x1cc */
    xn_int(0x33);                                                /* 12B121: int 0x33 */
    R.eax = 0x4;                                                 /* 12B123: mov eax, 4 */
    R.ecx = 0xA;                                                 /* 12B128: mov ecx, 0xa */
    R.edx = 0xA;                                                 /* 12B12D: mov edx, 0xa */
    xn_int(0x33);                                                /* 12B132: int 0x33 */
    R.edi = M32(R.esp); R.esi = M32(R.esp + 4); R.ebp = M32(R.esp + 8); /* 12B134: popal  */
    R.ebx = M32(R.esp + 16); R.edx = M32(R.esp + 20); R.ecx = M32(R.esp + 24);
    R.eax = M32(R.esp + 28); R.esp += 32;
    RET(0);                                                      /* 12B135: ret  */
}

/* xn_mouse_poll_clamped (strong): 107 game sites (every menu loop): 12B196 then clamps mouse_x/mouse_y to mouse_x_min..max /
   mouse_y_min..max */
void xn_0012B136(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_12B136:
    t = R.esp; PUSH32(R.eax); PUSH32(R.ecx); PUSH32(R.edx); PUSH32(R.ebx); /* 12B136: pushal  */
    PUSH32(t); PUSH32(R.ebp); PUSH32(R.esi); PUSH32(R.edi);
    PUSH32(XN(0x12B13C)); xn_call(XN(0x12B196));                 /* 12B137: call 0x12b196 */
    AX = M16(XN(0x12AC04));                                      /* 12B13C: mov ax, word ptr [0x12ac04] */
    fa = AX; fb = M16(XN(0x12AF34));                             /* 12B142: cmp ax, word ptr [0x12af34] */
    fr = fa - fb;
    if ((!((s16)fa < (s16)fb))) goto L_12B153;                   /* 12B149: jge 0x12b153 */
    AX = M16(XN(0x12AF34));                                      /* 12B14B: mov ax, word ptr [0x12af34] */
    goto L_12B162;                                               /* 12B151: jmp 0x12b162 */
L_12B153:
    fa = AX; fb = M16(XN(0x12AF36));                             /* 12B153: cmp ax, word ptr [0x12af36] */
    fr = fa - fb;
    if (((s16)fa <= (s16)fb)) goto L_12B162;                     /* 12B15A: jle 0x12b162 */
    AX = M16(XN(0x12AF36));                                      /* 12B15C: mov ax, word ptr [0x12af36] */
L_12B162:
    M16(XN(0x12AC04)) = AX;                                      /* 12B162: mov word ptr [0x12ac04], ax */
    AX = M16(XN(0x12AC06));                                      /* 12B168: mov ax, word ptr [0x12ac06] */
    fa = AX; fb = M16(XN(0x12AF38));                             /* 12B16E: cmp ax, word ptr [0x12af38] */
    fr = fa - fb;
    LF(XF_SUB | 1, fa, fb, fr);
    if ((!((s16)fa < (s16)fb))) goto L_12B17F;                   /* 12B175: jge 0x12b17f */
    AX = M16(XN(0x12AF38));                                      /* 12B177: mov ax, word ptr [0x12af38] */
    goto L_12B18E;                                               /* 12B17D: jmp 0x12b18e */
L_12B17F:
    fa = AX; fb = M16(XN(0x12AF3A));                             /* 12B17F: cmp ax, word ptr [0x12af3a] */
    fr = fa - fb;
    LF(XF_SUB | 1, fa, fb, fr);
    if (((s16)fa <= (s16)fb)) goto L_12B18E;                     /* 12B186: jle 0x12b18e */
    AX = M16(XN(0x12AF3A));                                      /* 12B188: mov ax, word ptr [0x12af3a] */
L_12B18E:
    M16(XN(0x12AC06)) = AX;                                      /* 12B18E: mov word ptr [0x12ac06], ax */
    R.edi = M32(R.esp); R.esi = M32(R.esp + 4); R.ebp = M32(R.esp + 8); /* 12B194: popal  */
    R.ebx = M32(R.esp + 16); R.edx = M32(R.esp + 20); R.ecx = M32(R.esp + 24);
    R.eax = M32(R.esp + 28); R.esp += 32;
    RET(0);                                                      /* 12B195: ret  */
}

/* xn_mouse_poll (strong): int 33h fn 3: mouse_buttons (previous in 0x12AC01), mouse_x, mouse_y; a new left/right press
   within 8 BIOS ticks and 4 pixels of the last sets mouse_double_click bit 0/1
   (docs/xngine.md) */
void xn_0012B196(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_12B196:
    t = (u16)R.ds; PUSH32(t);                                    /* 12B196: push ds */
    R.fs = M16(R.esp); R.esp += 4;                               /* 12B197: pop fs */
    AL = M8(XN(0x12AC00));                                       /* 12B199: mov al, byte ptr [0x12ac00] */
    M8(XN(0x12AC01)) = AL;                                       /* 12B19E: mov byte ptr [0x12ac01], al */
    R.eax = 0x3;                                                 /* 12B1A3: mov eax, 3 */
    xn_int(0x33);                                                /* 12B1A8: int 0x33 */
    M8(XN(0x12AC00)) = BL;                                       /* 12B1AA: mov byte ptr [0x12ac00], bl */
    M16(XN(0x12AC04)) = CX;                                      /* 12B1B0: mov word ptr [0x12ac04], cx */
    M16(XN(0x12AC06)) = DX;                                      /* 12B1B7: mov word ptr [0x12ac06], dx */
    M16(XN(0x12AC02)) = 0x0;                                     /* 12B1BE: mov word ptr [0x12ac02], 0 */
    R.edx = 0x46C;                                               /* 12B1C7: mov edx, 0x46c */
    R.edx = M32(R.edx);                                          /* 12B1CC: mov edx, dword ptr [edx] */
    AL = M8(XN(0x12AC00));                                       /* 12B1CE: mov al, byte ptr [0x12ac00] */
    AH = M8(XN(0x12AC01));                                       /* 12B1D3: mov ah, byte ptr [0x12ac01] */
    AX &= 0x101;                                                 /* 12B1D9: and ax, 0x101 */
    fa = AX; fb = 0x1;                                           /* 12B1DD: cmp ax, 1 */
    fr = fa - fb;
    if ((!((u16)fa == (u16)fb))) goto L_12B250;                  /* 12B1E1: jne 0x12b250 */
    /* 12B1E3: nop  */
    /* 12B1E4: nop  */
    /* 12B1E5: nop  */
    /* 12B1E6: nop  */
    R.eax = R.edx;                                               /* 12B1E7: mov eax, edx */
    R.eax -= M32(XN(0x12AF24));                                  /* 12B1E9: sub eax, dword ptr [0x12af24] */
    fa = R.eax; fb = R.eax;                                      /* 12B1EF: or eax, eax */
    fr = fa | fb;
    R.eax = fr;
    if ((!((s32)fr < 0))) goto L_12B1F5;                         /* 12B1F1: jns 0x12b1f5 */
    R.eax = 0 - R.eax;                                           /* 12B1F3: neg eax */
L_12B1F5:
    fa = R.eax; fb = 0x8;                                        /* 12B1F5: cmp eax, 8 */
    fr = fa - fb;
    if ((!((s32)fa < (s32)fb))) goto L_12B232;                   /* 12B1F8: jge 0x12b232 */
    AX = M16(XN(0x12AF28));                                      /* 12B1FA: mov ax, word ptr [0x12af28] */
    fa = AX; fb = M16(XN(0x12AC04));                             /* 12B200: sub ax, word ptr [0x12ac04] */
    fr = fa - fb;
    AX = (u16)fr;
    if (!((s16)fr < 0)) goto L_12B20C;                           /* 12B207: jns 0x12b20c */
    AX = 0 - AX;                                                 /* 12B209: neg ax */
L_12B20C:
    fa = AX; fb = 0x4;                                           /* 12B20C: cmp ax, 4 */
    fr = fa - fb;
    if ((!((s16)fa < (s16)fb))) goto L_12B232;                   /* 12B210: jge 0x12b232 */
    AX = M16(XN(0x12AF2A));                                      /* 12B212: mov ax, word ptr [0x12af2a] */
    fa = AX; fb = M16(XN(0x12AC06));                             /* 12B218: sub ax, word ptr [0x12ac06] */
    fr = fa - fb;
    AX = (u16)fr;
    if (!((s16)fr < 0)) goto L_12B224;                           /* 12B21F: jns 0x12b224 */
    AX = 0 - AX;                                                 /* 12B221: neg ax */
L_12B224:
    fa = AX; fb = 0x4;                                           /* 12B224: cmp ax, 4 */
    fr = fa - fb;
    if ((!((s16)fa < (s16)fb))) goto L_12B232;                   /* 12B228: jge 0x12b232 */
    M16(XN(0x12AC02)) |= 0x1;                                    /* 12B22A: or word ptr [0x12ac02], 1 */
L_12B232:
    M32(XN(0x12AF24)) = R.edx;                                   /* 12B232: mov dword ptr [0x12af24], edx */
    AX = M16(XN(0x12AC04));                                      /* 12B238: mov ax, word ptr [0x12ac04] */
    M16(XN(0x12AF28)) = AX;                                      /* 12B23E: mov word ptr [0x12af28], ax */
    AX = M16(XN(0x12AC06));                                      /* 12B244: mov ax, word ptr [0x12ac06] */
    M16(XN(0x12AF2A)) = AX;                                      /* 12B24A: mov word ptr [0x12af2a], ax */
L_12B250:
    AL = M8(XN(0x12AC00));                                       /* 12B250: mov al, byte ptr [0x12ac00] */
    AH = M8(XN(0x12AC01));                                       /* 12B255: mov ah, byte ptr [0x12ac01] */
    AX &= 0x202;                                                 /* 12B25B: and ax, 0x202 */
    fa = AX; fb = 0x2;                                           /* 12B25F: cmp ax, 2 */
    fr = fa - fb;
    LF(XF_SUB | 1, fa, fb, fr);
    if ((!((u16)fa == (u16)fb))) goto L_12B2D2;                  /* 12B263: jne 0x12b2d2 */
    /* 12B265: nop  */
    /* 12B266: nop  */
    /* 12B267: nop  */
    /* 12B268: nop  */
    R.eax = R.edx;                                               /* 12B269: mov eax, edx */
    R.eax -= M32(XN(0x12AF2C));                                  /* 12B26B: sub eax, dword ptr [0x12af2c] */
    fa = R.eax; fb = R.eax;                                      /* 12B271: or eax, eax */
    fr = fa | fb;
    R.eax = fr;
    if ((!((s32)fr < 0))) goto L_12B277;                         /* 12B273: jns 0x12b277 */
    R.eax = 0 - R.eax;                                           /* 12B275: neg eax */
L_12B277:
    fa = R.eax; fb = 0x8;                                        /* 12B277: cmp eax, 8 */
    fr = fa - fb;
    LF(XF_SUB | 2, fa, fb, fr);
    if ((!((s32)fa < (s32)fb))) goto L_12B2B4;                   /* 12B27A: jge 0x12b2b4 */
    AX = M16(XN(0x12AF30));                                      /* 12B27C: mov ax, word ptr [0x12af30] */
    fa = AX; fb = M16(XN(0x12AC04));                             /* 12B282: sub ax, word ptr [0x12ac04] */
    fr = fa - fb;
    AX = (u16)fr;
    if (!((s16)fr < 0)) goto L_12B28E;                           /* 12B289: jns 0x12b28e */
    AX = 0 - AX;                                                 /* 12B28B: neg ax */
L_12B28E:
    fa = AX; fb = 0x4;                                           /* 12B28E: cmp ax, 4 */
    fr = fa - fb;
    LF(XF_SUB | 1, fa, fb, fr);
    if ((!((s16)fa < (s16)fb))) goto L_12B2B4;                   /* 12B292: jge 0x12b2b4 */
    AX = M16(XN(0x12AF32));                                      /* 12B294: mov ax, word ptr [0x12af32] */
    fa = AX; fb = M16(XN(0x12AC06));                             /* 12B29A: sub ax, word ptr [0x12ac06] */
    fr = fa - fb;
    AX = (u16)fr;
    if (!((s16)fr < 0)) goto L_12B2A6;                           /* 12B2A1: jns 0x12b2a6 */
    AX = 0 - AX;                                                 /* 12B2A3: neg ax */
L_12B2A6:
    fa = AX; fb = 0x4;                                           /* 12B2A6: cmp ax, 4 */
    fr = fa - fb;
    LF(XF_SUB | 1, fa, fb, fr);
    if ((!((s16)fa < (s16)fb))) goto L_12B2B4;                   /* 12B2AA: jge 0x12b2b4 */
    ea = XN(0x12AC02);                                           /* 12B2AC: or word ptr [0x12ac02], 2 */
    fa = M16(ea); fb = 0x2;
    fr = fa | fb;
    M16(ea) = (u16)fr;
    LF(XF_LOGIC | 1, fa, fb, fr);
L_12B2B4:
    M32(XN(0x12AF2C)) = R.edx;                                   /* 12B2B4: mov dword ptr [0x12af2c], edx */
    AX = M16(XN(0x12AC04));                                      /* 12B2BA: mov ax, word ptr [0x12ac04] */
    M16(XN(0x12AF30)) = AX;                                      /* 12B2C0: mov word ptr [0x12af30], ax */
    AX = M16(XN(0x12AC06));                                      /* 12B2C6: mov ax, word ptr [0x12ac06] */
    M16(XN(0x12AF32)) = AX;                                      /* 12B2CC: mov word ptr [0x12af32], ax */
L_12B2D2:
    RET(0);                                                      /* 12B2D2: ret  */
}

/* xn_mouse_cursor_move (strong): (x, y): sets mouse_x/mouse_y, erases the software cursor (12B2EB) and draws it again
   (12B3ED); automap_draw title_menu chargen_draw pass mouse_x, mouse_y */
void xn_0012B2D3(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_12B2D3:
    M16(XN(0x12AC04)) = AX;                                      /* 12B2D3: mov word ptr [0x12ac04], ax */
    M16(XN(0x12AC06)) = DX;                                      /* 12B2D9: mov word ptr [0x12ac06], dx */
    PUSH32(XN(0x12B2E5)); xn_call(XN(0x12B2EB));                 /* 12B2E0: call 0x12b2eb */
    PUSH32(XN(0x12B2EA)); xn_call(XN(0x12B3ED));                 /* 12B2E5: call 0x12b3ed */
    RET(0);                                                      /* 12B2EA: ret  */
}

/* xn_mouse_cursor_erase (strong): if the cursor is drawn (D_00147964 bit 0): clears the bit and puts back the saved 16x16
   background 0x12AC10 at its saved position (144EF0) */
void xn_0012B2EB(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_12B2EB:
    ea = XN(0x147964);                                           /* 12B2EB: test word ptr [0x147964], 1 */
    fa = M16(ea); fb = 0x1;
    fr = fa & fb;
    LF(XF_LOGIC | 1, fa, fb, fr);
    if (((u16)fr == 0)) goto L_12B325;                           /* 12B2F4: je 0x12b325 */
    t = R.esp; PUSH32(R.eax); PUSH32(R.ecx); PUSH32(R.edx); PUSH32(R.ebx); /* 12B2F6: pushal  */
    PUSH32(t); PUSH32(R.ebp); PUSH32(R.esi); PUSH32(R.edi);
    M16(XN(0x147964)) &= 0xFFFE;                                 /* 12B2F7: and word ptr [0x147964], 0xfffe */
    R.eax = M32(XN(0x12AF1C));                                   /* 12B2FF: mov eax, dword ptr [0x12af1c] */
    R.edx = M32(XN(0x12AF20));                                   /* 12B304: mov edx, dword ptr [0x12af20] */
    R.ebx = M16(XN(0x12AF14));                                   /* 12B30A: movzx ebx, word ptr [0x12af14] */
    R.ecx = M16(XN(0x12AF16));                                   /* 12B311: movzx ecx, word ptr [0x12af16] */
    R.esi = XN(0x12AC10);                                        /* 12B318: mov esi, 0x12ac10 */
    fa = R.ebp; fb = R.ebp;                                      /* 12B31D: xor ebp, ebp */
    fr = fa ^ fb;
    R.ebp = fr;
    LF(XF_LOGIC | 2, fa, fb, fr);                                /* 12B31F: call 0x144ef0 */
    PUSH32(XN(0x12B324)); xn_call(XN(0x144EF0));
    R.edi = M32(R.esp); R.esi = M32(R.esp + 4); R.ebp = M32(R.esp + 8); /* 12B324: popal  */
    R.ebx = M32(R.esp + 16); R.edx = M32(R.esp + 20); R.ecx = M32(R.esp + 24);
    R.eax = M32(R.esp + 28); R.esp += 32;
L_12B325:
    RET(0);                                                      /* 12B325: ret  */
}

/* xn_mouse_cursor_clip (strong): cursor rect = mouse pos minus hotspot (0x12AF18 used for x and y), clipped to the screen
   (D_00142930/34): position 0x12AC08/0C, size 0x12AF14/16; copies the visible part of the
   16x16 image 0x12AE10 into 0x12AD10 */
void xn_0012B326(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_12B326:
    t = R.esp; PUSH32(R.eax); PUSH32(R.ecx); PUSH32(R.edx); PUSH32(R.ebx); /* 12B326: pushal  */
    PUSH32(t); PUSH32(R.ebp); PUSH32(R.esi); PUSH32(R.edi);
    R.ebx = 0;                                                   /* 12B327: xor ebx, ebx */
    M16(XN(0x12AF14)) = 0x10;                                    /* 12B329: mov word ptr [0x12af14], 0x10 */
    M16(XN(0x12AF16)) = 0x10;                                    /* 12B332: mov word ptr [0x12af16], 0x10 */
    R.eax = (u32)(s16)M16(XN(0x12AC04));                         /* 12B33B: movsx eax, word ptr [0x12ac04] */
    R.edx = (u32)(s16)M16(XN(0x12AF18));                         /* 12B342: movsx edx, word ptr [0x12af18] */
    fa = R.eax; fb = R.edx;                                      /* 12B349: sub eax, edx */
    fr = fa - fb;
    R.eax = fr;
    if (!((s32)fr < 0)) goto L_12B35A;                           /* 12B34B: jns 0x12b35a */
    R.eax = 0 - R.eax;                                           /* 12B34D: neg eax */
    R.ebx = R.eax;                                               /* 12B34F: mov ebx, eax */
    M16(XN(0x12AF14)) -= AX;                                     /* 12B351: sub word ptr [0x12af14], ax */
    R.eax = 0;                                                   /* 12B358: xor eax, eax */
L_12B35A:
    M32(XN(0x12AC08)) = R.eax;                                   /* 12B35A: mov dword ptr [0x12ac08], eax */
    R.ebp = M32(XN(0x142930));                                   /* 12B35F: mov ebp, dword ptr [0x142930] */
    R.ebp -= 0x10;                                               /* 12B365: sub ebp, 0x10 */
    fa = R.eax; fb = R.ebp;                                      /* 12B368: cmp eax, ebp */
    fr = fa - fb;
    if ((fa < fb)) goto L_12B37A;                                /* 12B36A: jb 0x12b37a */
    R.eax = 0 - R.eax;                                           /* 12B36C: neg eax */
    R.eax += M32(XN(0x142930));                                  /* 12B36E: add eax, dword ptr [0x142930] */
    M16(XN(0x12AF14)) = AX;                                      /* 12B374: mov word ptr [0x12af14], ax */
L_12B37A:
    R.eax = (u32)(s16)M16(XN(0x12AC06));                         /* 12B37A: movsx eax, word ptr [0x12ac06] */
    R.edx = (u32)(s16)M16(XN(0x12AF18));                         /* 12B381: movsx edx, word ptr [0x12af18] */
    fa = R.eax; fb = R.edx;                                      /* 12B388: sub eax, edx */
    fr = fa - fb;
    R.eax = fr;
    if (!((s32)fr < 0)) goto L_12B39C;                           /* 12B38A: jns 0x12b39c */
    R.eax = 0 - R.eax;                                           /* 12B38C: neg eax */
    M16(XN(0x12AF16)) -= AX;                                     /* 12B38E: sub word ptr [0x12af16], ax */
    R.eax <<= 4;                                                 /* 12B395: shl eax, 4 */
    R.ebx += R.eax;                                              /* 12B398: add ebx, eax */
    R.eax = 0;                                                   /* 12B39A: xor eax, eax */
L_12B39C:
    M32(XN(0x12AC0C)) = R.eax;                                   /* 12B39C: mov dword ptr [0x12ac0c], eax */
    R.ebp = M32(XN(0x142934));                                   /* 12B3A1: mov ebp, dword ptr [0x142934] */
    R.ebp -= 0x10;                                               /* 12B3A7: sub ebp, 0x10 */
    fa = R.eax; fb = R.ebp;                                      /* 12B3AA: cmp eax, ebp */
    fr = fa - fb;
    if ((fa < fb)) goto L_12B3BC;                                /* 12B3AC: jb 0x12b3bc */
    R.eax = 0 - R.eax;                                           /* 12B3AE: neg eax */
    R.eax += M32(XN(0x142934));                                  /* 12B3B0: add eax, dword ptr [0x142934] */
    M16(XN(0x12AF16)) = AX;                                      /* 12B3B6: mov word ptr [0x12af16], ax */
L_12B3BC:
    R.eax = (u32)(s16)M16(XN(0x12AF14));                         /* 12B3BC: movsx eax, word ptr [0x12af14] */
    R.ecx = (u32)(s16)M16(XN(0x12AF16));                         /* 12B3C3: movsx ecx, word ptr [0x12af16] */
    fa = R.eax; fb = R.eax;                                      /* 12B3CA: test eax, eax */
    fr = fa & fb;
    LF(XF_LOGIC | 2, fa, fb, fr);
    if (((s32)fr <= 0)) goto L_12B3EB;                           /* 12B3CC: jle 0x12b3eb */
    fa = R.ecx; fb = R.ecx;                                      /* 12B3CE: test ecx, ecx */
    fr = fa & fb;
    LF(XF_LOGIC | 2, fa, fb, fr);
    if (((s32)fr <= 0)) goto L_12B3EB;                           /* 12B3D0: jle 0x12b3eb */
    R.edi = XN(0x12AD10);                                        /* 12B3D2: mov edi, 0x12ad10 */
    R.esi = XN(0x12AE10);                                        /* 12B3D7: mov esi, 0x12ae10 */
    R.esi += R.ebx;                                              /* 12B3DC: add esi, ebx */
L_12B3DE:
    t = R.ecx; PUSH32(t);                                        /* 12B3DE: push ecx */
    R.ecx = R.eax;                                               /* 12B3DF: mov ecx, eax */
    t = R.esi; PUSH32(t);                                        /* 12B3E1: push esi */
    xn_movs(0, 1);                                               /* 12B3E2: rep movsb byte ptr es:[edi], byte ptr [esi] */
    t = M32(R.esp); R.esp += 4; R.esi = t;                       /* 12B3E4: pop esi */
    fa = R.esi; fb = 0x10;                                       /* 12B3E5: add esi, 0x10 */
    fr = fa + fb;
    R.esi = fr;
    LF(XF_ADD | 2, fa, fb, fr);
    t = M32(R.esp); R.esp += 4; R.ecx = t;                       /* 12B3E8: pop ecx */
    if (--R.ecx != 0) goto L_12B3DE;                             /* 12B3E9: loop 0x12b3de */
L_12B3EB:
    R.edi = M32(R.esp); R.esi = M32(R.esp + 4); R.ebp = M32(R.esp + 8); /* 12B3EB: popal  */
    R.ebx = M32(R.esp + 16); R.edx = M32(R.esp + 20); R.ecx = M32(R.esp + 24);
    R.eax = M32(R.esp + 28); R.esp += 32;
    RET(0);                                                      /* 12B3EC: ret  */
}

/* xn_mouse_cursor_draw (strong): if not drawn: sets D_00147964 bit 0, clips (12B326), saves the screen under it into 0x12AC10
   (144E9C) and draws it with transparency (144FC8) */
void xn_0012B3ED(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_12B3ED:
    ea = XN(0x147964);                                           /* 12B3ED: test word ptr [0x147964], 1 */
    fa = M16(ea); fb = 0x1;
    fr = fa & fb;
    LF(XF_LOGIC | 1, fa, fb, fr);
    if ((!((u16)fr == 0))) goto L_12B45A;                        /* 12B3F6: jne 0x12b45a */
    t = R.esp; PUSH32(R.eax); PUSH32(R.ecx); PUSH32(R.edx); PUSH32(R.ebx); /* 12B3F8: pushal  */
    PUSH32(t); PUSH32(R.ebp); PUSH32(R.esi); PUSH32(R.edi);
    ea = XN(0x147964);                                           /* 12B3F9: or word ptr [0x147964], 1 */
    fa = M16(ea); fb = 0x1;
    fr = fa | fb;
    M16(ea) = (u16)fr;
    LF(XF_LOGIC | 1, fa, fb, fr);                                /* 12B401: call 0x12b326 */
    PUSH32(XN(0x12B406)); xn_call(XN(0x12B326));
    R.eax = M32(XN(0x12AC08));                                   /* 12B406: mov eax, dword ptr [0x12ac08] */
    R.edx = M32(XN(0x12AC0C));                                   /* 12B40B: mov edx, dword ptr [0x12ac0c] */
    R.ebx = M16(XN(0x12AF14));                                   /* 12B411: movzx ebx, word ptr [0x12af14] */
    R.ecx = M16(XN(0x12AF16));                                   /* 12B418: movzx ecx, word ptr [0x12af16] */
    R.edi = XN(0x12AC10);                                        /* 12B41F: mov edi, 0x12ac10 */
    fa = R.ebp; fb = R.ebp;                                      /* 12B424: xor ebp, ebp */
    fr = fa ^ fb;
    R.ebp = fr;
    M32(XN(0x12AF1C)) = R.eax;                                   /* 12B426: mov dword ptr [0x12af1c], eax */
    M32(XN(0x12AF20)) = R.edx;                                   /* 12B42B: mov dword ptr [0x12af20], edx */
    LF(XF_LOGIC | 2, fa, fb, fr);                                /* 12B431: call 0x144e9c */
    PUSH32(XN(0x12B436)); xn_call(XN(0x144E9C));
    R.eax = M32(XN(0x12AC08));                                   /* 12B436: mov eax, dword ptr [0x12ac08] */
    R.edx = M32(XN(0x12AC0C));                                   /* 12B43B: mov edx, dword ptr [0x12ac0c] */
    R.ebx = (u32)(s16)M16(XN(0x12AF14));                         /* 12B441: movsx ebx, word ptr [0x12af14] */
    R.ecx = (u32)(s16)M16(XN(0x12AF16));                         /* 12B448: movsx ecx, word ptr [0x12af16] */
    R.esi = XN(0x12AD10);                                        /* 12B44F: mov esi, 0x12ad10 */
    PUSH32(XN(0x12B459)); xn_call(XN(0x144FC8));                 /* 12B454: call 0x144fc8 */
    R.edi = M32(R.esp); R.esi = M32(R.esp + 4); R.ebp = M32(R.esp + 8); /* 12B459: popal  */
    R.ebx = M32(R.esp + 16); R.edx = M32(R.esp + 20); R.ecx = M32(R.esp + 24);
    R.eax = M32(R.esp + 28); R.esp += 32;
L_12B45A:
    RET(0);                                                      /* 12B45A: ret  */
}

/* xn_mouse_set_cursor_image (strong): (image, hot_x, hot_y): copies a 16x16 (256-byte) cursor image into 0x12AE10, hotspot to
   0x12AF18/1A; intrface_init passes the game's arrow and 0,0 */
void xn_0012B45B(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_12B45B:
    t = R.esi; PUSH32(t);                                        /* 12B45B: push esi */
    t = R.edi; PUSH32(t);                                        /* 12B45C: push edi */
    t = R.ecx; PUSH32(t);                                        /* 12B45D: push ecx */
    R.esi = R.eax;                                               /* 12B45E: mov esi, eax */
    R.edi = XN(0x12AE10);                                        /* 12B460: mov edi, 0x12ae10 */
    R.ecx = 0x40;                                                /* 12B465: mov ecx, 0x40 */
    xn_movs(2, 1);                                               /* 12B46A: rep movsd dword ptr es:[edi], dword ptr [esi] */
    M16(XN(0x12AF18)) = DX;                                      /* 12B46C: mov word ptr [0x12af18], dx */
    M16(XN(0x12AF1A)) = BX;                                      /* 12B473: mov word ptr [0x12af1a], bx */
    t = M32(R.esp); R.esp += 4; R.ecx = t;                       /* 12B47A: pop ecx */
    t = M32(R.esp); R.esp += 4; R.edi = t;                       /* 12B47B: pop edi */
    t = M32(R.esp); R.esp += 4; R.esi = t;                       /* 12B47C: pop esi */
    RET(0);                                                      /* 12B47D: ret  */
}

/* xn_mouse_read_motion (confirmed): (short *dx, short *dy): int 33h fn 0Bh (motion counters since last call), each pointer may
   be 0; main passes &mouse_motion_x, &mouse_motion_y */
void xn_0012B47E(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_12B47E:
    t = R.ebx; PUSH32(t);                                        /* 12B47E: push ebx */
    t = R.ecx; PUSH32(t);                                        /* 12B47F: push ecx */
    t = R.edx; PUSH32(t);                                        /* 12B480: push edx */
    t = R.eax; PUSH32(t);                                        /* 12B481: push eax */
    t = (u16)R.ds; PUSH32(t);                                    /* 12B482: push ds */
    R.fs = M16(R.esp); R.esp += 4;                               /* 12B483: pop fs */
    AX = 0xB;                                                    /* 12B485: mov ax, 0xb */
    xn_int(0x33);                                                /* 12B489: int 0x33 */
    t = M32(R.esp); R.esp += 4; R.eax = t;                       /* 12B48B: pop eax */
    fa = R.eax; fb = R.eax;                                      /* 12B48C: test eax, eax */
    fr = fa & fb;
    if ((fr == 0)) goto L_12B493;                                /* 12B48E: je 0x12b493 */
    M16(R.eax) = CX;                                             /* 12B490: mov word ptr [eax], cx */
L_12B493:
    t = M32(R.esp); R.esp += 4; R.eax = t;                       /* 12B493: pop eax */
    fa = R.eax; fb = R.eax;                                      /* 12B494: test eax, eax */
    fr = fa & fb;
    if ((fr == 0)) goto L_12B49B;                                /* 12B496: je 0x12b49b */
    M16(R.eax) = DX;                                             /* 12B498: mov word ptr [eax], dx */
L_12B49B:
    t = M32(R.esp); R.esp += 4; R.ecx = t;                       /* 12B49B: pop ecx */
    t = M32(R.esp); R.esp += 4; R.ebx = t;                       /* 12B49C: pop ebx */
    LF(XF_LOGIC | 2, fa, fb, fr);                                /* 12B49D: ret  */
    RET(0);
}

/* xn_mouse_set_position (confirmed): (x, y): int 33h fn 4 set cursor position; note_find spellmaker_settings_update
   keys_world_actions */
void xn_0012B49E(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_12B49E:
    t = R.esp; PUSH32(R.eax); PUSH32(R.ecx); PUSH32(R.edx); PUSH32(R.ebx); /* 12B49E: pushal  */
    PUSH32(t); PUSH32(R.ebp); PUSH32(R.esi); PUSH32(R.edi);
    R.ecx = R.eax;                                               /* 12B49F: mov ecx, eax */
    R.eax = 0x4;                                                 /* 12B4A1: mov eax, 4 */
    t = (u16)R.ds; PUSH32(t);                                    /* 12B4A6: push ds */
    R.fs = M16(R.esp); R.esp += 4;                               /* 12B4A7: pop fs */
    xn_int(0x33);                                                /* 12B4A9: int 0x33 */
    R.edi = M32(R.esp); R.esi = M32(R.esp + 4); R.ebp = M32(R.esp + 8); /* 12B4AB: popal  */
    R.ebx = M32(R.esp + 16); R.edx = M32(R.esp + 20); R.ecx = M32(R.esp + 24);
    R.eax = M32(R.esp + 28); R.esp += 32;
    RET(0);                                                      /* 12B4AC: ret  */
}
