/* xn_142700.c: XnGine module xn_142700 (FALL.EXE object 2, 0x142700-0x142900) as literal C.
   Generated by tools/xn_c.py from the code in src/xngine/xn_142700.asm; do not edit (a hand-written
   replacement for a function goes in src/xngine_c/override/xn_<va>.c). Each function is the
   asm one instruction at a time, on the register file R (see runtime.h). */
#include "runtime.h"


/* xn_kbd_install (confirmed): init_video calls it: once (flag D_00142306) saves the int 9 vector (_dos_getvect) and
   installs 0x142840 (0xA12A6 setvect 9); locks its code and data (0x149F0C); keymap pointer
   D_00142393 = D_00142397 */
void xn_00142700(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_142700:
    t = R.esp; PUSH32(R.eax); PUSH32(R.ecx); PUSH32(R.edx); PUSH32(R.ebx); /* 142700: pushal  */
    PUSH32(t); PUSH32(R.ebp); PUSH32(R.esi); PUSH32(R.edi);
    ea = XN(0x142306);                                           /* 142701: cmp byte ptr [0x142306], 1 */
    fa = M8(ea); fb = 0x1;
    fr = fa - fb;
    LF(XF_SUB | 0, fa, fb, fr);
    if (((u8)fa == (u8)fb)) goto L_142761;                       /* 142708: je 0x142761 */
    M8(XN(0x142306)) = 0x1;                                      /* 14270A: mov byte ptr [0x142306], 1 */
    R.eax = 0x9;                                                 /* 142711: mov eax, 9 */
    LF(XF_SUB | 0, fa, fb, fr);                                  /* 142716: call 0xa1272 */
    PUSH32(XN(0x14271B)); xn_call(XN(0xA1272));
    M32(XN(0x142300)) = R.eax;                                   /* 14271B: mov dword ptr [0x142300], eax */
    M16(XN(0x142304)) = DX;                                      /* 142720: mov word ptr [0x142304], dx */
    R.eax = 0x9;                                                 /* 142727: mov eax, 9 */
    R.ebx = XN(0x142840);                                        /* 14272C: mov ebx, 0x142840 */
    CX = (u16)R.cs;                                              /* 142731: mov cx, cs */
    PUSH32(XN(0x142739)); xn_call(XN(0xA12A6));                  /* 142734: call 0xa12a6 */
    R.eax = XN(0x142700);                                        /* 142739: mov eax, 0x142700 */
    R.edx = 0x1EE;                                               /* 14273E: mov edx, 0x1ee */
    PUSH32(XN(0x142748)); xn_call(XN(0x149F0C));                 /* 142743: call 0x149f0c */
    R.eax = XN(0x142300);                                        /* 142748: mov eax, 0x142300 */
    R.edx = 0x397;                                               /* 14274D: mov edx, 0x397 */
    PUSH32(XN(0x142757)); xn_call(XN(0x149F0C));                 /* 142752: call 0x149f0c */
    M32(XN(0x142393)) = XN(0x142397);                            /* 142757: mov dword ptr [0x142393], 0x142397 */
L_142761:
    R.edi = M32(R.esp); R.esi = M32(R.esp + 4); R.ebp = M32(R.esp + 8); /* 142761: popal  */
    R.ebx = M32(R.esp + 16); R.edx = M32(R.esp + 20); R.ecx = M32(R.esp + 24);
    R.eax = M32(R.esp + 28); R.esp += 32;
    RET(0);                                                      /* 142762: ret  */
}

/* xn_kbd_remove (confirmed): shutdown_video and every fatal-error path call it: if installed restores the saved int 9
   vector D_00142300:D_00142304 and clears D_00142306 */
void xn_00142764(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_142764:
    t = R.esp; PUSH32(R.eax); PUSH32(R.ecx); PUSH32(R.edx); PUSH32(R.ebx); /* 142764: pushal  */
    PUSH32(t); PUSH32(R.ebp); PUSH32(R.esi); PUSH32(R.edi);
    ea = XN(0x142306);                                           /* 142765: cmp byte ptr [0x142306], 0 */
    fa = M8(ea); fb = 0x0;
    fr = fa - fb;
    LF(XF_SUB | 0, fa, fb, fr);
    if (((u8)fa == (u8)fb)) goto L_14278C;                       /* 14276C: je 0x14278c */
    M8(XN(0x142306)) = 0x0;                                      /* 14276E: mov byte ptr [0x142306], 0 */
    R.eax = 0x9;                                                 /* 142775: mov eax, 9 */
    R.ebx = M32(XN(0x142300));                                   /* 14277A: mov ebx, dword ptr [0x142300] */
    R.ecx = M16(XN(0x142304));                                   /* 142780: movzx ecx, word ptr [0x142304] */
    LF(XF_SUB | 0, fa, fb, fr);                                  /* 142787: call 0xa12a6 */
    PUSH32(XN(0x14278C)); xn_call(XN(0xA12A6));
L_14278C:
    R.edi = M32(R.esp); R.esi = M32(R.esp + 4); R.ebp = M32(R.esp + 8); /* 14278C: popal  */
    R.ebx = M32(R.esp + 16); R.edx = M32(R.esp + 20); R.ecx = M32(R.esp + 24);
    R.eax = M32(R.esp + 28); R.esp += 32;
    RET(0);                                                      /* 14278D: ret  */
}

/* xn_kbd_flush (confirmed): zeroes key_down[128] and the last scan code D_00142307; called before text input and prompts
   (inpstr_begin_text bank_input_amount saveload_confirm tavern_rent_room ...) */
void xn_00142790(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_142790:
    t = R.esp; PUSH32(R.eax); PUSH32(R.ecx); PUSH32(R.edx); PUSH32(R.ebx); /* 142790: pushal  */
    PUSH32(t); PUSH32(R.ebp); PUSH32(R.esi); PUSH32(R.edi);
    R.edi = XN(0x142308);                                        /* 142791: mov edi, 0x142308 */
    R.ecx = 0x20;                                                /* 142796: mov ecx, 0x20 */
    fa = R.eax; fb = R.eax;                                      /* 14279B: xor eax, eax */
    fr = fa ^ fb;
    R.eax = fr;
    xn_stos(2, 1);                                               /* 14279D: rep stosd dword ptr es:[edi], eax */
    M8(XN(0x142307)) = 0x0;                                      /* 14279F: mov byte ptr [0x142307], 0 */
    R.edi = M32(R.esp); R.esi = M32(R.esp + 4); R.ebp = M32(R.esp + 8); /* 1427A6: popal  */
    R.ebx = M32(R.esp + 16); R.edx = M32(R.esp + 20); R.ecx = M32(R.esp + 24);
    R.eax = M32(R.esp + 28); R.esp += 32;
    LF(XF_LOGIC | 2, fa, fb, fr);                                /* 1427A7: ret  */
    RET(0);
}

/* xn_kbd_read_key (strong): inpstr_read_key wait_key_from_list call it: returns AH=last scan code AL=ASCII from the
   keymap (shifted half if D_00142388 bit 0/1) and clears it, 0 if none; without the handler
   uses BIOS int 16h fn 1/0 */
void xn_001427A8(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_1427A8:
    ea = XN(0x142306);                                           /* 1427A8: cmp byte ptr [0x142306], 0 */
    fa = M8(ea); fb = 0x0;
    fr = fa - fb;
    if (((u8)fa == (u8)fb)) goto L_1427F8;                       /* 1427AF: je 0x1427f8 */
    t = R.ebx; PUSH32(t);                                        /* 1427B1: push ebx */
    R.eax = M8(XN(0x142307));                                    /* 1427B2: movzx eax, byte ptr [0x142307] */
    fa = R.eax; fb = R.eax;                                      /* 1427B9: test eax, eax */
    fr = fa & fb;
    LF(XF_LOGIC | 2, fa, fb, fr);
    if ((fr == 0)) goto L_1427EF;                                /* 1427BB: je 0x1427ef */
    R.eax -= 1;                                                  /* 1427BD: dec eax */
    R.eax += M32(XN(0x142393));                                  /* 1427BE: add eax, dword ptr [0x142393] */
    ea = XN(0x142388);                                           /* 1427C4: test dword ptr [0x142388], 1 */
    fa = M32(ea); fb = 0x1;
    fr = fa & fb;
    BL = (!(fr == 0));                                           /* 1427CE: setne bl */
    ea = XN(0x142388);                                           /* 1427D1: test dword ptr [0x142388], 2 */
    fa = M32(ea); fb = 0x2;
    fr = fa & fb;
    BH = (!(fr == 0));                                           /* 1427DB: setne bh */
    BL |= BH;                                                    /* 1427DE: or bl, bh */
    R.ebx &= 0x1;                                                /* 1427E0: and ebx, 1 */
    fa = R.ebx << 6; fr = fa << 1;                               /* 1427E3: shl ebx, 7 */
    R.ebx = fr;
    LF(XF_SHL | 2, fa, 0, fr);
    AL = M8(R.eax + R.ebx);                                      /* 1427E6: mov al, byte ptr [eax + ebx] */
    AH = M8(XN(0x142307));                                       /* 1427E9: mov ah, byte ptr [0x142307] */
L_1427EF:
    M8(XN(0x142307)) = 0x0;                                      /* 1427EF: mov byte ptr [0x142307], 0 */
    t = M32(R.esp); R.esp += 4; R.ebx = t;                       /* 1427F6: pop ebx */
    RET(0);                                                      /* 1427F7: ret  */
L_1427F8:
    AH = 0x1;                                                    /* 1427F8: mov ah, 1 */
    LF(XF_SUB | 0, fa, fb, fr);                                  /* 1427FA: int 0x16 */
    xn_int(0x16);
    if (xn_cond(4)) goto L_142803;                               /* 1427FC: je 0x142803 */
    fa = R.eax; fb = R.eax;                                      /* 1427FE: xor eax, eax */
    fr = fa ^ fb;
    R.eax = fr;
    LF(XF_LOGIC | 2, fa, fb, fr);                                /* 142800: int 0x16 */
    xn_int(0x16);
    RET(0);                                                      /* 142802: ret  */
L_142803:
    fa = R.eax; fb = R.eax;                                      /* 142803: xor eax, eax */
    fr = fa ^ fb;
    R.eax = fr;
    LF(XF_LOGIC | 2, fa, fb, fr);                                /* 142805: ret  */
    RET(0);
}

/* xn_kbd_wait_key (candidate): unreferenced: waits until D_00142307 is non-zero then 0x1427A8; without the handler BIOS int
   16h fn 0 */
void xn_00142808(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_142808:
    ea = XN(0x142306);                                           /* 142808: cmp byte ptr [0x142306], 0 */
    fa = M8(ea); fb = 0x0;
    fr = fa - fb;
    if (((u8)fa == (u8)fb)) goto L_142820;                       /* 14280F: je 0x142820 */
L_142811:
    ea = XN(0x142307);                                           /* 142811: cmp byte ptr [0x142307], 0 */
    fa = M8(ea); fb = 0x0;
    fr = fa - fb;
    if (((u8)fa == (u8)fb)) goto L_142811;                       /* 142818: je 0x142811 */
    LF(XF_SUB | 0, fa, fb, fr);                                  /* 14281A: call 0x1427a8 */
    PUSH32(XN(0x14281F)); xn_call(XN(0x1427A8));
    RET(0);                                                      /* 14281F: ret  */
L_142820:
    fa = R.eax; fb = R.eax;                                      /* 142820: xor eax, eax */
    fr = fa ^ fb;
    R.eax = fr;
    LF(XF_LOGIC | 2, fa, fb, fr);                                /* 142822: int 0x16 */
    xn_int(0x16);
    RET(0);                                                      /* 142824: ret  */
}

/* xn_kbd_int9_handler (confirmed): int 9 handler installed by 0x142700 (439 episodes): pushad, saves segment registers, loads
   DS (selector fixup); docs/xngine.md Input */
void xn_00142840(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_142840:
    t = R.esp; PUSH32(R.eax); PUSH32(R.ecx); PUSH32(R.edx); PUSH32(R.ebx); /* 142840: pushal  */
    PUSH32(t); PUSH32(R.ebp); PUSH32(R.esi); PUSH32(R.edi);
    t = (u16)R.ds; PUSH32(t);                                    /* 142841: push ds */
    t = (u16)R.es; PUSH32(t);                                    /* 142842: push es */
    t = (u16)R.gs; PUSH32(t);                                    /* 142843: push gs */
    t = (u16)R.fs; PUSH32(t);                                    /* 142845: push fs */
    AX = M16(XN(0x142849));                                      /* 142847: mov ax, 0 */
    R.ds = (u16)R.eax;                                           /* 14284B: mov ds, eax */
    GOTO_ASM(XN(0x14284D));
}

/* xn_kbd_int9_read_scancode (confirmed): int 9 handler block: in al,60h; acknowledges via port 61h bit 7; break codes (bit 7) go to
   0x1428A1 */
void xn_0014284D(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_14284D:
    R.ebx = 0;                                                   /* 14284D: xor ebx, ebx */
    AL = xn_in8(0x60);                                           /* 14284F: in al, 0x60 */
    BL = AL;                                                     /* 142851: mov bl, al */
    AL = xn_in8(0x61);                                           /* 142853: in al, 0x61 */
    AL |= 0x80;                                                  /* 142855: or al, 0x80 */
    xn_out8(0x61, AL);                                           /* 142857: out 0x61, al */
    AL &= 0x7F;                                                  /* 142859: and al, 0x7f */
    xn_out8(0x61, AL);                                           /* 14285B: out 0x61, al */
    fa = BL; fb = 0x80;                                          /* 14285D: test bl, 0x80 */
    fr = fa & fb;
    LF(XF_LOGIC | 0, fa, fb, fr);
    if ((!((u8)fr == 0))) GOTO_ASM(XN(0x1428A1));                /* 142860: jne 0x1428a1 */
    GOTO_ASM(XN(0x142862));
}

/* xn_kbd_int9_make_ctrl (confirmed): int 9 handler block: make code 1Dh (Ctrl) sets D_00142388 bit 3 (8) */
void xn_00142862(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_142862:
    fa = BL; fb = 0x1D;                                          /* 142862: cmp bl, 0x1d */
    fr = fa - fb;
    LF(XF_SUB | 0, fa, fb, fr);
    if ((!((u8)fa == (u8)fb))) GOTO_ASM(XN(0x14286E));           /* 142865: jne 0x14286e */
    ea = XN(0x142388);                                           /* 142867: or dword ptr [0x142388], 8 */
    fa = M32(ea); fb = 0x8;
    fr = fa | fb;
    M32(ea) = fr;
    LF(XF_LOGIC | 2, fa, fb, fr);
    GOTO_ASM(XN(0x14286E));
}

/* xn_kbd_int9_make_lshift (confirmed): int 9 handler block: make code 2Ah (left Shift) sets D_00142388 bit 0 */
void xn_0014286E(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_14286E:
    fa = BL; fb = 0x2A;                                          /* 14286E: cmp bl, 0x2a */
    fr = fa - fb;
    LF(XF_SUB | 0, fa, fb, fr);
    if ((!((u8)fa == (u8)fb))) GOTO_ASM(XN(0x14287A));           /* 142871: jne 0x14287a */
    ea = XN(0x142388);                                           /* 142873: or dword ptr [0x142388], 1 */
    fa = M32(ea); fb = 0x1;
    fr = fa | fb;
    M32(ea) = fr;
    LF(XF_LOGIC | 2, fa, fb, fr);
    GOTO_ASM(XN(0x14287A));
}

/* xn_kbd_int9_make_rshift (confirmed): int 9 handler block: make code 36h (right Shift) sets D_00142388 bit 1 */
void xn_0014287A(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_14287A:
    fa = BL; fb = 0x36;                                          /* 14287A: cmp bl, 0x36 */
    fr = fa - fb;
    LF(XF_SUB | 0, fa, fb, fr);
    if ((!((u8)fa == (u8)fb))) GOTO_ASM(XN(0x142886));           /* 14287D: jne 0x142886 */
    ea = XN(0x142388);                                           /* 14287F: or dword ptr [0x142388], 2 */
    fa = M32(ea); fb = 0x2;
    fr = fa | fb;
    M32(ea) = fr;
    LF(XF_LOGIC | 2, fa, fb, fr);
    GOTO_ASM(XN(0x142886));
}

/* xn_kbd_int9_make_alt (confirmed): int 9 handler block: make code 38h (Alt) sets D_00142388 bit 2 */
void xn_00142886(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_142886:
    fa = BL; fb = 0x38;                                          /* 142886: cmp bl, 0x38 */
    fr = fa - fb;
    LF(XF_SUB | 0, fa, fb, fr);
    if ((!((u8)fa == (u8)fb))) GOTO_ASM(XN(0x142892));           /* 142889: jne 0x142892 */
    ea = XN(0x142388);                                           /* 14288B: or dword ptr [0x142388], 4 */
    fa = M32(ea); fb = 0x4;
    fr = fa | fb;
    M32(ea) = fr;
    LF(XF_LOGIC | 2, fa, fb, fr);
    GOTO_ASM(XN(0x142892));
}

/* xn_kbd_int9_key_down (confirmed): int 9 handler block: D_00142307 = scan code and key_down[scan] = 1, then the EOI tail
   0x1428E2 */
void xn_00142892(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_142892:
    M8(XN(0x142307)) = BL;                                       /* 142892: mov byte ptr [0x142307], bl */
    M8(R.ebx + XN(0x142308)) = 0x1;                              /* 142898: mov byte ptr [ebx + 0x142308], 1 */
    GOTO_ASM(XN(0x1428E2));                                      /* 14289F: jmp 0x1428e2 */
}

/* xn_kbd_int9_break_ctrl (confirmed): int 9 handler block: break code: scan &= 7Fh; 1Dh (Ctrl) clears D_00142388 bit 3 */
void xn_001428A1(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_1428A1:
    BL &= 0x7F;                                                  /* 1428A1: and bl, 0x7f */
    fa = BL; fb = 0x1D;                                          /* 1428A4: cmp bl, 0x1d */
    fr = fa - fb;
    LF(XF_SUB | 0, fa, fb, fr);
    if ((!((u8)fa == (u8)fb))) GOTO_ASM(XN(0x1428B0));           /* 1428A7: jne 0x1428b0 */
    ea = XN(0x142388);                                           /* 1428A9: and dword ptr [0x142388], 0xfffffff7 */
    fa = M32(ea); fb = 0xFFFFFFF7;
    fr = fa & fb;
    M32(ea) = fr;
    LF(XF_LOGIC | 2, fa, fb, fr);
    GOTO_ASM(XN(0x1428B0));
}

/* xn_kbd_int9_break_lshift (confirmed): int 9 handler block: break of 2Ah clears D_00142388 bit 0 */
void xn_001428B0(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_1428B0:
    fa = BL; fb = 0x2A;                                          /* 1428B0: cmp bl, 0x2a */
    fr = fa - fb;
    LF(XF_SUB | 0, fa, fb, fr);
    if ((!((u8)fa == (u8)fb))) GOTO_ASM(XN(0x1428BC));           /* 1428B3: jne 0x1428bc */
    ea = XN(0x142388);                                           /* 1428B5: and dword ptr [0x142388], 0xfffffffe */
    fa = M32(ea); fb = 0xFFFFFFFE;
    fr = fa & fb;
    M32(ea) = fr;
    LF(XF_LOGIC | 2, fa, fb, fr);
    GOTO_ASM(XN(0x1428BC));
}

/* xn_kbd_int9_break_rshift (confirmed): int 9 handler block: break of 36h clears D_00142388 bit 1 */
void xn_001428BC(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_1428BC:
    fa = BL; fb = 0x36;                                          /* 1428BC: cmp bl, 0x36 */
    fr = fa - fb;
    LF(XF_SUB | 0, fa, fb, fr);
    if ((!((u8)fa == (u8)fb))) GOTO_ASM(XN(0x1428C8));           /* 1428BF: jne 0x1428c8 */
    ea = XN(0x142388);                                           /* 1428C1: and dword ptr [0x142388], 0xfffffffd */
    fa = M32(ea); fb = 0xFFFFFFFD;
    fr = fa & fb;
    M32(ea) = fr;
    LF(XF_LOGIC | 2, fa, fb, fr);
    GOTO_ASM(XN(0x1428C8));
}

/* xn_kbd_int9_break_alt (confirmed): int 9 handler block: break of 38h clears D_00142388 bit 2 */
void xn_001428C8(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_1428C8:
    fa = BL; fb = 0x38;                                          /* 1428C8: cmp bl, 0x38 */
    fr = fa - fb;
    LF(XF_SUB | 0, fa, fb, fr);
    if ((!((u8)fa == (u8)fb))) GOTO_ASM(XN(0x1428D4));           /* 1428CB: jne 0x1428d4 */
    ea = XN(0x142388);                                           /* 1428CD: and dword ptr [0x142388], 0xfffffffb */
    fa = M32(ea); fb = 0xFFFFFFFB;
    fr = fa & fb;
    M32(ea) = fr;
    LF(XF_LOGIC | 2, fa, fb, fr);
    GOTO_ASM(XN(0x1428D4));
}

/* xn_kbd_int9_key_up (confirmed): int 9 handler block: D_00142307 = 0 and key_down[scan] = 0 */
void xn_001428D4(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_1428D4:
    M8(XN(0x142307)) = 0x0;                                      /* 1428D4: mov byte ptr [0x142307], 0 */
    M8(R.ebx + XN(0x142308)) = 0x0;                              /* 1428DB: mov byte ptr [ebx + 0x142308], 0 */
    GOTO_ASM(XN(0x1428E2));
}

/* xn_kbd_int9_eoi (confirmed): int 9 handler block: out 20h,20h (PIC end of interrupt), pops fs gs es */
void xn_001428E2(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_1428E2:
    AL = 0x20;                                                   /* 1428E2: mov al, 0x20 */
    xn_out8(0x20, AL);                                           /* 1428E4: out 0x20, al */
    R.fs = M16(R.esp); R.esp += 4;                               /* 1428E6: pop fs */
    R.gs = M16(R.esp); R.esp += 4;                               /* 1428E8: pop gs */
    R.es = M16(R.esp); R.esp += 4;                               /* 1428EA: pop es */
    GOTO_ASM(XN(0x1428EB));
}

/* xn_kbd_int9_pop_ds (confirmed): int 9 handler block: pop ds */
void xn_001428EB(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_1428EB:
    R.ds = M16(R.esp); R.esp += 4;                               /* 1428EB: pop ds */
    GOTO_ASM(XN(0x1428EC));
}

/* xn_kbd_int9_iret (confirmed): int 9 handler block: popad; iretd */
void xn_001428EC(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_1428EC:
    R.edi = M32(R.esp); R.esi = M32(R.esp + 4); R.ebp = M32(R.esp + 8); /* 1428EC: popal  */
    R.ebx = M32(R.esp + 16); R.edx = M32(R.esp + 20); R.ecx = M32(R.esp + 24);
    R.eax = M32(R.esp + 28); R.esp += 32;
    xn_ret = M32(R.esp); xn_retcs = M16(R.esp + 4); xn_popf(M32(R.esp + 8)); /* 1428ED: iretd  */
    R.esp += 12; xn_far = 1; return XN_DONE;
}
