/* xn_155800.c: XnGine module xn_155800 (FALL.EXE object 2, 0x155800-0x155B00) as literal C.
   Generated by tools/xn_c.py from the code in src/xngine/xn_155800.asm; do not edit (a hand-written
   replacement for a function goes in src/xngine_c/override/xn_<va>.c). Each function is the
   asm one instruction at a time, on the register file R (see runtime.h). */
#include "runtime.h"


/* xn_span_solid (strong): D_0012A01D[0] (unlit): fills ebp pixels at edi+1 with the replicated colour dword [poly+40h]
   (rep stosb/stosd); also the steady-state routine 0x155820 installs in [poly+3Ch]. Called per
   span by the frame loop 0x12A870 */
void xn_00155800(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_155800:
    R.edi += 1;                                                  /* 155800: inc edi */
    R.ecx = R.ebp;                                               /* 155801: mov ecx, ebp */
    R.eax = M32(R.eax + 0x40);                                   /* 155803: mov eax, dword ptr [eax + 0x40] */
    R.ecx &= 0x3;                                                /* 155806: and ecx, 3 */
    xn_stos(0, 1);                                               /* 155809: rep stosb byte ptr es:[edi], al */
    R.ecx = R.ebp;                                               /* 15580B: mov ecx, ebp */
    fa = R.ecx >> 1; fr = fa >> 1;                               /* 15580D: shr ecx, 2 */
    R.ecx = fr;
    xn_stos(2, 1);                                               /* 155810: rep stosd dword ptr es:[edi], eax */
    LF(XF_SAR | 2, fa, 0, fr);                                   /* 155812: ret  */
    RET(0);
}

/* xn_span_solid_shaded_setup (strong): D_0012A01D[1] (constant shade): first span of a polygon: colour = shade row
   [poly+14h][colour byte], replicated via D_00149980 into [poly+40h]; sets [poly+3Ch]=0x155800
   and fills */
void xn_00155820(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_155820:
    R.ebx = M32(R.eax + 0x14);                                   /* 155820: mov ebx, dword ptr [eax + 0x14] */
    M32(R.eax + 0x3C) = XN(0x155800);                            /* 155823: mov dword ptr [eax + 0x3c], 0x155800 */
    BL = M8(R.eax + 0x40);                                       /* 15582A: mov bl, byte ptr [eax + 0x40] */
    R.ecx = R.ebp;                                               /* 15582D: mov ecx, ebp */
    R.ebx = M8(R.ebx);                                           /* 15582F: movzx ebx, byte ptr [ebx] */
    R.edi += 1;                                                  /* 155832: inc edi */
    R.ebx = M32(R.ebx * 4 + XN(0x149980));                       /* 155833: mov ebx, dword ptr [ebx*4 + 0x149980] */
    M32(R.eax + 0x40) = R.ebx;                                   /* 15583A: mov dword ptr [eax + 0x40], ebx */
    R.eax = R.ebx;                                               /* 15583D: mov eax, ebx */
    R.ecx &= 0x3;                                                /* 15583F: and ecx, 3 */
    xn_stos(0, 1);                                               /* 155842: rep stosb byte ptr es:[edi], al */
    R.ecx = R.ebp;                                               /* 155844: mov ecx, ebp */
    fa = R.ecx >> 1; fr = fa >> 1;                               /* 155846: shr ecx, 2 */
    R.ecx = fr;
    xn_stos(2, 1);                                               /* 155849: rep stosd dword ptr es:[edi], eax */
    LF(XF_SAR | 2, fa, 0, fr);                                   /* 15584B: ret  */
    RET(0);
}

/* xn_span_solid_lit_tail (strong): 16 unrolled 9-byte steps (ah=ch; dl=[eax]; store) of shade-table lookups for one colour;
   0x155920 enters it with a planted ret (offsets D_00155860) for the last <16 pixels */
void xn_00155880(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_155880:
    if (M8(XN(0x155880)) == 0xC3) { RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 155880: mov ah, ch */
    if (M8(XN(0x155882)) == 0xC3) { RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 155882: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x155884)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 155884: mov dl, byte ptr [eax] */
    if (M8(XN(0x155886)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0x1) = DL;                                        /* 155886: mov byte ptr [edi + 1], dl */
    if (M8(XN(0x155889)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 155889: mov ah, ch */
    if (M8(XN(0x15588B)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 15588B: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x15588D)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 15588D: mov dl, byte ptr [eax] */
    if (M8(XN(0x15588F)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0x2) = DL;                                        /* 15588F: mov byte ptr [edi + 2], dl */
    if (M8(XN(0x155892)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 155892: mov ah, ch */
    if (M8(XN(0x155894)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 155894: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x155896)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 155896: mov dl, byte ptr [eax] */
    if (M8(XN(0x155898)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0x3) = DL;                                        /* 155898: mov byte ptr [edi + 3], dl */
    if (M8(XN(0x15589B)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 15589B: mov ah, ch */
    if (M8(XN(0x15589D)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 15589D: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x15589F)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 15589F: mov dl, byte ptr [eax] */
    if (M8(XN(0x1558A1)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0x4) = DL;                                        /* 1558A1: mov byte ptr [edi + 4], dl */
    if (M8(XN(0x1558A4)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 1558A4: mov ah, ch */
    if (M8(XN(0x1558A6)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 1558A6: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x1558A8)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 1558A8: mov dl, byte ptr [eax] */
    if (M8(XN(0x1558AA)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0x5) = DL;                                        /* 1558AA: mov byte ptr [edi + 5], dl */
    if (M8(XN(0x1558AD)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 1558AD: mov ah, ch */
    if (M8(XN(0x1558AF)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 1558AF: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x1558B1)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 1558B1: mov dl, byte ptr [eax] */
    if (M8(XN(0x1558B3)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0x6) = DL;                                        /* 1558B3: mov byte ptr [edi + 6], dl */
    if (M8(XN(0x1558B6)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 1558B6: mov ah, ch */
    if (M8(XN(0x1558B8)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 1558B8: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x1558BA)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 1558BA: mov dl, byte ptr [eax] */
    if (M8(XN(0x1558BC)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0x7) = DL;                                        /* 1558BC: mov byte ptr [edi + 7], dl */
    if (M8(XN(0x1558BF)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 1558BF: mov ah, ch */
    if (M8(XN(0x1558C1)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 1558C1: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x1558C3)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 1558C3: mov dl, byte ptr [eax] */
    if (M8(XN(0x1558C5)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0x8) = DL;                                        /* 1558C5: mov byte ptr [edi + 8], dl */
    if (M8(XN(0x1558C8)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 1558C8: mov ah, ch */
    if (M8(XN(0x1558CA)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 1558CA: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x1558CC)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 1558CC: mov dl, byte ptr [eax] */
    if (M8(XN(0x1558CE)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0x9) = DL;                                        /* 1558CE: mov byte ptr [edi + 9], dl */
    if (M8(XN(0x1558D1)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 1558D1: mov ah, ch */
    if (M8(XN(0x1558D3)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 1558D3: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x1558D5)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 1558D5: mov dl, byte ptr [eax] */
    if (M8(XN(0x1558D7)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0xA) = DL;                                        /* 1558D7: mov byte ptr [edi + 0xa], dl */
    if (M8(XN(0x1558DA)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 1558DA: mov ah, ch */
    if (M8(XN(0x1558DC)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 1558DC: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x1558DE)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 1558DE: mov dl, byte ptr [eax] */
    if (M8(XN(0x1558E0)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0xB) = DL;                                        /* 1558E0: mov byte ptr [edi + 0xb], dl */
    if (M8(XN(0x1558E3)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 1558E3: mov ah, ch */
    if (M8(XN(0x1558E5)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 1558E5: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x1558E7)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 1558E7: mov dl, byte ptr [eax] */
    if (M8(XN(0x1558E9)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0xC) = DL;                                        /* 1558E9: mov byte ptr [edi + 0xc], dl */
    if (M8(XN(0x1558EC)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 1558EC: mov ah, ch */
    if (M8(XN(0x1558EE)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 1558EE: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x1558F0)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 1558F0: mov dl, byte ptr [eax] */
    if (M8(XN(0x1558F2)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0xD) = DL;                                        /* 1558F2: mov byte ptr [edi + 0xd], dl */
    if (M8(XN(0x1558F5)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 1558F5: mov ah, ch */
    if (M8(XN(0x1558F7)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 1558F7: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x1558F9)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 1558F9: mov dl, byte ptr [eax] */
    if (M8(XN(0x1558FB)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0xE) = DL;                                        /* 1558FB: mov byte ptr [edi + 0xe], dl */
    if (M8(XN(0x1558FE)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 1558FE: mov ah, ch */
    if (M8(XN(0x155900)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 155900: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x155902)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 155902: mov dl, byte ptr [eax] */
    if (M8(XN(0x155904)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0xF) = DL;                                        /* 155904: mov byte ptr [edi + 0xf], dl */
    if (M8(XN(0x155907)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    AH = CH;                                                     /* 155907: mov ah, ch */
    if (M8(XN(0x155909)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    fa = R.ecx; fb = R.ebp;                                      /* 155909: add ecx, ebp */
    fr = fa + fb;
    R.ecx = fr;
    if (M8(XN(0x15590B)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    DL = M8(R.eax);                                              /* 15590B: mov dl, byte ptr [eax] */
    if (M8(XN(0x15590D)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    M8(R.edi + 0x10) = DL;                                       /* 15590D: mov byte ptr [edi + 0x10], dl */
    if (M8(XN(0x155910)) == 0xC3) { LF(XF_ADD | 2, fa, fb, fr); RET(0); }   /* a planted ret */
    LF(XF_ADD | 2, fa, fb, fr);                                  /* 155910: ret  */
    RET(0);
}

/* xn_span_solid_lit (strong): D_0012A01D[2] (per-pixel light): solid colour shaded through the light shader [poly+14h],
   called every 16 px with the view ray (x from D_00120AC0, y patched per row by 0x12A870) and
   z from 1/z; 2 px per step; tail via 0x155880 */
void xn_00155920(void)
{
    u32 fa, fb, fr, fc, ea, t, t2;

L_155920:
    R.edx = M32(R.eax + 0x58);                                   /* 155920: mov edx, dword ptr [eax + 0x58] */
    R.ecx = M32(R.esi + 0x8);                                    /* 155923: mov ecx, dword ptr [esi + 8] */
    R.edx += R.edx;                                              /* 155926: add edx, edx */
    R.esi = R.eax;                                               /* 155928: mov esi, eax */
    M32(XN(0x155984)) = R.edx;                                   /* 15592A: mov dword ptr [0x155984], edx */
    t = R.ecx; PUSH32(t);                                        /* 155930: push ecx */
    fa = R.eax; fb = R.eax;                                      /* 155931: xor eax, eax */
    fr = fa ^ fb;
    R.eax = fr;
    R.edx = 0x4000;                                              /* 155933: mov edx, 0x4000 */
    LF(XF_LOGIC | 2, fa, fb, fr);                                /* 155938: div ecx */
    xn_div(R.ecx, 2, 0x155938);
    R.ecx = R.eax;                                               /* 15593A: mov ecx, eax */
    R.ebx = M32(R.ebx * 4 + XN(0x120AC0));                       /* 15593C: mov ebx, dword ptr [ebx*4 + 0x120ac0] */
    R.eax = M32(XN(0x155944));                                   /* 155943: mov eax, 0x186a0 */
    t = R.ebx; PUSH32(t);                                        /* 155948: push ebx */
    t = R.ebp; PUSH32(t);                                        /* 155949: push ebp */
    R.ebp = R.ebx;                                               /* 15594A: mov ebp, ebx */
    LF(XF_LOGIC | 2, fa, fb, fr);                                /* 15594C: call dword ptr [esi + 0x14] */
    t = M32(R.esi + 0x14);
    PUSH32(XN(0x15594F)); xn_call(t);
    M32(XN(0x155911)) = R.ebp;                                   /* 15594F: mov dword ptr [0x155911], ebp */
    t = M32(R.esp); R.esp += 4; R.ebp = t;                       /* 155955: pop ebp */
    t = M32(R.esp); R.esp += 4; R.ebx = t;                       /* 155956: pop ebx */
    t = M32(R.esp); R.esp += 4; R.ecx = t;                       /* 155957: pop ecx */
    fa = R.ebp; fb = 0x10;                                       /* 155958: cmp ebp, 0x10 */
    fr = fa - fb;
    if (((s32)fa < (s32)fb)) goto L_155A31;                      /* 15595B: jl 0x155a31 */
    t = R.ebp; PUSH32(t);                                        /* 155961: push ebp */
    R.eax = M32(R.esi + 0x40);                                   /* 155962: mov eax, dword ptr [esi + 0x40] */
    R.ebp &= 0xFFFFFFF0;                                         /* 155965: and ebp, 0xfffffff0 */
    M8(XN(0x1559B9)) = AL;                                       /* 155968: mov byte ptr [0x1559b9], al */
    R.ebp += R.edi;                                              /* 15596D: add ebp, edi */
    M32(XN(0x155A21)) = R.ebp;                                   /* 15596F: mov dword ptr [0x155a21], ebp */
    M32(XN(0x155A21)) = R.ebp;                                   /* 155975: mov dword ptr [0x155a21], ebp */
    /* 15597B: nop  */
    M32(XN(0x155A21)) = R.ebp;                                   /* 15597C: mov dword ptr [0x155a21], ebp */
L_155982:
    R.ecx += M32(XN(0x155984));                                  /* 155982: add ecx, 0x186a0 */
    fa = R.eax; fb = R.eax;                                      /* 155988: xor eax, eax */
    fr = fa ^ fb;
    R.eax = fr;
    R.edx = 0x4000;                                              /* 15598A: mov edx, 0x4000 */
    t = R.ecx; PUSH32(t);                                        /* 15598F: push ecx */
    LF(XF_LOGIC | 2, fa, fb, fr);                                /* 155990: div ecx */
    xn_div(R.ecx, 2, 0x155990);
    R.ecx = R.eax;                                               /* 155992: mov ecx, eax */
    fa = R.ebx; fb = M32(XN(0x155996));                          /* 155994: add ebx, 0x186a0 */
    fr = fa + fb;
    R.ebx = fr;
    R.eax = M32(XN(0x15599B));                                   /* 15599A: mov eax, 0x186a0 */
    t = R.ebx; PUSH32(t);                                        /* 15599F: push ebx */
    R.ebp = R.ebx;                                               /* 1559A0: mov ebp, ebx */
    LF(XF_ADD | 2, fa, fb, fr);                                  /* 1559A2: call dword ptr [esi + 0x14] */
    t = M32(R.esi + 0x14);
    PUSH32(XN(0x1559A5)); xn_call(t);
    R.ecx = M32(XN(0x155911));                                   /* 1559A5: mov ecx, dword ptr [0x155911] */
    M32(XN(0x155911)) = R.ebp;                                   /* 1559AB: mov dword ptr [0x155911], ebp */
    R.ebp -= R.ecx;                                              /* 1559B1: sub ebp, ecx */
    R.eax = R.ecx;                                               /* 1559B3: mov eax, ecx */
    R.ebp = (u32)((s32)R.ebp >> 3);                              /* 1559B5: sar ebp, 3 */
    AL = M8(XN(0x1559B9));                                       /* 1559B8: mov al, 0x64 */
    AH = CH;                                                     /* 1559BA: mov ah, ch */
    R.ecx += R.ebp;                                              /* 1559BC: add ecx, ebp */
    DL = M8(R.eax);                                              /* 1559BE: mov dl, byte ptr [eax] */
    DH = DL;                                                     /* 1559C0: mov dh, dl */
    M16(R.edi + 0x1) = DX;                                       /* 1559C2: mov word ptr [edi + 1], dx */
    AH = CH;                                                     /* 1559C6: mov ah, ch */
    R.ecx += R.ebp;                                              /* 1559C8: add ecx, ebp */
    DL = M8(R.eax);                                              /* 1559CA: mov dl, byte ptr [eax] */
    DH = DL;                                                     /* 1559CC: mov dh, dl */
    M16(R.edi + 0x3) = DX;                                       /* 1559CE: mov word ptr [edi + 3], dx */
    AH = CH;                                                     /* 1559D2: mov ah, ch */
    R.ecx += R.ebp;                                              /* 1559D4: add ecx, ebp */
    DL = M8(R.eax);                                              /* 1559D6: mov dl, byte ptr [eax] */
    DH = DL;                                                     /* 1559D8: mov dh, dl */
    M16(R.edi + 0x5) = DX;                                       /* 1559DA: mov word ptr [edi + 5], dx */
    AH = CH;                                                     /* 1559DE: mov ah, ch */
    R.ecx += R.ebp;                                              /* 1559E0: add ecx, ebp */
    DL = M8(R.eax);                                              /* 1559E2: mov dl, byte ptr [eax] */
    DH = DL;                                                     /* 1559E4: mov dh, dl */
    M16(R.edi + 0x7) = DX;                                       /* 1559E6: mov word ptr [edi + 7], dx */
    AH = CH;                                                     /* 1559EA: mov ah, ch */
    R.ecx += R.ebp;                                              /* 1559EC: add ecx, ebp */
    DL = M8(R.eax);                                              /* 1559EE: mov dl, byte ptr [eax] */
    DH = DL;                                                     /* 1559F0: mov dh, dl */
    M16(R.edi + 0x9) = DX;                                       /* 1559F2: mov word ptr [edi + 9], dx */
    AH = CH;                                                     /* 1559F6: mov ah, ch */
    R.ecx += R.ebp;                                              /* 1559F8: add ecx, ebp */
    DL = M8(R.eax);                                              /* 1559FA: mov dl, byte ptr [eax] */
    DH = DL;                                                     /* 1559FC: mov dh, dl */
    M16(R.edi + 0xB) = DX;                                       /* 1559FE: mov word ptr [edi + 0xb], dx */
    AH = CH;                                                     /* 155A02: mov ah, ch */
    R.ecx += R.ebp;                                              /* 155A04: add ecx, ebp */
    DL = M8(R.eax);                                              /* 155A06: mov dl, byte ptr [eax] */
    DH = DL;                                                     /* 155A08: mov dh, dl */
    M16(R.edi + 0xD) = DX;                                       /* 155A0A: mov word ptr [edi + 0xd], dx */
    AH = CH;                                                     /* 155A0E: mov ah, ch */
    R.ecx += R.ebp;                                              /* 155A10: add ecx, ebp */
    DL = M8(R.eax);                                              /* 155A12: mov dl, byte ptr [eax] */
    DH = DL;                                                     /* 155A14: mov dh, dl */
    M16(R.edi + 0xF) = DX;                                       /* 155A16: mov word ptr [edi + 0xf], dx */
    R.edi += 0x10;                                               /* 155A1A: add edi, 0x10 */
    t = M32(R.esp); R.esp += 4; R.ebx = t;                       /* 155A1D: pop ebx */
    t = M32(R.esp); R.esp += 4; R.ecx = t;                       /* 155A1E: pop ecx */
    fa = R.edi; fb = M32(XN(0x155A21));                          /* 155A1F: cmp edi, 0x186a0 */
    fr = fa - fb;
    if ((!(fa == fb))) goto L_155982;                            /* 155A25: jne 0x155982 */
    t = M32(R.esp); R.esp += 4; R.ebp = t;                       /* 155A2B: pop ebp */
    fa = R.ebp; fb = 0xF;                                        /* 155A2C: and ebp, 0xf */
    fr = fa & fb;
    R.ebp = fr;
    LF(XF_LOGIC | 2, fa, fb, fr);
    if ((fr == 0)) goto L_155A88;                                /* 155A2F: je 0x155a88 */
L_155A31:
    R.ebx += M32(R.ebp * 4 + XN(0x120AC0));                      /* 155A31: add ebx, dword ptr [ebp*4 + 0x120ac0] */
    t = R.ebp; PUSH32(t);                                        /* 155A38: push ebp */
    R.ebp = R.ebp * M32(R.esi + 0x5C);                           /* 155A39: imul ebp, dword ptr [esi + 0x5c] */
    R.ebp += R.ecx;                                              /* 155A3D: add ebp, ecx */
    fa = R.eax; fb = R.eax;                                      /* 155A3F: xor eax, eax */
    fr = fa ^ fb;
    R.eax = fr;
    R.edx = 0x4000;                                              /* 155A41: mov edx, 0x4000 */
    LF(XF_LOGIC | 2, fa, fb, fr);                                /* 155A46: div ebp */
    xn_div(R.ebp, 2, 0x155A46);
    R.ecx = R.eax;                                               /* 155A48: mov ecx, eax */
    R.eax = M32(XN(0x155A4B));                                   /* 155A4A: mov eax, 0x186a0 */
    R.ebp = R.ebx;                                               /* 155A4F: mov ebp, ebx */
    LF(XF_LOGIC | 2, fa, fb, fr);                                /* 155A51: call dword ptr [esi + 0x14] */
    t = M32(R.esi + 0x14);
    PUSH32(XN(0x155A54)); xn_call(t);
    R.ecx = M32(XN(0x155911));                                   /* 155A54: mov ecx, dword ptr [0x155911] */
    R.ebp -= R.ecx;                                              /* 155A5A: sub ebp, ecx */
    R.eax = R.ecx;                                               /* 155A5C: mov eax, ecx */
    t = M32(R.esp); R.esp += 4; R.ebx = t;                       /* 155A5E: pop ebx */
    AL = M8(R.esi + 0x40);                                       /* 155A5F: mov al, byte ptr [esi + 0x40] */
    R.ebp = R.ebp * M32(R.ebx * 4 + XN(0x147980));               /* 155A62: imul ebp, dword ptr [ebx*4 + 0x147980] */
    BX = M16(R.ebx * 2 + XN(0x155860));                          /* 155A6A: mov bx, word ptr [ebx*2 + 0x155860] */
    fa = (u32)((s32)R.ebp >> 15); fr = (u32)((s32)fa >> 1);      /* 155A72: sar ebp, 0x10 */
    R.ebp = fr;
    M8(R.ebx + XN(0x155880)) = 0xC3;                             /* 155A75: mov byte ptr [ebx + 0x155880], 0xc3 */
    LF(XF_SAR | 2, fa, 0, fr);                                   /* 155A7C: call 0x155880 */
    PUSH32(XN(0x155A81)); xn_call(XN(0x155880));
    M8(R.ebx + XN(0x155880)) = 0x8A;                             /* 155A81: mov byte ptr [ebx + 0x155880], 0x8a */
L_155A88:
    RET(0);                                                      /* 155A88: ret  */
}
