; XnGine module xn_15D100: FALL.EXE object 2, 0x15d100-0x15f600.
; Generated by tools/xn_disasm.py; reassembles to the original (tools/xn_link.py).
; B_<address>_<length> lines are data bytes the build takes from your FALL.EXE.
.486p
.387
include xn_15D100.inc
public D_0015DC00
public func_0015D170
public func_0015D2EC
public func_0015E400
public func_0015F50C
extrn D_0012B508:byte
extrn D_00142930:byte
extrn D_00142940:byte
extrn D_00142944:byte
extrn D_00142948:byte
extrn D_0014294C:byte
extrn D_00142950:byte
extrn D_00143550:byte
extrn D_00149980:byte
XN_15D100 segment byte public use32 'CODE'
    assume cs:XN_15D100, ds:XN_15D100, es:XN_15D100, ss:XN_15D100
    B_15D100_2
    dd D_0015D165
    B_15D106_2
    dd D_0015D165
    B_15D10C_2
    dd D_0015D169
    B_15D112_2
    dd D_0015D169
    B_15D118_25
    dd D_0015D165
    B_15D135_2
    dd D_0015D169
    B_15D13B_25
    dd D_0015D169
    B_15D158_13
D_0015D165:
    db 4 dup (0)
D_0015D169:
    B_15D169_7
func_0015D170:
    mov dword ptr [D_0015D1E9], ecx
    shl dword ptr [D_0015D1E9], 2
    mov dword ptr [D_0015D1ED], eax
    shl dword ptr [D_0015D1ED], 2
    mov dword ptr [D_0015D1F1], ebp
L_15D18F:
    push edi
    push ebx
    push eax
L_15D192:
    call func_0015D1B7
    add edi, 4
    add ebx, 4
    sub eax, 1
    jne short L_15D192
    pop eax
    pop ebx
    pop edi
    add esi, dword ptr [D_0015D1E9]
    add ebx, dword ptr [D_0015D1ED]
    sub edx, 1
    jne short L_15D18F
    ret
func_0015D1B7:
    push eax
    push ecx
    push edx
    push edi
    push esi
    push ebp
    push ebx
    xor ebx, ebx
    xor ebp, ebp
L_15D1C2:
    mov eax, dword ptr [esi]
    imul dword ptr [edi]
    add ebp, eax
    adc ebx, edx
    add esi, 4
    add edi, dword ptr [D_0015D1ED]
    dec ecx
    jne short L_15D1C2
    mov ecx, dword ptr [D_0015D1F1]
    shrd ebp, ebx, cl
    pop ebx
    mov dword ptr [ebx], ebp
    pop ebp
    pop esi
    pop edi
    pop edx
    pop ecx
    pop eax
    ret
D_0015D1E9:
    db 4 dup (0)
D_0015D1ED:
    db 4 dup (0)
D_0015D1F1:
    B_15D1F1_9
    dd D_0015D27C
    B_15D1FE_2
    dd D_0015D27C
    B_15D204_2
    dd D_0015D280
    B_15D20A_2
    dd D_0015D280
    B_15D210_4
    dd D_0015D284
    B_15D218_24
    dd D_0015D27C
    B_15D234_2
    dd D_0015D280
    B_15D23A_30
    dd D_0015D280
    B_15D25C_8
    dd D_0015D284
    B_15D268_20
D_0015D27C:
    db 4 dup (0)
D_0015D280:
    db 4 dup (0)
D_0015D284:
    B_15D284_104
func_0015D2EC:
    push ecx
    push esi
    push edi
    mov esi, eax
    mov edi, edx
    mov ecx, 9
    rep movsd
    mov eax, dword ptr [edx + 4]
    xchg dword ptr [edx + 0Ch], eax
    mov dword ptr [edx + 4], eax
    mov eax, dword ptr [edx + 8]
    xchg dword ptr [edx + 018h], eax
    mov dword ptr [edx + 8], eax
    mov eax, dword ptr [edx + 014h]
    xchg dword ptr [edx + 01Ch], eax
    mov dword ptr [edx + 014h], eax
    pop edi
    pop esi
    pop ecx
    ret
    db 232 dup (0)
    B_15D401_2047
D_0015DC00:
    db 8 dup (0)
    B_15DC08_2040
func_0015E400:
    cmp eax, dword ptr [D_00142948]
    jge short L_15E459
    cmp ebx, dword ptr [D_00142940]
    jle short L_15E459
    cmp edx, dword ptr [D_0014294C]
    jge short L_15E459
    cmp ecx, dword ptr [D_00142944]
    jle short L_15E459
    cmp eax, dword ptr [D_00142940]
    jge short L_15E42D
    mov eax, dword ptr [D_00142940]
L_15E42D:
    cmp ebx, dword ptr [D_00142948]
    jle short L_15E43B
    mov ebx, dword ptr [D_00142948]
L_15E43B:
    cmp edx, dword ptr [D_00142944]
    jge short L_15E449
    mov edx, dword ptr [D_00142944]
L_15E449:
    cmp ecx, dword ptr [D_0014294C]
    jle short L_15E457
    mov ecx, dword ptr [D_0014294C]
L_15E457:
    clc
    ret
L_15E459:
    stc
    ret
    B_15E45B_96
    dd D_00142950
    B_15E4BF_2
    dd D_00143550
    B_15E4C5_11
    dd D_0012B508
    B_15E4D4_2
    dd D_00142930
    B_15E4DA_3
    dd D_00149980
    B_15E4E1_31
D_0015E500:
    B_15E500_4108
func_0015F50C:
    push ebx
    push ecx
    push edx
    or eax, eax
    je short L_15F54F
    mov ebx, eax
    xor dl, dl
    bsr ecx, ebx
    cmp ecx, 0Ch
    jb short L_15F52F
    sub ecx, 0Bh
    mov dl, cl
    shr dl, 1
    adc cl, 0
    mov dl, cl
    shr dl, 1
    shr ebx, cl
L_15F52F:
    bsf ecx, ebx
    test ecx, 1
    setne al
    sub cl, al
    shr ebx, cl
    shr cl, 1
    movzx eax, byte ptr [ebx + D_0015E500]
    add cl, dl
    shl eax, cl
    shr eax, 2
L_15F54F:
    pop edx
    pop ecx
    pop ebx
    ret
    db 173 dup (0)
XN_15D100 ends
end
