; XnGine module xn_137F00: FALL.EXE object 2, 0x137f00-0x138100.
; Generated by tools/xn_disasm.py; reassembles to the original (tools/xn_link.py).
; B_<address>_<length> lines are data bytes the build takes from your FALL.EXE.
.486p
.387
include xn_137F00.inc
public D_00137F00
XN_137F00 segment byte public use32 'CODE'
    assume cs:XN_137F00, ds:XN_137F00, es:XN_137F00, ss:XN_137F00
D_00137F00:
    db 512 dup (0)
XN_137F00 ends
end
