; XnGine module xn_12DB00: FALL.EXE object 2, 0x12db00-0x12de00.
; Generated by tools/xn_disasm.py; reassembles to the original (tools/xn_link.py).
; B_<address>_<length> lines are data bytes the build takes from your FALL.EXE.
.486p
.487
JUMPS
include xn_12DB00.inc
public func_0012DD1C
XN_12DB00 segment byte public use32 'CODE'
    assume cs:XN_12DB00, ds:XN_12DB00, es:XN_12DB00, ss:XN_12DB00
extrn D_0012B508:byte
extrn D_0012DA00:byte
extrn D_0012DA04:byte
extrn D_0012DA0D:byte
extrn D_0012DA38:byte
extrn D_0012DA3C:byte
extrn D_0012DA40:byte
extrn D_0012DA44:byte
extrn D_0012DA48:byte
extrn D_0012DA4C:byte
extrn D_0012DA50:byte
extrn D_0012DA54:byte
extrn D_0012DA74:byte
extrn D_00142930:byte
extrn D_00142940:byte
extrn D_00142944:byte
extrn D_00142948:byte
extrn D_0014294C:byte
extrn D_00142950:byte
extrn D_00143550:byte
extrn func_000C0E24:near
extrn func_00142764:near
extrn func_00143700:near
extrn func_00149EF8:near
extrn func_00153900:near
func_0012DB00:
    pushad
    mov edi, offset D_0012DA54
    xor eax, eax
    mov ecx, 8
    rep stosd
    mov dword ptr [D_0012DA48], 1
    mov dword ptr [D_0012DA4C], 1
    popad
    ret
    B_12DB25_3
func_0012DB28:
    push edx
    mov edx, offset D_0012DA04
    mov ebx, 4
    call func_00153900
    mov eax, offset D_0012DA00
    xor edx, edx
    call func_000C0E24
    pop edx
    mov dword ptr [edx*4 + D_0012DA54], eax
    ret
    B_12DB4D_3
func_0012DB50:
    cmp dword ptr [eax*4 + D_0012DA54], 0
    je short L_12DB80
    push esi
    mov dword ptr [D_0012DA50], eax
    mov esi, dword ptr [eax*4 + D_0012DA54]
    mov dword ptr [D_0012DA74], esi
    movzx eax, word ptr [esi]
    mov dword ptr [D_0012DA40], eax
    movzx eax, word ptr [esi + 2]
    mov dword ptr [D_0012DA44], eax
    pop esi
    ret
L_12DB80:
    call func_00143700
    call func_00142764
    call func_00149EF8
    mov ah, 9
    mov edx, offset D_0012DA0D
    int 021h
    mov ax, 04C00h
    int 021h
    xchg ebx, ebx
    push ecx
    push ebp
    push esi
    push edi
    sub ebx, 021h
    jl short L_12DBC5
    shl ebx, 2
    add ebx, dword ptr [D_0012DA74]
    movzx esi, word ptr [ebx + 4]
    add esi, dword ptr [D_0012DA74]
    movzx ebx, word ptr [ebx + 6]
    call func_0012DC44
L_12DBC5:
    pop edi
    pop esi
    pop ebp
    pop ecx
    ret
    B_12DBCA_2
func_0012DBCC:
    push ecx
    push ebp
    push esi
    push edi
    mov dword ptr [D_0012DA38], eax
    mov dword ptr [D_0012DA3C], edx
L_12DBDB:
    movzx ecx, byte ptr [ebx]
    jecxz short L_12DC3D
    inc ebx
    sub cl, 021h
    jl short L_12DC0E
    push ebx
    shl ecx, 2
    add ecx, dword ptr [D_0012DA74]
    movzx esi, word ptr [ecx + 4]
    add esi, dword ptr [D_0012DA74]
    movzx ebx, word ptr [ecx + 6]
    call func_0012DC44
    add eax, ebx
    add eax, dword ptr [D_0012DA48]
    pop ebx
    jmp short L_12DBDB
L_12DC0E:
    add cl, 021h
    cmp cl, 020h
    jne short L_12DC1E
    add eax, dword ptr [D_0012DA40]
    jmp short L_12DBDB
L_12DC1E:
    cmp cl, 0Dh
    jne short L_12DC2A
    mov eax, dword ptr [D_0012DA38]
    jmp short L_12DBDB
L_12DC2A:
    cmp cl, 0Ah
    jne short L_12DC3B
    add edx, dword ptr [D_0012DA44]
    add edx, dword ptr [D_0012DA4C]
L_12DC3B:
    jmp short L_12DBDB
L_12DC3D:
    pop edi
    pop esi
    pop ebp
    pop ecx
    ret
    B_12DC42_2
func_0012DC44:
    push eax
    push ebx
    push ecx
    push edx
    cmp eax, dword ptr [D_00142948]
    jge L_12DD17
    cmp edx, dword ptr [D_0014294C]
    jge L_12DD17
    mov ebp, dword ptr [D_0012DA44]
    cmp edx, dword ptr [D_00142944]
    jge short L_12DC88
    sub edx, dword ptr [D_00142944]
    neg edx
    sub ebp, edx
    jle L_12DD17
    add edx, edx
    add esi, edx
    mov edx, dword ptr [D_00142944]
L_12DC88:
    mov ecx, edx
    add ecx, ebp
    sub ecx, dword ptr [D_0014294C]
    jle short L_12DC9C
    sub ebp, ecx
    jle L_12DD17
L_12DC9C:
    mov byte ptr [patch_12DD02], 010h
    cmp eax, dword ptr [D_00142940]
    jge short L_12DCC5
    sub eax, dword ptr [D_00142940]
    neg eax
    sub ebx, eax
    jle short L_12DD17
    add bl, 010h
    mov byte ptr [patch_12DD02], bl
    mov eax, dword ptr [D_00142940]
L_12DCC5:
    mov ecx, eax
    add ecx, ebx
    sub ecx, dword ptr [D_00142948]
    jle short L_12DCD5
    sub ebx, ecx
    jle short L_12DD17
L_12DCD5:
    mov edi, dword ptr [edx*4 + D_00142950]
    add edi, dword ptr [D_00143550]
    add edi, eax
    mov ecx, dword ptr [D_00142930]
    sub ecx, ebx
    mov dword ptr [patch_12DD10], ecx
    mov ch, byte ptr [D_0012B508]
L_12DCF8:
    mov ax, word ptr [esi]
    mov cl, bl
    add esi, 2
L_12DD00:
    shl eax, 064h
patch_12DD02 equ L_12DD00+2   ; rewritten at run time
L_12DD03:
    add eax, eax
    jae short L_12DD09
    mov byte ptr [edi], ch
L_12DD09:
    inc edi
    dec cl
    jne short L_12DD03
L_12DD0E:
    add edi, 03E8h
patch_12DD10 equ L_12DD0E+2   ; rewritten at run time
    dec ebp
    jne short L_12DCF8
L_12DD17:
    pop edx
    pop ecx
    pop ebx
    pop eax
    ret
func_0012DD1C:
    sub eax, 021h
    jle short L_12DD2F
    shl eax, 2
    add eax, dword ptr [D_0012DA74]
    movzx eax, word ptr [eax + 6]
    ret
L_12DD2F:
    mov eax, dword ptr [D_0012DA40]
    sub eax, dword ptr [D_0012DA48]
    ret
    db 197 dup (0)
XN_12DB00 ends
end
