; XnGine module xn_154D00: FALL.EXE object 2, 0x154d00-0x155800.
; Generated by tools/xn_disasm.py; reassembles to the original (tools/xn_link.py).
; B_<address>_<length> lines are data bytes the build takes from your FALL.EXE.
.486p
.387
include xn_154D00.inc
public L_1550E7
public L_1550F1
public L_155634
public func_00154DA5
public func_00154E20
public func_00154EDC
public func_00154FD4
public func_00154FD8
public func_001550BC
public func_001550C0
public func_001552A0
public func_00155415
public func_00155508
extrn D_000C23B8:byte
extrn D_000C23C4:byte
extrn D_000C23C8:byte
extrn D_000C23CC:byte
extrn D_000CEA24:byte
extrn D_000CEA30:byte
extrn D_000CEA34:byte
extrn D_000CEA38:byte
extrn D_000CEA40:byte
extrn D_000CEA64:byte
extrn D_000CEA98:byte
extrn D_000CEA99:byte
extrn D_000CEA9D:byte
extrn D_000F39F0:byte
extrn D_00120288:byte
extrn D_0012028C:byte
extrn D_00120290:byte
extrn D_00120294:byte
extrn D_00120298:byte
extrn D_001202A0:byte
extrn D_001202A4:byte
extrn D_001202A8:byte
extrn D_00136540:byte
extrn D_0013690D:byte
extrn D_0013691D:byte
extrn D_00136921:byte
extrn D_00136E24:byte
extrn D_00142930:byte
extrn D_00142950:byte
extrn D_00143550:byte
extrn D_00147980:byte
extrn D_00148980:byte
extrn D_0014CC0C:byte
extrn D_0014CC10:byte
extrn D_0014CC14:byte
extrn D_00153C00:byte
extrn D_00153C3C:byte
extrn D_00154C44:byte
extrn D_00154C48:byte
extrn D_00154C4C:byte
extrn D_00154C50:byte
extrn D_00154C54:byte
extrn D_00154C58:byte
extrn D_00154C5C:byte
extrn D_00154C60:byte
extrn D_00154C61:byte
extrn D_00154C65:byte
extrn D_00154C6D:byte
extrn D_00154C71:byte
extrn D_00154C7D:byte
extrn D_00154C85:byte
extrn D_00158210:byte
extrn D_00158211:byte
extrn D_00158EA0:byte
extrn D_00158EA4:byte
extrn D_00158EA8:byte
extrn D_00158EB0:byte
extrn D_00158EC4:byte
extrn D_0015B984:byte
extrn func_00135D00:near
extrn func_00135DE4:near
extrn func_00137000:near
extrn func_0013749E:near
extrn func_0013758A:near
extrn func_00137725:near
extrn func_00157620:near
extrn func_00157800:near
extrn func_00157B20:near
extrn func_00157E20:near
extrn func_0015830C:near
extrn func_00158360:near
extrn func_0015F50C:near
XN_154D00 segment byte public use32 'CODE'
    assume cs:XN_154D00, ds:XN_154D00, es:XN_154D00, ss:XN_154D00
func_00154D00:
    push ebp
    mov ebp, esp
    push esi
    push edi
    mov edi, dword ptr [ebp + 010h]
    mov esi, dword ptr [ebp + 0Ch]
    mov ebp, dword ptr [ebp + 8]
    call func_00154D20
    mov eax, edi
    pop edi
    pop esi
    pop ebp
    ret 0Ch
    B_154D1B_5
func_00154D20:
    push edi
    push ecx
    mov ecx, offset D_00136E24
    sub eax, dword ptr [D_000C23C4]
    sub edx, dword ptr [D_000C23C8]
    sub ebx, dword ptr [D_000C23CC]
    shl eax, 8
    shl edx, 8
    shl ebx, 8
    call func_0013749E
    test ebx, ebx
    jle short L_154DA2
    cmp ebx, dword ptr [D_000CEA24]
    jge short L_154DA2
    inc dword ptr [D_00154C48]
    cmp dword ptr [D_00154C48], 0200h
    jg short L_154DA2
    mov edi, dword ptr [D_000CEA64]
    add dword ptr [D_000CEA64], 064h
    pop dword ptr [edi]
    mov dword ptr [edi + 04Ch], ebp
    mov dword ptr [edi + 014h], esi
    mov dword ptr [edi + 050h], eax
    mov dword ptr [edi + 054h], edx
    mov dword ptr [edi + 058h], ebx
    mov dword ptr [edi + 4], 0
    mov esi, dword ptr [D_00154C44]
    add dword ptr [D_00154C44], 8
    neg ebx
    mov dword ptr [esi + 4], edi
    mov dword ptr [esi], ebx
    pop dword ptr [edi + 044h]
    ret
L_154DA2:
    pop ecx
    pop edi
    ret
func_00154DA5:
    inc dword ptr [D_00154C48]
    cmp dword ptr [D_00154C48], 0200h
    jg short L_154E01
    push edi
    mov edi, dword ptr [D_000CEA64]
    add dword ptr [D_000CEA64], 064h
    mov dword ptr [edi], ecx
    mov dword ptr [edi + 04Ch], 0
    mov dword ptr [edi + 014h], 4
    mov dword ptr [edi + 050h], eax
    mov dword ptr [edi + 054h], edx
    mov dword ptr [edi + 058h], ebx
    mov dword ptr [edi + 4], 0
    mov dword ptr [edi + 044h], 0100h
    mov esi, dword ptr [D_00154C44]
    add dword ptr [D_00154C44], 8
    neg ebx
    mov dword ptr [esi + 4], edi
    mov dword ptr [esi], ebx
    pop edi
L_154E01:
    ret
    B_154E02_30
func_00154E20:
    mov eax, dword ptr [edi]
    mov edx, eax
    shr eax, 7
    and edx, 07Fh
    mov ebx, dword ptr [edi + 04Ch]
    call func_00135D00
    jb near ptr L_154EDA
    movzx ebx, word ptr [eax + 0Ah]
    mov ebx, dword ptr [ebx*4 + D_00136921]
    mov dword ptr [edi + 04Ch], ebx
    mov eax, dword ptr [eax + 0Ch]
    mov ebp, dword ptr [edi + 044h]
    mov esi, dword ptr [eax + 0Eh]
    add bp, word ptr [eax + 018h]
    add esi, eax
    and ebp, 0FFFFh
    mov dword ptr [edi + 040h], esi
    mov word ptr [edi + 044h], bp
    movzx edx, word ptr [eax + 6]
    mov dword ptr [D_00154C5C], edx
    imul edx, ebp
    mov ebx, dword ptr [edi + 014h]
    movzx eax, word ptr [eax + 4]
    mov dword ptr [D_00154C54], eax
    and ebx, 01Fh
    imul eax, ebp
    call dword ptr [ebx*4 + D_00153C00]
    test byte ptr [D_00158210], 0FFh
    jne short L_154ED9
    mov eax, dword ptr [D_00158EA0]
    mov edx, dword ptr [D_00158EA4]
    mov ebx, dword ptr [D_00158EA8]
    sar eax, 3
    sar edx, 3
    sar ebx, 3
    mov dword ptr [D_00120288], eax
    mov dword ptr [D_0012028C], edx
    mov dword ptr [D_00120290], ebx
    inc dword ptr [D_00154C4C]
    mov dword ptr [patch_15526F], edi
    mov esi, offset D_00158EA0
    mov dword ptr [edi + 03Ch], offset func_00155610
    call func_00158360
L_154ED9:
    clc
L_154EDA:
    ret
    B_154EDB_1
func_00154EDC:
    mov esi, offset D_00158EA0
    db 0C1h, 0E8h, 01h   ; shr eax, 1
    db 0C1h, 0EAh, 01h   ; shr edx, 1
    mov dword ptr [D_00154C50], eax
    mov dword ptr [D_00154C58], edx
    mov word ptr [D_00158210], 0FFh
    mov ecx, dword ptr [D_00154C50]
    mov ebp, dword ptr [D_00154C58]
    neg ecx
    neg ebp
    call func_001553D8
    push eax
    push edx
    push ebx
    add eax, dword ptr [edi + 050h]
    add edx, dword ptr [edi + 054h]
    add ebx, dword ptr [edi + 058h]
    mov dword ptr [esi], eax
    mov dword ptr [esi + 4], edx
    mov dword ptr [esi + 8], ebx
    call func_0015830C
    mov byte ptr [esi + 0Ch], cl
    and byte ptr [D_00158210], cl
    or byte ptr [D_00158211], cl
    mov ecx, dword ptr [D_00154C50]
    mov ebp, dword ptr [D_00154C58]
    neg ebp
    call func_001553D8
    push eax
    push edx
    push ebx
    add eax, dword ptr [edi + 050h]
    add edx, dword ptr [edi + 054h]
    add ebx, dword ptr [edi + 058h]
    mov dword ptr [esi + 010h], eax
    mov dword ptr [esi + 014h], edx
    mov dword ptr [esi + 018h], ebx
    call func_0015830C
    mov byte ptr [esi + 01Ch], cl
    and byte ptr [D_00158210], cl
    or byte ptr [D_00158211], cl
    pop ebx
    pop edx
    pop eax
    neg eax
    neg edx
    neg ebx
    add eax, dword ptr [edi + 050h]
    add edx, dword ptr [edi + 054h]
    add ebx, dword ptr [edi + 058h]
    mov dword ptr [esi + 030h], eax
    mov dword ptr [esi + 034h], edx
    mov dword ptr [esi + 038h], ebx
    call func_0015830C
    mov byte ptr [esi + 03Ch], cl
    and byte ptr [D_00158210], cl
    or byte ptr [D_00158211], cl
    pop ebx
    pop edx
    pop eax
    neg eax
    neg edx
    neg ebx
    add eax, dword ptr [edi + 050h]
    add edx, dword ptr [edi + 054h]
    add ebx, dword ptr [edi + 058h]
    mov dword ptr [esi + 020h], eax
    mov dword ptr [esi + 024h], edx
    mov dword ptr [esi + 028h], ebx
    call func_0015830C
    mov byte ptr [esi + 02Ch], cl
    and byte ptr [D_00158210], cl
    or byte ptr [D_00158211], cl
    ret
    B_154FD3_1
func_00154FD4:
    ret
    B_154FD5_3
func_00154FD8:
    mov esi, offset D_00158EA0
    db 0C1h, 0E8h, 01h   ; shr eax, 1
    mov dword ptr [D_00154C50], eax
    mov dword ptr [D_00154C58], edx
    mov word ptr [D_00158210], 0FFh
    mov ecx, dword ptr [D_00154C50]
    mov ebp, dword ptr [D_00154C58]
    neg ecx
    neg ebp
    call func_001553D8
    push eax
    add eax, dword ptr [edi + 050h]
    add edx, dword ptr [edi + 054h]
    add ebx, dword ptr [edi + 058h]
    mov dword ptr [esi], eax
    mov dword ptr [esi + 4], edx
    mov dword ptr [esi + 8], ebx
    call func_0015830C
    mov byte ptr [esi + 0Ch], cl
    and byte ptr [D_00158210], cl
    or byte ptr [D_00158211], cl
    mov ecx, dword ptr [D_00154C50]
    mov ebp, dword ptr [D_00154C58]
    neg ebp
    call func_001553D8
    push eax
    add eax, dword ptr [edi + 050h]
    add edx, dword ptr [edi + 054h]
    add ebx, dword ptr [edi + 058h]
    mov dword ptr [esi + 010h], eax
    mov dword ptr [esi + 014h], edx
    mov dword ptr [esi + 018h], ebx
    call func_0015830C
    mov byte ptr [esi + 01Ch], cl
    and byte ptr [D_00158210], cl
    or byte ptr [D_00158211], cl
    pop eax
    neg eax
    add eax, dword ptr [edi + 050h]
    mov edx, dword ptr [edi + 054h]
    mov ebx, dword ptr [edi + 058h]
    mov dword ptr [esi + 030h], eax
    mov dword ptr [esi + 034h], edx
    mov dword ptr [esi + 038h], ebx
    call func_0015830C
    mov byte ptr [esi + 03Ch], cl
    and byte ptr [D_00158210], cl
    or byte ptr [D_00158211], cl
    pop eax
    neg eax
    add eax, dword ptr [edi + 050h]
    mov edx, dword ptr [edi + 054h]
    mov ebx, dword ptr [edi + 058h]
    mov dword ptr [esi + 020h], eax
    mov dword ptr [esi + 024h], edx
    mov dword ptr [esi + 028h], ebx
    call func_0015830C
    mov byte ptr [esi + 02Ch], cl
    and byte ptr [D_00158210], cl
    or byte ptr [D_00158211], cl
    ret
func_001550BC:
    ret
    B_1550BD_3
func_001550C0:
    ret
    B_1550C1_31
func_001550E0:
    push eax
    mov edi, dword ptr [patch_15526F]
L_1550E7:
    imul esi, dword ptr [D_00120288], 0186A0h
patch_1550ED equ L_1550E7+6   ; rewritten at run time
L_1550F1:
    imul ebp, dword ptr [D_0012028C], 0186A0h
patch_1550F7 equ L_1550F1+6   ; rewritten at run time
    xor eax, eax
    mov ecx, dword ptr [edi + 044h]
    mov edx, 2
    and ecx, 0FFFFh
    div ecx
    mov ecx, eax
L_15510F:
    mov eax, 0186A0h
patch_155110 equ L_15510F+1   ; rewritten at run time
    imul ecx
    mov dword ptr [edi + 8], edx
    sar edx, 3
    mov dword ptr [edi + 024h], edx
L_15511F:
    mov eax, 0186A0h
patch_155120 equ L_15511F+1   ; rewritten at run time
    imul ecx
    mov dword ptr [edi + 028h], edx
L_155129:
    mov eax, 0186A0h
patch_15512A equ L_155129+1   ; rewritten at run time
    imul ecx
    mov dword ptr [edi + 02Ch], edx
    mov eax, esi
    mov edx, ebp
    mov ebx, dword ptr [D_00120290]
    imul eax, dword ptr [edi + 024h]
    imul edx, dword ptr [edi + 028h]
    imul ebx, dword ptr [edi + 02Ch]
    add ebx, eax
L_15514B:
    mov eax, 0186A0h
patch_15514C equ L_15514B+1   ; rewritten at run time
    add ebx, edx
    imul ecx
    sar ebx, 1
    mov dword ptr [edi + 0Ch], edx
    sar edx, 3
    mov dword ptr [edi + 018h], ebx
    mov dword ptr [edi + 030h], edx
L_155162:
    mov eax, 0186A0h
patch_155163 equ L_155162+1   ; rewritten at run time
    imul ecx
    mov dword ptr [edi + 034h], edx
L_15516C:
    mov eax, 0186A0h
patch_15516D equ L_15516C+1   ; rewritten at run time
    imul ecx
    mov dword ptr [edi + 038h], edx
    imul esi, dword ptr [edi + 030h]
    imul ebp, dword ptr [edi + 034h]
    add esi, ebp
    mov ebp, dword ptr [D_00120290]
    imul ebp, dword ptr [edi + 038h]
    add esi, ebp
    pop eax
    mov dword ptr [edi + 01Ch], esi
    mov edx, dword ptr [edi + 028h]
    mov ebx, eax
    mov dword ptr [patch_155353], edx
    sub ebx, dword ptr [D_000CEA34]
    imul edx, ebx
    add dword ptr [edi + 02Ch], edx
    lea edx, [edi + 02Ch]
    mov dword ptr [patch_15534F], edx
    mov edx, dword ptr [edi + 034h]
    sub edx, 8
    mov dword ptr [patch_15535D], edx
    imul edx, ebx
    add dword ptr [edi + 038h], edx
    lea edx, [edi + 038h]
    mov dword ptr [patch_155359], edx
    test dword ptr [edi + 014h], 020h
    je short L_1551E9
    neg dword ptr [edi + 8]
    neg dword ptr [edi + 024h]
    mov edx, dword ptr [D_00154C54]
    neg dword ptr [edi + 018h]
    shl edx, 017h
    sub dword ptr [edi + 018h], edx
L_1551E9:
    ret
    B_1551EA_22
func_00155200:
    mov esi, dword ptr [esi]
    cmp word ptr [esi + 4], bx
    jle short func_00155200
    cmp bp, word ptr [esi + 6]
    jle short func_0015526C
    mov eax, dword ptr [esi + 0Ch]
    cmp bp, word ptr [esi + 4]
    jl short L_155259
    movzx edx, word ptr [esi + 6]
    sub edx, ebx
    je short L_155237
    jg short L_15523E
    neg edx
    imul edx, dword ptr [eax + 05Ch]
    add edx, dword ptr [esi + 8]
    sub edx, ecx
    jl short func_00155200
L_15522E:
    mov bx, word ptr [esi + 4]
    cmp ebx, ebp
    jl short func_00155200
    ret
L_155237:
    cmp dword ptr [esi + 8], ecx
    jl short func_00155200
    jmp short L_15522E
L_15523E:
    cmp ecx, dword ptr [esi + 8]
    jg short func_00155200
    push esi
    push ebp
    mov bp, word ptr [esi + 6]
    call func_0015526C
    pop ebp
    pop esi
    movzx ebx, word ptr [esi + 4]
    cmp ebx, ebp
    jl short func_00155200
    ret
L_155259:
    movzx edx, word ptr [esi + 6]
    sub edx, ebx
    je short L_155281
    jl short L_155287
    cmp ecx, dword ptr [esi + 8]
    jg short func_0015526C
    mov bp, word ptr [esi + 6]
func_0015526C:
    push ecx
    push edi
L_15526E:
    mov esi, 0186A0h
patch_15526F equ L_15526E+1   ; rewritten at run time
L_155273:
    lea edi, [ebx + 0186A0h]
patch_155275 equ L_155273+2   ; rewritten at run time
    sub ebp, ebx
    call dword ptr [esi + 03Ch]
    pop edi
    pop ecx
    ret
L_155281:
    cmp ecx, dword ptr [esi + 8]
    jg short func_0015526C
    ret
L_155287:
    neg edx
    imul edx, dword ptr [eax + 05Ch]
    add edx, dword ptr [esi + 8]
    sub edx, ecx
    jl short func_0015526C
    ret
    B_155295_11
func_001552A0:
    mov dword ptr [patch_1552E0], ebp
    mov dword ptr [patch_15539D], ebp
    call func_001550E0
    mov edx, dword ptr [eax*4 + D_00142950]
    dec edx
    add eax, eax
    add edx, dword ptr [D_00143550]
    xor edi, edi
    mov dword ptr [patch_155275], edx
    lea esi, [eax*8 + D_000F39F0]
    nop
    nop
    nop
L_1552D3:
    dec byte ptr [D_0015B984]
    js near ptr L_1553D5
L_1552DF:
    mov ebp, 0186A0h
patch_1552E0 equ L_1552DF+1   ; rewritten at run time
    add dword ptr [patch_1552E0], 4
    mov ecx, dword ptr [ebp + 4]
    mov ebp, dword ptr [ebp]
    mov di, word ptr [ecx + 4]
    sub di, word ptr [ebp + 4]
    jle short L_1552D3
    push edi
    mov edx, dword ptr [ecx]
    mov eax, dword ptr [ecx + 8]
    and edi, 0FFFFh
    mov ecx, dword ptr [ebp + 8]
    mov ebp, dword ptr [ebp]
    sub eax, ecx
    sub edx, ebp
    imul edx, dword ptr [edi*4 + D_00147980]
    shl ebp, 010h
    mov dword ptr [patch_155373], edx
    imul dword ptr [edi*4 + D_00148980]
    mov dword ptr [patch_15537F], edx
    pop edi
    jmp short L_15538C
func_00155332:
    xor eax, eax
L_155334:
    push ebx
    push ebp
    shr ebx, 015h
    shr ebp, 015h
    dec ebp
    cmp ebp, ebx
    jle short L_155348
    push esi
    call func_00155200
    pop esi
L_155348:
    pop ebp
    pop ebx
    add esi, 010h
L_15534D:
    add dword ptr [D_00154C58], 0186A0h
patch_15534F equ L_15534D+2   ; rewritten at run time
patch_155353 equ L_15534D+6   ; rewritten at run time
L_155357:
    add dword ptr [D_00154C50], 0186A0h
patch_155359 equ L_155357+2   ; rewritten at run time
patch_15535D equ L_155357+6   ; rewritten at run time
L_155361:
    add dword ptr [patch_155275], 0140h
patch_155367 equ L_155361+6   ; rewritten at run time
    sub edi, 010001h
L_155371:
    add ebp, 0186A0h
patch_155373 equ L_155371+2   ; rewritten at run time
L_155377:
    add ebx, 0186A0h
patch_155379 equ L_155377+2   ; rewritten at run time
L_15537D:
    add ecx, 0186A0h
patch_15537F equ L_15537D+2   ; rewritten at run time
    or di, di
    je near ptr L_1552D3
L_15538C:
    test edi, 0FFFF0000h
    jne short L_155334
L_155394:
    dec byte ptr [D_0015B984]
    js short L_1553D5
L_15539C:
    mov ebx, 0186A0h
patch_15539D equ L_15539C+1   ; rewritten at run time
    sub dword ptr [patch_15539D], 4
    mov eax, dword ptr [ebx - 4]
    mov ebx, dword ptr [ebx]
    mov edx, dword ptr [eax + 4]
    sub edx, dword ptr [ebx + 4]
    jle short L_155394
    mov eax, dword ptr [eax]
    mov ebx, dword ptr [ebx]
    sub eax, ebx
    imul eax, dword ptr [edx*4 + D_00147980]
    shl edx, 010h
    mov dword ptr [patch_155379], eax
    shl ebx, 010h
    or edi, edx
    jmp near ptr L_155334
L_1553D5:
    ret
    B_1553D6_2
func_001553D8:
    shl ecx, 4
    shl ebp, 4
    mov eax, ecx
    imul dword ptr [D_00154C61]
    mov eax, ebp
    mov ebx, edx
    imul dword ptr [D_00154C65]
    add ebx, edx
    mov eax, ecx
    push ebx
    imul dword ptr [D_00154C6D]
    mov eax, ebp
    mov ebx, edx
    imul dword ptr [D_00154C71]
    add ebx, edx
    push ebx
    mov eax, ebp
    imul dword ptr [D_00154C7D]
    mov ebx, edx
    pop edx
    pop eax
    ret
func_00155415:
    xor edx, edx
    xor ebx, ebx
    xor eax, eax
    cmp byte ptr [D_00154C60], 064h
    je short L_15542B
    mov eax, dword ptr [D_000C23B8]
    jmp short L_15542B
L_15542B:
    mov ecx, offset D_00154C61
    call func_00137000
    mov eax, offset D_00154C61
    mov edx, eax
    call func_00137725
    mov esi, offset D_00154C61
    mov edi, offset D_00154C85
    mov ebx, dword ptr [D_000CEA99]
    mov eax, dword ptr [esi]
    imul ebx
    mov dword ptr [edi], edx
    mov eax, dword ptr [esi + 4]
    imul ebx
    mov dword ptr [edi + 4], edx
    mov eax, dword ptr [esi + 8]
    imul ebx
    mov dword ptr [edi + 8], edx
    mov ebx, dword ptr [D_000CEA9D]
    mov eax, dword ptr [esi + 0Ch]
    imul ebx
    mov dword ptr [edi + 0Ch], edx
    mov eax, dword ptr [esi + 010h]
    imul ebx
    mov dword ptr [edi + 010h], edx
    mov eax, dword ptr [esi + 014h]
    imul ebx
    mov dword ptr [edi + 014h], edx
    mov eax, dword ptr [esi + 018h]
    mov edx, dword ptr [esi + 01Ch]
    mov ebx, dword ptr [esi + 020h]
    sar eax, 1
    sar edx, 1
    sar ebx, 1
    mov dword ptr [edi + 018h], eax
    mov dword ptr [edi + 01Ch], edx
    mov dword ptr [edi + 020h], ebx
    mov eax, dword ptr [D_00142930]
    mov dword ptr [patch_155367], eax
    mov eax, 040000000h
    xor edx, edx
    xor ebx, ebx
    mov ecx, offset D_00154C85
    call func_0013758A
    add edx, 4
    sar edx, 3
    add ebx, 4
    sar ebx, 3
    mov dword ptr [patch_155110], eax
    mov dword ptr [patch_155120], edx
    mov dword ptr [patch_15512A], ebx
    xor eax, eax
    mov edx, 040000000h
    xor ebx, ebx
    mov ecx, offset D_00154C85
    call func_0013758A
    add edx, 4
    sar edx, 3
    add ebx, 4
    sar ebx, 3
    mov dword ptr [patch_15514C], eax
    mov dword ptr [patch_155163], edx
    mov dword ptr [patch_15516D], ebx
    ret
func_00155508:
    mov dword ptr [D_00120294], eax
    mov dword ptr [D_00120298], edx
    test byte ptr [D_000CEA98], 0FFh
    jne near ptr L_15560D
    test dword ptr [D_00154C48], 0FFFFFFFFh
    je near ptr L_15560D
    push ebx
    push ecx
    push edx
    push ebp
    push esi
    push edi
    mov ecx, dword ptr [D_00154C48]
    lea esi, [ecx*8 + D_00153C3C]
L_155543:
    push ecx
    push esi
    mov edi, dword ptr [esi + 4]
    mov eax, dword ptr [edi]
    mov edx, eax
    shr eax, 7
    and edx, 07Fh
    call func_00135DE4
    mov ebp, dword ptr [edi + 044h]
    mov esi, dword ptr [eax + 0Eh]
    add esi, eax
    and ebp, 0FFFFh
    movzx edx, word ptr [eax + 6]
    imul edx, ebp
    mov ebx, dword ptr [edi + 014h]
    movzx eax, word ptr [eax + 4]
    and ebx, 01Fh
    imul eax, ebp
    call dword ptr [ebx*4 + D_00153C00]
    test byte ptr [D_00158210], 0FFh
    jne short L_1555F8
    nop
    nop
    nop
    nop
    mov eax, dword ptr [D_00120294]
    mov ebp, dword ptr [D_00158EA8]
    sub eax, dword ptr [D_000CEA30]
    imul ebp
    idiv dword ptr [D_000CEA38]
    mov dword ptr [D_001202A0], eax
    cmp eax, dword ptr [D_00158EA0]
    jle short L_1555F8
    cmp eax, dword ptr [D_00158EB0]
    jge short L_1555F8
    mov eax, dword ptr [D_00120298]
    sub eax, dword ptr [D_000CEA34]
    imul ebp
    idiv dword ptr [D_000CEA40]
    mov dword ptr [D_001202A4], eax
    cmp eax, dword ptr [D_00158EA4]
    jle short L_1555F8
    cmp eax, dword ptr [D_00158EC4]
    jge short L_1555F8
    add ebp, 080h
    sar ebp, 8
    mov dword ptr [D_001202A8], ebp
    pop esi
    pop ecx
    mov eax, edi
    jmp short L_155606
L_1555F8:
    pop esi
    pop ecx
    sub esi, 8
    dec ecx
    jne near ptr L_155543
    xor eax, eax
L_155606:
    pop edi
    pop esi
    pop ebp
    pop edx
    pop ecx
    pop ebx
    ret
L_15560D:
    xor eax, eax
    ret
func_00155610:
    test dword ptr [esi + 04Ch], 0FFFFFFFFh
    jne near ptr L_15571E
    mov ebp, dword ptr [esi + 044h]
    mov edi, offset D_00136540
    shr ebp, 8
    mov ecx, dword ptr [D_0013690D]
    and ebp, 0FF00h
L_155634:
    add ebp, 0186A0h
patch_155636 equ L_155634+2   ; rewritten at run time
    cmp ebp, dword ptr [D_0013691D]
    jge near ptr L_1556EF
    test ecx, ecx
    je short L_1556A9
    cmp ecx, 020h
    jle short L_155654
    mov ecx, 020h
L_155654:
    cmp dword ptr [edi + 018h], 8
    je near ptr L_1556DB
    mov eax, dword ptr [edi]
    mov edx, dword ptr [edi + 4]
    mov ebx, dword ptr [edi + 8]
    sub eax, dword ptr [esi + 050h]
    sub edx, dword ptr [esi + 054h]
    sub ebx, dword ptr [esi + 058h]
    sar eax, 8
    sar edx, 8
    sar ebx, 8
    imul eax, eax
    imul edx, edx
    imul ebx, ebx
    add eax, edx
    add eax, ebx
    cmp eax, dword ptr [edi + 014h]
    jge short L_1556A3
    mov ebx, eax
    call func_0015F50C
    shl eax, 010h
    imul dword ptr [edi + 0Ch]
    idiv ebx
    add ebp, eax
    cmp ebp, dword ptr [D_0013691D]
    jge short L_1556EF
L_1556A3:
    add edi, 01Dh
    dec ecx
    jne short L_155654
L_1556A9:
    mov dword ptr [esi + 010h], ebp
    mov dword ptr [esi + 03Ch], offset func_00157800
    mov eax, dword ptr [esi + 058h]
    shr eax, 8
    sub eax, dword ptr [D_0014CC10]
    jle short L_1556DA
    imul eax, dword ptr [D_0014CC14]
    neg eax
    add eax, dword ptr [D_0014CC0C]
    mov dword ptr [esi + 03Ch], offset func_00157B20
    mov dword ptr [esi + 04Ch], eax
L_1556DA:
    ret
L_1556DB:
    mov eax, dword ptr [edi + 0Ch]
    shl eax, 8
    add ebp, eax
    cmp ebp, dword ptr [D_0013691D]
    jl near ptr L_155654
L_1556EF:
    mov dword ptr [esi + 03Ch], offset func_00157620
    mov eax, dword ptr [esi + 058h]
    shr eax, 8
    sub eax, dword ptr [D_0014CC10]
    jle short L_15571D
    imul eax, dword ptr [D_0014CC14]
    neg eax
    add eax, dword ptr [D_0014CC0C]
    mov dword ptr [esi + 03Ch], offset func_00157800
    mov dword ptr [esi + 010h], eax
L_15571D:
    ret
L_15571E:
    mov dword ptr [esi + 03Ch], offset func_00157E20
    ret
    db 218 dup (0)
XN_154D00 ends
end
