; XnGine module xn_14A300: FALL.EXE object 2, 0x14a300-0x14bb00.
; Generated by tools/xn_disasm.py; reassembles to the original (tools/xn_link.py).
; B_<address>_<length> lines are data bytes the build takes from your FALL.EXE.
.486p
.387
include xn_14A300.inc
extrn D_000C23D4:byte
extrn D_000C28BC:byte
extrn D_000C28DC:byte
extrn D_000C28E4:byte
extrn D_000C29B8:byte
extrn D_00147954:byte
extrn D_0014A100:byte
extrn D_0014A13C:byte
extrn D_0014A140:byte
extrn D_0014A144:byte
extrn D_0014A148:byte
extrn D_0014A16C:byte
extrn D_0014A190:byte
extrn D_0014A194:byte
extrn D_0014A198:byte
extrn D_0014A19C:byte
extrn D_0014A1A0:byte
extrn D_0014A1A4:byte
extrn D_0014A1A8:byte
extrn D_0014A1AC:byte
extrn D_0014A1B0:byte
extrn D_0014A1B4:byte
extrn D_0014A1B8:byte
extrn D_0014A1BC:byte
extrn D_0014A1C0:byte
extrn D_0014A1C4:byte
extrn D_0014A1C8:byte
extrn D_0014A1CC:byte
extrn D_0014A1F0:byte
extrn D_0014A1F4:byte
extrn D_0014A1F8:byte
extrn D_0014A1FC:byte
extrn D_0014A200:byte
extrn D_0014A204:byte
extrn D_0014A208:byte
extrn D_0014A20C:byte
extrn D_0014A210:byte
extrn D_0014A214:byte
extrn D_0014A218:byte
extrn D_0014A21C:byte
extrn D_0014A220:byte
extrn D_0014A224:byte
extrn D_0014A228:byte
extrn D_0014A22C:byte
extrn D_0014A230:byte
extrn D_0014A234:byte
extrn D_0014A238:byte
extrn D_0014A23C:byte
extrn D_0014A240:byte
extrn D_0014A244:byte
extrn D_0014A249:byte
extrn func_00135DE4:near
extrn func_00137000:near
extrn func_0013749E:near
extrn func_00137514:near
extrn func_0014BC34:near
extrn func_0014BD94:near
extrn func_0014BDF7:near
extrn func_0014C021:near
extrn func_0014C2AD:near
extrn func_0014C711:near
extrn func_0014C7E5:near
extrn func_0014C904:near
extrn func_0014CA44:near
extrn func_0014CAEA:near
extrn func_0015CB00:near
extrn func_0015CE7E:near
extrn func_0015D170:near
extrn func_0015D2EC:near
XN_14A300 segment byte public use32 'CODE'
    assume cs:XN_14A300, ds:XN_14A300, es:XN_14A300, ss:XN_14A300
func_0014A300:
    push esi
    push edi
    push ebp
    mov dword ptr [D_0014A190], eax
    mov dword ptr [D_0014A19C], edx
    mov dword ptr [D_0014A198], ebx
    mov dword ptr [D_0014A1BC], ecx
    mov esi, eax
    mov edi, dword ptr [D_0014A198]
    mov eax, dword ptr [esi + 020h]
    mov edx, dword ptr [esi + 024h]
    mov ebx, dword ptr [esi + 028h]
    mov esi, dword ptr [esi]
    mov ecx, dword ptr [esi + 0Ch]
    shr ecx, 8
    mov esi, dword ptr [D_0014A19C]
    call func_0014C904
    test eax, eax
    js near ptr L_14A686
    cmp dword ptr [D_0014A1BC], 2
    je near ptr L_14A678
    mov esi, dword ptr [D_0014A190]
    mov ecx, offset D_0014A148
    mov eax, dword ptr [esi + 02Ch]
    mov edx, dword ptr [esi + 030h]
    mov ebx, dword ptr [esi + 034h]
    call func_00137000
    mov edi, dword ptr [D_0014A198]
    mov esi, dword ptr [D_0014A190]
    mov eax, dword ptr [edi]
    mov edx, dword ptr [edi + 4]
    mov ebx, dword ptr [edi + 8]
    sub eax, dword ptr [esi + 020h]
    sub edx, dword ptr [esi + 024h]
    sub ebx, dword ptr [esi + 028h]
    shl eax, 8
    shl edx, 8
    shl ebx, 8
    mov ecx, offset D_0014A148
    call func_00137514
    mov dword ptr [D_0014A1A0], eax
    mov dword ptr [D_0014A1A4], edx
    mov dword ptr [D_0014A1A8], ebx
    mov edi, dword ptr [D_0014A19C]
    mov eax, dword ptr [edi]
    mov edx, dword ptr [edi + 4]
    mov ebx, dword ptr [edi + 8]
    sub eax, dword ptr [esi + 020h]
    sub edx, dword ptr [esi + 024h]
    sub ebx, dword ptr [esi + 028h]
    shl eax, 8
    shl edx, 8
    shl ebx, 8
    call func_00137514
    mov dword ptr [D_0014A1AC], eax
    mov dword ptr [D_0014A1B0], edx
    mov dword ptr [D_0014A1B4], ebx
    mov eax, dword ptr [D_0014A190]
    mov eax, dword ptr [eax]
    mov edx, dword ptr [eax + 030h]
    add edx, eax
    mov dword ptr [D_0014A68F], edx
    mov edx, dword ptr [eax + 034h]
    add edx, eax
    mov dword ptr [D_0014A693], edx
    mov dword ptr [D_0014A697], eax
    mov edx, dword ptr [D_00147954]
    add edx, 02000h
    mov dword ptr [D_0014A69F], edx
    add edx, 01000h
    mov dword ptr [D_0014A6A3], edx
    mov dword ptr [D_0014A6A7], 0
    mov edx, dword ptr [D_00147954]
    mov dword ptr [D_0014A6AB], edx
    mov dword ptr [edx], 0
    add edx, 4
    mov dword ptr [D_0014A6AF], edx
    mov esi, dword ptr [eax + 01Ch]
    add esi, eax
    mov ebp, dword ptr [eax + 020h]
    test ebp, ebp
    jle near ptr L_14A678
L_14A458:
    push esi
    mov eax, dword ptr [esi]
    mov edx, dword ptr [esi + 4]
    mov ebx, dword ptr [esi + 8]
    mov ecx, dword ptr [esi + 0Ch]
    mov esi, offset D_0014A1AC
    mov edi, offset D_0014A1A0
    call func_0014C7E5
    test eax, eax
    pop esi
    jns short L_14A48B
L_14A478:
    movzx edi, word ptr [esi + 010h]
    lea edi, [edi + edi*2]
    lea esi, [esi + edi*2 + 012h]
    dec ebp
    jne short L_14A458
    jmp near ptr L_14A558
L_14A48B:
    cmp dword ptr [D_0014A1BC], 1
    je near ptr L_14A678
    push esi
    push ebp
    mov edi, dword ptr [D_0014A69F]
    movzx ebp, word ptr [esi + 010h]
    mov edx, dword ptr [D_0014A6A7]
    mov dword ptr [D_0014A6A7], 0
    add esi, 012h
    mov ecx, dword ptr [D_0014A6A3]
    test edx, edx
    je short L_14A4E2
L_14A4C1:
    mov eax, dword ptr [edi]
    cmp eax, dword ptr [esi]
    jl short L_14A501
    je short L_14A516
    mov dword ptr [ecx], eax
    mov bx, word ptr [edi + 4]
    mov word ptr [ecx + 4], bx
    inc dword ptr [D_0014A6A7]
    add edi, 6
    add ecx, 6
    dec edx
    jne short L_14A4C1
L_14A4E2:
    test ebp, ebp
    je short L_14A53B
    mov ebx, dword ptr [esi]
    mov dword ptr [ecx], ebx
    mov bx, word ptr [esi + 4]
    mov word ptr [ecx + 4], bx
    inc dword ptr [D_0014A6A7]
    add esi, 6
    add ecx, 6
    dec ebp
    jmp short L_14A4E2
L_14A501:
    mov ebx, dword ptr [esi]
    mov dword ptr [ecx], ebx
    mov bx, word ptr [esi + 4]
    mov word ptr [ecx + 4], bx
    inc dword ptr [D_0014A6A7]
    add ecx, 6
L_14A516:
    add esi, 6
    dec ebp
    jne short L_14A4C1
L_14A51C:
    test edx, edx
    je short L_14A53B
    mov ebx, dword ptr [edi]
    mov dword ptr [ecx], ebx
    mov bx, word ptr [edi + 4]
    mov word ptr [ecx + 4], bx
    inc dword ptr [D_0014A6A7]
    add edi, 6
    add ecx, 6
    dec edx
    jmp short L_14A51C
L_14A53B:
    mov eax, dword ptr [D_0014A69F]
    mov ebx, dword ptr [D_0014A6A3]
    mov dword ptr [D_0014A69F], ebx
    mov dword ptr [D_0014A6A3], eax
    pop ebp
    pop esi
    jmp near ptr L_14A478
L_14A558:
    mov ebp, dword ptr [D_0014A6A7]
    test ebp, ebp
    je near ptr L_14A686
    mov ecx, dword ptr [D_0014A69F]
    mov esi, offset D_0014A1AC
    mov edi, offset D_0014A1A0
L_14A576:
    push ecx
    movzx ebx, word ptr [ecx + 4]
    mov edx, dword ptr [D_0014A697]
    lea ebx, [ebx + ebx*2]
    add edx, dword ptr [ecx]
    add ebx, dword ptr [D_0014A693]
    mov dword ptr [D_0014A69B], ebx
    mov ecx, dword ptr [edx + 8]
    mov edx, dword ptr [ebx + 4]
    add ecx, dword ptr [D_0014A68F]
    mov eax, dword ptr [ebx]
    mov ebx, dword ptr [ebx + 8]
    shl eax, 8
    shl edx, 8
    shl ebx, 8
    call func_0014C2AD
    mov dword ptr [D_0014A1B8], ecx
    test ecx, ecx
    pop ecx
    jns short L_14A5C7
L_14A5BC:
    add ecx, 6
    dec ebp
    jne short L_14A576
    jmp near ptr L_14A67C
L_14A5C7:
    push ecx
    push esi
    push edi
    mov edi, dword ptr [D_0014A69B]
    mov ecx, dword ptr [ecx]
    add ecx, dword ptr [D_0014A697]
    mov esi, dword ptr [D_0014A68F]
    push eax
    push edx
    push ebx
    call func_0015CB00
    test eax, eax
    pop ebx
    pop edx
    pop eax
    pop edi
    pop esi
    pop ecx
    js short L_14A5BC
    push esi
    push ecx
    mov esi, dword ptr [D_0014A6AF]
    mov ecx, offset D_0014A148
    call func_0013749E
    mov ecx, dword ptr [D_0014A190]
    add eax, 080h
    sar eax, 8
    add edx, 080h
    sar edx, 8
    add ebx, 080h
    sar ebx, 8
    add eax, dword ptr [ecx + 020h]
    add edx, dword ptr [ecx + 024h]
    add ebx, dword ptr [ecx + 028h]
    mov dword ptr [esi], eax
    mov dword ptr [esi + 4], edx
    mov dword ptr [esi + 8], ebx
    mov eax, dword ptr [D_0014A69B]
    mov ecx, offset D_0014A148
    mov edx, dword ptr [eax + 4]
    mov ebx, dword ptr [eax + 8]
    mov eax, dword ptr [eax]
    call func_0013749E
    mov dword ptr [esi + 010h], eax
    mov dword ptr [esi + 014h], edx
    mov dword ptr [esi + 018h], ebx
    pop ecx
    mov eax, dword ptr [ecx]
    mov dword ptr [esi + 0Ch], eax
    mov eax, dword ptr [D_0014A1B8]
    sar eax, 1
    mov word ptr [esi + 01Ch], ax
    mov eax, dword ptr [D_0014A6AB]
    add dword ptr [D_0014A6AF], 01Eh
    inc dword ptr [eax]
    pop esi
    jmp near ptr L_14A5BC
L_14A678:
    xor eax, eax
    jmp short L_14A68B
L_14A67C:
    mov eax, dword ptr [D_0014A6AB]
    cmp dword ptr [eax], 1
    jge short L_14A68B
L_14A686:
    mov eax, 0FFFFFFFFh
L_14A68B:
    pop ebp
    pop edi
    pop esi
    ret
D_0014A68F:
    db 4 dup (0)
D_0014A693:
    db 4 dup (0)
D_0014A697:
    db 4 dup (0)
D_0014A69B:
    db 4 dup (0)
D_0014A69F:
    db 4 dup (0)
D_0014A6A3:
    db 4 dup (0)
D_0014A6A7:
    db 4 dup (0)
D_0014A6AB:
    db 4 dup (0)
D_0014A6AF:
    B_14A6AF_17
func_0014A6C0:
    push ecx
    push esi
    push edi
    push ebp
    mov dword ptr [D_0014A190], eax
    mov dword ptr [D_0014A194], edx
    mov dword ptr [D_0014A1BC], ebx
    mov ebx, dword ptr [edx]
    mov edi, dword ptr [ebx + 0Ch]
    shr edi, 8
    lea esi, [edx + 020h]
    mov ebx, dword ptr [eax]
    mov ecx, dword ptr [ebx + 0Ch]
    shr ecx, 8
    mov ebx, dword ptr [eax + 028h]
    mov edx, dword ptr [eax + 024h]
    mov eax, dword ptr [eax + 020h]
    call func_0014CA44
    test eax, eax
    js near ptr L_14AA5C
    cmp dword ptr [D_0014A1BC], 2
    je near ptr L_14AA58
    jmp near ptr L_14AA58
func_0014A710:
    mov esi, dword ptr [D_0014A190]
    mov eax, dword ptr [esi + 02Ch]
    mov edx, dword ptr [esi + 030h]
    mov ebx, dword ptr [esi + 034h]
    mov ecx, offset D_0014A148
    call func_00137000
    mov eax, offset D_0014A148
    mov edx, offset D_0014A16C
    call func_0015D2EC
    mov esi, dword ptr [D_0014A190]
    mov edi, dword ptr [D_0014A194]
    mov eax, dword ptr [edi + 020h]
    sub eax, dword ptr [esi + 020h]
    mov edx, dword ptr [edi + 024h]
    sub edx, dword ptr [esi + 024h]
    mov ebx, dword ptr [edi + 028h]
    sub ebx, dword ptr [esi + 028h]
    shl eax, 8
    shl edx, 8
    shl ebx, 8
    mov ecx, offset D_0014A16C
    call func_0013749E
    mov dword ptr [D_0014A1A0], eax
    mov dword ptr [D_0014A1A4], edx
    mov dword ptr [D_0014A1A8], ebx
    neg eax
    neg edx
    neg ebx
    mov dword ptr [D_0014A1AC], eax
    mov dword ptr [D_0014A1B0], edx
    mov dword ptr [D_0014A1B4], ebx
    mov dword ptr [D_0014AA6E], 0
    mov eax, dword ptr [D_00147954]
    mov dword ptr [D_0014AA66], eax
    mov dword ptr [D_0014AA6A], eax
    mov esi, dword ptr [D_0014A194]
    mov esi, dword ptr [esi]
    mov edi, dword ptr [esi + 0Ch]
    mov esi, dword ptr [D_0014A190]
    mov esi, dword ptr [esi]
    mov ecx, dword ptr [esi + 01Ch]
    add ecx, esi
    mov ebp, dword ptr [esi + 020h]
    test ebp, ebp
    jle near ptr L_14AA58
    mov esi, offset D_0014A1A0
L_14A7D2:
    push ecx
    mov eax, dword ptr [ecx]
    mov edx, dword ptr [ecx + 4]
    mov ebx, dword ptr [ecx + 8]
    mov ecx, dword ptr [ecx + 0Ch]
    call func_0014CA44
    pop ecx
    test eax, eax
    jns short L_14A7F8
L_14A7E8:
    movzx eax, word ptr [ecx + 010h]
    lea eax, [eax + eax*2]
    lea ecx, [ecx + eax*2 + 012h]
    dec ebp
    jne short L_14A7D2
    jmp short L_14A80E
L_14A7F8:
    mov eax, dword ptr [D_0014AA6A]
    add dword ptr [D_0014AA6A], 4
    mov dword ptr [eax], ecx
    inc dword ptr [D_0014AA6E]
    jmp short L_14A7E8
L_14A80E:
    cmp dword ptr [D_0014AA6E], 0
    je near ptr L_14AA5C
    mov dword ptr [D_0014AA7A], 0
    mov eax, dword ptr [D_00147954]
    add eax, 01000h
    mov dword ptr [D_0014AA72], eax
    mov dword ptr [D_0014AA76], eax
    mov esi, dword ptr [D_0014A190]
    mov esi, dword ptr [esi]
    mov edi, dword ptr [esi + 0Ch]
    mov esi, dword ptr [D_0014A194]
    mov esi, dword ptr [esi]
    mov ecx, dword ptr [esi + 01Ch]
    add ecx, esi
    mov ebp, dword ptr [esi + 020h]
    test ebp, ebp
    jle near ptr L_14AA58
    mov esi, offset D_0014A1AC
L_14A861:
    push ecx
    mov eax, dword ptr [ecx]
    mov edx, dword ptr [ecx + 4]
    mov ebx, dword ptr [ecx + 8]
    mov ecx, dword ptr [ecx + 0Ch]
    call func_0014CA44
    pop ecx
    test eax, eax
    jns short L_14A887
L_14A877:
    movzx eax, word ptr [ecx + 010h]
    lea eax, [eax + eax*2]
    lea ecx, [ecx + eax*2 + 012h]
    dec ebp
    jne short L_14A861
    jmp short L_14A89D
L_14A887:
    mov eax, dword ptr [D_0014AA76]
    add dword ptr [D_0014AA76], 4
    mov dword ptr [eax], ecx
    inc dword ptr [D_0014AA7A]
    jmp short L_14A877
L_14A89D:
    cmp dword ptr [D_0014AA7A], 0
    je near ptr L_14AA5C
    mov esi, dword ptr [D_0014A194]
    mov eax, dword ptr [esi + 02Ch]
    mov edx, dword ptr [esi + 030h]
    mov ebx, dword ptr [esi + 034h]
    mov ecx, offset D_0014A100
    call func_00137000
    mov esi, offset D_0014A16C
    mov edi, offset D_0014A100
    mov ebx, offset D_0014A1CC
    mov edx, 3
    mov ecx, edx
    mov eax, edx
    mov ebp, 01Ch
    call func_0015D170
    mov dword ptr [D_0014AA7E], 0
    mov eax, dword ptr [D_00147954]
    add eax, 02000h
    mov dword ptr [D_0014AA82], eax
    mov dword ptr [D_0014AA86], eax
    mov edx, dword ptr [D_0014AA66]
    mov ebx, dword ptr [D_0014AA6E]
L_14A90F:
    push edx
    push ebx
    mov esi, dword ptr [edx]
    mov eax, dword ptr [D_0014AA72]
    mov ebp, dword ptr [D_0014AA7A]
L_14A91E:
    mov edi, dword ptr [eax]
    push eax
    mov eax, dword ptr [edi]
    mov edx, dword ptr [edi + 4]
    mov ebx, dword ptr [edi + 8]
    mov ecx, offset D_0014A1CC
    call func_0013749E
    add eax, dword ptr [D_0014A1A0]
    add edx, dword ptr [D_0014A1A4]
    add ebx, dword ptr [D_0014A1A8]
    mov ecx, dword ptr [edi + 0Ch]
    mov edi, dword ptr [esi + 0Ch]
    call func_0014CA44
    test eax, eax
    pop eax
    jns short L_14A965
L_14A955:
    add eax, 4
    dec ebp
    jne short L_14A91E
    pop ebx
    pop edx
    add edx, 4
    dec ebx
    jne short L_14A90F
    jmp short L_14A98E
L_14A965:
    cmp dword ptr [D_0014A1BC], 1
    je near ptr L_14AA56
    mov edx, dword ptr [D_0014AA86]
    mov ebx, dword ptr [eax]
    mov dword ptr [edx + 4], ebx
    mov dword ptr [edx], esi
    add dword ptr [D_0014AA86], 8
    inc dword ptr [D_0014AA7E]
    jmp short L_14A955
L_14A98E:
    cmp dword ptr [D_0014AA7E], 0
    je near ptr L_14AA5C
    mov eax, dword ptr [D_0014A190]
    mov eax, dword ptr [eax]
    mov dword ptr [D_0014AA8A], eax
    mov edx, dword ptr [eax + 034h]
    add edx, eax
    mov dword ptr [D_0014AA8E], edx
    mov esi, dword ptr [D_0014AA82]
    mov ebp, dword ptr [D_0014AA7E]
L_14A9BE:
    push esi
    push ebp
    mov edi, dword ptr [esi + 4]
    mov ecx, offset D_0014A1CC
    mov eax, dword ptr [edi]
    mov edx, dword ptr [edi + 4]
    mov ebx, dword ptr [edi + 8]
    call func_0013749E
    add eax, dword ptr [D_0014A1A0]
    add edx, dword ptr [D_0014A1A4]
    add ebx, dword ptr [D_0014A1A8]
    mov dword ptr [D_0014A1C0], eax
    mov dword ptr [D_0014A1C4], edx
    mov dword ptr [D_0014A1C8], ebx
    mov edi, dword ptr [edi + 0Ch]
    mov ecx, dword ptr [esi]
    movzx ebp, word ptr [ecx + 010h]
    lea ecx, [ecx + 012h]
    mov esi, offset D_0014A1C0
L_14AA09:
    push ecx
    movzx eax, word ptr [ecx + 4]
    mov ecx, dword ptr [ecx]
    add ecx, 8
    lea eax, [eax + eax*2]
    add eax, dword ptr [D_0014AA8E]
    add ecx, dword ptr [D_0014AA8A]
    mov ebx, dword ptr [eax + 8]
    mov edx, dword ptr [eax + 4]
    mov eax, dword ptr [eax]
    shl eax, 8
    shl edx, 8
    shl ebx, 8
    call func_0014C711
    test eax, eax
    js short L_14AA41
    pop eax
    pop eax
    pop eax
    jmp short L_14AA58
L_14AA41:
    pop ecx
    add ecx, 6
    dec ebp
    jne short L_14AA09
    pop ebp
    pop esi
    add esi, 8
    dec ebp
    jne near ptr L_14A9BE
    jmp short L_14AA5C
L_14AA56:
    pop eax
    pop eax
L_14AA58:
    xor eax, eax
    jmp short L_14AA61
L_14AA5C:
    mov eax, 0FFFFFFFFh
L_14AA61:
    pop ebp
    pop edi
    pop esi
    pop ecx
    ret
D_0014AA66:
    db 4 dup (0)
D_0014AA6A:
    db 4 dup (0)
D_0014AA6E:
    db 4 dup (0)
D_0014AA72:
    db 4 dup (0)
D_0014AA76:
    db 4 dup (0)
D_0014AA7A:
    db 4 dup (0)
D_0014AA7E:
    db 4 dup (0)
D_0014AA82:
    db 4 dup (0)
D_0014AA86:
    db 4 dup (0)
D_0014AA8A:
    db 4 dup (0)
D_0014AA8E:
    db 4 dup (0)
func_0014AA92:
    push ecx
    push esi
    push edi
    push ebp
    mov dword ptr [D_0014A190], eax
    mov dword ptr [D_0014A194], edx
    mov dword ptr [D_0014A1BC], ebx
    movzx ebp, word ptr [edx + 018h]
    test ebp, ebp
    je near ptr L_14AF02
    mov ecx, dword ptr [edx]
    mov edi, dword ptr [edx + 4]
    mov ebx, dword ptr [edx + 8]
    mov dword ptr [D_0014A1C0], ecx
    mov dword ptr [D_0014A1C4], edi
    mov dword ptr [D_0014A1C8], ebx
    add edx, 01Ah
    mov esi, dword ptr [eax]
    xor ecx, ecx
    mov edi, dword ptr [esi + 0Ch]
    lea esi, [eax + 020h]
    shr edi, 8
    mov ebx, dword ptr [D_00147954]
    add ebx, 01000h
L_14AAE9:
    push edx
    push ebx
    push ecx
    mov ecx, dword ptr [edx + 0Ch]
    mov eax, dword ptr [edx]
    mov ebx, dword ptr [edx + 8]
    mov edx, dword ptr [edx + 4]
    add eax, dword ptr [D_0014A1C0]
    add edx, dword ptr [D_0014A1C4]
    add ebx, dword ptr [D_0014A1C8]
    call func_0014CA44
    pop ecx
    pop ebx
    pop edx
    test eax, eax
    js short L_14AB28
    cmp dword ptr [D_0014A1BC], 2
    je near ptr L_14AEF4
    mov dword ptr [ebx], edx
    add ebx, 4
    inc ecx
L_14AB28:
    add edx, 010h
    dec ebp
    jne short L_14AAE9
    test ecx, ecx
    jle near ptr L_14AF02
    mov dword ptr [D_0014AF2C], ecx
    mov esi, dword ptr [D_0014A190]
    mov eax, dword ptr [esi + 02Ch]
    mov edx, dword ptr [esi + 030h]
    mov ebx, dword ptr [esi + 034h]
    mov ecx, offset D_0014A148
    call func_00137000
    mov eax, offset D_0014A148
    mov edx, offset D_0014A16C
    call func_0015D2EC
    mov esi, dword ptr [D_0014A190]
    mov edi, dword ptr [D_0014A194]
    mov eax, dword ptr [edi]
    sub eax, dword ptr [esi + 020h]
    mov edx, dword ptr [edi + 4]
    sub edx, dword ptr [esi + 024h]
    mov ebx, dword ptr [edi + 8]
    sub ebx, dword ptr [esi + 028h]
    shl eax, 8
    shl edx, 8
    shl ebx, 8
    mov ecx, offset D_0014A16C
    call func_0013749E
    mov dword ptr [D_0014A1A0], eax
    mov dword ptr [D_0014A1A4], edx
    mov dword ptr [D_0014A1A8], ebx
    mov esi, dword ptr [D_0014A194]
    mov eax, dword ptr [esi + 0Ch]
    mov edx, dword ptr [esi + 010h]
    mov ebx, dword ptr [esi + 014h]
    mov ecx, offset D_0014A100
    call func_00137000
    mov esi, offset D_0014A16C
    mov edi, offset D_0014A100
    mov ebx, offset D_0014A1CC
    mov edx, 3
    mov ecx, edx
    mov eax, edx
    mov ebp, 01Ch
    call func_0015D170
    mov esi, dword ptr [D_00147954]
    add esi, 01000h
    lea edi, [esi + 0400h]
    mov ebp, dword ptr [D_0014AF2C]
L_14ABF8:
    push esi
    mov esi, dword ptr [esi]
    mov eax, dword ptr [esi]
    mov edx, dword ptr [esi + 4]
    mov ebx, dword ptr [esi + 8]
    shl eax, 8
    shl edx, 8
    shl ebx, 8
    mov ecx, offset D_0014A1CC
    call func_0013749E
    add eax, dword ptr [D_0014A1A0]
    add edx, dword ptr [D_0014A1A4]
    add ebx, dword ptr [D_0014A1A8]
    mov dword ptr [edi], eax
    mov dword ptr [edi + 4], edx
    mov dword ptr [edi + 8], ebx
    mov eax, dword ptr [esi + 0Ch]
    shl eax, 8
    mov dword ptr [edi + 0Ch], eax
    add edi, 010h
    pop esi
    add esi, 4
    dec ebp
    jne short L_14ABF8
    mov eax, dword ptr [D_0014A190]
    mov eax, dword ptr [eax]
    mov edx, dword ptr [eax + 030h]
    add edx, eax
    mov dword ptr [D_0014AF0C], edx
    mov edx, dword ptr [eax + 034h]
    add edx, eax
    mov dword ptr [D_0014AF10], edx
    mov dword ptr [D_0014AF14], eax
    mov edx, dword ptr [D_00147954]
    add edx, 02000h
    mov dword ptr [D_0014AF20], edx
    add edx, 01000h
    mov dword ptr [D_0014AF24], edx
    mov dword ptr [D_0014AF28], 0
    mov edx, dword ptr [D_00147954]
    mov dword ptr [D_0014AF18], edx
    mov dword ptr [edx], 0
    add edx, 4
    mov dword ptr [D_0014AF1C], edx
    mov esi, dword ptr [eax + 01Ch]
    add esi, eax
    mov ebp, dword ptr [eax + 020h]
    test ebp, ebp
    jle near ptr L_14AEF4
L_14ACB8:
    mov edi, dword ptr [esi + 0Ch]
    mov ecx, dword ptr [D_00147954]
    add ecx, 01400h
    mov edx, dword ptr [D_0014AF2C]
L_14ACCD:
    push edx
    push ecx
    mov eax, dword ptr [ecx]
    mov edx, dword ptr [ecx + 4]
    mov ebx, dword ptr [ecx + 8]
    mov ecx, dword ptr [ecx + 0Ch]
    call func_0014CA44
    test eax, eax
    pop ecx
    pop edx
    jns short L_14ACFE
    add ecx, 010h
    dec edx
    jne short L_14ACCD
L_14ACEB:
    movzx edi, word ptr [esi + 010h]
    lea edi, [edi + edi*2]
    lea esi, [esi + edi*2 + 012h]
    dec ebp
    jne short L_14ACB8
    jmp near ptr L_14ADCD
L_14ACFE:
    cmp dword ptr [D_0014A1BC], 1
    je near ptr L_14AEF2
    push esi
    push edi
    push ebp
    mov edi, dword ptr [D_0014AF20]
    movzx ebp, word ptr [esi + 010h]
    mov edx, dword ptr [D_0014AF28]
    mov dword ptr [D_0014AF28], 0
    add esi, 012h
    mov ecx, dword ptr [D_0014AF24]
    test edx, edx
    je short L_14AD56
L_14AD35:
    mov eax, dword ptr [edi]
    cmp eax, dword ptr [esi]
    jl short L_14AD75
    je short L_14AD8A
    mov dword ptr [ecx], eax
    mov bx, word ptr [edi + 4]
    mov word ptr [ecx + 4], bx
    inc dword ptr [D_0014AF28]
    add edi, 6
    add ecx, 6
    dec edx
    jne short L_14AD35
L_14AD56:
    test ebp, ebp
    je short L_14ADAF
    mov ebx, dword ptr [esi]
    mov dword ptr [ecx], ebx
    mov bx, word ptr [esi + 4]
    mov word ptr [ecx + 4], bx
    inc dword ptr [D_0014AF28]
    add esi, 6
    add ecx, 6
    dec ebp
    jmp short L_14AD56
L_14AD75:
    mov ebx, dword ptr [esi]
    mov dword ptr [ecx], ebx
    mov bx, word ptr [esi + 4]
    mov word ptr [ecx + 4], bx
    inc dword ptr [D_0014AF28]
    add ecx, 6
L_14AD8A:
    add esi, 6
    dec ebp
    jne short L_14AD35
L_14AD90:
    test edx, edx
    je short L_14ADAF
    mov ebx, dword ptr [edi]
    mov dword ptr [ecx], ebx
    mov bx, word ptr [edi + 4]
    mov word ptr [ecx + 4], bx
    inc dword ptr [D_0014AF28]
    add edi, 6
    add ecx, 6
    dec edx
    jmp short L_14AD90
L_14ADAF:
    mov eax, dword ptr [D_0014AF20]
    mov ebx, dword ptr [D_0014AF24]
    mov dword ptr [D_0014AF20], ebx
    mov dword ptr [D_0014AF24], eax
    pop ebp
    pop edi
    pop esi
    jmp near ptr L_14ACEB
L_14ADCD:
    mov ebp, dword ptr [D_0014AF28]
    test ebp, ebp
    je near ptr L_14AF02
    mov edi, dword ptr [D_0014AF20]
L_14ADE1:
    push ebp
    mov edx, dword ptr [D_0014AF14]
    add edx, dword ptr [edi]
    mov ecx, dword ptr [edx + 8]
    add ecx, dword ptr [D_0014AF0C]
    movzx ebx, word ptr [edi + 4]
    lea ebx, [ebx + ebx*2]
    add ebx, dword ptr [D_0014AF10]
    mov eax, dword ptr [ebx]
    mov edx, dword ptr [ebx + 4]
    mov ebx, dword ptr [ebx + 8]
    shl eax, 8
    shl edx, 8
    shl ebx, 8
    mov esi, dword ptr [D_00147954]
    add esi, 01400h
    mov ebp, dword ptr [D_0014AF2C]
L_14AE23:
    push eax
    push edx
    push ebx
    push esi
    push edi
    mov edi, dword ptr [esi + 0Ch]
    call func_0014C711
    test eax, eax
    pop edi
    pop esi
    jns short L_14AE4B
L_14AE36:
    pop ebx
    pop edx
    pop eax
    add esi, 010h
    dec ebp
    jne short L_14AE23
L_14AE3F:
    pop ebp
    add edi, 6
    dec ebp
    jne short L_14ADE1
    jmp near ptr L_14AEF8
L_14AE4B:
    push ecx
    push edi
    push esi
    mov eax, dword ptr [esi]
    mov edx, dword ptr [esi + 4]
    mov ebx, dword ptr [esi + 8]
    mov ecx, dword ptr [D_0014AF14]
    add ecx, dword ptr [edi]
    movzx edi, word ptr [edi + 4]
    lea edi, [edi + edi*2]
    add edi, dword ptr [D_0014AF10]
    mov esi, dword ptr [D_0014AF0C]
    call func_0015CB00
    test eax, eax
    jns short L_14AE9D
    pop esi
    push esi
    push ecx
    mov eax, dword ptr [esi]
    mov edx, dword ptr [esi + 4]
    mov ebx, dword ptr [esi + 8]
    mov edi, dword ptr [esi + 0Ch]
    mov esi, dword ptr [D_0014AF0C]
    call func_0015CE7E
    test eax, eax
    pop ecx
    jns short L_14AE9D
    pop esi
    pop edi
    pop ecx
    jmp short L_14AE36
L_14AE9D:
    pop esi
    pop edi
    mov ecx, dword ptr [D_0014AF1C]
    mov eax, dword ptr [edi]
    mov dword ptr [ecx + 0Ch], eax
    mov word ptr [ecx + 01Ch], 0FFFFh
    movzx ebx, word ptr [edi + 4]
    lea ebx, [ebx + ebx*2]
    add ebx, dword ptr [D_0014AF10]
    mov eax, dword ptr [ebx]
    mov edx, dword ptr [ebx + 4]
    mov ebx, dword ptr [ebx + 8]
    push ecx
    mov ecx, offset D_0014A148
    call func_0013749E
    pop ecx
    mov dword ptr [ecx + 010h], eax
    mov dword ptr [ecx + 014h], edx
    mov dword ptr [ecx + 018h], ebx
    add dword ptr [D_0014AF1C], 01Eh
    mov ecx, dword ptr [D_0014AF18]
    inc dword ptr [ecx]
    pop ecx
    pop ebx
    pop edx
    pop eax
    jmp near ptr L_14AE3F
L_14AEF2:
    pop eax
    pop eax
L_14AEF4:
    xor eax, eax
    jmp short L_14AF07
L_14AEF8:
    mov eax, dword ptr [D_0014AF18]
    cmp dword ptr [eax], 1
    jge short L_14AF07
L_14AF02:
    mov eax, 0FFFFFFFFh
L_14AF07:
    pop ebp
    pop edi
    pop esi
    pop ecx
    ret
D_0014AF0C:
    db 4 dup (0)
D_0014AF10:
    db 4 dup (0)
D_0014AF14:
    db 4 dup (0)
D_0014AF18:
    db 4 dup (0)
D_0014AF1C:
    db 4 dup (0)
D_0014AF20:
    db 4 dup (0)
D_0014AF24:
    db 4 dup (0)
D_0014AF28:
    db 4 dup (0)
D_0014AF2C:
    db 4 dup (0)
func_0014AF30:
    push ecx
    push esi
    push edi
    push ebp
    mov dword ptr [D_0014A190], eax
    mov dword ptr [D_0014A19C], edx
    mov dword ptr [D_0014A198], ebx
    mov esi, dword ptr [D_0014A190]
    mov ecx, offset D_0014A148
    mov eax, dword ptr [esi + 0Ch]
    mov edx, dword ptr [esi + 010h]
    mov ebx, dword ptr [esi + 014h]
    call func_00137000
    mov eax, offset D_0014A148
    mov edx, offset D_0014A16C
    call func_0015D2EC
    mov edi, dword ptr [D_0014A198]
    mov esi, dword ptr [D_0014A190]
    mov eax, dword ptr [edi]
    sub eax, dword ptr [esi]
    mov edx, dword ptr [edi + 4]
    sub edx, dword ptr [esi + 4]
    mov ebx, dword ptr [edi + 8]
    sub ebx, dword ptr [esi + 8]
    mov ecx, offset D_0014A16C
    call func_0013749E
    mov dword ptr [D_0014A1A0], eax
    mov dword ptr [D_0014A1A4], edx
    mov dword ptr [D_0014A1A8], ebx
    mov edi, dword ptr [D_0014A19C]
    mov eax, dword ptr [edi]
    sub eax, dword ptr [esi]
    mov edx, dword ptr [edi + 4]
    sub edx, dword ptr [esi + 4]
    mov ebx, dword ptr [edi + 8]
    sub ebx, dword ptr [esi + 8]
    call func_0013749E
    mov dword ptr [D_0014A1AC], eax
    mov dword ptr [D_0014A1B0], edx
    mov dword ptr [D_0014A1B4], ebx
    mov ecx, dword ptr [D_0014A190]
    movzx ebp, word ptr [ecx + 018h]
    test ebp, ebp
    jle short L_14B00D
    add ecx, 01Ah
L_14AFE1:
    push ecx
    mov eax, dword ptr [ecx]
    mov edx, dword ptr [ecx + 4]
    mov ebx, dword ptr [ecx + 8]
    mov ecx, dword ptr [ecx + 0Ch]
    mov esi, offset D_0014A1AC
    mov edi, offset D_0014A1A0
    call func_0014C904
    pop ecx
    test eax, eax
    jns short L_14B009
    add ecx, 010h
    dec ebp
    jne short L_14AFE1
    jmp short L_14B00D
L_14B009:
    xor eax, eax
    jmp short L_14B012
L_14B00D:
    mov eax, 0FFFFFFFFh
L_14B012:
    pop ebp
    pop edi
    pop esi
    pop ecx
    ret
func_0014B017:
    push ebx
    push ecx
    push esi
    push edi
    push ebp
    mov dword ptr [D_0014A190], eax
    mov dword ptr [D_0014A194], edx
    mov esi, dword ptr [D_0014A190]
    mov eax, dword ptr [esi + 0Ch]
    mov edx, dword ptr [esi + 010h]
    mov ebx, dword ptr [esi + 014h]
    mov ecx, offset D_0014A148
    call func_00137000
    mov eax, offset D_0014A148
    mov edx, offset D_0014A16C
    call func_0015D2EC
    mov esi, dword ptr [D_0014A190]
    mov edi, dword ptr [D_0014A194]
    mov eax, dword ptr [edi]
    sub eax, dword ptr [esi]
    mov edx, dword ptr [edi + 4]
    sub edx, dword ptr [esi + 4]
    mov ebx, dword ptr [edi + 8]
    sub ebx, dword ptr [esi + 8]
    shl eax, 8
    shl edx, 8
    shl ebx, 8
    mov ecx, offset D_0014A16C
    call func_0013749E
    mov dword ptr [D_0014A1A0], eax
    mov dword ptr [D_0014A1A4], edx
    mov dword ptr [D_0014A1A8], ebx
    mov esi, dword ptr [D_0014A194]
    mov eax, dword ptr [esi + 0Ch]
    mov edx, dword ptr [esi + 010h]
    mov ebx, dword ptr [esi + 014h]
    mov ecx, offset D_0014A100
    call func_00137000
    mov esi, offset D_0014A16C
    mov edi, offset D_0014A100
    mov ebx, offset D_0014A1CC
    mov edx, 3
    mov ecx, edx
    mov eax, edx
    mov ebp, 01Ch
    call func_0015D170
    mov edx, dword ptr [D_00147954]
    mov dword ptr [D_0014B193], edx
    mov dword ptr [edx], 0
    add edx, 4
    mov dword ptr [D_0014B197], edx
    mov esi, dword ptr [D_0014A190]
    movzx ebp, word ptr [esi + 018h]
    add esi, 01Ah
L_14B0F2:
    mov edi, dword ptr [esi + 0Ch]
    mov ebx, dword ptr [D_0014A194]
    movzx edx, word ptr [ebx + 018h]
    add ebx, 01Ah
L_14B102:
    push edx
    push ebx
    push dword ptr [ebx + 0Ch]
    mov eax, dword ptr [ebx]
    mov edx, dword ptr [ebx + 4]
    mov ebx, dword ptr [ebx + 8]
    mov ecx, offset D_0014A1CC
    call func_0013749E
    add eax, dword ptr [D_0014A1A0]
    add edx, dword ptr [D_0014A1A4]
    add ebx, dword ptr [D_0014A1A8]
    pop ecx
    call func_0014CA44
    pop ebx
    pop edx
    test eax, eax
    js short L_14B16E
    mov eax, dword ptr [D_0014B197]
    add dword ptr [D_0014B197], 01Eh
    push edx
    push ebp
    mov ecx, dword ptr [D_0014A194]
    neg edx
    add dx, word ptr [ecx + 018h]
    mov ecx, dword ptr [D_0014A190]
    neg ebp
    add bp, word ptr [ecx + 018h]
    mov word ptr [eax + 0Ch], bp
    mov word ptr [eax + 0Eh], dx
    pop ebp
    pop edx
    mov eax, dword ptr [D_0014B193]
    inc dword ptr [eax]
L_14B16E:
    add ebx, 010h
    dec edx
    jne short L_14B102
    add esi, 010h
    dec ebp
    jne near ptr L_14B0F2
    mov eax, dword ptr [D_0014B193]
    cmp dword ptr [eax], 0
    jg short L_14B18D
    mov eax, 0FFFFFFFFh
L_14B18D:
    pop ebp
    pop edi
    pop esi
    pop ecx
    pop ebx
    ret
D_0014B193:
    db 4 dup (0)
D_0014B197:
    db 4 dup (0)
func_0014B19B:
    push ebp
    mov ebp, esp
    push esi
    push edi
    mov esi, dword ptr [ebp + 0Ch]
    mov edi, dword ptr [ebp + 8]
    call func_0014B1B1
    pop edi
    pop esi
    pop ebp
    ret 8
func_0014B1B1:
    mov eax, 0FFFFFFFFh
    ret
func_0014B1B7:
    call func_0014C711
    call func_0015CB00
    call func_0015CE7E
    ret
func_0014B1C7:
    push ebp
    mov ebp, esp
    push esi
    push edi
    mov esi, dword ptr [ebp + 8]
    mov edi, dword ptr [ebp + 0Ch]
    mov ebp, dword ptr [ebp + 010h]
    call func_0014B1E0
    pop edi
    pop esi
    pop ebp
    ret 0Ch
func_0014B1E0:
    mov dword ptr [D_0014A190], eax
    mov dword ptr [D_0014A19C], edx
    mov dword ptr [D_0014A198], ebx
    mov dword ptr [D_0014A1BC], ebp
    mov eax, ecx
    mov edx, eax
    and edx, 07Fh
    shr eax, 7
    xor ebx, ebx
    call func_00135DE4
    mov ecx, eax
    movzx eax, word ptr [ecx + 6]
    movzx edx, word ptr [ecx + 4]
    imul eax, edi
    imul edx, edi
    sar eax, 8
    sar edx, 8
    mov dword ptr [D_0014B453], eax
    mov dword ptr [D_0014B457], edx
    xor ebx, ebx
    sar eax, 1
    sar edx, 1
    call func_0014BD94
    mov ecx, eax
    sar ecx, 3
    add ecx, eax
    push ecx
    shr esi, 1
    and esi, 0Fh
    mov cl, byte ptr [esi*2 + D_0014A249]
    mov edx, dword ptr [D_0014B453]
    sar edx, cl
    mov ecx, dword ptr [D_0014B453]
    sar ecx, 1
    sub edx, ecx
    xor eax, eax
    xor ebx, ebx
    mov dword ptr [D_0014A1C0], eax
    mov dword ptr [D_0014A1C4], edx
    mov dword ptr [D_0014A1C8], ebx
    pop ecx
    mov esi, dword ptr [D_0014A190]
    mov edi, dword ptr [D_0014A198]
    add eax, dword ptr [esi]
    add edx, dword ptr [esi + 4]
    add ebx, dword ptr [esi + 8]
    mov esi, dword ptr [D_0014A19C]
    call func_0014C904
    test eax, eax
    js near ptr L_14B44D
    cmp dword ptr [D_0014A1BC], 2
    je near ptr L_14B449
    mov ecx, dword ptr [D_0014A190]
    mov esi, dword ptr [D_0014A19C]
    mov edi, dword ptr [D_0014A198]
    mov eax, dword ptr [esi]
    mov edx, dword ptr [esi + 4]
    mov ebx, dword ptr [esi + 8]
    sub eax, dword ptr [ecx]
    sub edx, dword ptr [ecx + 4]
    sub ebx, dword ptr [ecx + 8]
    sub eax, dword ptr [D_0014A1C0]
    sub edx, dword ptr [D_0014A1C4]
    sub ebx, dword ptr [D_0014A1C8]
    shl eax, 8
    shl edx, 8
    shl ebx, 8
    mov dword ptr [D_0014A1AC], eax
    mov dword ptr [D_0014A1B0], edx
    mov dword ptr [D_0014A1B4], ebx
    mov eax, dword ptr [edi]
    mov edx, dword ptr [edi + 4]
    mov ebx, dword ptr [edi + 8]
    sub eax, dword ptr [ecx]
    sub edx, dword ptr [ecx + 4]
    sub ebx, dword ptr [ecx + 8]
    sub eax, dword ptr [D_0014A1C0]
    sub edx, dword ptr [D_0014A1C4]
    sub ebx, dword ptr [D_0014A1C8]
    shl eax, 8
    shl edx, 8
    shl ebx, 8
    mov dword ptr [D_0014A1A0], eax
    mov dword ptr [D_0014A1A4], edx
    mov dword ptr [D_0014A1A8], ebx
    sub eax, dword ptr [D_0014A1AC]
    xor edx, edx
    sub ebx, dword ptr [D_0014A1B4]
    call func_0014BDF7
    mov dword ptr [D_0014A13C], eax
    mov dword ptr [D_0014A140], edx
    mov dword ptr [D_0014A144], ebx
    mov ecx, offset D_0014A1C0
    mov esi, offset D_0014A1AC
    mov edi, offset D_0014A1A0
    call func_0014C2AD
    test ecx, ecx
    js near ptr L_14B44D
    mov dword ptr [D_0014A1B8], ecx
    mov ecx, offset D_0014A1C0
    mov esi, dword ptr [D_0014B457]
    shl esi, 8
    mov edi, dword ptr [D_0014B453]
    shl edi, 8
    push eax
    push edx
    call func_0014CAEA
    test eax, eax
    pop edx
    pop eax
    js near ptr L_14B44D
    cmp dword ptr [D_0014A1BC], 1
    je short L_14B3A5
L_14B3A5:
    mov esi, dword ptr [D_00147954]
    mov dword ptr [esi], 1
    add esi, 4
    mov edi, dword ptr [D_0014A190]
    add eax, 080h
    sar eax, 8
    add edx, 080h
    sar edx, 8
    add ebx, 080h
    sar ebx, 8
    add eax, dword ptr [edi]
    add edx, dword ptr [edi + 4]
    add ebx, dword ptr [edi + 8]
    add eax, dword ptr [D_0014A1C0]
    add edx, dword ptr [D_0014A1C4]
    add ebx, dword ptr [D_0014A1C8]
    mov dword ptr [esi], eax
    mov dword ptr [esi + 4], edx
    mov dword ptr [esi + 8], ebx
    mov eax, dword ptr [D_0014A13C]
    mov edx, dword ptr [D_0014A140]
    mov ebx, dword ptr [D_0014A144]
    add eax, 080h
    sar eax, 8
    add edx, 080h
    sar edx, 8
    add ebx, 080h
    sar ebx, 8
    add eax, dword ptr [edi]
    add edx, dword ptr [edi + 4]
    add ebx, dword ptr [edi + 8]
    mov dword ptr [esi + 010h], eax
    mov dword ptr [esi + 014h], edx
    mov dword ptr [esi + 018h], ebx
    mov dword ptr [esi + 0Ch], 0FFFFFFFFh
    mov eax, dword ptr [D_0014A1B8]
    sar eax, 1
    mov word ptr [esi + 01Ch], ax
    lea eax, [esi - 4]
    jmp short L_14B452
L_14B449:
    xor eax, eax
    jmp short L_14B452
L_14B44D:
    mov eax, 0FFFFFFFFh
L_14B452:
    ret
D_0014B453:
    db 4 dup (0)
D_0014B457:
    db 4 dup (0)
func_0014B45B:
    push ebx
    push ecx
    push ebp
    push esi
    push edi
    mov dword ptr [D_000C28DC], eax
    shr eax, 8
    and eax, 0FFh
    neg edx
    add edx, dword ptr [D_000C23D4]
    mov dword ptr [D_000C28E4], edx
    and edx, 0FF00h
    add edx, eax
    mov ebp, dword ptr [D_000C28BC]
    mov bl, byte ptr [edx + ebp]
    and ebx, 07Fh
    mov edi, offset D_0014A100
    mov ebx, dword ptr [ebx*4 + D_000C29B8]
    shl ebx, 8
    mov dword ptr [edi + 4], ebx
    mov eax, dword ptr [D_000C28E4]
    and eax, 0FFh
    mov ebx, dword ptr [D_000C28DC]
    and ebx, 0FFh
    sub eax, ebx
    jle short L_14B507
    inc dh
    mov bl, byte ptr [edx + ebp]
    and ebx, 07Fh
    mov ebx, dword ptr [ebx*4 + D_000C29B8]
    shl ebx, 8
    inc dl
    mov dword ptr [edi + 010h], ebx
    mov bl, byte ptr [edx + ebp]
    and ebx, 07Fh
    mov ebx, dword ptr [ebx*4 + D_000C29B8]
    shl ebx, 8
    mov dword ptr [edi + 01Ch], ebx
    xor eax, eax
    xor edx, edx
    mov dword ptr [edi], eax
    mov dword ptr [edi + 0Ch], eax
    mov dword ptr [edi + 8], edx
    add eax, 010000h
    mov dword ptr [edi + 018h], eax
    add edx, 010000h
    mov dword ptr [edi + 014h], edx
    mov dword ptr [edi + 020h], edx
    jmp short L_14B551
L_14B507:
    inc dl
    mov bl, byte ptr [edx + ebp]
    and ebx, 07Fh
    mov ebx, dword ptr [ebx*4 + D_000C29B8]
    shl ebx, 8
    inc dh
    mov dword ptr [edi + 01Ch], ebx
    mov bl, byte ptr [edx + ebp]
    and ebx, 07Fh
    mov ebx, dword ptr [ebx*4 + D_000C29B8]
    shl ebx, 8
    mov dword ptr [edi + 010h], ebx
    xor eax, eax
    xor edx, edx
    mov dword ptr [edi], eax
    mov dword ptr [edi + 8], edx
    mov dword ptr [edi + 020h], edx
    add eax, 010000h
    mov dword ptr [edi + 0Ch], eax
    mov dword ptr [edi + 018h], eax
    add edx, 010000h
    mov dword ptr [edi + 014h], edx
L_14B551:
    mov eax, offset D_0014A100
    mov edx, dword ptr [D_000C28DC]
    mov ebx, dword ptr [D_000C28E4]
    and edx, 0FFh
    and ebx, 0FFh
    shl edx, 8
    shl ebx, 8
    call func_0014C021
    add eax, 080h
    sar eax, 8
    neg eax
    mov edx, offset D_0014A100
    pop edi
    pop esi
    pop ebp
    pop ecx
    pop ebx
    ret
func_0014B58E:
    push ecx
    push esi
    push edi
    push ebp
    mov dword ptr [D_0014A190], eax
    mov edi, eax
    mov dword ptr [D_0014A1F4], edx
    mov dword ptr [D_0014A22C], ebx
    mov edx, dword ptr [eax + 030h]
    add edx, eax
    mov dword ptr [D_0014BA7D], edx
    mov edx, dword ptr [eax + 034h]
    add edx, eax
    mov dword ptr [D_0014BA81], edx
    mov edx, dword ptr [eax + 8]
    mov dword ptr [D_0014BA8D], edx
    mov ecx, dword ptr [eax + 4]
    add eax, dword ptr [eax + 03Ch]
    mov dword ptr [D_0014BA85], eax
    mov dword ptr [D_0014BA89], 0
    mov dword ptr [D_0014A230], 0800000h
    mov dword ptr [D_0014A234], 0800000h
    mov dword ptr [D_0014A238], 0800000h
    mov dword ptr [D_0014A23C], 0FF800000h
    mov dword ptr [D_0014A240], 0FF800000h
    mov dword ptr [D_0014A244], 0FF800000h
    mov esi, dword ptr [D_0014BA7D]
L_14B61B:
    mov eax, dword ptr [esi]
    cmp eax, dword ptr [D_0014A230]
    jge short L_14B62A
    mov dword ptr [D_0014A230], eax
L_14B62A:
    cmp eax, dword ptr [D_0014A23C]
    jle short L_14B637
    mov dword ptr [D_0014A23C], eax
L_14B637:
    mov eax, dword ptr [esi + 4]
    cmp eax, dword ptr [D_0014A234]
    jge short L_14B647
    mov dword ptr [D_0014A234], eax
L_14B647:
    cmp eax, dword ptr [D_0014A240]
    jle short L_14B654
    mov dword ptr [D_0014A240], eax
L_14B654:
    mov eax, dword ptr [esi + 8]
    cmp eax, dword ptr [D_0014A238]
    jge short L_14B664
    mov dword ptr [D_0014A238], eax
L_14B664:
    cmp eax, dword ptr [D_0014A244]
    jle short L_14B671
    mov dword ptr [D_0014A244], eax
L_14B671:
    add esi, 0Ch
    dec ecx
    jne short L_14B61B
    mov eax, 016A0Ah
    imul dword ptr [D_0014A1F4]
    add eax, 08000h
    adc edx, 0
    shrd eax, edx, 010h
    mov dword ptr [D_0014A1F0], eax
    mov eax, dword ptr [D_0014A1F4]
    mov edx, 0133h
    imul edx
    add eax, 080h
    adc edx, 0
    shrd eax, edx, 8
    mov dword ptr [D_0014A1F4], eax
    mov eax, dword ptr [D_0014A23C]
    sub eax, dword ptr [D_0014A230]
    cdq
    idiv dword ptr [D_0014A1F0]
    inc eax
    mov dword ptr [D_0014A1F8], eax
    mov eax, dword ptr [D_0014A240]
    sub eax, dword ptr [D_0014A234]
    cdq
    idiv dword ptr [D_0014A1F0]
    inc eax
    mov dword ptr [D_0014A1FC], eax
    mov eax, dword ptr [D_0014A244]
    sub eax, dword ptr [D_0014A238]
    cdq
    idiv dword ptr [D_0014A1F0]
    inc eax
    mov dword ptr [D_0014A200], eax
    imul eax, dword ptr [D_0014A1F8]
    imul eax, dword ptr [D_0014A1FC]
    mov esi, eax
    shl esi, 2
    cmp esi, 010000h
    jge near ptr L_14BA76
    mov esi, dword ptr [D_00147954]
    mov dword ptr [D_0014A21C], esi
L_14B723:
    mov dword ptr [esi], 0
    add esi, 4
    dec eax
    jne short L_14B723
    mov dword ptr [D_0014BA91], esi
    mov eax, dword ptr [D_0014A23C]
    sub eax, dword ptr [D_0014A230]
    xor edx, edx
    idiv dword ptr [D_0014A1F8]
    sar eax, 1
    add eax, dword ptr [D_0014A230]
    mov dword ptr [D_0014A204], eax
    mov dword ptr [D_0014A210], eax
    mov eax, dword ptr [D_0014A240]
    sub eax, dword ptr [D_0014A234]
    xor edx, edx
    idiv dword ptr [D_0014A1FC]
    sar eax, 1
    add eax, dword ptr [D_0014A234]
    mov dword ptr [D_0014A208], eax
    mov dword ptr [D_0014A214], eax
    mov eax, dword ptr [D_0014A244]
    sub eax, dword ptr [D_0014A238]
    xor edx, edx
    idiv dword ptr [D_0014A200]
    sar eax, 1
    add eax, dword ptr [D_0014A238]
    mov dword ptr [D_0014A20C], eax
    mov dword ptr [D_0014A218], eax
L_14B7A4:
    mov edi, dword ptr [D_0014BA85]
    mov ecx, dword ptr [D_0014BA7D]
    add ecx, dword ptr [edi + 8]
    mov edi, dword ptr [D_0014BA81]
    mov eax, dword ptr [edi]
    mov edx, dword ptr [edi + 4]
    mov ebx, dword ptr [edi + 8]
    shl eax, 8
    shl edx, 8
    shl ebx, 8
    mov esi, offset D_0014A210
    mov edi, dword ptr [D_0014A1F4]
    mov ebp, dword ptr [D_0014A200]
    mov dword ptr [D_0014A228], ebp
L_14B7E1:
    mov ebp, dword ptr [D_0014A1FC]
    mov dword ptr [D_0014A224], ebp
L_14B7ED:
    mov ebp, dword ptr [D_0014A1F8]
    mov dword ptr [D_0014A220], ebp
L_14B7F9:
    push eax
    push edx
    push ebx
    call func_0014C711
    test eax, eax
    js near ptr L_14B8E9
    push ecx
    push esi
    push edi
    mov ecx, edx
    mov eax, edx
    imul eax
    mov ebx, eax
    mov ebp, edx
    mov eax, dword ptr [D_0014A1F4]
    imul eax
    sub eax, ebx
    db 01Bh, 0D5h   ; sbb edx, ebp
    call func_0014BC34
    mov ebp, eax
    neg ecx
    mov edi, dword ptr [D_0014BA81]
    mov eax, dword ptr [edi]
    imul eax, ecx
    add eax, 080h
    sar eax, 8
    mov edx, dword ptr [edi + 4]
    imul edx, ecx
    add edx, 080h
    sar edx, 8
    mov ebx, dword ptr [edi + 8]
    imul ebx, ecx
    add ebx, 080h
    sar ebx, 8
    add eax, dword ptr [esi]
    add edx, dword ptr [esi + 4]
    add ebx, dword ptr [esi + 8]
    mov ecx, dword ptr [D_0014BA85]
    mov esi, dword ptr [D_0014BA7D]
    mov edi, dword ptr [D_0014BA81]
    push eax
    push edx
    push ebx
    push esi
    call func_0015CB00
    test eax, eax
    pop esi
    pop ebx
    pop edx
    pop eax
    jns short L_14B896
    mov edi, ebp
    call func_0015CE7E
    test eax, eax
    jns short L_14B896
    pop edi
    pop esi
    pop ecx
    jmp short L_14B8E9
L_14B896:
    pop edi
    pop esi
    pop ecx
    mov eax, dword ptr [D_0014A21C]
    mov ebx, dword ptr [eax]
    mov edx, dword ptr [D_0014BA91]
    mov dword ptr [eax], edx
    mov dword ptr [edx], ebx
    mov ebx, dword ptr [D_0014BA85]
    sub ebx, dword ptr [D_0014A190]
    mov dword ptr [edx + 4], ebx
    mov ebx, dword ptr [D_0014BA89]
    shl ebx, 2
    mov dword ptr [edx + 8], ebx
    add dword ptr [D_0014BA91], 0Ch
    push edx
    mov edx, dword ptr [D_0014BA91]
    add edx, 0Ch
    sub edx, dword ptr [D_00147954]
    cmp edx, 010000h
    pop edx
    jge near ptr L_14BA73
L_14B8E9:
    pop ebx
    pop edx
    pop eax
    mov ebp, dword ptr [D_0014A1F0]
    add dword ptr [D_0014A21C], 4
    add dword ptr [D_0014A210], ebp
    dec dword ptr [D_0014A220]
    jne near ptr L_14B7F9
    mov ebp, dword ptr [D_0014A204]
    mov dword ptr [D_0014A210], ebp
    mov ebp, dword ptr [D_0014A1F0]
    add dword ptr [D_0014A214], ebp
    dec dword ptr [D_0014A224]
    jne near ptr L_14B7ED
    mov ebp, dword ptr [D_0014A208]
    mov dword ptr [D_0014A214], ebp
    mov ebp, dword ptr [D_0014A1F0]
    add dword ptr [D_0014A218], ebp
    dec dword ptr [D_0014A228]
    jne near ptr L_14B7E1
    mov ebp, dword ptr [D_0014A20C]
    mov dword ptr [D_0014A218], ebp
    mov eax, dword ptr [D_00147954]
    mov dword ptr [D_0014A21C], eax
    add dword ptr [D_0014BA81], 0Ch
    mov eax, dword ptr [D_0014BA85]
    movzx eax, byte ptr [eax]
    shl eax, 3
    add eax, 8
    add dword ptr [D_0014BA85], eax
    inc dword ptr [D_0014BA89]
    dec dword ptr [D_0014BA8D]
    jne near ptr L_14B7A4
    mov edi, dword ptr [D_0014A21C]
    mov esi, dword ptr [D_0014A22C]
    xor ecx, ecx
    mov ebp, dword ptr [D_0014A200]
    mov dword ptr [D_0014A228], ebp
L_14B9B0:
    mov ebp, dword ptr [D_0014A1FC]
    mov dword ptr [D_0014A224], ebp
L_14B9BC:
    mov ebp, dword ptr [D_0014A1F8]
    mov dword ptr [D_0014A220], ebp
L_14B9C8:
    mov eax, dword ptr [edi]
    test eax, eax
    je short L_14BA15
    inc ecx
    mov edx, dword ptr [D_0014A210]
    mov dword ptr [esi], edx
    mov edx, dword ptr [D_0014A214]
    mov dword ptr [esi + 4], edx
    mov edx, dword ptr [D_0014A218]
    mov dword ptr [esi + 8], edx
    mov edx, dword ptr [D_0014A1F4]
    mov dword ptr [esi + 0Ch], edx
    push esi
    add esi, 012h
    xor dx, dx
L_14B9F9:
    mov ebp, dword ptr [eax + 4]
    mov dword ptr [esi], ebp
    mov ebp, dword ptr [eax + 8]
    mov word ptr [esi + 4], bp
    add esi, 6
    inc dx
    mov eax, dword ptr [eax]
    test eax, eax
    jne short L_14B9F9
    pop eax
    mov word ptr [eax + 010h], dx
L_14BA15:
    mov ebp, dword ptr [D_0014A1F0]
    add edi, 4
    add dword ptr [D_0014A210], ebp
    dec dword ptr [D_0014A220]
    jne short L_14B9C8
    mov eax, dword ptr [D_0014A204]
    mov dword ptr [D_0014A210], eax
    add dword ptr [D_0014A214], ebp
    dec dword ptr [D_0014A224]
    jne near ptr L_14B9BC
    mov eax, dword ptr [D_0014A208]
    mov dword ptr [D_0014A214], eax
    add dword ptr [D_0014A218], ebp
    dec dword ptr [D_0014A228]
    jne near ptr L_14B9B0
    sub esi, dword ptr [D_0014A22C]
    mov eax, esi
    mov edx, ecx
L_14BA6E:
    pop ebp
    pop edi
    pop esi
    pop ecx
    ret
L_14BA73:
    pop eax
    pop eax
    pop eax
L_14BA76:
    mov eax, 0FFFFFFFFh
    jmp short L_14BA6E
D_0014BA7D:
    db 4 dup (0)
D_0014BA81:
    db 4 dup (0)
D_0014BA85:
    db 4 dup (0)
D_0014BA89:
    db 4 dup (0)
D_0014BA8D:
    db 4 dup (0)
D_0014BA91:
    db 111 dup (0)
XN_14A300 ends
end
