; XnGine module xn_132F00: FALL.EXE object 2, 0x132f00-0x135d00.
; Generated by tools/xn_disasm.py; reassembles to the original (tools/xn_link.py).
; B_<address>_<length> lines are data bytes the build takes from your FALL.EXE.
.486p
.387
include xn_132F00.inc
public D_00132F00
public D_00132F16
public D_00132F3B
public D_00132F58
public D_00132F5C
public D_00132F60
public D_00132F64
public D_00132F6C
public D_00133F6C
public D_0013436C
public D_00134374
public D_00134375
public D_00134376
public D_00134378
public D_001343B9
public D_001343C0
public D_001343C4
public D_001343C8
public D_001343D0
public D_001343DC
public D_001343E0
public D_001343E4
public D_001343F0
public D_001343FA
public D_00134BFA
public D_00134BFE
public D_00134C02
public D_00134C06
public D_00135402
XN_132F00 segment byte public use32 'CODE'
    assume cs:XN_132F00, ds:XN_132F00, es:XN_132F00, ss:XN_132F00
D_00132F00:
    B_132F00_22
D_00132F16:
    B_132F16_37
D_00132F3B:
    B_132F3B_29
D_00132F58:
    db 4 dup (0)
D_00132F5C:
    db 4 dup (0)
D_00132F60:
    db 4 dup (0)
D_00132F64:
    db 8 dup (0)
D_00132F6C:
    db 4096 dup (0)
D_00133F6C:
    db 1024 dup (0)
D_0013436C:
    B_13436C_8
D_00134374:
    B_134374_1
D_00134375:
    B_134375_1
D_00134376:
    B_134376_2
D_00134378:
    db 65 dup (0)
D_001343B9:
    db 7 dup (0)
D_001343C0:
    db 2 dup (0)
D_001343C2:
    db 2 dup (0)
D_001343C4:
    db 4 dup (0)
D_001343C8:
    db 8 dup (0)
D_001343D0:
    db 12 dup (0)
D_001343DC:
    db 4 dup (0)
D_001343E0:
    db 4 dup (0)
D_001343E4:
    db 12 dup (0)
D_001343F0:
    db 10 dup (0)
D_001343FA:
    db 2048 dup (0)
D_00134BFA:
    db 4 dup (0)
D_00134BFE:
    db 4 dup (0)
D_00134C02:
    db 4 dup (0)
D_00134C06:
    db 2044 dup (0)
D_00135402:
    B_135402_2046
    db 256 dup (0)
XN_132F00 ends
end
