; XnGine module xn_153400: FALL.EXE object 2, 0x153400-0x153500.
; Generated by tools/xn_disasm.py; reassembles to the original (tools/xn_link.py).
; B_<address>_<length> lines are data bytes the build takes from your FALL.EXE.
.486p
.387
include xn_153400.inc
public D_00153400
public D_00153404
public D_00153408
public D_00153409
public D_0015340D
public D_00153411
public D_00153415
public D_00153419
public D_00153425
public D_00153431
public D_0015343D
public D_00153461
public D_00153465
public D_00153469
public D_0015346D
extrn D_00160E00:byte
extrn D_00160E44:byte
extrn D_00160E45:byte
extrn D_00160E57:byte
extrn D_00160E64:byte
extrn D_00160EAC:byte
extrn D_00161000:byte
extrn D_00161084:byte
extrn D_00161094:byte
extrn D_001610B4:byte
extrn D_001610C4:byte
extrn D_0016116C:byte
extrn D_00161400:byte
extrn D_001614D0:byte
extrn D_001614E4:byte
extrn D_001614E8:byte
extrn D_001614EC:byte
extrn D_001614F0:byte
XN_153400 segment byte public use32 'CODE'
    assume cs:XN_153400, ds:XN_153400, es:XN_153400, ss:XN_153400
D_00153400:
    db 4 dup (0)
D_00153404:
    B_153404_4
D_00153408:
    db 1 dup (0)
D_00153409:
    db 4 dup (0)
D_0015340D:
    db 4 dup (0)
D_00153411:
    db 4 dup (0)
D_00153415:
    db 4 dup (0)
D_00153419:
    dd D_00160E00
    dd D_00161000
    dd D_00161400
D_00153425:
    dd D_00160E44
    dd D_00161084
    dd D_001614D0
D_00153431:
    dd D_00160EAC
    dd D_0016116C
    dd D_001614F0
D_0015343D:
    dd D_00160E64
    dd D_001610C4
    dd D_001614E8
    dd D_00160E45
    dd D_00161094
    dd D_001614E4
    dd D_00160E57
    dd D_001610B4
    dd D_001614EC
D_00153461:
    db 4 dup (0)
D_00153465:
    db 4 dup (0)
D_00153469:
    db 4 dup (0)
D_0015346D:
    db 147 dup (0)
XN_153400 ends
end
