; XnGine module xn_12AB00: FALL.EXE object 2, 0x12ab00-0x12ac00.
; Generated by tools/xn_disasm.py; reassembles to the original (tools/xn_link.py).
; B_<address>_<length> lines are data bytes the build takes from your FALL.EXE.
.486p
.487
JUMPS
include xn_12AB00.inc
XN_12AB00 segment byte public use32 'CODE'
    assume cs:XN_12AB00, ds:XN_12AB00, es:XN_12AB00, ss:XN_12AB00
extrn D_0012AA04:byte
extrn D_0012AA08:byte
extrn D_0012AA0C:byte
    B_12AB00_10
    dd D_0012AA0C
    B_12AB0E_57
    dd D_0012AA08
    B_12AB4B_42
    dd D_0012AA08
    B_12AB79_3
    dd D_0012AA08
    B_12AB80_1
    dd D_0012AA0C
    B_12AB85_5
    dd D_0012AA04
    B_12AB8E_11
    db 103 dup (0)
XN_12AB00 ends
end
