; XnGine module xn_15D100: FALL.EXE object 2, 0x15d100-0x15f600.
; Generated by tools/xn_disasm.py; reassembles to the original (tools/xn_link.py).
; B_<address>_<length> lines are data bytes the build takes from your FALL.EXE.
.486p
.387
include xngine.inc
include xn_15D100.inc
public D_0015DC00
public func_0015D170
public func_0015D288
public func_0015D2EC
public func_0015E400
public func_0015F50C
extrn D_0012B508:byte
extrn D_00142930:byte
extrn D_00142940:byte
extrn D_00142944:byte
extrn D_00142948:byte
extrn D_0014294C:byte
extrn D_00142950:byte
extrn D_00143550:byte
extrn D_00149980:byte
extrn func_0015310C:near
extrn func_00153188:near
XN_15D100 segment byte public use32 'CODE'
    assume cs:XN_15D100, ds:XN_15D100, es:XN_15D100, ss:XN_15D100
func_0015D100:
    mov dword ptr [D_0015D165], ecx
    shl dword ptr [D_0015D165], 2
    mov dword ptr [D_0015D169], eax
    shl dword ptr [D_0015D169], 2
L_15D119:
    push edi
    push ebx
    push eax
L_15D11C:
    call func_0015D141
    add edi, 4
    add ebx, 4
    sub eax, 1
    jne short L_15D11C
    pop eax
    pop ebx
    pop edi
    add esi, dword ptr [D_0015D165]
    add ebx, dword ptr [D_0015D169]
    sub edx, 1
    jne short L_15D119
    ret
func_0015D141:
    push eax
    push ecx
    push edx
    push edi
    push esi
    xor@ edx, edx
L_15D148:
    mov eax, dword ptr [esi]
    imul eax, dword ptr [edi]
    add@ edx, eax
    add esi, 4
    add edi, dword ptr [D_0015D169]
    sub ecx, 1
    jne short L_15D148
    mov dword ptr [ebx], edx
    pop esi
    pop edi
    pop edx
    pop ecx
    pop eax
    ret
D_0015D165:
    db 4 dup (0)
D_0015D169:
    B_15D169_7
func_0015D170:
    mov dword ptr [D_0015D1E9], ecx
    shl dword ptr [D_0015D1E9], 2
    mov dword ptr [D_0015D1ED], eax
    shl dword ptr [D_0015D1ED], 2
    mov dword ptr [D_0015D1F1], ebp
L_15D18F:
    push edi
    push ebx
    push eax
L_15D192:
    call func_0015D1B7
    add edi, 4
    add ebx, 4
    sub eax, 1
    jne short L_15D192
    pop eax
    pop ebx
    pop edi
    add esi, dword ptr [D_0015D1E9]
    add ebx, dword ptr [D_0015D1ED]
    sub edx, 1
    jne short L_15D18F
    ret
func_0015D1B7:
    push eax
    push ecx
    push edx
    push edi
    push esi
    push ebp
    push ebx
    xor@ ebx, ebx
    xor@ ebp, ebp
L_15D1C2:
    mov eax, dword ptr [esi]
    imul dword ptr [edi]
    add@ ebp, eax
    adc@ ebx, edx
    add esi, 4
    add edi, dword ptr [D_0015D1ED]
    dec ecx
    jne short L_15D1C2
    mov ecx, dword ptr [D_0015D1F1]
    shrd ebp, ebx, cl
    pop ebx
    mov dword ptr [ebx], ebp
    pop ebp
    pop esi
    pop edi
    pop edx
    pop ecx
    pop eax
    ret
D_0015D1E9:
    db 4 dup (0)
D_0015D1ED:
    db 4 dup (0)
D_0015D1F1:
    B_15D1F1_7
func_0015D1F8:
    mov dword ptr [D_0015D27C], ecx
    shl dword ptr [D_0015D27C], 3
    mov dword ptr [D_0015D280], eax
    shl dword ptr [D_0015D280], 3
    mov word ptr [D_0015D284], bp
L_15D218:
    push edi
    push ebx
    push eax
L_15D21B:
    call func_0015D240
    add edi, 8
    add ebx, 8
    sub eax, 1
    jne short L_15D21B
    pop eax
    pop ebx
    pop edi
    add esi, dword ptr [D_0015D27C]
    add ebx, dword ptr [D_0015D280]
    sub edx, 1
    jne short L_15D218
    ret
func_0015D240:
    push eax
    push ecx
    push edx
    push edi
    push esi
    push ebp
    push ebx
    xor@ ebx, ebx
    xor@ ebp, ebp
L_15D24B:
    mov eax, dword ptr [esi]
    imul dword ptr [edi]
    add@ ebp, eax
    adc@ ebx, edx
    add esi, 8
    add edi, dword ptr [D_0015D280]
    sub ecx, 1
    jne short L_15D24B
    mov cx, word ptr [D_0015D284]
    shrd ebp, ebx, cl
    sar ebx, cl
    mov@ ecx, ebx
    pop ebx
    mov dword ptr [ebx + 4], ecx
    mov dword ptr [ebx], ebp
    pop ebp
    pop esi
    pop edi
    pop edx
    pop ecx
    pop eax
    ret
D_0015D27C:
    db 4 dup (0)
D_0015D280:
    db 4 dup (0)
D_0015D284:
    B_15D284_4
func_0015D288:
    push ecx
    mov@ ecx, edx
    mov edx, 1
    shl edx, cl
    mov@ ecx, ebx
    imul ecx, ebx
L_15D297:
    mov dword ptr [eax], edx
    add eax, 4
    dec ecx
    je short L_15D2B0
    push ebx
L_15D2A0:
    mov dword ptr [eax], 0
    add eax, 4
    dec ecx
    dec ebx
    jne short L_15D2A0
    pop ebx
    jmp short L_15D297
L_15D2B0:
    pop ecx
    ret
    B_15D2B2_2
func_0015D2B4:
    push ecx
    mov@ ecx, edx
    mov edx, 1
    shl edx, cl
    mov@ ecx, ebx
    imul ecx, ebx
L_15D2C3:
    mov dword ptr [eax], edx
    mov dword ptr [eax + 4], 0
    add eax, 8
    dec ecx
    je short L_15D2EA
    push ebx
L_15D2D3:
    mov dword ptr [eax], 0
    mov dword ptr [eax + 4], 0
    add eax, 8
    dec ecx
    dec ebx
    jne short L_15D2D3
    pop ebx
    jmp short L_15D2C3
L_15D2EA:
    pop ecx
    ret
func_0015D2EC:
    push ecx
    push esi
    push edi
    mov@ esi, eax
    mov@ edi, edx
    mov ecx, 9
    rep movsd
    mov eax, dword ptr [edx + 4]
    xchg dword ptr [edx + 0Ch], eax
    mov dword ptr [edx + 4], eax
    mov eax, dword ptr [edx + 8]
    xchg dword ptr [edx + 018h], eax
    mov dword ptr [edx + 8], eax
    mov eax, dword ptr [edx + 014h]
    xchg dword ptr [edx + 01Ch], eax
    mov dword ptr [edx + 014h], eax
    pop edi
    pop esi
    pop ecx
    ret
    db 232 dup (0)
    B_15D401_2047
D_0015DC00:
    db 8 dup (0)
    B_15DC08_2040
func_0015E400:
    cmp eax, dword ptr [D_00142948]
    jge short L_15E459
    cmp ebx, dword ptr [D_00142940]
    jle short L_15E459
    cmp edx, dword ptr [D_0014294C]
    jge short L_15E459
    cmp ecx, dword ptr [D_00142944]
    jle short L_15E459
    cmp eax, dword ptr [D_00142940]
    jge short L_15E42D
    mov eax, dword ptr [D_00142940]
L_15E42D:
    cmp ebx, dword ptr [D_00142948]
    jle short L_15E43B
    mov ebx, dword ptr [D_00142948]
L_15E43B:
    cmp edx, dword ptr [D_00142944]
    jge short L_15E449
    mov edx, dword ptr [D_00142944]
L_15E449:
    cmp ecx, dword ptr [D_0014294C]
    jle short L_15E457
    mov ecx, dword ptr [D_0014294C]
L_15E457:
    clc
    ret
L_15E459:
    stc
    ret
    B_15E45B_1
func_0015E45C:
    push ebp
    push edi
    cmp@ eax, ebx
    jle short L_15E463
    xchg ebx, eax
L_15E463:
    cmp@ edx, ecx
    jle short L_15E469
    xchg ecx, edx
L_15E469:
    call func_0015E400
    jb short L_15E4A1
    push eax
    push ebx
    push ecx
    push edx
    call func_0015310C
    pop edx
    pop ecx
    pop ebx
    pop eax
    push eax
    push ebx
    push ecx
    push edx
    mov@ edx, ecx
    call func_0015310C
    pop edx
    pop ecx
    pop ebx
    pop eax
    push eax
    push ebx
    push ecx
    push edx
    call func_00153188
    pop edx
    pop ecx
    pop ebx
    pop eax
    mov@ eax, ebx
    dec eax
    call func_00153188
L_15E4A1:
    pop edi
    pop ebp
    ret
func_0015E4A4:
    push ebp
    push edi
    cmp@ eax, ebx
    jle short L_15E4AB
    xchg ebx, eax
L_15E4AB:
    cmp@ edx, ecx
    jle short L_15E4B1
    xchg ecx, edx
L_15E4B1:
    call func_0015E400
    jb short L_15E4F6
    mov edi, dword ptr [edx*4 + D_00142950]
    add edi, dword ptr [D_00143550]
    add@ edi, eax
    sub@ ebx, eax
    sub@ ecx, edx
    mov@ edx, ecx
    movzx eax, byte ptr [D_0012B508]
    mov ebp, dword ptr [D_00142930]
    mov eax, dword ptr [eax*4 + D_00149980]
    sub@ ebp, ebx
L_15E4E3:
    mov@ ecx, ebx
    shr ecx, 2
    rep stosd
    mov@ ecx, ebx
    and ecx, 3
    rep stosb
    add@ edi, ebp
    dec edx
    jne short L_15E4E3
L_15E4F6:
    pop edi
    pop ebp
    ret
    db 7 dup (0)
D_0015E500:
    B_15E500_4108
func_0015F50C:
    push ebx
    push ecx
    push edx
    or@ eax, eax
    je short L_15F54F
    mov@ ebx, eax
    xor@ dl, dl
    bsr ecx, ebx
    cmp ecx, 0Ch
    jb short L_15F52F
    sub ecx, 0Bh
    mov@ dl, cl
    shr dl, 1
    adc cl, 0
    mov@ dl, cl
    shr dl, 1
    shr ebx, cl
L_15F52F:
    bsf ecx, ebx
    test ecx, 1
    setne al
    sub@ cl, al
    shr ebx, cl
    shr cl, 1
    movzx eax, byte ptr [ebx + D_0015E500]
    add@ cl, dl
    shl eax, cl
    shr eax, 2
L_15F54F:
    pop edx
    pop ecx
    pop ebx
    ret
    db 173 dup (0)
XN_15D100 ends
end
