; XnGine module xn_155800: FALL.EXE object 2, 0x155800-0x155b00.
; Generated by tools/xn_disasm.py; reassembles to the original (tools/xn_link.py).
; B_<address>_<length> lines are data bytes the build takes from your FALL.EXE.
.486p
.387
include xn_155800.inc
public D_00155800
public D_00155820
public D_00155920
public D_00155944
public D_00155996
public D_0015599B
public D_00155A4B
extrn D_00120AC0:byte
extrn D_00147980:byte
extrn D_00149980:byte
XN_155800 segment byte public use32 'CODE'
    assume cs:XN_155800, ds:XN_155800, es:XN_155800, ss:XN_155800
D_00155800:
    B_155800_32
D_00155820:
    B_155820_6
    dd D_00155800
    B_15582A_12
    dd D_00149980
    B_15583A_38
D_00155860:
    B_155860_32
D_00155880:
    B_155880_145
D_00155911:
    B_155911_15
D_00155920:
    B_155920_12
    dd D_00155984
    B_155930_15
    dd D_00120AC0
    B_155943_1
D_00155944:
    B_155944_13
    dd D_00155911
    B_155955_20
    dd D_001559B9
    B_15596D_4
    dd D_00155A21
    B_155975_2
    dd D_00155A21
    B_15597B_3
    dd D_00155A21
    B_155982_2
D_00155984:
    B_155984_18
D_00155996:
    B_155996_5
D_0015599B:
    B_15599B_12
    dd D_00155911
    B_1559AB_2
    dd D_00155911
    B_1559B1_8
D_001559B9:
    B_1559B9_104
D_00155A21:
    B_155A21_19
    dd D_00120AC0
    B_155A38_19
D_00155A4B:
    B_155A4B_11
    dd D_00155911
    B_155A5A_12
    dd D_00147980
    B_155A6A_4
    dd D_00155860
    B_155A72_5
    dd D_00155880
    B_155A7B_8
    dd D_00155880
    B_155A87_2
    db 119 dup (0)
XN_155800 ends
end
