; XnGine module xn_CE300: FALL.EXE object 2, 0xce300-0xcea00.
; Generated by tools/xn_disasm.py; reassembles to the original (tools/xn_link.py).
; B_<address>_<length> lines are data bytes the build takes from your FALL.EXE.
.486p
.487
JUMPS
include xn_CE300.inc
XN_CE300 segment byte public use32 'CODE'
    assume cs:XN_CE300, ds:XN_CE300, es:XN_CE300, ss:XN_CE300
extrn D_000CDE00:byte
extrn D_000CDE06:byte
extrn D_000CDE0A:byte
extrn D_000CDE0E:byte
extrn D_000CDE12:byte
extrn D_000CDE2F:byte
extrn D_000CDE33:byte
extrn D_000CDE37:byte
extrn D_000CDE3B:byte
extrn D_000CDE3F:byte
extrn D_000CDE43:byte
extrn D_000CDE47:byte
extrn D_000CDE4B:byte
extrn D_000CDE4F:byte
extrn D_0012AA04:byte
extrn D_0012B508:byte
extrn D_00142306:byte
extrn D_00142307:byte
extrn D_00142950:byte
extrn D_00143550:byte
extrn D_00150200:byte
extrn D_00150A00:byte
extrn D_00195B00:byte
extrn func_00050069:near
func_000CE300:
    push ecx
L_0CE301:
    mov cl, byte ptr [edx]
    inc edx
    and cl, cl
    je short L_0CE316
    cmp cl, 0Dh
    jne short L_0CE311
    xor cl, cl
    jmp short L_0CE316
L_0CE311:
    mov byte ptr [eax], cl
    inc eax
    jmp short L_0CE301
L_0CE316:
    mov byte ptr [eax], cl
    pop ecx
    mov eax, edx
    ret
func_000CE31C:
    push ebp
    mov ebp, esp
    push esi
    push edi
    mov esi, eax
    mov edi, edx
    mov edx, dword ptr [ebp + 8]
L_0CE328:
    push esi
    push edi
    push ecx
    mov ecx, ebx
L_0CE32D:
    mov al, byte ptr [esi]
    mov byte ptr [edi], al
    inc esi
    inc edi
    dec ecx
    jne short L_0CE32D
    pop ecx
    pop edi
    pop esi
    add edi, 0140h
    add esi, edx
    dec ecx
    jne short L_0CE328
    pop edi
    pop esi
    pop ebp
    ret 4
    B_0CE34A_7
    dd D_000CDE00
    B_0CE355_142
func_000CE3E3:
    push ebx
    push ecx
    xor ecx, ecx
L_0CE3E7:
    mov bl, byte ptr [edx]
    cmp bl, 020h
    jbe short L_0CE3F5
    inc ecx
    mov byte ptr [eax], bl
    inc edx
    inc eax
    jmp short L_0CE3E7
L_0CE3F5:
    mov byte ptr [eax], 0
    mov eax, ecx
    pop ecx
    pop ebx
    ret
func_000CE3FD:
    push ebx
    push ecx
    xor ecx, ecx
L_0CE401:
    mov bl, byte ptr [edx]
    cmp bl, 030h
    jb short L_0CE42D
    cmp bl, 039h
    jbe short L_0CE426
    cmp bl, 041h
    jb short L_0CE42D
    cmp bl, 05Ah
    jbe short L_0CE423
    cmp bl, 061h
    jb short L_0CE42D
    cmp bl, 07Ah
    ja short L_0CE42D
    jmp short L_0CE426
L_0CE423:
    and bl, 0DFh
L_0CE426:
    inc ecx
    mov byte ptr [eax], bl
    inc edx
    inc eax
    jmp short L_0CE401
L_0CE42D:
    mov byte ptr [eax], 0
    mov eax, ecx
    pop ecx
    pop ebx
    ret
func_000CE435:
    push ecx
    and ebx, ebx
    je short L_0CE448
L_0CE43A:
    mov cl, byte ptr [eax]
    test cl, cl
    je short L_0CE448
    cmp cl, dl
    je short L_0CE44A
    inc eax
    dec ebx
    jne short L_0CE43A
L_0CE448:
    xor eax, eax
L_0CE44A:
    pop ecx
    ret
func_000CE44C:
    and ebx, ebx
    je short L_0CE45A
L_0CE450:
    cmp dword ptr [eax], edx
    je short L_0CE45D
    add eax, 4
    dec ebx
    jne short L_0CE450
L_0CE45A:
    xor eax, eax
    ret
L_0CE45D:
    ret
func_000CE45E:
    cmp word ptr [eax], dx
    je short L_0CE46C
    add eax, 2
    dec ebx
    jne short func_000CE45E
    xor eax, eax
    ret
L_0CE46C:
    ret
func_000CE46D:
    push ecx
L_0CE46E:
    mov cl, byte ptr [edx]
    cmp cl, bl
    je short L_0CE47E
    and cl, cl
    je short L_0CE47E
    mov byte ptr [eax], cl
    inc edx
    inc eax
    jmp short L_0CE46E
L_0CE47E:
    mov byte ptr [eax], 0
    pop ecx
    ret
func_000CE483:
    push edi
    push ecx
    mov edi, eax
    mov ax, dx
    movzx ecx, bx
    shr ecx, 1
    rep stosw
    pop ecx
    pop edi
    ret
func_000CE495:
    mov byte ptr [eax], dl
    inc dl
    inc eax
    dec ebx
    jne short func_000CE495
    ret
func_000CE49E:
    test byte ptr [eax], 0FFh
    je short L_0CE4A6
    inc eax
    jmp short func_000CE49E
L_0CE4A6:
    mov byte ptr [eax], dl
    ret
func_000CE4A9:
    test ebx, ebx
    je short L_0CE4B2
    not dl
    and byte ptr [eax], dl
    ret
L_0CE4B2:
    or byte ptr [eax], dl
    ret
func_000CE4B5:
    test ebx, ebx
    je short L_0CE4C0
    not dx
    and word ptr [eax], dx
    ret
L_0CE4C0:
    or word ptr [eax], dx
    ret
func_000CE4C4:
    push ebx
    xor ebx, ebx
    cmp byte ptr [eax], dl
    je short L_0CE4DB
    inc ebx
    cmp byte ptr [eax + 2], dl
    je short L_0CE4DB
    inc ebx
    cmp byte ptr [eax + 4], dl
    je short L_0CE4DB
    xor eax, eax
    pop ebx
    ret
L_0CE4DB:
    lea eax, [ebx + 1]
    pop ebx
    ret
func_000CE4E0:
    cmp byte ptr [eax], 0FFh
    jne short L_0CE4F7
    cmp byte ptr [eax + 2], 0FFh
    jne short L_0CE4F7
    cmp byte ptr [eax + 2], 0FFh
    jne short L_0CE4F7
    mov eax, 1
    ret
L_0CE4F7:
    xor eax, eax
    ret
func_000CE4FA:
    push ds
    push esi
    push edi
    cld
    mov dword ptr [D_000CDE3F], eax
    mov dword ptr [D_000CDE43], edx
    mov dword ptr [D_000CDE47], ebx
    mov dword ptr [D_000CDE4B], ecx
    mov esi, 0140h
    mov ecx, dword ptr [D_000CDE47]
    sub ecx, dword ptr [D_000CDE3F]
    je L_0CE5BF
    jns short L_0CE554
    neg ecx
    mov ebx, dword ptr [D_000CDE47]
    xchg dword ptr [D_000CDE3F], ebx
    mov dword ptr [D_000CDE47], ebx
    mov ebx, dword ptr [D_000CDE4B]
    xchg dword ptr [D_000CDE43], ebx
    mov dword ptr [D_000CDE4B], ebx
L_0CE554:
    mov ebx, dword ptr [D_000CDE4B]
    sub ebx, dword ptr [D_000CDE43]
    je L_0CE5F7
    jns short L_0CE56C
    neg ebx
    neg esi
L_0CE56C:
    push esi
    mov dword ptr [D_000CDE3B], offset func_000CE61E
    cmp ebx, ecx
    jle short L_0CE587
    mov dword ptr [D_000CDE3B], offset func_000CE63F
    xchg ebx, ecx
L_0CE587:
    shl ebx, 1
    mov dword ptr [D_000CDE33], ebx
    sub ebx, ecx
    mov esi, ebx
    sub ebx, ecx
    mov dword ptr [D_000CDE37], ebx
    push ecx
    mov eax, dword ptr [D_000CDE43]
    mov ebx, dword ptr [D_000CDE3F]
    add ebx, dword ptr [eax*4 + D_00142950]
    add ebx, dword ptr [D_00143550]
    mov edi, ebx
    pop ecx
    inc ecx
    pop ebx
    jmp dword ptr [D_000CDE3B]
L_0CE5BF:
    mov eax, dword ptr [D_000CDE43]
    mov ebx, dword ptr [D_000CDE4B]
    mov ecx, ebx
    sub ecx, eax
    jge short L_0CE5D4
    neg ecx
    mov eax, ebx
L_0CE5D4:
    inc ecx
    mov ebx, dword ptr [D_000CDE3F]
    add ebx, dword ptr [eax*4 + D_00142950]
    add ebx, dword ptr [D_00143550]
    mov edi, ebx
    dec esi
    mov al, byte ptr [D_0012B508]
L_0CE5F0:
    stosb
    add edi, esi
    loop short L_0CE5F0
    jmp short L_0CE65F
L_0CE5F7:
    cld
    push ecx
    mov eax, dword ptr [D_000CDE43]
    mov ebx, dword ptr [D_000CDE3F]
    add ebx, dword ptr [eax*4 + D_00142950]
    add ebx, dword ptr [D_00143550]
    mov edi, ebx
    pop ecx
    inc ecx
    mov al, byte ptr [D_0012B508]
    rep stosb
    jmp short L_0CE65F
func_000CE61E:
    mov al, byte ptr [D_0012B508]
    cld
L_0CE624:
    stosb
    or esi, esi
    jns short L_0CE633
    add esi, dword ptr [D_000CDE33]
    loop short L_0CE624
    jmp short L_0CE65F
L_0CE633:
    add esi, dword ptr [D_000CDE37]
    add edi, ebx
    loop short L_0CE624
    jmp short L_0CE65F
func_000CE63F:
    mov al, byte ptr [D_0012B508]
    cld
L_0CE645:
    stosb
    add edi, ebx
    or esi, esi
    jns short L_0CE657
    add esi, dword ptr [D_000CDE33]
    dec edi
    loop short L_0CE645
    jmp short L_0CE65F
L_0CE657:
    add esi, dword ptr [D_000CDE37]
    loop short L_0CE645
L_0CE65F:
    pop edi
    pop esi
    pop ds
    ret
func_000CE663:
    mov byte ptr [eax], dl
    inc dl
    inc eax
    dec ebx
    jne short func_000CE663
    ret
func_000CE66C:
    dec edx
    add eax, edx
    not edx
    and eax, edx
    ret
    B_0CE674_38
func_000CE69A:
    pushad
    mov ax, 7
    xor cx, cx
    mov dx, 0136h
    int 033h
    mov ax, 8
    xor cx, cx
    mov dx, 0C2h
    int 033h
    popad
    ret
func_000CE6B7:
    pushad
    mov ax, 7
    xor cx, cx
    mov dx, 026Ch
    int 033h
    mov ax, 8
    xor cx, cx
    mov dx, 01CCh
    int 033h
    popad
    ret
func_000CE6D4:
    imul dword ptr [edx*4 + D_00150200]
    shld edx, eax, 4
    mov eax, edx
    ret
func_000CE6E2:
    push esi
    push edx
    mov esi, eax
    and esi, 07FFh
    mov eax, dword ptr [esi*4 + D_00150A00]
    imul edx
    shld edx, eax, 4
    mov dword ptr [ecx], edx
    mov eax, dword ptr [esi*4 + D_00150200]
    pop edx
    imul edx
    shld edx, eax, 4
    mov dword ptr [ebx], edx
    pop esi
    ret
func_000CE70D:
    push esi
    push eax
    mov esi, edx
    and esi, 07FFh
    mov eax, dword ptr [esi*4 + D_00150A00]
    imul ebx
    shld edx, eax, 4
    add dword ptr [ecx + 8], edx
    mov eax, dword ptr [esi*4 + D_00150200]
    imul ebx
    shld edx, eax, 4
    add dword ptr [ecx], edx
    pop esi
    and esi, 07FFh
    mov eax, dword ptr [esi*4 + D_00150200]
    imul ebx
    shld edx, eax, 4
    add dword ptr [ecx + 4], edx
    pop esi
    ret
func_000CE74F:
    imul edx
    shld edx, eax, 4
    mov eax, edx
    ret
func_000CE758:
    push ecx
    push edx
    push edi
    mov edi, eax
    mov dx, 03C7h
    mov ecx, 0100h
    xor ah, ah
L_0CE768:
    mov al, ah
    out dx, al
    add dl, 2
    inc ah
    in al, dx
    stosb
    in al, dx
    stosb
    in al, dx
    stosb
    sub dl, 2
    loop short L_0CE768
    pop edi
    pop edx
    pop ecx
    ret
func_000CE77F:
    push ebx
    xor ebx, ebx
L_0CE782:
    test byte ptr [eax], 0FFh
    je short L_0CE788
    inc ebx
L_0CE788:
    inc eax
    dec edx
    jne short L_0CE782
    mov eax, ebx
    pop ebx
    ret
func_000CE790:
    and ebx, ebx
    je short L_0CE7A6
L_0CE794:
    test byte ptr [eax], 0FFh
    je short L_0CE7A4
    cmp byte ptr [eax], dl
    je short L_0CE7A0
    inc eax
    jmp short L_0CE794
L_0CE7A0:
    dec ebx
    inc eax
    jmp short func_000CE790
L_0CE7A4:
    xor eax, eax
L_0CE7A6:
    ret
func_000CE7A7:
    cmp word ptr [eax], dx
    je short L_0CE7B2
    inc eax
    dec ebx
    jne short func_000CE7A7
    xor eax, eax
L_0CE7B2:
    ret
func_000CE7B3:
    add dword ptr [D_00195B00], 019h
    ret
func_000CE7BB:
    push edx
    inc dword ptr [D_000CDE06]
    mov edx, 046Ch
    mov eax, dword ptr [edx]
    sub eax, dword ptr [D_000CDE0A]
    cmp eax, 012h
    mov eax, dword ptr [D_0012AA04]
    jbe short L_0CE803
    mov eax, dword ptr [edx]
    mov dword ptr [D_000CDE0A], eax
    mov eax, dword ptr [D_000CDE06]
    mov dword ptr [D_0012AA04], eax
    push eax
    add eax, dword ptr [D_000CDE0E]
    shr eax, 1
    mov dword ptr [D_000CDE0E], eax
    pop eax
    mov dword ptr [D_000CDE06], 0
L_0CE803:
    movzx eax, ax
    pop edx
    ret
func_000CE808:
    push ecx
    push esi
    mov ecx, dword ptr [eax + 4]
    mov esi, dword ptr [eax + 030h]
    add esi, eax
    mov eax, 0FFFE7960h
L_0CE817:
    cmp eax, dword ptr [esi + 4]
    jg short L_0CE81F
    mov eax, dword ptr [esi + 4]
L_0CE81F:
    add esi, 0Ch
    dec ecx
    jne short L_0CE817
    pop esi
    pop ecx
    ret
func_000CE828:
    pushad
    push edx
    push ebx
    mov ecx, dword ptr [eax + 4]
    mov esi, dword ptr [eax + 030h]
    add esi, eax
    mov eax, 0FFFE7960h
    mov ebx, 0186A0h
    mov edx, 0FFFE7960h
    mov edi, 0186A0h
L_0CE847:
    cmp eax, dword ptr [esi]
    jl short L_0CE84D
    mov eax, dword ptr [esi]
L_0CE84D:
    cmp ebx, dword ptr [esi]
    jg short L_0CE853
    mov ebx, dword ptr [esi]
L_0CE853:
    cmp edx, dword ptr [esi + 8]
    jl short L_0CE85B
    mov edx, dword ptr [esi + 8]
L_0CE85B:
    cmp edi, dword ptr [esi + 8]
    jg short L_0CE863
    mov edi, dword ptr [esi + 8]
L_0CE863:
    add esi, 0Ch
    dec ecx
    jne short L_0CE847
    sub ebx, eax
    sub edi, edx
    shr ebx, 8
    shr edi, 8
    pop eax
    mov dword ptr [eax], edi
    pop eax
    mov dword ptr [eax], ebx
    popad
    ret
func_000CE87B:
    push edi
    push ecx
    mov edi, eax
    xor eax, eax
    mov ecx, edx
    repe scasb
    je short L_0CE88A
    lea eax, [edi - 1]
L_0CE88A:
    pop ecx
    pop edi
    ret
func_000CE88D:
    pushad
    mov ebx, eax
    mov ecx, edx
    mov eax, 01Ah
    mov edx, 032h
    int 033h
    popad
    ret
func_000CE8A0:
    pushad
    push eax
    push edx
    mov eax, 01Bh
    int 033h
    pop edx
    mov byte ptr [edx], cl
    pop edx
    mov byte ptr [edx], bl
    popad
    ret
func_000CE8B2:
    mov al, 0B0h
    out 043h, al
    in al, 040h
    mov ah, al
    in al, 040h
    xchg ah, al
    and eax, 0FFFFh
    ret
func_000CE8C4:
    pushad
    xor esi, esi
    mov edi, offset D_000CDE4F
    mov ecx, 0100h
    rep movsd
    popad
    ret
func_000CE8D5:
    pushad
    xor esi, esi
    mov edi, offset D_000CDE4F
    mov ecx, 0100h
L_0CE8E2:
    repe cmpsd
    je short L_0CE916
    cmp esi, 8
    je short L_0CE8E2
    cmp esi, 024h
    je short L_0CE8E2
    cmp esi, 4
    je short L_0CE8E2
    sub esi, 4
    mov dword ptr [D_000CDE2F], esi
    mov esi, offset D_000CDE4F
    xor edi, edi
    mov ecx, 0100h
    rep movsd
    mov eax, offset D_000CDE12
    call func_00050069
L_0CE916:
    popad
    ret
func_000CE918:
    pushad
    mov ecx, 046Ch
    mov edx, dword ptr [ecx]
L_0CE920:
    mov ebx, edx
    sub ebx, dword ptr [ecx]
    neg ebx
    cmp ebx, eax
    jb short L_0CE920
    popad
    ret
func_000CE92C:
    pushfd
    pushad
    cmp byte ptr [D_00142306], 0
    je short L_0CE948
    cld
L_0CE938:
    mov edi, offset D_00142307
    mov ecx, 080h
    mov al, 1
    repne scasb
    je short L_0CE938
L_0CE948:
    popad
    popfd
    ret
func_000CE94B:
    pushad
    mov bh, al
    mov eax, 0C202h
    int 015h
    popad
    ret
func_000CE957:
    pushad
    mov edx, 0417h
    and byte ptr [edx], 0DFh
    mov ah, 1
    int 016h
    popad
    ret
    db 154 dup (0)
XN_CE300 ends
end
